### ISSUE TITLE
No API support to verify whether you can self-register exists

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#2793]
This won't work correctly because e.g. the LDAP `canSelfRegister` will return true due to auto-register, while that doesn't imply a new user can register explicitly. The `allowSetPassword` is currently the only method returning true only where expected. A new `canSelfRegisterManually` might be required instead

_Originally posted by @benbosman in https://github.com/DSpace/DSpace/pull/2763/files/891ab3f3e261e8a78321091b8835fab413937899_

See also https://github.com/DSpace/DSpace/pull/2763#discussion_r432400876

Related to / possible duplicate of #3272

**Comment by tdonohue** [comment]
Stumbled back on this ticket while looking into whether we had a replacement for the old XMLUI specific configuration `xmlui.user.registration=true` (which allowed you to enable/disable user registration).

I think this ticket might be asking for the same general feature/configuration.  It seems (to me) that we don't necessarily need an endpoint that specifies whether you can "self register", as that feature is *only available* if you have Password Authentication enabled.  So, we might want to consider whether we solve this ticket simply via a new configuration along the lines of `authentication.user.registration=true/false`.   

(That said, if we found a need to have this returned for each authentication plugin, I'm not against that idea. Just wanted to note that in DSpace 6.x, this seems to have been implemented via a simple true/false configuration)

**Comment by benbosman** [comment]
That's indeed a possible alternative solution.
Instead of asking the authentication methods whether self registration is possible, rather checking whether `authentication.user.registration=true` AND password authentication is enabled.
It should also a bit simpler to implement

**Comment by lap82** [comment]
We (at 4Science) are interested in working on that.

**Comment by tdonohue** [comment]
@benbosman or @lieven-atmire :  Trying to clarify who is working on this issue between Atmire & 4Science. As you can see above, the 4Science team would like to work on fixing this issue in 7.5.  However, it looks like @benbosman previously volunteered for #3272 which seems directly related to this ticket.   Could one of you verify whether Atmire is working on this or not?

**Comment by tdonohue** [comment]
Per the discussion in today's DevMtg, this has been assigned to @benbosman as it appears to overlap with #3272 and #3281 which are being worked on by the Atmire team.   These issues appear to all be related (possibly duplicates), and all are high priority for 7.5.

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/DSpace/pull/8619
