### ISSUE TITLE
DS-4485 Assure that test with full projection exists for all endpoints

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2796]
This is a duplicate of [DS-4485](https://jira.lyrasis.org/browse/DS-4485)

As part of the discussion in https://github.com/DSpace/DSpace/pull/2722#issuecomment-614161107 it was noted the need to remove/alter test with full projection due to constraint to run them as Admin only.

The DS-4444 should ideally allow us to use the project full also with less powered user receiving a "partial" response instead than a forbidden.

It would be valuable to restore some of the original test to proof other than verify that the projection full is still tested at least one time for all the endpoints

**Comment by KevinVdV** [comment]
We created a PR to add additional tests: https://github.com/DSpace/DSpace/pull/2932
