### ISSUE TITLE
DS-4036: Delete EPersons in DSpace

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2803]
This is a duplicate of [DS-4036](https://jira.lyrasis.org/browse/DS-4036)  --- see this ticket for description

Estimate from release plan: 29 hours
Expressing interest: none

From the release plan sheet: REQUIRED FOR GDPR COMPLIANCE
Add test to verify that inprogress submission are deleted as well, including pending workflow tasks. Add test to verify that the EPerson is removed from Groups without touching other members. Add test to include item without submitter in Search and Browse endpoint. Add test to check edit of item with null submitter. Add tests related to verify that subscriptions and request-a-copy about such eperson are deleted as well. Add test to include submitter null item in the versioning items endpoint (or create a task for future check)

Add a configuration parameter to limit the DELETE operation to only administrator and implement proper security

**Comment by tdonohue** [comment]
Early work on this was already started in this PR from @pnbecker : https://github.com/DSpace/DSpace/pull/2229
