### ISSUE TITLE
User Agreement / Privacy Statement

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2808]
Estimate from release plan: 24 hours
Expressing interest: 4Science

From release plan: 
To be agreed at self-registration and on login if they got updated

**Comment by benbosman** [comment]
From our point of view, we don't know what the plan of this feature is. Does anyone have details of the planned functionality?

**Comment by tdonohue** [comment]
@benbosman : From a report of the DSpace GDPR Working Group (chaired by @pnbecker), they have requested the following for this task.  I'm quoting them directly here:

> Information and consent of users
GDPR stipulates that a user has to be made aware of the privacy statements of a site, of all data processing with his or her personal data and has to agree to most of the data processing before it is performed. This includes the usage of cookies.
>
>In the following sections we differentiate between Privacy Statements, the End user agreement, and cookie preferences. Privacy Statements of a site describe the data stored, how it is processed, informs any user about his/her rights, and declares who is responsible to protect these data. The end user agreement is a list of private data stored, and information about how it is processed, that a user has to acknowledge before he/she creates an account or that he/she has to agree up on login if it was changed since the user agreed to a previous version. With the cookie preferences users can declare which cookies they are willing to accept and which not. 
>
>Privacy Statement
>The privacy statement contains declarations on all personal data stored for visitors, how it is processed, and which rights the user has (we try to give an overview of rights the GDPR grants every user in the Appendix of this document). Visitors to DSpace need to be made aware of the privacy statement of the installation. If they acknowledged to have read the privacy statements, the privacy statements don't have to be shown to this user again, until the privacy statements changes. Their acknowledgement can be stored in a cookie for visitors or a field in the user profile for registered users. The cookie can be permanent if the user agrees (in an opt-in manner) to make it permanent. The privacy statements also have to be linked in a place easy to find for every user anytime (e.g. in the footer of the site).
>
>The GDPR Working Group will provide an example of a privacy statement. Nevertheless, the privacy statement will have to adopt special national regulations (see Introduction about how GDPR and national differ).
>
>End user agreement
>Before any user is registered into DSpace, the user need to acknowledge any private data stored and processed by the site and all included services (e.g. ORCID, altmetrics, Google Analytics, ...). This has to be done using simple language and in a way that anyone can understand. Once a user creates an account he/she must acknowledge the end user agreement. If the end user agreement changes, the users has to give permission again. This can be requested by e-mail or on the next login of a user. The GDPR Working Group recommends therefore, to store to which version of the end user agreement a user agreed to, so that they can be asked again once the agreement changed on their next login. Since this is relevant only to registered users, the information should be part of the user account in the database.

Therefore, this is also loosely related to #2807 (which as discussed today, could be implemented as user metadata).

The full report can be found at: https://wiki.lyrasis.org/display/PSFDGWG/Result+summary+for+DSpace+Leadership+Group  (_Please be aware that this report is not public at this time. However, I've just given you access_)

**Comment by benbosman** [comment]
We can work on this combined with https://github.com/DSpace/DSpace/issues/2807
