### ISSUE TITLE
DS-4491: Remove (deprecated) BTE Framework from 7.x codebase

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2817]
This is a duplicate of [DS-4491](https://jira.lyrasis.org/browse/DS-4491)

https://wiki.lyrasis.org/display/DSPACE/BTE+transition%3A+4Science+implementation+proposal+and+estimation

**Estimate from release plan: TBD
Expressing interest: 4Science**

The BTE (Biblio-Transformation-Engine) Framework was officially deprecated in DSpace 6.x. This framework was used by the JSPUI for importing metadata from external sources and/or common structured files (like BibTeX, etc). This framework was built/maintained by the Hellenic National Documentation Centre (EKT)

Deprecation (and removal) is necessary for the following reasons:

The EKT developer who built this framework left their organization in/around 2015. While EKT staff said they'd try to support it for one more release (v6.x), it's long term future was uncertain.
Since 2014, no maintenance/updates have occurred on BTE: https://github.com/EKT/Biblio-Transformation-Engine Obviously, DSpace cannot use continue to use third-party libraries that are unmaintained.
The BTE codebase has become stale and uses additional libraries with known security vulnerabilities. See comment below for full details.
The recommendation of this ticket is to remove BTE in favor of the "Live Import" framework (which overlaps in functionality, but was XMLUI specific in v6). See the "Live Import" 6.x docs at:

General overview: https://wiki.lyrasis.org/pages/viewpage.action?pageId=68064788#Introduction
More details: https://wiki.lyrasis.org/display/DSDOC6x/2016+Framework+for+live+import+from+external+sources
This choice of a single importer framework also aligns with the goals laid out in our last Strategic Plan, namely to be "lean" and avoid duplicative functionality in our codebase.

Before removing BTE, we should look to replace each of its features with a Live Import based version. Full replacement need not be required for BTE removal, but ideally there is minimal (or zero) loss of functionality for old JSPUI-based users (XMLUI-based users would have no functionality loss as BTE never supported XMLUI). Additional tickets should be linked to this one describing each of the missing gaps in "Live Import" that are necessary to replace BTE.

This ticket has been tentatively scheduled for 7.0, as we should not encourage institutions upgrading to 7.0 to continue to utilize BTE. Ideally, therefore, it should be removed prior to the 7.0 final release, in order to no longer support two parallel frameworks.

**Comment by abollini** [comment]
According to  https://wiki.lyrasis.org/display/DSPACE/BTE+transition%3A+4Science+implementation+proposal+and+estimation

The only step still needed to remove BTE without loss of existing functionalities is **Implementation of the Extract Panel using the live import framework**, we are still interested in working on that. Please note that this task doesn't include the creation of any further provider for the live import (such as the grobid extractor mentioned in the quoted text below) but only the option to use the existing extractor to automatically expands identifier.

This task is related to the step org.dspace.submit.step.MetadataStep, org.dspace.app.rest.submit.step.ExtractMetadataStep currently in the master.

According to the javadoc

This submission steps allow to extract metadata from an uploaded file to enrich or initialize a submission. The  processing is delegated to a list of extractor specialized by format (i.e. a Grobid extractor to get data from a PDF  file, an extractor to get data from bibliographic file such as BibTeX, etc)

the plan is to provide equivalent steps that will use extractors build with the Live Import framework instead than BTE.

The current class should be flagged as deprecated and renamed in 

MetadataStepDeprecatedBTEStep
ExtractMetadataDeprecatedBTEStep
This step, that can be enabled or disabled via the item-submission.xml has the effect to automatically enrich an inprogress submission when new information that can be used by the extractor (doi, pmid, pdf file, etc.) are added to the workspace (or workflow) item.

The whole feature is already implemented and has been demonstrated at OR and the youtube video of the DSpace 7 preview, there is no interaction with the user about the additional information found in the external provider but the extra changes automatically applied are notified with the usual sticky messages.

**Comment by tdonohue** [comment]
@abollini : Does the estimate of 16 hours here *include* **removing all existing BTE classes from the backend**?  To clarify the task here, I think we also *must remove* all BTE classes from the codebase.  So, I would not "deprecate" any classes  (as your description above describes) and instead would request that we estimate removing BTE.

So, this ticket would not be considered completed until the following also occurs:
* All usages of `gr.ekt.bte.*` or `gr.ekt.bteio.*` classes have been removed from our codebase
* All old BTE DataLoader classes are removed (see `bte.xml`) and the corresponding `bte.xml`
* Removal of `bte_batch_import_success` email template
* BTE dependencies removed from `dspace-api` POM.

Just to clarify, is that work included in the 16 hours?

**Comment by abollini** [comment]
hi @tdonohue  yes the estimation of 16 hours is related to remove all the gr.ekt.bte classes and reference and also rebuild the current extract feature (as it works now) using the live import framework so in some way it absorbs also the work on #3012

Thanks to point out the `bte_batch_import_success` this make me aware that there was another BTE related feature available only to system administrator via UI (in the JSPUI) or from the command line to import data from reference files. Can this be or has been already postponed to a next version (7.1/7.2)?

**Comment by tdonohue** [comment]
@abollini : Thanks for clarifying. That sounds fine.  I've assigned this to you (along with #3012) & moved to "in progress" so that your team can work on this.

As for the commandline tools you mention for BTE, I think they should be removed for now.  In my opinion, any future commandline tools should be written as Processes/Scripts, so that they can also be triggered from the Admin UI.  So, it sounds like you'd really be asking for a way to trigger Live Import via Scripts & Processes.  I don't believe a ticket for that exists yet, but if you agree with this idea, then I can always create a ticket for 7.2 to describe this idea.
