### ISSUE TITLE
"metadata-export" script should NOT allow file location to be specified via REST API /scripts endpoint

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2821]
Created based on feedback in https://github.com/DSpace/dspace-angular/pull/636#pullrequestreview-441228120

Currently, in the Scripts & Processes UI, any administrator can specify a `--file` location, for the `metadata-export` script.  Since that script is only able to write a file to the server where DSpace is running, it's unlikely the Admin will know an exact path to type in. Additionally, this could be a security issue if you can write the output file anywhere on the system. Ideally, instead, the file should always be written to the `[dspace]/exports/` folder (which is where it was written in DSpace 6.x, IIRC).

Ideally, the REST API should NOT allow a `--file` parameter to be passed in.  Instead, it should automatically create a new file in the `[dspace]/exports`/ folder at all times.  Therefore, the user should not be able to specify this location, however they can download the file once the export completes.

**Comment by lieven-atmire** [comment]
we estimate the work to be around 3 hours

**Comment by KevinVdV** [comment]
@tdonohue There is some misunderstanding on how the "--file" options works. For the REST call this requires a file name, while for the CLI it DOES require a file PATH. This wasn't clear from the help messages as they are currently the same between REST & CLI, the following PR rectifies that issue: https://github.com/DSpace/DSpace/pull/2901

A small note on the `[dspace]/exports` folder: This folder wasn't used for the metadata-export script, but rather for the SAF exports, in DSpace 6 the csv generated by the metadata-export script was stored in memory before offering the download to the end user. The SAF exports where to big to store in memory & that is why that exports folder was created. But we can now stop using this exports folders as processes make use of bitstreams to store files now.

**Comment by tdonohue** [comment]
@KevinVdV : Thanks for clarifying the different usage of the `--file` option.  However, I'd still much rather *remove* this flag from the REST API and provide a default name (as I see no reason why the name of the file should be something the user can specify). This is exactly what this Angular UI PR does (it sets the name to `[uuid].csv` & doesn't provide an option to change it): https://github.com/DSpace/dspace-angular/pull/798  

That behavior will provide a more consistent interaction with the "metadata-export" script, no matter whether you use it via the new "Export" UI or via the Processes UI.  The current Processes UI behavior is not user friendly as it requires a `--file` to be specified before you can start an export.

**Comment by tdonohue** [comment]
@KevinVdV : Based on the recently submitted solution for limiting the `--email` flag to CLI (see #2915), I'd recommend we implement a similar solution for this `--file` flag.  It should only be possible to set from the CLI, and otherwise should default to something like `[uuid].csv` or `[type]-[uuid].csv` or similar.

**Comment by KevinVdV** [comment]
@tdonohue I opened up a new PR for this issue that follows the suggestion you made: https://github.com/DSpace/DSpace/pull/2924
