### ISSUE TITLE
POSTing item returns null as 'name'

### ISSUE THREAD

**Issue by cuehs** [DSpace/DSpace#2826]
When using the REST API and POSTing to `collections/{collectionId}/items` the field `name` of the Item is ignored.   

So the command:
 `curl -X POST https://demo.dspace.org/rest/collections/{collection id}/items -H 'Content-Type: application/json'  -H 'Accept: application/json'  -d '{"name": "TEST"}'`
returns
`{
    "uuid": "someuuid",
    "name": null,
    ...
}`

Please correct me if I am wrong but the code in `rest/CollectionsResource.java` suggests that only the metadata, but not the name, of an Item is considered. As [` if (item.getMetadata() != null) {`](https://github.com/DSpace/DSpace/blob/master/dspace-rest/src/main/java/org/dspace/rest/CollectionsResource.java#L356) is the only time when Item is accessed.

Do I miss something?

**Comment by tdonohue** [comment]
@cuehs : Your analysis seems to be accurate.  That said, the `name` of an Item is the value of it's `dc.title` metadata field.  So, I suspect you should be able to assign the name by passing a `dc.title` on the POST.  Here's an example that does just that: https://github.com/BrunoNZ/dspace-rest-requests/blob/master/requests/POST_new-items.sh

That github repo has a number of example requests for the DSpace v6 (and below) REST API (as the docs are lacking in some areas).   It's also linked from the docs in the "Additional Resources" section: https://wiki.lyrasis.org/display/DSDOC6x/REST+API#RESTAPI-AdditionalInformation

**Comment by cuehs** [comment]
Thanks for the feedback. Adding the `dc.title` metadata field does indeed work.
