### ISSUE TITLE
Documentation of DSpace 7, especially new UI, Install & Upgrade

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2835]
From release plan spreadsheet
Estimate from release plan: 120 hours
Expressing interest: none

https://wiki.duraspace.org/display/DSDOC7x/

**Comment by tdonohue** [comment]
Closing as "obsolete" this has been split into many tickets with the [`documentation` label](https://github.com/DSpace/DSpace/labels/documentation)
