### ISSUE TITLE
Embargo Item Metadata

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2839]
From release plan spreadsheet

Estimate from release plan: 20 hours
Expressing interest: none

Embargo bitstream already exists (REST contract is missing though). Mimic the implemented solution for the bitstream. Heavy testing is required to verify that embargo is also respected once the items are archived. NEEDS DISCUSSION. UNCERTAIN ESTIMATE.

Related UI ticket: https://github.com/DSpace/dspace-angular/issues/767

**Comment by tdonohue** [comment]
Related issue: https://jira.lyrasis.org/browse/DS-3746

**Comment by atarix83** [comment]
@tdonohue we are interested on this task

**Comment by tdonohue** [comment]
Thanks @atarix83 .  As this is backend related, assigning to @abollini for your team to start work on.  Please also be aware that the initial estimate was listed as "uncertain".  So, let me know if the estimate needs to change *before* you start work.
