### ISSUE TITLE
More easily embargo an archived Item (using a form)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2846]
From release plan spreadsheet

Estimate from release plan: none
Expressing interest: none

In DSpace 6.x, this was done via editing Resource Policies directly (see "Edit Item - Manage Resource Policies / Roles")

Related UI ticket: https://github.com/DSpace/dspace-angular/issues/778

**Comment by tdonohue** [comment]
This can already be done in 7.0 via "Edit Item" -> "Authorizations" by adding a new policy restricting the Item to a group (e.g. Administrator) until a specific _end date_ passes.

So, this ticket is really just about making that process *easier* (perhaps via an Embargo button, or via a new submission-style edit option like described in #2876)

**Comment by tdonohue** [comment]
Might be solved by https://github.com/DSpace/dspace-angular/issues/781 , based on the initial design of the bulk access control management tool.  One use case was to modify a single Item (via Edit Item).  

@abollini : Do you agree this is likely a subtask of that larger work?

**Comment by tdonohue** [comment]
Closing as fixed by the Bulk Access management tool added in 7.6: https://wiki.lyrasis.org/display/DSDOC7x/Bulk+Access+Management

Using that tool you can now add an embargo to a single item or multiple via a form.
