### ISSUE TITLE
Bulk Access Control Management (Wildcard / Advanced Policy Manager)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2848]
From release plan spreadsheet

Estimate from release plan: 16 hours
Expressing interest: none

This is the [Wildcard/Advanced Item Policy tool](https://www.youtube.com/watch?v=PFlq-yGSPY4) in v6.x.

Related front-end ticket: https://github.com/DSpace/dspace-angular/issues/781

**Comment by abollini** [comment]
Hi @tdonohue  we (4Science) are interested in this task. We have already done an initial internal analysis and we would like to get assigned of it. We ask to raise the estimation to 56 hours for the REST part

**Comment by tdonohue** [comment]
Assigned to you per the discussion in today's meeting summarized in the other ticket: https://github.com/DSpace/dspace-angular/issues/781#issuecomment-1442100001
