### ISSUE TITLE
Batch Import (from ZIP)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2850]
From release plan spreadsheet

Estimate from release plan: 8 hours
Expressing interest: none

Depends on "Scripts & Processes" endpoint.

This ticket is for the REST API.  See also related UI ticket DSpace/dspace-angular#783

**Comment by abollini** [comment]
@tdonohue we are interested in that. We can work on it after / in parallel with the other higher priority tickets already claimed
