### ISSUE TITLE
Submission via an identifier

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2872]
From release plan spreadsheet

Estimate from release plan: TBD
Expressing interest: none

The submission PR includes the capabilities to enrich the submission with information retrieved by the bibliographic database once than an identifier is provided. This is slightly different than the current JSPUI functionality "Search by Identifiers". We are interested in implement also this functionality but it has a very low priority and could IMHO eventually excluded from DSpace 7 - ab

**Comment by tdonohue** [comment]
Closing, as this appears to duplicate #2834   No additional information is provided in this ticket, and they sound like the same feature.
