### ISSUE TITLE
Type-bind submission

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2873]
From release plan spreadsheet
Estimate from release plan: 36 Hours
Expressing interest: none

Some metadata should be included only for specific value of dc.type https://wiki.duraspace.org/display/DSDOC6x/Submission+User+Interface#SubmissionUserInterface-ItemtypeBasedMetadataCollection 

* Related dspace-angular issue: https://github.com/DSpace/dspace-angular/issues/806
* Related RestContract PR: https://github.com/DSpace/RestContract/pull/179
* Related DSpace PR: https://github.com/DSpace/DSpace/pull/8175
* Related dspace-angular PR: https://github.com/DSpace/dspace-angular/pull/1529

**Comment by pnbecker** [comment]
We got a contract to develop this. Of course, we will create a pull-request once we're done with it.

**Comment by abollini** [comment]
This is already supported in DSpace-CRIS so you should take a look to backport the feature.
It was introduced in the first 7 version so it is a bit hard now to find all the reference but I'm able to track down the feature to this commit on the REST side https://github.com/4Science/DSpace/commit/874ec129d2ac5f59fec8f309b02343cb90c31137

**Comment by kshepherd** [comment]
I've opened PRs for DSpace and dspace-angular. There are some tests to write / fix before it is fully ready but they are functional and can be practically tested as of now.

**Comment by pnbecker** [comment]
PR is here: https://github.com/DSpace/DSpace/pull/8175
