### ISSUE TITLE
Control Panel

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2877]
From release plan spreadsheet
Estimate from release plan: TBD
Expressing interest: none

This is an XMLUI only feature in 6.x. REQUIRES DISCUSSION

Corresponding UI ticket: https://github.com/DSpace/dspace-angular/issues/801

### Java Information Tab
![Java-info](https://user-images.githubusercontent.com/483997/155408182-a877e7e9-6afa-49f5-b2bd-32e4c6d65e86.png)

### Configuration Tab
![config](https://user-images.githubusercontent.com/483997/155408194-20b82320-8b9b-4c6a-ae07-60eb5c905d1d.png)

### Systemwide Alerts Tab
**NOTE: This task has been split into a separate ticket:** https://github.com/DSpace/dspace-angular/issues/1537
![systemwide](https://user-images.githubusercontent.com/483997/155408201-af8c55f0-ff8e-4d50-a8db-0289ae9beaa8.png)

### Harvesting Tab
![harvester](https://user-images.githubusercontent.com/483997/155408207-3d59e2ed-cc44-498e-be87-653871f48063.png)

### Current Activity Tab
![currentactivity](https://user-images.githubusercontent.com/483997/155408214-9c785d5e-6baf-4f56-a918-19540ecec859.png)

**Comment by tdonohue** [comment]
NOTE that this feature also included some "extensible" options, configured in `dspace/config/modules/controlpanel.cfg` and documented at https://wiki.lyrasis.org/display/DSDOC6x/Extensible+control+panel

We'll need to discuss which of these extensible features should be retained, etc.

**Comment by LucaGiamminonni** [comment]
Hi @tdonohue @heathergreerklein, for this issue we propose to use the spring boot actuator endpoints. You can find more information here: https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
By default, the exposed endpoints would be /actuator/info, where it is possible to add general information about the application (name, version, etc.) and /actuator/health, where the application status would be displayed. 
To calculate the status, we can use a series of predefined health indicators (such as those based on the status of the db or solr) or we can define custom indicators (which, for example, can check if particular configurations are ok).
We can also establish strategies based on the current user to show or not the details of the status.
In addition to the health endpoint, there are other actuators available by default (to see, for example, all the beans configured in the context, the properties, the scheduled tasks, etc.) and in addition, other custom ones can also be added.

If you agree I would try to do a PR where I try to include the actuators in dspace with a health indicator that shows the status of the application based on:
- the status of the db
- to the status of solr
- the status calculated with a custom logic (for example, I could add a check on the correct GeoIP configuration).
I should be able to integrate them in 8h.

**Comment by tdonohue** [comment]
@LucaGiamminonni : I do like the idea of using existing Spring Boot Actuator endpoints & configuring/customizing them (or adding new ones where needed) for a control panel. I like that we can use something that's built into Spring already, rather than designing our own separate REST API endpoints for this interaction.

That said, we'd obviously need to make sure though that there's no issues with interacting with these Actuator endpoints from the Angular UI. I don't think there would be, but this is obviously the first time we'd be using Actuator endpoints.... and my understanding here is that these Actuator endpoints would be separate from our REST API endpoints, as they are provided by Spring Boot, instead of by our REST API.

In any case, this basic design sounds fine to me.  That said, I'm going to add this to next week's DevMtg agenda as well, to ensure others (like @benbosman) have a chance to give immediate feedback on this approach as well.

**Comment by LucaGiamminonni** [comment]
Hi @tdonohue, the actuators by default have /actuator as base path, so in our case can be used by contacting /server/actuator. I don't think this can be a problem for angular. In any case it would also be possible to configure the base path adding api as prefix (so it could be /api/actuator). But I think that if there are no problems on the angular side it is better to divide the actuators from the standard dspace api.

**Comment by tdonohue** [comment]
As discussed in today's meeting, the team likes the idea to use Spring Boot Actuators to fit the needs of the Control Panel.  Specifically the "info" and "health" actuators look to match up well with the old "Configuration" and "Java Information" tabs.
We also decided:
1. We'd like a very basic "Control Panel" Angular UI to simply display the "info" and "health" actuator responses in a nice manner.
2. All other actuators will ONLY be accessible via the Spring Boot Admin Server (https://github.com/codecentric/spring-boot-admin)... and we should provide basic documentation on how to run the Spring Boot Admin Server alongside DSpace
    * If possible, this may mean we'd want to find a way to easily "enable" the DSpace backend as a Spring Boot Admin client.
    * This may either mean enabling it out-of-the-box...or seeing if we can use something like `@ConditionalOnProperty` similar to what we do to enable OAI-PMH or SWORD, e.g. https://github.com/DSpace/DSpace/blob/main/dspace-oai/src/main/java/org/dspace/xoai/controller/DSpaceOAIDataProvider.java#L56
    * I think we should *avoid* requiring users to make Java code changes to use the Spring Boot Admin Server.  Either DSpace is setup to use that Spring Boot Admin Server by default, or a configuration should control it.
3. The other Control Panel tabs (displayed in screenshots at the top of this ticket) will be addressed separately:
    * The "SystemWide Alerts" tab will be treated as a separate ticket. (To be created)
    * The "Harvesting" tab is already addressed as this has moved to Scripts & Processes.  This feature exists in DSpace 7.2 already.
    * The "Current Activity" tab may need to be addressed separately, unless there's a Spring Actuator that corresponds well with the ability to "see" individual user activity in the system (e.g. it might be possible by viewing logs in Spring Actuator, but it may require additional analysis).  So, this tab is not required for the initial Control Panel feature.
   

@LucaGiamminonni : As we came to an agreement on this feature today, I'm assigning these tickets to you for you/your team to work on for 7.3.  However, please do verify if your initial estimate is still accurate, or if you'd like to update it based on discussions.
