### ISSUE TITLE
Supervision Orders (JSPUI Only)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2878]
From release plan spreadsheet
Estimate from release plan: TBD
Expressing interest: none

May need DCAT feedback.  Unclear if this is used much.  

Described at: https://wiki.lyrasis.org/display/DSDOC6x/Functional+Overview#FunctionalOverview-SupervisionandCollaboration
See JSPUI: http://demo.dspace.org/jspui/dspace-admin/supervise

Description from 6.x JSPUI help menu:
> ## Supervision Orders
> Select Supervisors in the administration area and you are presented with three options:
> * Add a Supervision Order
> * View Current Supervision Orders
> * Clean Supervision Order Database
>The sections below detail how to deal with common supervision order tasks.
> _Note: The option to Clean Supervision Order Database should be used once in a while just to perform basic maintenance operations on the database. It is completely automatic and takes a very short time to execute._
>
> ### Viewing Current Supervision Orders
> Select View Current Supervision Orders and you are presented with a list of all supervision orders currently in effect. From this page you can modify the policies for the supervision order or remove the supervision order. (see the sections below).
>
>The details you have on this page allow you to see the name of the group doing the supervising, the author of the item being supervised and the title of that item.
>
>You may also add a supervision order from this page as per the section _Adding Supervision Orders_ below.
>
> ### Adding Supervision Orders
>Select _Add a Supervision Order_ from either the main supervision order page or the Current Supervision Orders page.
>
>To set a supervision order you need to define the group to do the supervising and the item in the workspace to be supervised. In addition, this page gives you the option to set a default set of policies for the supervising group to have over the item.
>
>Select the desired group from the pull down list of groups on this page; this box contains all the groups that currently exist on the system. Next select the WorkSpace item to be Supervised. This means clicking on the round select box on the right of the item in the listing you can see on this page, which shows all items currently in user workspaces.
>
>_Note: the ID that is in the left hand column of the item listing is the database id for the workspace item, and is there for the reference of system administrators._
>
>Once you have chosen the group and the workspace item to be connected you may also select a default policy from the Initial Policy Setting pull down box. The default policy options that this provides are:
>* None - The supervision order is created but the supervising group is not given any policies regarding the item to be supervised. This usually indicates that the administrator has decided to manually set policies for this supervision order.
>* Observer - The supervising group is given READ access to the item (but not to any bundles or bitstreams that already exist). Any new bundles or bitstreams inherit the supervision group's policy to permit READ operations.
>* Editor - The supervising group is given ADD, WRITE, and READ access to the item (but not any bundles or bitstreams that already exist). Any new bundles or bitstreams inherit the supervising groups's policy to permit ADD, WRITE and READ operations.
>Once happy with your selection click on Submit Supervision Order and your settings will be applied, and you will be returned to the supervision order main page.
>
>### Removing Supervision Orders
>Go to the View Current Supervision Orders page and select Remove from the supervision order that to wish to remove. You will be asked to confirm the removal of the order, upon confirmation of which it will be removed from the system.
>
>### Customising Supervision Order Policies
>Go to the View Current Supervision Orders page and select Policies for the supervision order for which you would like to customise the policies. You will be taken to the Policies for Item page. From here you may customise the policies for the particular item.
>
>In order to set policies for the supervisor group you should select, for example, Add New Policy for the item or any of its component parts, then select the supervisor group that you are wanting to configure from the given list of groups. You can then select the Action that you want to perform and hit Save Policy.

**Comment by abollini** [comment]
We (at 4Science) can work on that.
It is not a trivial task as in DSpace 7 some extra security around the workspaceitem have been implemented to make sure that only the submitter is able to access and manipulate the item overriding the default ACL based security.

The plan is to index in the workspaceitem solr document which groups have received a supervisor order. In this way we can build a dedicated supervision orders discovery configuration that will be used to list all the existing workspaceitem with active supervisor orders allowing the admin to remove these orders or check the specific permissions associated with them (view / write).

A new supervision order endpoint needs to be defined to allow creation and removal of the supervisor order. Listing will be not necessary or in any case will be not used by the UI (that will use the discovery endpoint).

We estimate 96 hours for this task (REST side) focusing on a working implementation for the default supervision setup (editor, observer). Additional works could emerge in the case the administrator want to apply custom policies.

**Comment by tdonohue** [comment]
Thanks @abollini . That all sounds reasonable.  I'd recommend keeping this as simple as reasonably possible, so I don't think any custom policies should be supported, as those don't seem to be available in 6.x.

In case it's helpful, I've copied the 6.x docs on this feature into the description of this ticket (see above).

In any case, I'll assign to your team for 7.5 and add the estimate.
