### ISSUE TITLE
DS-3589: Implement signposting pattern in DSpace

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2881]
This is a duplicate of [DS-3589](https://jira.lyrasis.org/browse/DS-3589)

Estimate from release plan: 12 hours
Expressing interest: none

The Next Generation Repositories Working Group from COAR has recently released the first draft of its outcome report presenting 12 user stories that outline priority functionalities for repositories (see http://comment.coar-repositories.org/). The update following the public comment phase is forthcoming.

The 1st user story is about "Discovering metadata that describes a scholarly resource" one of the enabling technologies / strategy is the implementation of the convention detailed by the initiative: signposting the Scholarly Web see http://signposting.org/conventions/

I propose to implement these conventions in the new DSpace UI

**Comment by abollini** [comment]
As we were involved in the first implementation of the protocol in DSpace-CRIS 5 we would like to get this task assigned to us

**Comment by tdonohue** [comment]
@abollini : I'll assign this to you for 7.3 then.  You may want to analyze first whether the estimates here are still accurate (as they are almost 2 years old), or whether they need updating.

**Comment by abollini** [comment]
just a note for the 7.5, the estimation should be corrected and set to 48 hours. Since 2 years ago the signposting protocol has released new recommendation that requires the creation of additional endpoints (and test) to deal with scenarios with a large number of header links

**Comment by tdonohue** [comment]
@abollini : I just realized that Signposting has no PRs created for 7.5.  Does this need to be rescheduled for 7.6?

**Comment by tdonohue** [comment]
Removing "needs funding" label as Susanna from 4Science volunteered to contribute this code back to DSpace without funding.

In yesterday's Steering meeting, Signposting was **approved** to be included in 7.6, if it can be developed/reviewed in time. Even though Signposting did not exist in 6.x, Steering voted to make a one-time exception that this feature can be added to 7.6 as it helps achieve our goals of alignment with [COAR Next Generation Repositories](https://www.coar-repositories.org/news-updates/what-we-do/next-generation-repositories/) recommendations.
