### ISSUE TITLE
Documentation / Recommendations on grouping Entities in Collections

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/DSpace#2885]
From release plan spreadsheet
Estimate from release plan: 4 hours
Expressing interest: none

Suggested in Preview Release that separate Entity Types (e.g. Person, OrgUnit, Project) should likely be in different Collections

**Comment by tdonohue** [comment]
Closing, as this Documentation was created already for 7.0.  See https://wiki.lyrasis.org/display/DSDOC7x/Configurable+Entities
