### ISSUE TITLE
Support for ORCID and other external providers in the authority framework is needed

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#2891]
**Describe the bug**
It was noted in https://github.com/DSpace/DSpace/pull/2792 that support for the ORCIDAuthority but also for Library of Congress and Sherpa related authorities were dropped here https://github.com/DSpace/DSpace/commit/9bb2e7e526348bb87661d59959271ccda2879c9c#diff-c4bcce032ec14858759cf4cef1a2d627

Not all the institutions would like to immediately use the Configurable Entities and in any case there are always the chance that some of this authorities are intended to be used only to improve the quality of the metadata without dealing with local record for them.

**Comment by tdonohue** [comment]
@abollini : I've also added this one to beta4 for now, as it seems to be closely related to existing controlled vocab work & could be a simple follow-up PR. Thanks again for adding an estimate here already. Let us know if you'd like to claim this.
