### ISSUE TITLE
Error Code: 400 Bad Request when rebuilding dspace 6.3 with Amazon s3 storage enabled

### ISSUE THREAD

**Issue by otuoma** [DSpace/DSpace#2902]
I enabled s3 storage on dspace 6.3 and tried to rebuild but I am getting this error

----------------
Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; 
----------------
Full error is in the attached file. I am following the instructions at [Configuring Amazon S3 Storage](https://wiki.lyrasis.org/display/DSDOC6x/Storage+Layer#StorageLayer-ConfiguringAmazonS3Storage) to configure s3 storage. I have more than double ckecked the bucketName, awsAccessKey and awsSecretKey are all correct with permissions to read/write on the s3 bucket. Bucket region is eu-west-2

---Java
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

---OS
Ubuntu 18.04.4 LTS 

--- Web Server
tomcat8

Is this a bug I am unaware of or am I doing something wrong ?

[error-code.txt](https://github.com/DSpace/DSpace/files/4970701/error-code.txt)

**Comment by tdonohue** [comment]
As best as I can tell, something may have gone wrong with the initial build of DSpace 6.3. The errors in your logs have nothing to do with Amazon S3 storage, instead they all refer to the `/opt/dspace-6.3/config/spring/api/sherpa.xml` and Sherpa related classes.  See this section:
```
org.springframework.context.support.ClassPathXmlApplicationContext @ Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.app.sherpa.submit.SHERPASubmitService' defined in URL [jar:file:/home/ubuntu/dspace-6.3/dspace/target/dspace-installer/lib/dspace-api-6.3.jar!/spring/spring-dspace-addon-sherpa-services.xml]: Cannot resolve reference to bean 'org.dspace.app.sherpa.submit.SHERPASubmitConfigurationService' while setting bean property 'configuration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.app.sherpa.submit.SHERPASubmitConfigurationService'
....
```

A large number of bean creation errors occur, which make me wonder if your initial build of DSpace failed with unexpected errors.  In any case, I'd recommend moving this discussion to our support mailing list (https://groups.google.com/g/dspace-tech/) if you need additional help.  Other support options available at https://wiki.lyrasis.org/display/DSPACE/Support

As GitHub issues are not for support questions, I'll close this ticket as it doesn't seem to be a bug in DSpace itself.
