### ISSUE TITLE
Features endpoint - Edit item permissions in REST

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#2921]
**Is your feature request related to a problem? Please describe.**
DSpace 6 edit item will verify the current user's permission to determine where the link to edit the item is displayed, and whether you can add bitstreams, make an item private, …

**Describe the solution you'd like**
Based on https://docs.google.com/spreadsheets/d/1182LcD_WqIZRbUGWpLtBw0aOMR9jhbOVB7GZqtTpR9A/edit#gid=0, implement the features:
* canManagePolicies
* canEditMetadata
* canMove
* canMakePrivate
* canMakeDiscoverable
* canDelete
* canReorderBitstreams
* canCreateBitstream
* canCreateBundle

**Comment by benbosman** [comment]
We would like to claim this ticket. Once the REST work is completed, it can be started for Angular as well

**Comment by tdonohue** [comment]
Sounds good, @benbosman . Assigned it to you.
