### ISSUE TITLE
Features endpoint - Edit collection permissions in REST

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#2944]
**Is your feature request related to a problem? Please describe.**
DSpace 6 edit collection will verify the current user's permission to determine whether the link to edit the collection is displayed, and whether you can manage workflow groups, manage the template item, …

**Describe the solution you'd like**
Based on https://docs.google.com/spreadsheets/d/1182LcD_WqIZRbUGWpLtBw0aOMR9jhbOVB7GZqtTpR9A/edit#gid=0, implement the features:
* canManageTemplateItem
* canManageWorkflowGroup
* canManageSubmitterGroup
* canManageAdminGroup

**Additional context**
A large amount of edit collection features are already supported using https://github.com/DSpace/DSpace/pull/2940, which was extended to support any DSO where possible

**Comment by tdonohue** [comment]
@benbosman : Correct me if I'm wrong, but I believe this issue was fixed by #822?  Should we close this?

**Comment by benbosman** [comment]
https://github.com/DSpace/dspace-angular/pull/822 is only part 1 of the work, it only verifies whether the user is an admin of the collection
