### ISSUE TITLE
Features endpoint - Edit community permissions in REST

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#2945]
**Is your feature request related to a problem? Please describe.**
DSpace 6 edit community will verify the current user's permission to determine whether the link to edit the community is displayed, and whether you can create communities, collection

**Describe the solution you'd like**
Based on https://docs.google.com/spreadsheets/d/1182LcD_WqIZRbUGWpLtBw0aOMR9jhbOVB7GZqtTpR9A/edit#gid=0, implement the features:
* canCreateCommunities
* canCreateCollections

**Additional context**
A large amount of edit community features are already supported using #2940, which was extended to support any DSO where possible

**Comment by tdonohue** [comment]
@benbosman : Same here...I think this was already fixed, as it looks like it was used by Angular PR DSpace/dspace-angular#822? Should we close this?

**Comment by benbosman** [comment]
https://github.com/DSpace/dspace-angular/pull/822 is only part 1 of the work, it only verifies whether the user is an admin of the community
