### ISSUE TITLE
Mysterious linkage between config/../*.cfg and Spring dependency injection

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#2958]
**Describe the bug**
If there is a configuration property `foo.bar` and a Bean `some.Clazz` with `id="foo"` then instantiating the Bean causes *something* to try to call `some.Clazz.setBar(String)`, even though no such property is mentioned in the ApplicationContext.

The culprit is DSpaceBeanPostProcessor, which Spring calls during Bean instantiation.  I asked, and nobody recalled why it does this.  It may be left over from when dspace-services had the never-used ability do DI with Guice instead of Spring.

**To Reproduce**
1. create a DSpace configuration property with a dotted name like `this.that`.
1. define a Bean which has the `id` equal to the part of the DSpace property name before the first dot (e.g. `this`), and which is embodied by a class which does *not* have a property with a name equal to the part of the DSpace property *after* the first dot (e.g. `that`).  Configure it for eager instantiation.  Do *not* give it a `<property>` with that name.
1. start DSpace and you should log a failure to instantiate the bean, noting a missing setter.

**Expected behavior**
Spring should not complain about mysterious properties that were not defined to it.

**Related work**
Link to any related tickets or PRs here.

**Comment by mwoodiupui** [comment]
I saw this while working on something else, and tracked it down to a Bean with `id = "curate"`.  We have a number of `curate.*` properties set in `config/modules/curate.cfg`.

**Comment by tdonohue** [comment]
Fixed by #2968
