### ISSUE TITLE
DSpaceBeanPostProcessor duplicates Spring features

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#2967]
`DSpaceBeanPostProcessor` is responsible for calling methods on implementations of `InitializedService` and `ShutdownService`, which are intended to initialize an instance after dependency injection and to clean up resources no longer used when we are done with the instance.  These actions duplicate the standard `@PostContstruct` and `@PreDestroy` methods defined in `javax.annotation`.  Spring understands the standard annotations.  The duplication is confusing and wasteful.  We should remove the post processor and the duplicative interfaces.

**Comment by tdonohue** [comment]
Fixed by #2968
