### ISSUE TITLE
Features endpoint - Permissions to view stats, map items, see versions

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#2969]
**Is your feature request related to a problem? Please describe.**
DSpace 6 statistics links are only displayed depending permissions configured in https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/usage-statistics.cfg#L26-L31, and are not always accessible to all
DSpace 6 item mapping features is only available if the user has ADD and WRITE permissions to the current collection
DSpace 6 versioning details are only displayed if configured in https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/versioning.cfg#L11

**Describe the solution you'd like**
Based on https://docs.google.com/spreadsheets/d/1182LcD_WqIZRbUGWpLtBw0aOMR9jhbOVB7GZqtTpR9A/edit#gid=0, implement the features:
* canViewUsageStatistics
* canViewWorkflowStatistics
* canViewSearchStatistics
* canManageMappedItems
* canViewVersions

**Comment by tdonohue** [comment]
@benbosman : Looks good to me. I've assigned this to you & added to the Beta 5 board. Feel free to reassign internally as you see fit.
