### ISSUE TITLE
Create a script which can reset `dspace.agreements.end-user` metadata field whenever the User Agreement changes.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2973]
**Is your feature request related to a problem? Please describe.**
Based on discussion in https://github.com/DSpace/dspace-angular/pull/862#issuecomment-694173128

If a site changes/modifies the "User Agreement" text, the administrator would need a way to "reset" the `dspace.agreements.end-user` for all EPersons.  Currently, when an EPerson agrees to the "User Agreement", this metadata field is set to `true`. They no longer see the "User Agreement" after that point. 

**Describe the solution you'd like**
A Script should be created which can delete this `dspace.agreements.end-user` field (or set to `false`) for all EPersons.  This will force EPersons to then read the Agreement again and accept it again.  This script would need to be triggered manually whenever an Administrator knows they've made major modifications to the User Agreement which require users to agree to it again.

This Script should ideally support the Scripts & Processes framework. That would allow it to be run from *either* the CLI or from the Admin UI. 

**Describe alternatives or workarounds you've considered**
For the time being, a valid workaround is to remove this `dspace.agreements.end-user` field (or set them all to `false`) using SQL queries on database.

**Comment by tdonohue** [comment]
@LucaGiamminonni : I know you expressed interest in this ticket in your comments here https://github.com/DSpace/dspace-angular/pull/862#issuecomment-694220008  Should we assign this to you?  (Keep in mind, this work is not required immediately as it is not scheduled until Beta 5.)

**Comment by LucaGiamminonni** [comment]
@tdonohue yes I can work on it

**Comment by abollini** [comment]
@tdonohue estimation added. Please note that we have already done some work on that so we would appreciate to be assigned to it

**Comment by tdonohue** [comment]
Thanks @abollini : I'll go ahead and assign this back to @LucaGiamminonni as it was previously. The estimate looks fine to me
