### ISSUE TITLE
DSpace 6.3 searching for bitstream identifier

### ISSUE THREAD

**Issue by stuartayeates** [DSpace/DSpace#2976]
**Describe the bug**
Searching for the bitstream identifier returns no results and returns a recommended search which also returns no results. 

**To Reproduce**
1. Find a bitstream identifier (I used "f705a8ce-485f-4c4e-ae8e-7b9fc13cffad" from the media extraction cronjob)
2. Search for it in GUI
3. Notice that there are no results. 
4. Notice that there's a "Did you mean:" search for a very similar string (usually one character different, which one depends on the exact identifier used)
5. Click in the recommendation
6. Notice that the recommended search doesn't have any hits either.

**Expected behavior**
(a) Items should be findable by their bitstream and other identifiers
(b) Recommended searches should return items.

**Comment by tdonohue** [comment]
This sounds like a "new feature" request to me.  I don't believe bitstream Identifiers are currently indexed in DSpace 6.x (or above).  So, I suspect that's why they do not work in searches.
