### ISSUE TITLE
Default Proxy settings should automatically use CORS settings

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2984]
**Describe the bug**
Setting up the Angular UI to run on a separate hostname from the REST API is unnecessarily difficult.  This is especially true with the Proxy and CORS settings which are similar in nature.

More specifically, our default proxy settings include:
```
# Proxies are enabled by default to support Angular Universal (SSR)
useProxies = true
# Trusted, comma separated list of IPs.  It's recommended that this include minimally the IP address of the Angular UI
proxies.trusted.ipranges = 127.0.0.1
```

Somewhat similarly, the CORS settings include:
```
# Trusted, comma separated list of origins/clients.  This defaults to minimally including the URL of the Angular UI
rest.cors.allowed-origins = ${dspace.ui.url}
```

**Expected behavior**

* Either, `proxies.trusted.ipranges`  should automatically default to the IP addresses of the URLs specified in `rest.cors.allowed-origins`
* OR, alternatively, we could think of removing `proxies.trusted.ipranges` altogether, replacing it with `rest.cors.allowed-origins`.  In this approach, we'd recommend that the Proxy server be added to the list of `allow-origins` in order for it to be "trusted".

I lean slightly toward the latter approach, as it seems like any origin which is "trusted" by CORS should also be trusted as a Proxy.

**Comment by tdonohue** [comment]
NOTE: This `proxies.trusted.ipranges` setting is new with DSpace 7.  It was added for additional security in https://github.com/DSpace/DSpace/pull/2207 *before* we added CORS support.

**Comment by tdonohue** [comment]
@benbosman and/or @abollini : I'd be interested in your feedback on this ticket.  I created this a month or so back, and I still wonder if it's worth *dropping* the `proxies.trusted.ipranges` setting altogether (in favor of managing everything via CORS).  That said, if either of you see flaws with that approach, I'd be interested in feedback.

**Comment by vahem2lu** [comment]
This is definitely a thing for me (as an user), because even running them on same host with local IP (not 127.0.0.1/localhost) this proxies.trusted.ipranges breaks login entirely.

**Comment by batpurev** [comment]
Dear @tdonohue and All,

I am newbie to Dspace. I installed Dspace 7.4 on ubuntu 22.04 LTS.  Got following dependency warnings. Will these warnings have effect on the normal operation? Sorry for my noob question.

Thanks.
Bp

complete list of warnings.

```
dspace@localhost:~/dspace-angular-dspace-7.4$ yarn add install-peers
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @nicky-lenaers/ngx-scroll-to@9.0.0" has incorrect peer dependency "@angular/common@^8.0.0 || ^9.0.0".
warning " > @nicky-lenaers/ngx-scroll-to@9.0.0" has incorrect peer dependency "@angular/core@^8.0.0 || ^9.0.0".
warning " > @nicky-lenaers/ngx-scroll-to@9.0.0" has incorrect peer dependency "tslib@^1.10.0".
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
warning " > ngx-sortablejs@11.1.0" has incorrect peer dependency "@angular/common@^11.0.0".
warning " > ngx-sortablejs@11.1.0" has incorrect peer dependency "@angular/core@^11.0.0".
warning " > ngx-ui-switch@11.0.1" has incorrect peer dependency "@angular/core@>=5.0.0 <12.0.0".
warning " > ngx-ui-switch@11.0.1" has incorrect peer dependency "@angular/common@>=5.0.0 <12.0.0".
warning " > ngx-ui-switch@11.0.1" has incorrect peer dependency "@angular/forms@>=5.0.0 <12.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
└─ install-peers@1.0.4
info All dependencies
├─ executioner@2.0.1
├─ fulcon@1.0.2
├─ install-peers@1.0.4
└─ mixly@1.0.0
Done in 14.78s.
```

**Comment by tdonohue** [comment]
@batpurev ; This is not a support area. this is an old ticket for a feature that was built in 2020/2021. We will not answer unrelated support questions on closed issue tickets.  If you require support, please use one of our public support options listed at https://wiki.lyrasis.org/display/DSPACE/Support

**Comment by batpurev** [comment]
@tdonohue Plz accept my apologies, thank you so much.
