### ISSUE TITLE
Facet filters in search page display wrong number

### ISSUE THREAD

**Issue by MarisArins** [DSpace/DSpace#3011]
Can be repeated on https://dspace7-demo.atmire.com/

1. Go to demo site global search page and open Author filter:
2. 2nd author , "De Wael, Karolien" has a number 8 next to it, meaning there would be 8 matches when filtered
3. When selecting this filter value there are 9 results displayed in list.

Similar mismatch was observed on different filters (local setup, standard test data)

![image](https://user-images.githubusercontent.com/2697696/89540619-f9774200-d805-11ea-87f0-a1a886b4b05f.png)

![image](https://user-images.githubusercontent.com/2697696/89540705-14e24d00-d806-11ea-9d07-3767d5619e2e.png)

**Comment by tdonohue** [comment]
May be related loosely to #3010, but this ticket is more specific to **name variants** on authors & how those are indexed in Solr.  So, it's unclear if it would be solved by #3010.

**Comment by tdonohue** [comment]
Retested this today and it appears resolved.  At least it's no longer reproducible on the demo site https://demo7.dspace.org/ as described in the description. Closing as fixed.  If someone is able to later reproduce we can always reopen

**Comment by SrinivasRao17** [comment]
I have query which is similar to above.
My query is when i search for any particular metric it will display all metric related to the matching names.
For example if i search for "Test $" behalf of showing test $ on first it will display all the matching names to "Test" then somewhere it will be display "Test $" for that i need to search page by page.

Can you please help/guide me how can we get accurate result when we search for particular metric?

**Comment by SrinivasRao17** [comment]
If you see in the attached test file.
i have entered "Collection Test 07" but i got multiple results. Can we get exact result for searched metrics.

![image](https://user-images.githubusercontent.com/101823122/183089899-7dfe810d-6116-450a-8ca0-828633ebcdb8.png)

**Comment by tdonohue** [comment]
@SrinivasRao17 : The best place to ask support questions is using one of our Support options listed at https://wiki.lyrasis.org/display/DSPACE/Support

A quick answer to your question though is to use quotes for more exact matching:
* Searching `Collection Test 07` will find any items which include any of those words (but the ones that include all three words will appear closest to the top)
* Searching `"Collection Test 07"` with find only items that include the exact phrase "Collection Test 07" (in the title, description, etc)
