### ISSUE TITLE
LCNameDataProvider's service is archived

### ISSUE THREAD

**Issue by Raf-atmire** [DSpace/DSpace#3019]
**Describe the bug**
Currently the http://alcme.oclc.org/srw/search/lcnaf site is down and the service is unavailable. This means that any call to LCNameDataProvider is going to fail as it cannot reach the data that it's supposed to.
This is because this project is archived, which can be seen on this link: https://www.oclc.org/research/archive/projects/authority.html

**To Reproduce**
1. Navigate to http://alcme.oclc.org/srw/search/lcnaf

**Possible fixes**
- Remove the LCNameDataProvider if it's never going to work
- Temporarily disable this feature and look into if we can re-enable it in the future. The possibly new url can be found here: https://authorities.loc.gov/cgi-bin/Pwebrecon.cgi?DB=local&PAGE=First

**Comment by mwoodiupui** [comment]
Exactly how does the provider fail?  If it fails gracefully, then this is an annoyance but not a bug.  If it makes mistakes or throws a stack trace at the user or says nothing useful, that is a bug.  *All network providers should fail gracefully if the remote service is down or crazy.*

**Comment by Raf-atmire** [comment]
It does fail gracefully, but the service isn't just down. The service is gone, it won't ever be available again.

**Comment by tdonohue** [comment]
@Raf-atmire : have you looked at all at whether the "LC Authorities" (https://authorities.loc.gov/cgi-bin/Pwebrecon.cgi?DB=local&PAGE=First) is an easy replacement? 

* If LC Authorities is essentially just the same service (similar return format, etc) but just renamed, then I'd lean towards quickly fixing our `LCNameDataProvider` to use the new service.
* If LC Authorities is a completely different service, that implies to me that `LCNameDataProvider` is now "useless code" & we should remove it & create a new ticket to develop a new DataProvider for "LC Authorities".

I'd appreciate any thoughts/analysis you have here & I haven't had the chance to look closely at this myself yet.

**Comment by Raf-atmire** [comment]
@tdonohue I've quickly checked the parameters for both endpoints and they're different already. "query" in the old service is new "Search_Arg" in the new service for example. This means that it at the very least won't be a simple "change the URL" case

**Comment by tdonohue** [comment]
Thanks @Raf-atmire ! In that case, I'd agree with your initial recommendation that we should just **remove** the `LCNameDataProvider` at this time, since the backend service is unavailable.

I've tentatively moved this over to Beta 5 as necessary cleanup.  Would you be willing to provide an estimate for this work, @Raf-atmire ?

**Comment by Raf-atmire** [comment]
@tdonohue I estimate this to be 2 hours of work. This includes the removal of the LCNameDataProvider class and code specific to it, as well as removing it from the xml files, combined with proper testing
