### ISSUE TITLE
In 6.3 Embargo item shows up in browse and search

### ISSUE THREAD

**Issue by blancoj** [DSpace/DSpace#3022]
In version 6.3  and using the demo site ( http://demo.dspace.org/xmlui/), I logged in as Admin and deposited an item and placed an embargo on the item.  I did not mark it as private.  The item received the appropriate permissions.  I checked this from the Authorization page, but using the title I was able to search and browse to the item.  When I tried to open the item, I was given the item restricted message, but I was still able to find the item using the UI.  Embargo items should not be discoverable until the embargo period ends.  Here is the item on the demo:

http://demo.dspace.org/xmlui/handle/10673/111

**To Reproduce**
1. Deposit an item and make it embargo.  Do not make it private.
2. You will notice that the item shows up in Recent Deposit area from the home url.
3. Search for the item, and notice that the item shows up.
4. Try to browse to the item using the title and/or author and notice that the item shows up.
5.  Use a facet to try to get to the item, and notice that the item shows up.  I tried it with the Author facet and saw it show up.

**Expected behavior**
When an item is placed under embargo, and not marked as private, it should not be discoverable.  Users should not be able to see the item as part of a search or from a browse, or facet.  It should not show up as part of OAI or RSS or REST until the embargo period ends.  It really should be treated as if it were WITHDRAWN until the embargo period ends.

**Comment by tdonohue** [comment]
I've linked this up to the 7.x ticket related to Full Item embargo #2839 , as I think it may be fixable in 7.x.
