### ISSUE TITLE
findSubmitAuthorized endpoint for collections returning wrong amount of objects

### ISSUE THREAD

**Issue by Atmire-Kristof** [DSpace/DSpace#3025]
**Describe the bug**
When querying the `api/core/collections/search/findSubmitAuthorized` endpoint with a page number other than the first page and a custom page size, the amount of returned objects do not match the requested amount.

**To Reproduce**
1. Visit the endpoint with page set to 1 and size set to 5, for example: https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/core/collections/search/findSubmitAuthorized?page=1&size=5&query=t
2. The resulting amount of objects is higher than 5

**Expected behavior**
Expecting the resulting amount of objects to be equal or smaller than (in case of the last page) the requested page size.

**Comment by tdonohue** [comment]
@abollini : Could you or @Micheleboychuk look into this and provide an estimate for fixing this bug?  It looks like this code was added in #2771 which was created by your team, so you might be able to provide a quick estimate.

**Comment by abollini** [comment]
it is the same type of issue than #3032 and #3033 it could be faster if the same developer can work on all of them.
For this single task I estimate 2-3 hours. Can we be assigned of al the three tasks @tdonohue ?

**Comment by tdonohue** [comment]
@abollini : Sounds good. Assigning all three to you (for your team) and moved to "in progress".  Thanks!

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/DSpace/pull/3050
