### ISSUE TITLE
Enforce that facet "filter-operator" is a valid value

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3027]
_Originally posted by @KevinVdV in https://github.com/DSpace/dspace-angular/issues/915#issuecomment-713540955_

In https://github.com/DSpace/dspace-angular/issues/915, an invalid request is being sent from the Angular UI to the REST API because the "operator" appears to be missing.

On the REST side we should be enforcing the operator to have a valid value (for the request in https://github.com/DSpace/dspace-angular/issues/915 the operator would be "kb" which is invalid). What I would suggest is to return a bad request if the operator is missing or invalid.

I think the work for this is half a day (the change is small but we would also require tests)

**Comment by KevinVdV** [comment]
Dropping a note in here for myself (so I don't forget), if we have a "date" facet than the operator doesn't need to be mandatory, else the query will differ too much from what we need.
