### ISSUE TITLE
pagination for eperson/epersons/search/byMetadata method doesn't work properly

### ISSUE THREAD

**Issue by atarix83** [DSpace/DSpace#3033]
**Describe the bug**
If I make a request to `api/eperson/epersons/search/byMetadata` the pagination works properly only for the first page. Indeed if I make a request for a page after the first I get a number of results which are twice as many as required

**To Reproduce**
It can be verified directly on the demo server:
1. login as admin through hal browser https://dspace7.4science.cloud/server 
2. make a new request for the first page, and verify the server return 10 results : https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/eperson/epersons/search/byMetadata?page=0&size=10&query=
3. make a new request for the second page, and verify the server return 20 results instead of 10 : https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/eperson/epersons/search/byMetadata?page=1&size=10&query= 

**Expected behavior**
It should return the exact number of results for every page requested

**Comment by abollini** [comment]
it is a bug on the repository implementation. Tests need to be added to demonstrate the bug and avoid regression. Estimation 3hrs

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/DSpace/pull/3050
