### ISSUE TITLE
Collection Resource endpoints don't include pagination information in the self link

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#3044]
**Describe the bug**
All the collection resource endpoints, i.e. /api/core/communities /api/core/items etc don't contains information about the pagination in the self link.
This is similar to https://github.com/DSpace/DSpace/issues/2919 and was noted in the discussion of the related PR https://github.com/DSpace/DSpace/pull/3030#pullrequestreview-523273601

**To Reproduce**
1. https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/core/communities?page=1&size=20
2. Then the self link will be https://dspace7.4science.cloud/server/api/core/communities losing the details about page and size

**Expected behavior**
The self link should reflect the original request

**Comment by tdonohue** [comment]
Thanks for adding this @abollini & adding an estimate. I've added this to our beta 5 board.

**Comment by abollini** [comment]
@tdonohue can we work on that?

**Comment by tdonohue** [comment]
Sure, assigning to you (for your team) and moving to "in progress".  Thanks @abollini !
