### ISSUE TITLE
Self link of the top community search endpoint doesn't contain pagination info

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#3052]
**Describe the bug**
The [/communities/search/top endpoint](https://github.com/DSpace/Rest7Contract/blob/main/communities.md#top) doesn't take the pagination info in to account for its self link. Every page has the same self link. 

**To Reproduce**
* Go to [the top communities search endpoint](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/core/communities/search/top)
* Note the self link
* click the next link
* Verify that the self link hasn't changed

**Expected behavior**
The self link should contain any paramaters that affect the response.

**Related work**
I noticed this while working on https://github.com/DSpace/dspace-angular/issues/739. It means caching can never work properly for this endpoint.

**Comment by tdonohue** [comment]
@abollini & @Micheleboychuk : This sounds similar to the work done in #3050   Would one of you be able to provide an estimate for this?  It seems like something we should resolve in Beta 5.

**Comment by artlowel** [comment]
Closing, as this is fixed on the demo server now. Due to https://github.com/DSpace/DSpace/pull/3030 I expect.
