### ISSUE TITLE
SWORD error: Unable to recognize URL as a valid service document 

### ISSUE THREAD

**Issue by carlj11** [DSpace/DSpace#3053]
Hi,  

I’m on 7.0-beta5-SNAPSHOT and enabled SWORD v2 in config/modules/swordv2-server.cfg. My SWORD URL string is:

   curl -i --user carlj@mit.edu http://libme25-0492221.mit.edu:8080/server/swordv2/servicedocument 

Redeployed/restarted Tomcat but getting the following ‘unable to recognize URL’ error when trying to confirm if SWORD is working:

Unable to recognise URL as a valid service document: http://libme25-0492221.mit.edu:8080/server/swordv2/servicedocument

	curl -i --user carlj@mit.edu http://libme25-0492221.mit.edu:8080/server/swordv2/servicedocument 
Enter host password for user 'carlj@mit.edu’: 

HTTP/1.1 400 Content-Language: en Content-Type: text/xml;charset=UTF-8 Transfer-Encoding: chunked Date: Tue, 10 Nov 2020 23:04:11 GMT Connection: close <?xml version=“1.0” encoding=“ISO-8859-1"?> <sword:error href=“http://www.dspace.org/ns/sword/2.0/errors/BadUrl” xmlns:sword=“http://purl.org/net/sword/terms/”><atom:title xmlns:atom=“http://www.w3.org/2005/Atom”>ERROR</atom:title><atom:updated xmlns:atom=“http://www.w3.org/2005/Atom”>2020-11-10T18:04:11Z</atom:updated><atom:generator uri=“http://www.dspace.org/ns/sword/2.0/” version=“2.0" xmlns:atom=“http://www.w3.org/2005/Atom”>carlj@mit.edu</atom:generator><sword:treatment>Processing failed</sword:treatment><atom:summary xmlns:atom=“http://www.w3.org/2005/Atom”>Unable to recognise URL as a valid service document: http://libme25-0492221.mit.edu:8080/server/swordv2/servicedocument</atom:summary><sword:verboseDescription>org.swordapp.server.SwordError: Unable to recognise URL as a valid service document: http://libme25-0492221.mit.edu:8080/server/swordv2/servicedocument at org.dspace.sword2.SwordUrlManager.extractDSpaceObject(SwordUrlManager.java:285) at org.dspace.sword2.ServiceDocumentManagerDSpace.getServiceDocument(ServiceDocumentManagerDSpace.java:152) at org.dspace.sword2.ServiceDocumentManagerDSpace.getServiceDocument(ServiceDocumentManagerDSpace.java:72) at org.swordapp.server.ServiceDocumentAPI.get(ServiceDocumentAPI.java:56) at org.swordapp.server.servlets.ServiceDocumentServletDefault.doGet(ServiceDocumentServletDefault.java:32)

I’ve also enabled SWORD v1 with similar results.   Is anyone else having this issue?

Thanks

**Comment by carlj11** [comment]
OK, 'fixed' by explicitly defining the servicedocument URL in modules/swordv2-server.cfg 

In my case this is:

swordv2-server.servicedocument.url = http://libme25-0492221.mit.edu:8080/swordv2/servicedocument

Which we'd actually tried earlier and restarted Tomcat to no effect (thinking the change didn't work).   Needed to do a fresh install for the change to be recognized  (mvn package, ant fresh_install, restart Tomcat) and I got the appropriate response.

**Comment by carlj11** [comment]
Closing.  Was also able to successfully submit to a collection. 

Maybe more documentation on the need not only to enable SWORD but also to uncomment and explicitly define swordv2-servicedocument.url in swordv2-server.cfg as the default setting doesn't seem to be sufficient. Ditto, I think, for swordv2-server.collection.url.

**Comment by tdonohue** [comment]
Reopening.  @carlj11 : I'd like to keep this open a bit longer as it is *unexpected* to me that you **must** configure `swordv2-server.servicedocument.url` in order for SWORDv2 to work.  The expected behavior is that there is a "sane default" value for that configuration (if unspecified).  So, that makes me expect the code which determines the "sane default" might be flawed here.

Nonetheless, it's good to hear that there's an easy workaround to simply set `swordv2-server.servicedocument.url`.  That means this ticket is slightly lower priority, but I still believe this is likely pointing out a flaw in our current SWORDv2 code which needs more investigation.

**Comment by tdonohue** [comment]
Moving this to 7.0, but flagging as `low priority` as it can be worked around via configuration. Nonetheless, I'd like to fix this in 7.0 if we have time.  Assigned to myself to analyze as this is an area of the code I've worked in more than others.

**Comment by tdonohue** [comment]
Might be fixed by #3335

**Comment by J4bbi** [comment]
Just to note that this appears to be an issue for 6.4 as well.
