### ISSUE TITLE
Search links in facet values don't contain the configuration

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#3057]
**Describe the bug**
If you retrieve facet values for a discovery search with a particular configuration, the search links for those values don't contain that configuration. As a consequence if the UI uses that link to update the search results, the results will no longer match the configuration, or REST may throw an exception if that facet doesn't work for the default configuration

**To Reproduce**
1. Sign in to the hal browser as an admin
2. Retrieve the `discoverable` facet with the `administrativeView` configuration: https://dspace7.4science.cloud/server/#/server/api/discover/facets/discoverable?page=0&size=10&sort=score,DESC&page=0&size=10&configuration=administrativeView
3. Take a look at the search links for the returned values, they don't contain the configuration
4. If you follow a search link you'll get an exception because the discoverable filter isn't configured for the default configuration

**Expected behavior**
The search links should contain all paramaters from the original request that affect the search results. Note that configuration may not be the only one that is needed. It's just the one I noticed was missing.

**Related work**
This came up during the work on https://github.com/DSpace/dspace-angular/issues/915

**Comment by artlowel** [comment]
The same issue exists for the self links of the results on the `/discover/facets` endpoint:
If you [retrieve the facets for configuration=person](https://dspace7.4science.cloud/server/api/discover/facets?configuration=person), the self links of the results won't contain the configuration, and therefore won't work.

**Comment by tdonohue** [comment]
@abollini & @Micheleboychuk : This is also loosely similar to #3050 (though it's a different param than pagination). Again, would one of you be able to provide an estimate for this?  It seems like something we should resolve in Beta 5.

**Comment by artlowel** [comment]
I tested this again today, because the similar issue #3052 was fixed by deploying #3030 on the demo server. But the issues reported here still remain.

**Comment by abollini** [comment]
It is hard to estimate this task without going really deeper up to his resolution. Unfortunately the Discovery endpoints have followed a very custom approach outside the normal approach of REST resource/repository.
Looking to the sample provided here I see that the configuration is also missing in the json properties of the response and this seems to be common to all the discovery endpoints.

My best guess for this task is between 4-12 hours, we can work on that if you wish and we can provide an updated estimation after the first 4 hours

**Comment by tdonohue** [comment]
@abollini : Apologies for not getting back on this.  Yes, that sounds fine to provide an updated estimate after the first 4 hours of work.  For now, I'll add a **8hr** estimate (median), and assign this to you for your team to work on.  Thanks!
