### ISSUE TITLE
OAI-PMH contexts index page doesn't look good when accessed without /

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#3059]
**Describe the bug**
If you access the base url of the OAI-PMH server without specifying any context and omitting the last / you will get an unstylised html page

**To Reproduce**
https://dspace7.4science.cloud/server/oai

**Expected behavior**
The page should looks good with or without the ending /, compare with
https://dspace7.4science.cloud/server/oai/

**Reason / troubleshooting**
The issue is due to the use of wrong URL to access the bootstrap CSSs and JQuery as they hardcode a "../". A fix would require to get the full URL of the oai endpoint or at least the context path from the controller so that it can be used in the jtwig template

**Comment by tdonohue** [comment]
Agreed, this is a bug.  But, it seems low priority, so I'm adding this to 7.2.  If we get to it earlier, that's fine.
