### ISSUE TITLE
Self links contain embed params

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#3062]
**Describe the bug**
https://github.com/DSpace/DSpace/pull/3030 has fixed most of the issues with self links that didn't contain all relevant parameters, but it seems to have introduced a new bug: embed parameters are now included in the self link. Since they don't affect the resource itself, only which _other_ resources are also included in the response, they should not be included.

**To Reproduce**
1. Retrieve any resource with an embed param. e.g. [this authorization ](https://dspace7.4science.cloud/server/#https://dspace7.4science.cloud/server/api/authz/authorizations/search/object?uri=https://dspace7.4science.cloud/server/api/core/sites/6d65c6a2-3fe7-44dd-bacb-79271257c35d&feature=epersonRegistration&embed=feature
)
2. Observe that, while the self link now contains all required params, it also contains the embed params

**Expected behavior**
The self link for a HAL resource should contain the parameters that have a (possible) effect on that resource but it shouldn't contain parameters that can't affect it.

**Related work**
This issue seems to have been introduced by https://github.com/DSpace/DSpace/pull/3030

**Comment by tdonohue** [comment]
This does sound like a bug to me. Thanks @artlowel .  I've flagged this as needing an estimate and added to beta 5.
