### ISSUE TITLE
When you retrieve an entity type by label it doesn't have a _links section

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#3089]
**Describe the bug**
When you retrieve an EntityType [by label](https://github.com/DSpace/Rest7Contract/blob/main/entitytypes.md#get-entity-type-from-label) it's missing the `_links` section

**To Reproduce**
1. Retrieve the list of entity types: e.g. https://dspace7.4science.cloud/server/api/core/entitytypes
2. Verify that all of them have a _links section with a self link
3. Retrieve any entity type by label. e.g. https://dspace7.4science.cloud/server/api/core/entitytypes/label/Person
4. Verify that there is no links section

**Expected behavior**
Any resource returned by a GET request should have `_links` section with a unique self link

**Related work**
I noticed this issue when reviewing https://github.com/DSpace/dspace-angular/pull/965, which replaces the hardcoded list of entity types with requests to the backend to fetch them.

**Comment by AndrewZWood** [comment]
Updated the related controller to return a REST resource which will include the required _links: https://github.com/DSpace/DSpace/pull/3079

**Comment by artlowel** [comment]
Closing, duplicate of https://github.com/DSpace/DSpace/issues/3078
