### ISSUE TITLE
Bitstream format cannot be retrieved if you don't have read rights on the file 

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#3090]
**Describe the bug**
When you make a file private (or add an embargo to it) and you aren't logged in (or if you are logged in but without read rights to the file)  the format of the file isn't displayed on the full item view page.

This is because the format endpoint doesn't allow you to retrieve the format if you don't have read rights to the file.

The url that is being used for that request is: 
> /server/api/core/bitstreams/{id}/format

**To Reproduce**
1. Upload a file to an item
2. Add an embargo to it, or make it admin only by removing the anonymous read rights
3. Go to the full item view page & the format won't be there

**Expected behavior**

The format should be able to be displayed even if you don't have read rights to the actual file.

**Comment by tdonohue** [comment]
Thanks for this @KevinVdV .  I agree this sounds like a bug we need to fix.  Would you be able to provide an estimate for what this might take/require?  My assumption is this might be a small change to the endpoint permissions, unless I'm misunderstanding.

**Comment by benbosman** [comment]
I would expect a small change as well, but it should also have sufficient ITs
Including tests, I would expect 3 hours of work

**Comment by tdonohue** [comment]
Thanks @benbosman .  Added that estimate to the ticket
