### ISSUE TITLE
OpenAIRE 4 crosswalk for datacite:rights only using first dc:rights value found

### ISSUE THREAD

**Issue by uofmsean** [DSpace/DSpace#3097]
**Describe the bug**
If there are multiple dc:rights metadata values, only the first one is used for conversion to a valid OpenAIRE 4 Access Rights (datacite:rights) element.

**To Reproduce**
Add two dc:rights metadata values to an item, with the first one having a value of something like "Test rights" and the second one having a valid OpenAIRE 4 value (e.g., "open access"). Accessing the openaire4 OAI context using metadataPrefix=oai_openaire will only show a single datacite:rights element that has an empty rightsURI attribute and a value of "Test rights". The second valid OpenAIRE 4 dc:rights value is ignored. Reversing the order of the values will result in the correct datacite:rights element being produced.

**Expected behavior**
The first valid OpenAIRE 4 Access Rights (datacite:rights) value from the dc:rights metadata should be taken. It is safe to ignore other valid OpenAIRE 4 values since the specification states only one is allowed.

**Related work**
N/A

**Comment by uofmsean** [comment]
The three key lines in oai_openaire.xsl that need to be addressed are: [531](https://github.com/DSpace/DSpace/blob/c1e97188f99b7e98f295feeb2a501e65fd581668/dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl#L531), [540](https://github.com/DSpace/DSpace/blob/c1e97188f99b7e98f295feeb2a501e65fd581668/dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl#L540), and [1011](https://github.com/DSpace/DSpace/blob/c1e97188f99b7e98f295feeb2a501e65fd581668/dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl#L1011)

The XPath in the getRightsURI template (line 1011) needs to be addressed since it assigns the oaire:file accessRightsURI for the bitstreams.

One potential fix in the XPaths that I tested is to use:
`@name='value' and ends-with(translate(text(), $uppercase, $smallcase),' access')`
instead of just:
`@name='value'`

It is not a perfect solution since there's a chance some non-OpenAIRE dc:rights fields might end in ' access' (note the extra space at the beginning). The translate was used to match how resolveRightsURI works. If one could assume that only perfect values are allowed ('open access', 'embargoed access', 'restricted access', 'metadata only access') then the XPath could just check for those values.

**Comment by tdonohue** [comment]
@paulo-graca : also interested in your feedback on this ticket.

**Comment by paulo-graca** [comment]
Thank you @uofmsean!
I will give a closer look as soon as possible (It will be my season holidays).

But I just want to leave a note that OpenAIRE Access Rights can only have one single occurrence:
https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_accessrights.html

but I will take a closer look to what you propose.

**Comment by uofmsean** [comment]
That's right, there can be only one occurrence of datacite:rights for OpenAIRE, but there might be multiple dc:rights values for one item in DSpace. The XSL is only picking up the first one found, and if it's not the OpenAIRE 4 one, it will produce an incorrect datacite:rights element.

**Comment by paulo-graca** [comment]
@uofmsean I've just created #3106 to address this. I would also appreciate your feedback in it!

Despite it's a simple solution and I'm ok with it, I just think it will be a workaround for repositories that aren't using openaire setup (like openaire specific forms) and will always encounter issues like this one. In my humble opinion, a better approach is using specific and proper validation mechanisms that can help and guide repository managers to fix metadata in items.

**Comment by uofmsean** [comment]
@paulo-graca A similar change is needed for the [getRightsURI template](https://github.com/DSpace/DSpace/blob/c1e97188f99b7e98f295feeb2a501e65fd581668/dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl#L1007-L1013) since it also uses the dc:rights to assign the oaire:file accessRightsURI attribute for each bitstream. One thing to note is that the (now rejected) [PR 2709](https://github.com/DSpace/DSpace/pull/2709) backport for 6.x is extracting per-bitstream accessRightsURI using [PermissionElementAdditional](https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-oai/src/main/java/org/dspace/xoai/app/PermissionElementAdditional.java) instead of just assigning all of them from a single dc:rights value. The accepted [PR 2859](https://github.com/DSpace/DSpace/pull/2859) for 6.x has the capability but not the oai_openaire.xsl changes (leaving it up to repository managers to decide on implementation). I'm not sure how per-bitstream accessRightsURI would be assignable with DSpace 7 though.

**Comment by paulo-graca** [comment]
Thank you @uofmsean ! I've just updated the PR with getRightsURI change.

I think further XOAI support, like the permissions you refer, should be considered always accounting for performance aspects. I think that might be the case on the referred PR (please mind that at XSL level you already need to have objects available to render the full XML and you might not need all of them) and I agree that should be repository managers to decide.

**Comment by paulo-graca** [comment]
@tdonohue I've added your comment (it was better than the one I've first added). And @uofmsean, I've fixed the issue with multiple dc:rights. Thank you so much for testing it!
