### ISSUE TITLE
OpenAIRE 4 relatedIdentifier being used for all dc:identifier:* metadata other than dc:identifier:uri

### ISSUE THREAD

**Issue by uofmsean** [DSpace/DSpace#3099]
**Describe the bug**
datacite:relatedIdentifier element being used for all dc:identifier:* metadata other than dc:identifier:uri. Not all dc:identifier:* values can be assumed to be relatedIdentifier and may be alternateIdentifier instead.

**To Reproduce**
Access an openaire4 OAI record for an item that has many different dc:identifier:* values. Every one other than dc:identifier:uri will show up as datacite:relatedIdentifier elements.

**Expected behavior**
When it isn't known for sure that the dc:identifier:* value is actually a relatedIdentifier value, perhaps it is better to assume it is an alternateIdentifier by default. This follows the approach originally included with the proposed [PR 2709](https://github.com/DSpace/DSpace/pull/2709) for DSpace 6.x that used alternateIdentifier, except for the case of dc:identifier:issn that was handled separately as a relatedIdentifier. Another common use case is with dc:identifier:doi being an externally-generated DOI for the item (i.e., not generated by DSpace automatically) and being an alternateIdentifier to the DSpace Handle. 

**Related work**
See discussions from:
[PR 2576](https://github.com/DSpace/DSpace/pull/2576) (specifically [this comment](https://github.com/DSpace/DSpace/pull/2576#issuecomment-559110676))
[DS-3708](https://jira.lyrasis.org/browse/DS-3708)

**Comment by tdonohue** [comment]
@paulo-graca : pinging you on this to get your feedback since you created the initial implementation here.  This seems reasonable to me, but I don't know if you foresee problems with this approach.

**Comment by paulo-graca** [comment]
Thank you so much @uofmsean for testing this out. I will take a closer look as soon as possible.

You are right, we decided what's in this post:
https://github.com/DSpace/DSpace/pull/2576#issuecomment-559110676

If the result is different, to me it can only be one of two things: there is a bug, or the schema used it's poor and it's not the OpenAIRE 4 (please check: https://wiki.lyrasis.org/display/DSDOC7x/OpenAIRE4+Guidelines+Compliancy for more details)

**Comment by paulo-graca** [comment]
@uofmsean I've just created PR #3107 to address this issue. Some of the approaches referred might need further discussion. For instance, `dc.identifier.doi` will be a custom change. So, any support for it should be also custom. Also the relation type might require a proper field type (complex field), so we are assuming that all supported related identifiers have the relation type `isPartOf`. And alternate identifiers will be mapped from dc.identifier.uri (the case of DSpace registered DOIs when you already have an Handle)
