### ISSUE TITLE
Exception messages from a failed REST request are not properly displayed in the response

### ISSUE THREAD

**Issue by benbosman** [DSpace/DSpace#3101]
**Describe the bug**
The response of a failed REST request with status 422 won't include the description of the actual problem in the response. It only displays the generic status 422, and if you have the stacktrace enabled, the full stacktrace.
This doesn't allow the UI to inform the user what's conceptually wrong with their request

**To Reproduce**
1. Create an EPerson
2. Assign them as the only person in a workflow group
3. Create an item, and assign it to the workflow group
4. Try to delete the EPerson
5. You will get a status 422, but don't get the details why the request is not ok unless you enable the stack traces and retrieve the details from the stack traces

**Expected behavior**
A clear and concise description of the problem should be presented by REST, also when stack traces are disabled.
This problem can be included in the message property of the REST Exception Response.

**Related work**
This replaces https://github.com/DSpace/DSpace/issues/3045

**Comment by tdonohue** [comment]
Keep in mind the feedback listed in [this comment](https://github.com/DSpace/DSpace/issues/3045#issuecomment-726193696).  This should likely be fixed via custom Exception class(es) which return *translatable* messages.
