### ISSUE TITLE
An item missing dc.title is not selectable in the user interface in certain contexts

### ISSUE THREAD

**Issue by uofmsean** [DSpace/DSpace#3104]
**Describe the bug**
An item missing a dc.title cannot be selected in the user interface in certain contexts (e.g., collection item list and search results). If a direct link isn't known for the item (e.g., using the handle or UUID), a workaround is to use the Admin Search to get to an Edit link for the item.

Cases where dc.title can be missing are when a submission form does not make it required, or (less likely) a user intentionally removes the dc.title metadata. Some known cases where dc.title is not required in a submission form are the openAIREOrganizationForm, openAIREPersonForm, and openAIREProjectForm.

**To Reproduce**
Add items using one of the above-mentioned forms and then browse the collection(s) or try searching for the items. All that is displayed is the icon for "Item" and there is no link that can be selected to take you to the item page.

**Expected behavior**
If dc.title is not an absolute requirement, then there should at least be a hyperlink with something like "No Title" that the user can select when dc.title isn't present.

**Related work**
N/A

**Comment by tdonohue** [comment]
I've been able to reproduce this recently.  Somehow, I have an Item without a title, and the response from the REST API looks like:
```
{
  "id": "e18f1ff9-9f75-4e6d-ae47-b05a7e301cc2",
  "uuid": "e18f1ff9-9f75-4e6d-ae47-b05a7e301cc2",
  "name": null,
  "handle": "123456789/1124",
  "metadata": {
      .. [a bunch of metadata fields, but no dc.title]...
   }
}
```

While technically a `dc.title` should be required, we should handle this problem more gracefully.  I think the correct approach here would be to catch this in the Angular UI (if `name=null` for any object, not just an Item), and simply replace it with "Untitled" (and this should be in i18n so it can be translated).

@artlowel : Do you agree here?  If so, would you be willing to estimate what this would take?  My assumption is this likely is in the 2-3 hour range, but I'm sure you'd know better what this might take.
