### ISSUE TITLE
Update Installation Documentation for 7.0

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3120]
This ticket is about updating this page:
https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace

The documentation is currently "mostly accurate", but needs more details on a **production quality** installation of the Frontend / User Interface (e.g. how one would setup the DSpace UI to run in [PM2](https://pm2.keymetrics.io/) or [Passenger](https://www.phusionpassenger.com/), or similar.)

**Comment by parphis** [comment]
I can not edit/add comments on the Wiki pages so let me inform you here about a [typo](https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-InstallingtheFrontend(UserInterface))
The example code of the 4. point of the _Frontend Installation_ section is missing a comma `,` after the `ui` JSON key.

**Comment by tdonohue** [comment]
Closing this, as I believe https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace is now "good enough".  Any further issues or questions can be resolved via comments on that page (or additional tickets)
