### ISSUE TITLE
Replace old User Interface Documentation in 7.0

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3124]
The old User Interface documentation section must be replaced in 7.0: 
https://wiki.lyrasis.org/display/DSDOC7x/User+Interfaces

We should add more detailed documentation in that area around configuring/customizing the new Angular UI.  Technical topics include:
* Overview of UI-specific configs
* Theming guide/tips
* Overview of UI design / technologies & perhaps overview of code folder structure.

**Comment by tdonohue** [comment]
I've started some UI configuration documentation at : https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration  Currently, this just documents the `environment.*.ts` files, but it's a start. This should be reviewed by @artlowel and @atarix83 for correctness (or someone on your teams).

I did come across a few questions though as I wrote this page of docs.  This might be best answered by @artlowel :
1. Do we still need the [`rewriteDownloadUrls` setting](https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.common.ts#L284)?  I thought that was rendered obsolete now that all download URLs are based on the UI's URL.  However, it's obviously still in the config & used in the [HardRedirectService](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/services/hard-redirect.service.ts)
2. It appears (to me) that we have a [`logDirectory` setting](https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.common.ts#L152) that is entirely unused?  Should this be removed, or am I missing how/where it's used?

Next, I do plan to draft some early docs on how to create custom themes (based heavily on the OR2021 workshop)

**Comment by mwoodiupui** [comment]
I came to the same conclusion regarding `logDirectory`.  I could find no use or even meaning for it.

**Comment by tdonohue** [comment]
My questions above were both fixed in https://github.com/DSpace/dspace-angular/pull/1276

**Comment by tdonohue** [comment]
Closing this as "complete". An early version of these docs now exist:
* Configuration Docs: https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration
* Customization Docs (including theme changes): https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Customization

Updates/reviews from others are welcome, but these are likely "good enough" for 7.0
