### ISSUE TITLE
Update Live Import / External Sources documentation

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3128]
Depends on #2817, as the BTE system has not been entirely removed.

Once BTE has been removed, the DSpace 7 "Importing Items via basic bibliographic formats" documentation should be updated to remove mentions of BTE & replace the BTE docs with examples from Live Import / External Sources (where plausible):

Documentation to be updated:
* https://wiki.lyrasis.org/pages/viewpage.action?pageId=104566672 (Remove sections on BTE, update Live import as needed)
* https://wiki.lyrasis.org/display/DSDOC7x/Live+Import+from+external+sources (Remove mentions of BTE, verify configuration is still accurate)

**Comment by abollini** [comment]
We have documented the live import framework as used in DSpace-CRIS 7 here https://github.com/4Science/DSpace/releases/download/dspace-cris-2021.01.00/dspace-cris7-2021_01_00-technical-documentation.pdf (look to page 87 and forward). There is a chance to reuse content, it would be necessary for sure to
- remove mention of Providers not yet part of DSpace 7
- remove mention of the Provider - Entity type binding
- add a warning that only one item can be imported at time (in DSpace-CRIS we have removed this constraint)
- other...? we could have other improvements / changes that I don't remember right now

if you found anything wrong or difference that you like to see in DSpace as well please just let us know we will be happy to contribute back

**Comment by tdonohue** [comment]
Closing this as "good enough".  Thanks to @abollini , I've copied over some of the docs from 4Science into https://wiki.lyrasis.org/display/DSDOC7x/Live+Import+from+external+sources

I've also simplified this page so that it's more about user experience / UI (and it links to the Live Import docs for more technical details): https://wiki.lyrasis.org/pages/viewpage.action?pageId=104566672

Overall, I'm sure these docs can be improved, but the basics are now there.
