### ISSUE TITLE
Mapped Items not visible in Collection browse

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3141]
**Describe the bug**
Discovered while testing https://github.com/DSpace/dspace-angular/pull/983.  While Items can be mapped successfully to different Collections, they **never** seem to appear in the Collection browse listing.  They are, however, visible in the Collection's "Item Mapper" tab (on the Edit Collection screen) when using https://github.com/DSpace/dspace-angular/pull/983.

**To Reproduce**
1. This is most easily tested by installing https://github.com/DSpace/dspace-angular/pull/983
2. Edit a Collection and Map a few items to that Collection.
3. Now, visit the Collection homepage (mapped items will not be listed).  Under that Collection, click on Browse "By Title", "By Issue Date", "By Author" or "By Subject"... the Mapped Item will also not appear in any of those browses.

My guess is that Mapped Items are not being properly added/updated in our Discovery/Solr indexes.

**Expected behavior**
Obviously, an Item mapped into a Collection should appear in that Collection's browse pages.

**Comment by benbosman** [comment]
I'd expect this change to require 4 hours of work, including ITs which verify browse and search correctly work when mapping/unmapping items

We can implement this solution

**Comment by tdonohue** [comment]
@benbosman : Thanks! I've added the estimate & reassigned back to you for you or your team to work on this.

**Comment by tdonohue** [comment]
As discussed today, the upcoming PR for this ticket can be assigned to @abollini and @tdonohue

**Comment by jonas-atmire** [comment]
@tdonohue 
> My guess is that Mapped Items are not being properly added/updated in our Discovery/Solr indexes.

To test that, I've setup the repo as described in your initial description, and triggered a discovery index through a metadata update in the UI.
This already fixed the problem, confirming your theory.

I've created following PR and assigned @abollini and yourself for reviewal (Explanation of changes in PR itself)
