### ISSUE TITLE
Embedded lists don't have pagination options in their self link

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#3174]
**Describe the bug**
With https://github.com/DSpace/DSpace/pull/3114 you can now specify the page size of an embedded list. However the self links of those embedded lists don't contain that page size at the moment. While regular (not embedded) lists do have it in their self link

**To Reproduce**
1. Perform a request with an embed.size parameter e.g. [https://api7.dspace.org/server/api/core/communities/search/top?size=1&embed.size=subcommunities=1&embed=subcommunities&embed.size=collections=1&embed=collections
](https://api7.dspace.org/server/#https://api7.dspace.org/server/api/core/communities/search/top?size=1&embed.size=subcommunities=1&embed=subcommunities&embed.size=collections=1&embed=collections)
2. Notice that the self link for the root resource contains the pagination params, while the self links for the embedded resources don't

**Expected behavior**
All params that affect the resource should be present in the self link, whether that resource is embedded or not

**Note** that the hrefs in the links section of the root resource should stay the same, as they're part of the root resource that _shouldn't_ be affected by size params on the embeds

To clarify, for the example above with embedded subcommunities and collections, both with size 1:
```javascript
{
  "_embedded": {
    "communities": [
      {
        "id": "7b0-0bfc",
        ...
        "_links": {
          "collections": {
            "href": "https://rest.api/core/communities/7b0-0bfc/collections"   // <= stays the same
          },
          "subcommunities": {
            "href": "https://rest.api/core/communities/7b0-0bfc/subcommunities"  // <= stays the same
          },
          "self": {
            "href": "https://rest.api/core/communities/7b0-0bfc"
          }
        },
        "_embedded": {
          "collections": {
            "_embedded": {
              "collections": [
                ...
              ]
            },
            "page": {
              "number": 0,
              "size": 1,
              "totalPages": 1,
              "totalElements": 1
            },
            "_links": {
              "self": {
                "href": "https://rest.api/core/communities/7b0-0bfc/collections?size=1"  // <= added size
              }
            }
          },
          "subcommunities": {
            "_embedded": {
              "subcommunities": []
            },
            "page": {
              "number": 0,
              "size": 1,
              "totalPages": 0,
              "totalElements": 0
            },
            "_links": {
              "self": {
                "href": "https://rest.api/core/communities/7b0-0bfc/subcommunities?size=1" // <= added size
              }
            }
          }
        }
      }
    ]
  },
  "_links": {
    "first": {
      "href": "https://rest.api/core/communities/search/top?page=0&size=1"
    },
    "self": {
      "href": "https://rest.api/core/communities/search/top?size=1"   // <= already correct
    },
    "next": {
      "href": "https://rest.api/core/communities/search/top?page=1&size=1"
    },
    "last": {
      "href": "https://rest.api/core/communities/search/top?page=154&size=1"
    }
  },
  "page": {
    "size": 1,
    "totalElements": 155,
    "totalPages": 155,
    "number": 0
  }
}
```

**Related work**
#3114.

**Comment by tdonohue** [comment]
@artlowel : Thanks for logging this.  Just to clarify, do you feel this is a bug that needs resolution immediately (for example is it needed to solve https://github.com/DSpace/dspace-angular/issues/918)?   I agree this is a bug in the initial implementation in #3114, but just trying to determine whether we need to rush this into Beta 5, or if it really has no impact on the work currently happening in https://github.com/DSpace/dspace-angular/issues/918

**Comment by artlowel** [comment]
For #918 we're only using embed sizes for the community and collection list page. And while the self links are wrong, the concept still works for that page. The urls with sizes in them are being considered to be alternative links to the same list. 

An example of an alternative link is `/collections/collection-uuid/logo`. This is an alternative to the self link for the logo bitstream: `/bitstream/logo-uuid`. 

In this case `/community/community-uuid/collections?size=1` is being considered an alternative link to the self link this issue is about:`/community/community-uuid/collections`, simply because they differ. 

This is wrong of course, but since neither`/community/community-uuid/collections?size=1` nor `/community/community-uuid/collections` seems to be used anywhere else at first sight (the community homepage uses `/community/community-uuid/collections?size=5`), I don't think it matters much that it's wrong at the moment. So I wouldn't consider this issue critical for beta 5

But I encourage to see if you can find bugs as a result of this when you review the PR for #918.

**Comment by tdonohue** [comment]
@artlowel : I've verified that this issue doesn't seem to affect the UI, including in https://github.com/DSpace/dspace-angular/pull/1049.  So, I've labeled this low priority.

@abollini : Would you or your team be interested in looking at this issue / providing an estimate?  It's currently *low priority* (does _not_ have to be in Beta 5, but might be nice to fix if we find time prior to 7.0 final) as it doesn't seem to affect anything on the UI side.  This issue also seems somewhat similar to #3044 which your team fixed recently.

**Comment by tdonohue** [comment]
Assigning to @abollini to investigate. Note however that this is `low priority` as it doesn't appear to affect the UI at this time. It's just an inconsistency in the REST API

**Comment by abollini** [comment]
3 hours should be sufficient to track down the bug and write tests to proof the solution

**Comment by abollini** [comment]
feel free to assign to us if you want us to work on that on low priority

**Comment by tdonohue** [comment]
@abollini : Sounds good. I'll add the estimate and assign to you to work on.  Yes, as this is `low priority` obviously work on other tasks first (if there are any), but you are welcome to work on this when you have time.
