### ISSUE TITLE
Consider building SiteMaps from Discovery/Solr index for better performance

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3182]
Initially mentioned in the review of https://github.com/DSpace/DSpace/pull/3150#discussion_r592435411

Currently [`GenerateSitemaps`](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/sitemap/GenerateSitemaps.java) primarily uses direct database calls (`.findAll()`) to build our sitemaps.

However, as noted in #3150, we found that (in some scenarios) Discovery/Solr is much quicker than these database calls. 

We should consider refactoring `GenerateSitemaps` to use the Discover/Solr index.  The only risk in doing so is ensuring that the Sitemaps are not scheduled to be built during a Discovery reindex, as that would result in inaccurate sitemaps.  However, full Discovery reindexing should be rare, as (when done while the UI is running) it also would result in inaccurate search/browse results until the reindex is complete.

This is low priority at this time.

**Comment by mwoodiupui** [comment]
Would it not be simpler and safer to find out why the current code is slow, and fix that?  Because `findAll` should not be slow:  it has nothing to do but walk pages and return whatever it finds, exactly the same as `q="*:*"`.  But there are a number of ways to use either Solr or an RDBMS improperly and make it *very* slow.

**Comment by tdonohue** [comment]
@mwoodiupui : Just a clarification on this ticket.  I don't have any proof at this point that `findAll` is too slow for generating Sitemaps.  I logged this ticket more as a reminder that  @abollini mentioned we may want to consider refactor Sitemaps to use Discovery in this discussion: https://github.com/DSpace/DSpace/pull/3150#discussion_r592435411  

I think the main thing to note here is that Sitemap generation is currently using both `findAll` (hitting database) and then Solr to grab individual item info.  The main question here is whether we want to reconsider this approach in the future, but it's very low priority right now as the approach works fine for now.
