### ISSUE TITLE
workflow discovery configuration query with query parameter set with free text returns no results

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#3184]
**Describe the bug**
If a discovery search with configuration param set as "workflow" and a query param does not return any result.  

**To Reproduce**
1. login on dspace 7 demo
2. go to "MyDSpace"
3. select "all tasks"
4. enter a query string in search input box (i.e. title of an item that appears among "all tasks")
5. Search won't return results

The same search can be made against REST api as logged in user, by calling /server/api/discover/search/objects?configuration=workflow&query=<query parameter>

**Expected behavior**
Results according to query content should be returned

**Related work**

We (4Science) can take this in charge, right after other beta5 tasks that we already have in charge. our estimation is 4 hours of work. Work that consists in the item indexing into task's solr documents (PooledTask and ClaimedTask resource types) and the creation of a specific test that proves the provided solution.

![Screenshot from 2021-03-12 15-17-16](https://user-images.githubusercontent.com/70699836/110952059-0e8cf400-8346-11eb-93ca-5366f572c08f.png)
![Screenshot from 2021-03-12 15-16-34](https://user-images.githubusercontent.com/70699836/110952063-0f258a80-8346-11eb-9b8b-ac90f0b96900.png)

**Comment by tdonohue** [comment]
Thanks @corrad82-4s .  I've assigned this back to you for your team to work on when you find time.  Ideally, if you could get this done this week it'd be best, but if not, we can see if we can fit it into Beta 5 prior to Testathon.

**Comment by tdonohue** [comment]
As discussed today, the upcoming PR for this ticket can be assigned to @benbosman and @tdonohue
