### ISSUE TITLE
Facet entries in the discover/facets/{facet} endpoint does not return the authority key

### ISSUE THREAD

**Issue by Raf-atmire** [DSpace/DSpace#3185]
**Describe the bug**
When calling the {dspace.url}/api/discover/facets/{facet} endpoint, the results won't include the authority key, even though it should be there.

**To Reproduce**
1. Set up a discovery core that has authority values for facets in the config
2. Try to retrieve the values through the call above
3. The resulting facet entries won't include the authority key

**Expected behavior**
The authority keys should be present in the response

**Related work**
This was discovered due to the failing tests in this PR: https://github.com/DSpace/DSpace/pull/3176

**Comment by tdonohue** [comment]
Thanks @Raf-atmire and @benbosman .  This does seem like something that needs fixing.  I suspect it **also** will require minor changes to the REST Contract (as I don't see any examples where an authority key would be returned as part of a facet): https://github.com/DSpace/RestContract/blob/main/search-endpoint.md

I'll move this over to Beta 5 as it seems small.  Is this something your team would like to work on, or does this overlap with #3177 enough that we should talk with @abollini about whether his team would be interested in implementing both together?

**Comment by benbosman** [comment]
@tdonohue Raf can work on this as part of https://github.com/DSpace/DSpace/pull/3176
Is it ok if this implies that PR is not fixed by Thu morning (it is already an open PR)
We will of course try to get it ready in time

**Comment by tdonohue** [comment]
@benbosman : That's fine. I'll update #3176 to note that it will fix this issue.
