### ISSUE TITLE
Collection location is not indexed for in submission items

### ISSUE THREAD

**Issue by jonas-atmire** [DSpace/DSpace#3202]
**Describe the bug**
When [searching for an in submission item](https://github.com/DSpace/RestContract/blob/main/search-endpoint.md#workflow), the attached collection of the item is not indexed, and not attached as a location of the record in solr
This has the side effect that, when searching using the workflow configuration of discovery, that:
* The item CAN searchable when using a general search
* The item CAN NOT be found using the collection as a scope parameter

The underlying reason for this is that, when the item is indexed, the [related collections](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/discovery/indexobject/ItemIndexFactoryImpl.java#L677) are checked 
But in progress items do not have a link to the owning collection -> The [InProgressSubmission does have a link to the collection](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/content/InProgressSubmission.java#L42)

**To Reproduce**
1. Create an in submission item in a particular collection
2. Search that it's present in a 'general, non scoped' search for the workflow items
2.1 This item should be retrieved since it's indexed through [this indexer](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/discovery/indexobject/InprogressSubmissionIndexFactoryImpl.java#L49)
3. Search that it's present in a 'scoped' search, using the collection that the item is being submitted into
3.1 This item can not be found, since it doesn't contain location information for the collection

**Expected behavior**
Both the scoped and non scoped searches should return the relevant item

**Comment by tdonohue** [comment]
@jonas-atmire : Would you or someone on your team be willing to provide an estimate for this?  Is it work of interest to you or your team?  This seems like something that would be worth fixing in Beta 5 or 7.0, but that likely assumes it's a small amount of effort to correct this bug.  Thanks for logging this.

**Comment by jonas-atmire** [comment]
@tdonohue I think this should be doable in the ballpark of 1 hour (most of which would be the creation of the tests)

It basically comes down to making sure that, in the [InprogressSubmissionIndexFactoryImpl](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/discovery/indexobject/InprogressSubmissionIndexFactoryImpl.java#L49) we need to retrieve the collection id to add into the location information (And that should do it IMO)

**Comment by tdonohue** [comment]
Thanks @jonas-atmire !  In that case, I'll add this to the Beta 5 board and assign it back to you to work on.  I think it'd obviously be nice to get this into Beta 5 if possible.
