### ISSUE TITLE
Patch Add entire array with virtual values does not work

### ISSUE THREAD

**Issue by alemarte** [DSpace/DSpace#3214]
**Describe the bug**
When we try to execute a patch add request of a metadata with multi values in presence of _at least one virtual value_, an exception is thrown and 500 error returned.

**To Reproduce**
The easiest way to reproduce is testing by running the work of the https://github.com/DSpace/dspace-angular/pull/1025.

1. Start a submission in [this collection ](http://localhost:4000/submit?collection=dd1240ae-d7dd-405c-bdc3-d6c960609433) on the api7.dspace.org backend
2. Add a virtual value to the author field through the lookup feature.
3. Add a second value (plain value)
![repeatable1](https://user-images.githubusercontent.com/63857/113313647-bc6b3d00-930b-11eb-9111-5ddad022ca5f.png)
4. Click on Save
![repeatable2](https://user-images.githubusercontent.com/63857/113313666-c12ff100-930b-11eb-9a02-61e52a71709e.png)

**Expected behavior**
The patch operation should be successful.

**Related work**
This is related to https://github.com/DSpace/dspace-angular/pull/1025

**Comment by abollini** [comment]
As the virtual:: authority prefix is used to mask relations as metadata the patch operation should deal with them as well. It should be at least possible to reorder or remove some of them.

**Comment by tdonohue** [comment]
@abollini : As promised in today's meeting, I've moved this into Beta 5 and assigned to you for your team to work on.  As discussed today, ideally a PR is ready by next week's meeting (at the latest) so we can try to get this into Beta 5.
