### ISSUE TITLE
NPE in SherpaService constructor when running any IT

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#3217]
**Describe the bug**
`SherpaService#configurationService` is both injected and explicitly initialized.  Apparently Spring is calling the constructor before `DSpaceServicesFactory.getInstance()` is ready, leading to an NPE.  The explicit initialization should be removed.

This showed up after I merged today's `main` into a patch that I'm developing.

**To Reproduce**
1. Run integration tests.

**Expected behavior**
Spring should succeed in creating the bean.

**Note**
The explicit initialization was removed in commit dd10104661ce9cf6887093674c684852c9ad167f but reappeared in fdabd643f0eb3620612aad6ba08758f3a1629275.

**Comment by tdonohue** [comment]
@mwoodiupui : This is odd, as the ITs are succeeding in GitHub CI. You can see recent builds of our `main` branch have all been successful: https://github.com/DSpace/DSpace/actions/workflows/build.yml?query=branch%3Amain

I'll see if I can try to run them locally...I wonder if there's an environment specific thing going on.

**Comment by mwoodiupui** [comment]
Yes, I wondered why we aren't seeing this all the time.  OTOH clearly the code is wrong.  At best it is redundant.

This actually needs more than just removing the premature initialization.  Also the initialization of `endpoint` and `apikey` must move to a `@PostConstruct` method, since they depend on `configurationService`.  Doing this cures the bug here.  And it's the Right Thing to Do.

**Comment by tdonohue** [comment]
@mwoodiupui : I'm not against the change you suggest, the code does indeed look odd [here](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/sherpa/SHERPAService.java#L56-L57) and [here](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/app/sherpa/SHERPAService.java#L64).  You are correct, we shouldn't need to initialize twice.

So, please feel free to create a PR if you have a moment.  It is strange though that I'm not seeing the same error that you do.

**Comment by mwoodiupui** [comment]
It must be to do with the order of bean *construction*.  If, on my system, Spring thinks it can/should construct a SherpaService before the DSpace kernel is initialized, then here the problem would be seen.  I have no idea whether Spring's order of construction has any definite relationship to the order of *instantiation*, which includes post-construction activities like injection.  But that's just speculation.
