### ISSUE TITLE
Sort options are not reported in the proper order

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#3227]
**Describe the bug**
The `discovery.xml` file allows to configure which sortOptions are available for each configuration and set also a default sorting
see
https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L160
https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/discovery.xml#L157-L159

The structure is not efficient as having the default sort set in a separate property can lead to different scenarios that need to be managed
- the default sort option is included in the list of available options
- the default sort option is an additional one

Moreover, in the current implementation the default sort is always appended as last options in the REST response, see
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverConfigurationConverter.java#L39

and there is no explicit mention of the default sort in the REST response, instead the example of the default configuration seems to indicate that the order of sort options matter (using the blame link as I haven't found a different way to link directly the line)
https://github.com/DSpace/RestContract/blame/main/search-endpoint.md#L151

**To Reproduce**
1. https://api7.dspace.org/server/#https://api7.dspace.org/server/api/discover/search
2. look to the sortOptions 
```
"sortOptions": [
    {
      "name": "dc.title"
    },
    {
      "name": "dc.date.issued"
    },
    {
      "name": "dc.date.accessioned"
    },
    {
      "name": "score"
    }
```
**Expected behavior**
We propose to simplify the discovery.xml configuration revisiting the sortOption bean definition to include a defaultDirection property that can be used to set the default direction of the sort option (i.e. DESC for score and date, ASC for title).
We suggest to don't include any restriction about the directions that can be manually applied to the sort, i.e. it will be possible for the user to ask for result in score ASC, this is currently supported by solr and the REST API so we should introduce this constraint only if we get an explicit motivated request from our users as it would lead obviously to extra complexity (in configuration and validation)

`discovery.xml`

```
  <bean id="defaultConfiguration" class="org.dspace.discovery.configuration.DiscoveryConfiguration" scope="prototype">
         ...
            <property name="searchSortConfiguration">
            <bean class="org.dspace.discovery.configuration.DiscoverySortConfiguration">
                <property name="sortFields">
                    <list>
                        <ref bean="sortScore" />
                        <ref bean="sortTitle" />
                        <ref bean="sortDateIssued" />
                        <ref bean="sortDateAccessioned"/>
                    </list>
                </property>
            </bean>
        </property>
     ....
</bean>
...
     <bean id="sortScore" class="org.dspace.discovery.configuration.DiscoverySortFieldConfiguration">
        <!-- no metadataField specified to represent the score or a different implementation of the sortFieldConfiguration. TBD during implementation -->
        <property name="defaultSortOrder" value="desc"/>
    </bean>

   <bean id="sortTitle" class="org.dspace.discovery.configuration.DiscoverySortFieldConfiguration">
        <property name="metadataField" value="dc.title"/>
        <property name="defaultSortOrder" value="desc"/>
    </bean>
```

**Related work**
This is related to https://github.com/DSpace/dspace-angular/issues/1071 and the corresponding PR https://github.com/DSpace/dspace-angular/pull/1086

**Comment by abollini** [comment]
Test should be revisited / enforced to verify that sort options are returned in the proper order. Moreover, the REST API should validate the requested sort options against the configuration to forbid (422) invalid sort request (that could eventually result in heavy load / error on the solr side if run over not optimized field). A refactoring of the discovery sort option configuration is also required defined a way to deal with the score sort option in a transparent way. This lead to an estimation of 8 - 16 hours, 4Science can claim this task

**Comment by tdonohue** [comment]
@abollini : This sounds found to me.  Just to make sure I'm understanding the proposal here...there's a few main changes:
1. You are suggesting to slightly modify the structure of the sort file configuration in `discovery.xml` so that the `defaultSortOrder` is configured on each sort option (instead of once globally).
2. You are also implying that the order returned by the REST API *matters*. That the first sort option in the list is the *default sort* (therefore, `scoreSort` should be first, as we default to a relevance sort).

Assuming I understand your proposal, that all sounds good to me. I'll add **12 hours** to this (the average of your range) and assign to you for your team to work on.  As noted in today's meeting, as soon as this REST PR can be tested/approved alongside https://github.com/DSpace/dspace-angular/pull/1086 we will deploy both to the Testathon servers.
