### ISSUE TITLE
Browse by author broken if author name has special character

### ISSUE THREAD

**Issue by samuelcambien** [DSpace/DSpace#3230]
**Describe the bug**
If an author name has a special character (e.g. '&'), the browse for it doesn't work properly.

**To Reproduce**
1. Go to https://demo7.dspace.org/browse/author
2. Click on 'ANZNN, Women's & Children's Health'

**Expected behavior**
You would expect to see one publication, however no publication is shown.

**Related work**
Not sure if this should be fixed by Angular (encoding the character) or REST.

**Comment by tdonohue** [comment]
@benbosman : Assigning this one to you (or someone on your team to review).  My guess is it may more likely be a backend issue (perhaps even with indexing) which is why I'm passing it your way.  This sounds like a `medium priority` task to fix for 7.0 (it's not broken entirely, but likely to be annoying to many users)

**Comment by benbosman** [comment]
This is a UI issue
`/server/api/discover/browses/author/items?sort=default,ASC&page=0&size=20&filterValue=ANZNN,%20Women%27s%20%26%20Children%27s%20Health` works but Angular uses `https://api7.dspace.org/server/api/discover/browses/author/items?sort=default,ASC&page=0&size=20&filterValue=ANZNN,%20Women%27s%20&%20Children%27s%20Health` splitting the parameter in half

**Comment by benbosman** [comment]
I'm picking this up again, although REST correctly responds to a valid query, it's REST which sends the incorrect search link to Angular in the first place

https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=0&size=10 contains
```json
{
  "search": {
    "href": "https://api7.dspace.org/server/api/discover/search/objects?f.author=Simmons, Cameron,equals"
  }
}
```

https://api7.dspace.org/server/api/discover/browses/author/entries?sort=default,ASC&page=0&size=20 contains
```json
{
  "items": {
    "href": "https://api7.dspace.org/server/api/discover/browses/author/items?filterValue=Abdominal and Paediatric Surgery"
  }
}
```

And with the ampersand issue, it's also REST which sends it without escaping

To fix this, I'd expect 4 hours of work (including ITs)

**Comment by tdonohue** [comment]
@benbosman : That sounds reasonable. Adding the 4hour estimate to the ticket & assigning back to you for your team to work on.

**Comment by benbosman** [comment]
I'm picking this up another time. While fixing REST, we noticed that Angular ALSO has a bug.
If REST responds with a correct link, Angular still builds an incorrect link:
```json
{
 "authority": null,
 "value": "Biomolecular & Analytical Mass Spectrometry (BAMS)",
 "valueLang": null,
 "count": 4,
 "type": "browseEntry",
 "_links": {
 "items": {
  "href": "http://localhost:8080/server/api/discover/browses/author/items?filterValue=Biomolecular%20%26%20Analytical%20Mass%20Spectrometry%20(BAMS)"
 }
 }
},
```
results in http://localhost:8080/server/api/discover/browses/author/items?sort=default,ASC&page=0&size=100&filterValue=Biomolecular%20&%20Analytical%20Mass%20Spectrometry%20(BAMS)

I would estimate the Angular fix to require 2 hours, and we can also deal with that (it will still require the REST fix)

**Comment by tdonohue** [comment]
@benbosman : Ok, I'll add 2 more hours to this ticket then, bringing the total to 6hours.  Your team can tackle the small Angular fix then too as part of this ticket.
