### ISSUE TITLE
Backend logs almost useless

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#3244]
**Describe the bug**
The rest logs are almost useless there are tons of page of 
```
2021-04-21 23:50:02,216 WARN  org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:404)
```
sometimes there are error stack trace but most of time there is no reference to which endpoint have generated the stack trace. In previous versions it was possible to identify/guess at the least the Servlet that was invoked as an INFO entry was prosent somewhere before. It was not ideal because with high load concurrent request was hard to distinguish but better than nothing.

In the current main branch the logs don't contain any information about the invoked endpoint, so the only chance is to check the dspace log together with the apache/web log side by side

**To Reproduce**
Browse a dspace 7 repository and check the dspace.log file

**Expected behavior**
The ideal solution would be to have
-  an anonymous and automatic generated request ID included in each log line to keep them together. Each rest call should at least log one entry to note that the call happened;
- at least in the first entry a reference to the page from where the request was generated so that we can quickly identify which page of our angular application use the endpoint. This would apply only to our angular app but maybe could be a suggestion for all the rest client (include a referrer header or something like that)
- expected 404 response as in the case of the configuration endpoint should be identified and reported at info level.

**Comment by tdonohue** [comment]
@abollini : Assigning this back to your team to investigate / estimate further.  Your suggestions sound reasonable to me. 

Here's a possibly resource I found in logging every incoming request in a Spring / Spring Boot app: https://www.baeldung.com/spring-http-logging

I like the idea of a unique request ID, though we'd have to figure out how to "store" that (or accurately regenerate it) to ensure the same request ID is used in each request from the same person.  I know Apache & Tomcat logs just use the IP address for this purpose, but I realize that can be a privacy issue...so, I'd be interested to better understand what you'd suggest here.  I'd also recommend we not go overboard. If adding the IP address to logs is "good enough" we may just want to do that (and provide a way to anonymize the logs via a commandline script which can be run regularly to anonymize the real IP, similar to our anonymize statistics tool added in #2693).

In any case, the direction here sounds good. So, let me know what you feel is achievable for 7.0.

**Comment by tdonohue** [comment]
@abollini : Just a reminder that this high priority ticket is waiting on an estimate / recommended solution.

**Comment by mwoodiupui** [comment]
I think that we need to be very clear on what we mean by "request ID".  Is the unit of work here an HTTP request, or something larger?

If the scope is HTTP request, then the obvious place to store it is in the `HttpServletRequest` object's attributes.  Perhaps we could use a time-based UUID.  But that doesn't square with the idea of using the same ID for each request from the same person.  The latter sounds like a "session ID" and we might simply use the `HttpSession`'s ID.  If the scope is several REST operations fulfilling a single user action, we'll need to invent some sort of "transaction" scope.

Perhaps we need all of these, eventually.

We could (eventually) think about using any or all as Log4j `Marker`s to facilitate automated log searching or post-processing.

**Comment by abollini** [comment]
My idea is to have the rest client to randomly generate an uuid to include for all the request in a specific "session". For our angular application this would mean an uuid generated when the app state is created. In addition angular should send a referrer header with the url of the page that has generated the REST request.
This information are mainly to help debugging, in the rare case the same identifier would be generated / spoofen there are no security risk or implication.
@tdonohue thanks for point to the Spring Interceptor documentation it is very useful and we can try to use it to accomplish "Each rest call should at least log one entry to note that the call happened;". The out-of-box logging interceptor from Spring seems to provide richer details and are put to DEBUG level, we should have minimal information available at INFO level. Adding some traditional logging in the `org.dspace.app.rest.repository.DSpaceRestRepository<T, ID>` that proxy all the common call to a Rest Repository should be also a good addition.

**Comment by tdonohue** [comment]
A few notes after the discussion in today's meeting:
* The need for the `Referrer` header coming from Angular makes perfect sense. We should add that, as we definitely want to know which Angular page generated the REST API request.
* The randomly generated UUID to represent the "session" also does make some sense...though, it sounds like we'd be dependent on the client generating this identifier, and we'd need some sort of fallback when the identifier is _not_ passed.  This means that the logs may lack information if the client doesn't send this identifier.
    * Another option here is to just use IP address and/or `X-Forwarded-For` (which most Proxies use to pass the original client IP).  It may not be perfect, but it'd avoid our having to create a custom solution for our logs.  (Obviously, for GDPR, we may need to provide a script to anonymize logs by removing the last digits of the IP). In addition, this is more similar to how Tomcat & Apache identify individuals in their logs...so it'd be easier to follow a "session" across several log files, as you can match it based on client IP address.

**Comment by abollini** [comment]
the session client side generated uuid is also required by https://github.com/DSpace/DSpace/issues/3257
I would prefer to lack information in the dspace.log instead than adding extra complexity to deal with anonymization. Anonymize Web server logs is a common need for hosting providers that usually (or at least this is the case in 4Science) is managed in a general not dspace specific way.
In the case an additional rest client is not so friendly to follow what we will document as a best practice we can always look back also to the web server logs.

**Comment by mwoodiupui** [comment]
I don't understand why we allow Spring Boot to suppress the JSESSIONID.  (TBH I don't understand why Boot does this, except that the Boot developers seem determined to reinvent every wheel in sight.)

**Comment by tdonohue** [comment]
@mwoodiupui : The simple answer is that we are attempting to make the backend completely "stateless".  So, ideally, we never use a `HttpSession` object and never generate a JSESSIONID (and that's why Spring Boot supports disabling JSESSIONID, for stateless apps).  (That said, as a sidenote, I think there are still a few instances of `HttpSession` hanging around that need cleanup.) The reason for "statelessness" is to allow for DSpace to scale more horizontally (potentially run one frontend with multiple backends).  But, this does mean that we need a different, "stateless" identifier for a user's "session", and @abollini is proposing that be achieved via a client-side session UUID, which can be passed to whatever backend you are currently using.

**Comment by mwoodiupui** [comment]
Oh, clustering?  That has been around in Tomcat since forever.  https://tomcat.apache.org/tomcat-8.5-doc/cluster-howto.html

**Comment by tdonohue** [comment]
@mwoodiupui : We're trying to align with core REST principles, and a key part of REST is statelessness as a requirement...where the "session" is on the client side, not on the server side (see this similar [SO question/answer](https://stackoverflow.com/a/3105337/3750035)).  Statelessness also means that you can more easily spin up an extra backend if one gets overwhelmed. So, yes it's somewhat similar to clustering, but in a more dynamic way...think of something like spinning up a new backend dynamically in AWS (or similar), without needing to predefine several "nodes" of a cluster in a more complex Tomcat setup (or your servlet container of choice).

**Comment by mwoodiupui** [comment]
OK, I give up.
