### ISSUE TITLE
Thumbnail resolution should happen on the rest side

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#3286]
**Is your feature request related to a problem? Please describe.**

Finding the correct thumbnail for an item or a bitstream is every slow at the moment, because it is done client side. The UI has to download the entire thumbnail bundle, ignoring pagination, to compare filenames with bitstreams in the ORIGINAL bundle and find a match.

We've never had much issues with this because we've never used DSpace 7 in a situation where we had a lot of items with a lot of bitstreams and thumbnails. If you do the performance becomes very poor in situations where you need to resolve multiple thumbnails quickly, e.g. the search result grid view.

**Describe the solution you'd like**

I propose we add an optional thumbnail link to bitstreams. If a bitstream is in the ORIGINAL bundle, rest should check if there's a matching thumbnail. If there is, add a `thumbnail` link to the links section of the ORIGINAL bitstream, with the self link to the THUMBNAIL bitstream (or to a new `/bitstreams/:uuid/thumbnail` alias if that's preferable)

Items should get a thumbnail link as well, for the default thumbnail that should be used for that item (best to check dspace 6 for the exact logic to determine which one that is, because as it stands the UI just picks the first one it finds). We should get that both for items retrieved directly, as well as discovery results.

For performance it would be probably good if this would happen using a projection: by default the links aren't added, but if you ask for the thumbnail projection they are. However I don't think we've used projections that way before, so if this adds a significant amount of extra effort we can drop that requirement for now.

**Comment by benbosman** [comment]
I would suggest to work with something like https://github.com/DSpace/RestContract/pull/163

In REST, this would add links which can be embedded. It works quite similar to the `templateItemOf` link (but returns a bitstream instead).

The REST implementation would imply:
* For items, the first bitstream in the THUMBNAIL bundle is returned (if any)
* For bitstreams, the first bitstream in the THUMBNAIL bundle with the name starting with the original bitstream's name is returned (if any)

This can be done in REST with **6 hours of work** (including ITs)

The link will always be present, but if there's no thumbnail, it will simply return 204 (similar to the `templateItemOf` link)
A projection can be used to embed it (the thumbnail's metadata), but not to determine whether the link is included

**Comment by tdonohue** [comment]
Thanks @benbosman for the estimate.  I've added it and assigned back to you for your team to work on.  I also reviewed the REST Contract design...overall it's fine but I've asked for a minor clarification/update: https://github.com/DSpace/RestContract/pull/163#pullrequestreview-682062367
