### ISSUE TITLE
DS-2904 Asynchronous & Batch Google Analytics Reporting  for DSpace 5.x

### ISSUE THREAD

**Issue by AndrewZachWood** [DSpace/DSpace#3305]
See: https://github.com/DSpace/DSpace/pull/2248 as a reference.

This feature request is a place holder for the following PR:
https://github.com/DSpace/DSpace/pull/3306

This is a back port of https://github.com/DSpace/DSpace/pull/2248 for DSpace 5.x.

**Comment by tdonohue** [comment]
Closing, fixed in 7.1 See #2248
