### ISSUE TITLE
Update collection metadata or removing the administrator group will not produce a solr reindex

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#3326]
**Describe the bug**
If you change the name of a collection the collection cannot be found under the new name until a full reindex is forced.
If you remove the admin group of the collection you will note that its uuid is still present in the SOLR document related to the collection (this not imply any visible bug at the moment but it is still inaccurate)

**To Reproduce**
1. Login as administrator
2. Edit a collection and set a new unique name
3. search for this name: you get no result
4. reindex the site
5. search again you should find your collection

**Expected behavior**
Update of a collection should update the solr index

**Comment by abollini** [comment]
No modify event is generated by the service and this imply that the index consumer is not invoked. We should investigate to verify that other dspace objects don't suffer of the same issue Community but also  EPerson, Group, Site that are not currently indexed but could have other consumer listening for modify event.
Test should be added to cover the identified scenarios, it should took more or less 2 hours

**Comment by atarix83** [comment]
@tdonohue estimation is about 2/4 hours, he can take it

**Comment by tdonohue** [comment]
Thanks @atarix83 .  I've added the estimate and assigned back to @abollini & his team to start work on.
