### ISSUE TITLE
How the way best custom template dspace 7?

### ISSUE THREAD

**Issue by thanapoj** [DSpace/DSpace#3327]
Hi,  today I have problem.
I don't have not idea, how to custom template dspace7?

becuease I read some source recommend "Don't custom in the core template".

I want to clone original template to custom theme but 
the some HTML file much use original TS file,
If I copy TS original file to custom, I find configurate is difficult and so many.

Whold you have idea how to custom template dspace 7?

 Thank you very much.

**Comment by tdonohue** [comment]
Please see the user interface customization documentation at https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Customization

If you have more specific questions, feel free to ask them via one of our official support channels: https://wiki.lyrasis.org/display/DSPACE/Support  GitHub issues is only for suspected bugs and new features.
