### ISSUE TITLE
test case in InstallItemTest expects wrong Exception to be thrown

### ISSUE THREAD

**Issue by bruno-atmire** [DSpace/DSpace#3337]
**Describe the bug**
[InstallItemTest#testInstallItem_invalidHandle](https://github.com/DSpace/DSpace/blob/e1478f6fddb6c919548602ce1200b169e5bf637d/dspace-api/src/test/java/org/dspace/content/InstallItemTest.java#L158) intends to verify that items cannot be installed when the handle already exists. It currently expects an AuthorizeException to be thrown.

This is the stack trace of where the exception occurs:
- https://github.com/DSpace/DSpace/blob/e1478f6fddb6c919548602ce1200b169e5bf637d/dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java#L75
- https://github.com/DSpace/DSpace/blob/e1478f6fddb6c919548602ce1200b169e5bf637d/dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java#L204
- https://github.com/DSpace/DSpace/blob/e1478f6fddb6c919548602ce1200b169e5bf637d/dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java#L605
- https://github.com/DSpace/DSpace/blob/e1478f6fddb6c919548602ce1200b169e5bf637d/dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java#L152

As you can see, this exception is not related to having duplicate handles.

**To Reproduce**
Run the test and notice that it passes.

**Expected behavior**
Instead of an AuthorizeException, the following IllegalStateException should be thrown: https://github.com/DSpace/DSpace/blob/34c1e82275dbbc42010b79cd5872a86d861d9827/dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java#L180-L181

The following line should be modified to accept an IllegalStateException: https://github.com/DSpace/DSpace/blob/e1478f6fddb6c919548602ce1200b169e5bf637d/dspace-api/src/test/java/org/dspace/content/InstallItemTest.java#L157

Then the underlying code should be updated to ensure the test passes again.

**Comment by tdonohue** [comment]
@bruno-atmire : Thanks for all the investigation work.  Would you be willing to submit a small PR with these fixes?  It looks like you've already figured out the necessary changes, so it may be a quick PR to create.
