### ISSUE TITLE
Unable to start up DSpace 7 using docker-compose

### ISSUE THREAD

**Issue by deunitato-d4l** [DSpace/DSpace#3348]
Hello, Im trying to run a local setup for Dspace 7 using docker-compose..
I followed the steps in the following [link](https://wiki.lyrasis.org/display/DSPACE/Running+DSpace+7+with+Docker) and was able to see back-end properly
However, when I tried to load the front end, I am unable to see the details in the page.. Inspecting the console shows the following error. Any ideas regarding this?

![image](https://user-images.githubusercontent.com/83936304/127314987-1a95bb83-a005-4889-90f6-0604ca1f7694.png)

Steps used to install
```
git clone https://github.com/DSpace-Labs/DSpace-Docker-Images.git
cd DSpace-Docker-Images/docker-compose-files/dspace-compose
git pull
docker-compose -p d7ent -f docker-compose.yml -f d7.override.yml -f load.entities.yml up -d
--
```

### `localhost:8088/server`:

![image](https://user-images.githubusercontent.com/83936304/127315715-c580a383-80fe-4752-af68-782af8aa0ca7.png)

**Comment by tdonohue** [comment]
@deunitato-d4l : It looks like you have an outdated link (I'll update that wiki page to point to the correct place).

Latest DSpace 7 + Docker instructions are at https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+7

Also, see the Docker readmes in the frontend & backend:
* https://github.com/DSpace/DSpace/blob/main/dspace/src/main/docker-compose/README.md
* https://github.com/DSpace/dspace-angular/blob/main/docker/README.md
