### ISSUE TITLE
Restore Primary Bitstream as a capability of DSpace 7

### ISSUE THREAD

**Issue by hardyoyo** [DSpace/DSpace#3349]
**Is your feature request related to a problem? Please describe.**
Prior versions of DSpace had a field in the Bundle table [1] which provided a link to a bitstream, called 'primary_bitstream_id'[1] This was used to determine what thumbnail to show for a specific item that had multiple bitstreams attached. This would also help for instances of scholarly publications, where you would have the "primary" bitstream as the PDF of the article, and then any supporting bitstreams (images, other media files, software, a data set, etc.)

**Describe the solution you'd like**
There needs to be a way to indicate whether a bitstream is a “primary bitstream” for an item. This should be part of the ingest process, and should be utilized in thumbnail selection for items. This metadata should also be accessible to item templates, so that a designated primary bitstream can be displayed differently on an item page, in order to give it prominence, and to otherwise fit an institution’s use case and site designs. The text extracted from a primary bitstream should also be given a higher relevance ranking in the fulltext search index.

_UPDATE from DevMtg on April 7, 2022:_  All the functionality of "primary bitstreams" still exists in the codebase, but the REST endpoints are missing. We discussed the solution is likely two REST endpoints:
* Submission Side (selecting primary bitstream during submission), perhaps as part of the Upload endpoints: https://github.com/DSpace/RestContract/blob/main/submissionuploads.md
* Bundle Side (updating/selecting primary bitstream while editing): https://github.com/DSpace/RestContract/blob/main/bundles.md
* (NOTE: The individual claiming this ticket could implement both endpoints or just one endpoint...in which case a separate follow-up ticket would be created to implement the other endpoint.)

**Describe alternatives or workarounds you've considered**
Use an earlier version of DSpace, or reorder bitstreams so that the "primary" is listed first (as first bitstream is considered the primary one when no primary is selected)

**Additional context**

* https://wiki.lyrasis.org/display/DSDOC7x/Storage+Layer
* Required by this UI feature request: https://github.com/DSpace/dspace-angular/issues/1578

**Comment by mwoodiupui** [comment]
This would be an opportunity to re-think the concept.  For one thing, if we consider "primary Bitstream" to be a property of an Item, then what is it doing in Bundle?  Right now each Bundle has a primary Bitstream.  Why?

While we're at it, we should consider the effort involved in matching derivative Bitstreams to their sources.  Does a Bitstream have metadata:  has-{thumbnail | text | etc.} [derived Bitstream's ID]?  Should it?

**Comment by hardyoyo** [comment]
According to the [REST Contract](https://github.com/DSpace/RestContract/blob/main/items.md#linked-entities) the bundle endpoint still has a notion of "primary bitstream". If this is correct, I'd like to see DSpace-Angular provide a UI for it (say a checkbox for an item's bitstreams). FYI, we're working on drafting at least one use formal use case for this feature request.

**Comment by mwoodiupui** [comment]
Further to re-thinking:  why is it possible for an item to *not* have a primary bitstream?

For that matter, *precisely* what does "primary" *mean* to DSpace?

**Comment by hardyoyo** [comment]
I can tell you what I *think* it *ought* to mean to DSpace: a "primary" bitstream should be the bitstream used for generating a thumbnail for the item. It should also be the first listed bitstream in a list of bitstreams associated with an item, in the UI.

**Comment by tdonohue** [comment]
Just wanted to note here... that the meaning of "primary" has become confusing to me as of late.  It used to be exactly what @hardyoyo states. However, now that Bitstreams are easily reorderable (via drag & drop), the *first listed bitstream* is simply the one used for the Item thumbnail.

So, in a way, the use case @hardyoyo notes is already in DSpace 7.  Just drag & drop reorder your "primary" bitstream to be first in the list.  

Hence, I'm also questioning the true meaning / use case of "primary" bitstream.  I _think_ it was initially created at a time when bitstream reordering was difficult. (If I'm wrong though, please correct me)  But, does it still have a use case when bitstream reordering is now easy to achieve either in the Submission UI or Edit Item pages?

**Comment by hardyoyo** [comment]
I would say that ordering of bitstreams would be "implicit" while a toggle would be "explicit". Though, redesigning the submission form, with a big arrow pointing to the top of the list of bitstreams with "primary bitstream" on it... might make this explicit enough.

**Comment by Rajamuthukrishna** [comment]
Hello Team,

I need to find the items which is not available in thumbnails, kindly share any API is available for this, otherwise share which table is used for thumbnail Id is stored.
