### ISSUE TITLE
Menu toggle from right to left

### ISSUE THREAD

**Issue by mtpatterson** [DSpace/DSpace#3351]
Would like to request a feature where it's possible to toggle the side menu where the search bar is from the right side to the left. This is in regards to users making that change on their own browser or account. I've attached a screenshot so hopefully help explain what menu I mean. The one where it has the search bar, and Browse, My Account, Discover, etc.

![Dspace menu](https://user-images.githubusercontent.com/2236722/127877291-acfa5327-0272-4cdb-bdfe-9b2cc6c6cc88.png)

**Comment by tdonohue** [comment]
@mtpatterson : this is possible to achieve via CSS already, but you are correct there's no "toggle" which allows you to change the location per user account.

With the [release of 7.0](https://duraspace.org/dspace-7-press-release/), the 6.x codebase will move primarily into bug/security fix mode.  So, unfortunately, this sort of feature will not be coming to 6.x.  

However, I can report that in 7.0, the sidebar is non-existent for unauthenticated users.  If you login, there is now a sidebar on the left side, and it auto-collapses by default.

Closing this ticket as "won't fix" for now.  However, if there are other future responses/feedback related to 7.0, we may revisit and reopen later as needed.

**Comment by mwoodiupui** [comment]
At some point we should consider whether this is an I18N issue.  Do UIs developed first for right-to-left languages tend to have a different layout than those for LTR languages?
