### ISSUE TITLE
Migrate extra DSpace-CRIS "Live Import" sources to DSpace core

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3359]
DSpace-CRIS (built/maintained by 4Science) has a number of [Live Import sources](https://wiki.lyrasis.org/display/DSDOC7x/Live+Import+from+external+sources) which are not yet available in DSpace core.  
These may include:
* Scopus
* CrossRef
* CiNii
* NASA/ADS
* Web of Science
* VuFind
* OpenAIRE (by Author and Title)

If possible, we should work with the 4Science team to contribute these back to core code, so that they can be available to and maintained by the entire DSpace community.

This can also benefit upcoming features which also build on Live Import / External Sources, like https://github.com/DSpace/DSpace/issues/2834 and https://github.com/DSpace/DSpace/issues/2833

**Comment by tdonohue** [comment]
All, I talked with @abollini and @atarix83 today about this task.  

@abollini noted that **anyone is welcome to port code from DSpace-CRIS to DSpace at any time**.   DSpace-CRIS is open source and follows the same license as DSpace.  4Science only asks that they be credited with the initial development of any  feature ported from DSpace-CRIS.

At this time, the 4Science team noted this task is unfortunately lower priority for them right now, as they are worried it'd distract from their ability to help build & review other important 7.1 features.  This is why they wanted to make it clear this task doesn't need to rely on 4Science, but that anyone is welcome to port over code as they see fit.  These "Live Import" sources likely can be ported over rather easily as they are mostly "standalone" and likely don't need 4Science support in doing so.

Therefore, I'm un-assigning this from @atarix83 for now.  I'll leave it on our 7.1 board as a task that we may still want to try to fit into 7.1

**Comment by paulo-graca** [comment]
I don't know if it will help, but I've made a contribution to OpenAIRE model library (PR: https://github.com/openaire/openaire-funders-jaxb-model/pull/2):
https://search.maven.org/artifact/eu.openaire/funders-model

I only test it for funding, but this library supports full OpenAIRE model (even results, organizations). I don't know what 4Science it's using as a library to support OpenAIRE model on DSpace-CRIS, but I suggest the usage of openaire library.

**Comment by abollini** [comment]
We have reviewed which connectors are currently available in DSpace-CRIS but not in DSpace, below the list

- ADSImportMetadataSourceServiceImpl
- ArXivImportMetadataSourceServiceImpl
- CiniiImportMetadataSourceServiceImpl
- CrossRefImportMetadataSourceServiceImpl
- EpoImportMetadataSourceServiceImpl
- PubmedEuropeMetadataSourceServiceImpl
- PubmedImportMetadataSourceServiceImpl
- ScieloImportMetadataSourceServiceImpl
- ScopusImportMetadataSourceServiceImpl
- VuFindImportMetadataSourceServiceImpl
- WOSImportMetadataSourceServiceImpl
**- OpenAireImportMetadataSourceServiceImpl
- OpenAireProjectImportMetadataSourceServiceImpl
- OrcidPublicationDataProvider**

The **OpenAIRE connectors will be excluded by this activity** as they would require discussion about which approach should be used, in DSpace-CRIS they are based on the Live Import Framework but in DSpace 7.1 the Project import was included according to a different custom implementation based on the openaire data model library see https://github.com/DSpace/DSpace/pull/3365#pullrequestreview-778824482

The **ORCID Publication import will be excluded** as it can be better addressed in the scope of a porting of the DSpace-CRIS ORCID features.

The estimation to port the resulting **11 connectors is about 48 hours.**

Please note that this estimation include
- porting of the feature/code as is applying code cleanup if required but without major redesign work that can happen in a subsequent PR
- adding javadoc where missing as required by our community policies
- integration test for WOS, Scopus, EPO will interact with the live service requiring real apikey to be executed. Without api key the test will be skipped. We can provide test based on mock service but license rights to include such mock data should be obtained/verified by Lyrasis
- adding integration test based on mocking the external service for the other open providers

**Comment by abollini** [comment]
@tdonohue we were almost ready to open the PR for this issue but we have decided to rebase it on top of your PR https://github.com/DSpace/DSpace/pull/8222 as most of the connector were based on AXIOM.
I can anticipated a little extra effort on this task about 12-16 hour

**Comment by tdonohue** [comment]
@abollini : That makes sense. I'll add it to the existing estimate.  PR #8222 has now been merged, so it should be easier to rebase against latest `main`.
