### ISSUE TITLE
[DS-239]  java.net.MalformedURLException: unknown protocol: resource

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#3614]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-239">[DS-239]</a> created by mdiggory</i>
<p>We currently have two instances of dspace that we use, a live dspace and dspacetest.</p>

<p>Dspacetest was recently (about a month or two ago), upgraded from 1.5.1 to 1.5.2, with no problems. You can see it in all it's glory here: dspacetest.nt.gov.au</p>

<p>Today, we attempted to upgrade our live dspace instance to 1.5.2. After restarting tomcat though, we got a java.net.MalformedURLException: unknown protocol: resource error (full stack trace included).</p>

<p>After looking around I found that in 1.5.1 there was a cocoon.xconf which included</p>

<p>    <component-instance class="org.apache.excalibur.source.impl.ResourceSourceFactory" name="resource"/><br/>
which I assume is pointing to the resource. Looking around I couldn't find cocoon.xconf anywhere in 1.5.2 and thought it must have been removed. But still needing the site to work I included it back in webapps/xmlui/WEB-INF, which still did nothing at the time.</p>

<p>Looking in webapps/xmlui/WEB-INF/web.xml shows that 1.5.1 included</p>

<p>    <servlet><br/>
<servlet-name>Cocoon</servlet-name><br/>
<display-name>Cocoon</display-name><br/>
<description>Cocoon</description></p>

<p><servlet-class><br/>
    org.dspace.app.xmlui.cocoon.DSpaceCocoonServlet<br/>
</servlet-class></p>

<p><init-param><br/>
    <param-name>configurations</param-name><br/>
    <param-value>/WEB-INF/cocoon.xconf</param-value><br/>
</init-param></p>

<p>but that 1.5.2 doesn't and seems to use DSpaceCocoonServletFilter instead<img class="emoticon" src="https://jira.lyrasis.org/images/icons/emoticons/help_16.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>After playing around a bit more, moving files here and there, finally I received no more errors and could view the webpage. However it turns out that all I did was return the xmlui/WEB-INF folder to its exact state before upgrading to 1.5.2, so that technically the site was still running on 1.5.1 code.</p>

<p>What I would like is any assistance if possible, as to why I would get this error on one instance of dspace, after another instance had been upgraded properly.</p>

<p>To go through my processes for upgrading:</p>

<p>ran mvn package in src/dspace-1.5.2-src-release<br/>
turned off tomcat (which by the way, both instances of dspace are using the same instance of tomcat)<br/>
ran ant update in src/dspace-1.5.2-src-release/dspace/target/dspace-1.5.2-build.dir<br/>
ran ant update_configs in src/dspace-1.5.2-src-release/dspace/target/dspace-1.5.2-build.dir (which is redudant?)<br/>
restarted tomcat</p>

<p>If it helps the live site is www.territorystories.nt.gov.au, and though looks good is using 1.5.1 code.</p>

<p>Thanks<br/>
Jennifer Whalan</p>

**Comment by tdonohue** [comment]
Closing as outdated. This is >5 years old & last version mentioned is 3.0
