### ISSUE TITLE
[DS-304] XMLUI's METS generator ignores authorization

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#3679]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-304">[DS-304]</a> created by kshepherd</i>
<p>(apologies if this is a duplicate, I couldn't find any related issues, though I know the OAI interface has been under similar scrunity)</p>

<p>By default, XMLUI will generate and send METS metadata for a DSO if the URL pattern matches: metadata/handle/<b>/</b>/**</p>

<p>Item/collection/community authorisations are not checked by DSpaceMETSGenerator first, which means that items with no anonymous READ access, items with <span class="error">&#91;Harvard/MIT-style&#93;</span> embargos applied, etc. are still ultimately exposing metadata to users and machines who know who to take advantage of this bug.</p>

<p>I am not sure whether this should be handled by patching DSpaceMETSGenerator or disabling the pattern match in sitemap.xmap by default and documenting its behaviour thoroughly, so admins can enable it once they are sure they are happy with unrestricted metadata access.</p>

<p>I can't promise these URLs will remain live/relevant forever, but you can quickly replicate this bug by viewing:</p>

<p><a href="http://www.anonymous.org.nz:8180/handle/123456789/23" class="external-link" target="_blank" rel="nofollow noopener">http://www.anonymous.org.nz:8180/handle/123456789/23</a><br/>
<a href="http://www.anonymous.org.nz:8180/metadata/handle/123456789/23/mets.xml" class="external-link" target="_blank" rel="nofollow noopener">http://www.anonymous.org.nz:8180/metadata/handle/123456789/23/mets.xml</a></p>

<p>Any comments/suggestions?</p>

**Comment by tdonohue** [comment]
Will be fixed by #2364 as that's the same issue

**Comment by tdonohue** [comment]
Closing, fixed by #2364
