### ISSUE TITLE
[DS-570] Redirect users to current page on login

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#3944]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-570">[DS-570]</a> created by caryn.n</i>
<p>I would like to be able to direct a user to the "current" page after login.  </p>

<p>For example, if a user is not logged in, and they are looking at an item page, when they click login, I would like to be able to send them back to the item page.  </p>

<p>As it functions now, a user who has found an item they want, then clicked log in, will be authenticated and sent either home or to the profile (this option is set in dspace.cfg file).  This means they will need to find the item they wanted again, which is not the most user-friendly.  </p>

**Comment by tdonohue** [comment]
Closing, as this is fixed in 7.0.  Just verified on demo7.dspace.org.  Activities on JSPUI or XMLUI have stalled since 2017...but if someone wants to implement it could be done in a separate ticket.
