### ISSUE TITLE
[DS-883] Artifact preview thumbnail in browse screens does not display primary bitstream

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#4256]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-883">[DS-883]</a> created by ottenhoffs</i>
<p>Steps to replicate in XMLUI:</p>

<p>1) Add new DSpace item with one image<br/>
2) Run filter-media and update your browse index<br/>
3) View a browse index like Recent Submissions; your thumbnail now displays in the the browse<br/>
4) Go to the item<br/>
5) Edit this item<br/>
6) Item Bitstreams<br/>
7) Upload a new bitstream<br/>
8) Upload new image -> save<br/>
9) Click on the new image name<br/>
10) Make it the Primary bitstream -> Save<br/>
11) Run filter-media again, update the browse index</p>

<p>Look at a browse index like Recent Submissions, notice that the primary bitstream flag is not being respected. The old image is still the thumbnail for this item.</p>

**Comment by tdonohue** [comment]
Closing as outdated/obsolete.
