### ISSUE TITLE
[DS-995] support XSLT 2.0 in XMLUI

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#4367]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-995">[DS-995]</a> created by helix84</i>
<p>This issue is to track work needed to make XMLUI support XSL 2.0 (using Saxon).</p>

<p>Details why it was created are here:<br/>
<a href="http://dspace.2283337.n4.nabble.com/Why-does-DSpace-use-XSLT-1-0-td3750179.html" class="external-link" target="_blank" rel="nofollow noopener">http://dspace.2283337.n4.nabble.com/Why-does-DSpace-use-XSLT-1-0-td3750179.html</a></p>

**Comment by tdonohue** [comment]
Closing as "won't fix".  6.x is in bug fix mode now, and this is a significant change.  That said, if anyone really wants this, see the early work in #2609
