### ISSUE TITLE
[DS-1705] Show persistent identifier in submission process

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#5072]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-1705">[DS-1705]</a> created by pbecker</i>
<p>DSpace generates persistent identifier, handles and <del>starting with DSpace 4.0</del> DOIs. Sometimes you want to write those identifier into the file(s), you'll upload in the submission process (e.g. a not on how to cite this work, an imprint, ...).<br/>
The IdentifierService in DSpace can mint, reserve and register Identifiers. Currently an Identifier gets minted, reserved and registered when an Item gets approved. It would be good, if DSpace would generate, reserve and show the persistent identifier whenever a submission is started and would register it when the submission gets approved.</p>

**Comment by tdonohue** [comment]
Closing as obsolete. Would need recreating for 7.x
