### ISSUE TITLE
[DS-1900] Selectively provide identifiers for incoming Items, based on Collection to which submitted

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#5267]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-1900">[DS-1900]</a> created by mwood</i>
<p>We have a requirement to generate DOIs for new submissions to our ETD collections, but not to other collections in the same repository.  To do this, I propose a mechanism to tag a given Collection with a list of desired IdentifierProvider classes.  IdentifierService clients would provide the service a callback object which would return true/false for a given provider, and if false, the provider would be skipped.  To address situations like ours, a "default" provider list can also be defined, so that the exceptional Collections can have <b>augmented</b> as well as diminished sets of providers applied &#8211; the default list can be less than the full set of providers, and a Collection can then permit providers not in the default set (but known to the IdentifierService).</p>

<p>This will require changing several method signatures in IdentifierService.  The cascading changes are not extensive.</p>

**Comment by tdonohue** [comment]
@mwoodiupui : This looks to be an old ticket from you (carried over from JIRA).  Should this be closed or is it still valid?

**Comment by mwoodiupui** [comment]
I think I submitted two Jira tickets on this idea:  [DS-1900](https://jira.lyrasis.org/browse/DS-1900) and [DS-3749](https://jira.lyrasis.org/browse/DS-3749).  It's still valid.

**Comment by tdonohue** [comment]
@mwoodiupui : In that case, closing this one in favor of #7096 (DS-3749) as that one has a PR already
