### ISSUE TITLE
[DS-1977] "Private" Items are incorrectly listed in Google Sitemaps

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#5343]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-1977">[DS-1977]</a> created by tdonohue</i>
<p>If you mark an item as "private" in the Submission UI or the Admin UI, it is still listed in the generated Sitemaps.</p>

<p>By definition, a "private" item should be hidden from all browse/search interfaces, and therefore we should not encourage Google and other search engines to index them. Private items are still potentially accessible via direct URL, but should not be easy to discover/find in any search engines.</p>

<p><a href="https://wiki.duraspace.org/display/DSDOC4x/DSpace+Item+State+Definitions" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.duraspace.org/display/DSDOC4x/DSpace+Item+State+Definitions</a></p>

<p>To Reproduce this issue:</p>
<ul>
	<li>Create a Item, and mark it as "private"</li>
	<li>That item will not be discoverable in the DSpace Browse or Search UIs</li>
	<li>However, if you regenerate the DSpace Sitemaps, that item will still be listed in the Sitemap.</li>
</ul>

<p>The expected result:</p>
<ul>
	<li>If an item is marked as "private" it should NEVER appear in the generated SiteMaps.</li>
</ul>

**Comment by tdonohue** [comment]
Abandoned PR #2584 for 6.x exists (it was tested & worked but submitter deleted their branch & cannot be merged).  It needs updating/resubmitting & also porting to `main`.

**Comment by alejandratenorio** [comment]
Hi @tdonohue,

Sorry, if we restructured our repositories and our branch was deleted. 
Today I am doing the PR again.

**Comment by tdonohue** [comment]
Thanks @alejandratenorio !  Please link it up to this ticket as we'd like to see if we can get this fixed *both* in 6.x (`dspace-6_x` branch) and in 7.x (`main` branch).
