### ISSUE TITLE
[DS-2199] DSpace stores DOIs in different metadata values depending on which DOI registration agency is used

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#5565]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-2199">[DS-2199]</a> created by pbecker</i>
<p>DSpace currently does have two DOI implementations: one to register DOIs using the DataCite API and one to register DOIs using EZID. If the DataCite API is used, DOIs are stored as dc.identifier.uri and prefixed with "http://dx.doi.org/" so they can be linked as they are. If EZID is used DOIs are stored in dc.identifier. This should be harmonized as it is odd to look for a DOI in two different metadata fields.</p>

<p>The code to register DOIs using DataCite supports using different backends. One way to harmonize both implementations would be to write an EZID-Backend and to use most of the code independently from the registration agency.</p>

**Comment by tdonohue** [comment]
Closing this bug ticket as it has been replaced by #9901 

This new ticket documents the DOI consensus achieved during the discussion in today's developers meeting (see [DevMtg on Oct 17, 2024](https://wiki.lyrasis.org/display/DSPACE/2024-10-17+DSpace+Developers+Meeting))
