### ISSUE TITLE
[DS-2715] add ORCID integration for JSPUI

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6075]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-2715">[DS-2715]</a> created by gperosillo</i>
<p>In DSpace 5.0 the ORCID authority control is only enabled for the XMLUI Mirage and Mirage 2 themes. Dspace 6 would need to enable ORCID authority control for the Dspace JSPUI User Interface.</p>

**Comment by tdonohue** [comment]
Closing, fixed by #2710
