### ISSUE TITLE
[DS-3128] Update Spider detection our lists are out of date

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6483]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3128">[DS-3128]</a> created by cjuergen</i>
<p>While having trouble with the turnitin bot I checked the<br/>
<a href="http://www.iplists.com/" class="external-link" target="_blank" rel="nofollow noopener">http://www.iplists.com/</a> and noted that the bot was not in the list and that all the lists are quite out of date.<br/>
The latest update to the list seemed to have been 2014-01-26 as stated in <br/>
<a href="http://www.iplists.com" class="external-link" target="_blank" rel="nofollow noopener">http://www.iplists.com</a><br/>
and there are no further updates in this list<br/>
<a href="http://www.ihategoogle.org/category/ip-lists/" class="external-link" target="_blank" rel="nofollow noopener">http://www.ihategoogle.org/category/ip-lists/</a></p>

<p>This falsifies the statistics.</p>

**Comment by tdonohue** [comment]
This seems like a duplicate of #7020 ... and that one has a little more movement.  So, closing this in favor of #7020. That said, if other approaches come up, we can reopen this as needed.
