### ISSUE TITLE
[DS-3418] DSpace Build Error When Git is Not Present

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6772]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3418">[DS-3418]</a> created by terrywbrady</i>
<p>Reported to DSpace Tech by Devaux Cédric </p>

<p><a href="https://groups.google.com/forum/#!topic/dspace-tech/ePevCFj8Ofw" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/dspace-tech/ePevCFj8Ofw</a></p>

<p>IRC Discusson on this subject:<br/>
‹tdonohue›  First up in that list is not actually a ticket, but I saw this report that DSpace 6 may <b>require</b> Git to actually build? <a href="https://groups.google.com/forum/#!topic/dspace-tech/ePevCFj8Ofw" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/dspace-tech/ePevCFj8Ofw</a><br/>
<span class="error">&#91;12:02:54&#93;</span>	‹kompewter›  [ Google Groups ] - <a href="https://groups.google.com/forum/#!topic/dspace-tech/ePevCFj8Ofw" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/dspace-tech/ePevCFj8Ofw</a><br/>
<span class="error">&#91;12:03:17&#93;</span>	‹tdonohue›  That seems very odd to me, and no one responded on the lists...It'd be nice to get someone to investigate that<br/>
<span class="error">&#91;12:05:04&#93;</span>	‹tdonohue›  Anyone have time to look into whether DSpace 6 <b>requires</b> Git? It really <b>shouldn't</b>...so if it is doing so, we need to log a bug and resolve in 6.1<br/>
<span class="error">&#91;12:07:37&#93;</span>	‹tdonohue›  no volunteers for Git issues...ok, well, it sounds like this might at least need a ticket to track it.<br/>
<span class="error">&#91;12:07:59&#93;</span>	‹terry-b›  I will create a ticket<br/>
<span class="error">&#91;12:08:10&#93;</span>	‹mhwood›  Actually I just took a quick look, and buildnumber-maven-plugin will indeed call the SCM &#8211; git in our case.<br/>
<span class="error">&#91;12:08:34&#93;</span>	‹tdonohue›  thanks terry-b. If you could respond to the thread, that'd be great too...even if just to say: we created a ticket for this and are investigating<br/>
<span class="error">&#91;12:09:05&#93;</span>	‹hpottinger›  +1 we need a ticket for that for sure<br/>
<span class="error">&#91;12:09:24&#93;</span>	‹tdonohue›  mhwood: that sounds like a bug then, right? Is there a way to get it to <b>not</b> call SCM? Is this plugin for figuring out the version of DSpace they are running?<br/>
<span class="error">&#91;12:09:48&#93;</span>	‹mhwood›  Dunno what we are doing with the build number.</p>

**Comment by ammanabrolua** [comment]
I found this: [https://stackoverflow.com/questions/6947827/maven-build-number-plugin-how-to-save-the-build-number-in-a-file](https://stackoverflow.com/questions/6947827/maven-build-number-plugin-how-to-save-the-build-number-in-a-file).

Please let me know how to proceed with this?
