### ISSUE TITLE
[DS-3427] DIM2DataCite crosswalk update to version 4.0

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6781]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3427">[DS-3427]</a> created by cjuergen</i>
<p>In September 2016 the <a href="http://doi.org/10.5438/0012" class="external-link" target="_blank" rel="nofollow noopener">DataCite Schema 4.0</a> has been published.<br/>
The major changes are:</p>
<ul>
	<li>Changing resourceTypeGeneral from optional to mandatory</li>
	<li>Addition of a new property: FundingReference, with subproperties funderName, funderIdentifier, awardNumber, awardURI and awardTitle. Deprecation of contributorType “funder”</li>
	<li>Addition of new optional subproperties for creatorName and contributorName: familyName and givenName</li>
	<li>Addition of a new relatedIdentifierType option “IGSN”</li>
	<li>Addition of a new subproperty for GeoLocation “geoLocationPolygon”, and changing the definition of the existing GeoLocation subproperties (geoLocationPoint and geoLocationBox)</li>
</ul>

<p>DSpace 5.x uses the version 2.2.<br/>
DSpace 6.0 uses the version 3.1</p>

<p>The schema should be updated with the next release.</p>

**Comment by pilasou** [comment]
Hi @tdonohue, it seems that the Datacite crosswalk is already compliant with Datacite 4.0 schema. The crosswalk XSL stylsheet ([DIM2DataCite.xsl](https://github.com/DSpace/DSpace/blob/dspace-7_x/dspace/config/crosswalks/DIM2DataCite.xsl)) from DSpace 7 branch even mentions compliance with 4.5. All this to say that this ticket can be close. :)

**Comment by alanorth** [comment]
Thanks @pilasou!
