### ISSUE TITLE
[DS-3453] OAI-PMH verb Identify doesn't work on Oracle

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6806]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3453">[DS-3453]</a> created by no-reply</i>
<p>Original report here:<br/>
<a href="https://groups.google.com/forum/#!topic/dspace-tech/Q_9wnr0mVbg" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/#!topic/dspace-tech/Q_9wnr0mVbg</a></p>

<p>We've just installed DSpace 6 with Oracle and seem to have encountered a bug. There is an ORDER BY TEXT_VALUE field clause in the OAI Data Provider query that fails because the TEXT_VALUE field is a CLOB. I was wondering if this was a known bug. I have not been able to find it if it is.<br/>
Our proposed solution is:<br/>
order by cast(text_value as varchar2(NNN))</p>

**Comment by tdonohue** [comment]
Fixed in 6.x (see #2112), but has not yet been applied to 7.x or above

**Comment by tdonohue** [comment]
@mwoodiupui : Would you be willing to port your #2112 PR to `main` & assign to me for quick review?  That way we can close out this ticket.

**Comment by mwoodiupui** [comment]
Is there some reason why we don't just ask the submitter to fix the conflicts in #2121?

**Comment by tdonohue** [comment]
@mwoodiupui : I didn't notice that existing port! I'll ask on that first....and see if we can get an update

**Comment by tdonohue** [comment]
Closing as Oracle Support was removed in #8822
