### ISSUE TITLE
[DS-3559] OAI Indexing extremely slow and memory inefficient for bigger amount of items

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6909]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3559">[DS-3559]</a> created by christian.scheible</i>
<p>When building the OAI index in 6.x</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-none">
sudo JAVA_OPTS="-Xmx2048M -Xms2048M" /dspace/bin/dspace oai import -c
</pre>
</div></div>
<p>The process becomes really slow after a while and consumes a lot of memory.</p>

<p>It is the same problem as describe in ---<del><a href="https://jira.lyrasis.org/browse/DS-2965" title="Re-indexing performance degrades when processing a large number of items" class="issue-link" data-issue-key="DS-2965"><del>DS-2965</del></a></del>---. I have seen that the solution which was found for this bug was clearing the hibernate session which works great for my problem as well.</p>

<p>But the pull request <a href="https://github.com/DSpace/DSpace/pull/1276" class="external-link" target="_blank" rel="nofollow noopener">#1276</a> was changed in a later <a href="https://github.com/DSpace/DSpace/commit/17af928b05f26a8a9112cbeeee57b1b9213e439d" class="external-link" target="_blank" rel="nofollow noopener">commit</a>. </p>

<p>I think that the problem was that Session#clear() in the DBConnection not only evicts all items from the cache but also cancels all pending saves/updates/deletes.</p>

<p>but it should be save to be used in a read only use case, like reading all items from the database to get indexed.</p>

<p> </p>

<p>Some number to help understanding the problem:</p>

<p><b>Using the current code</b> to index 33013 items:</p>

<p>after 1463 Minutes and 26400 item:  the 2GB memory are completely in use, 1043967 items in the hibernate cache. To index one item needs about 5 seconds (instead of ~ 5 milliseconds)</p>

<p><b>Trying to evict every object</b> that is touched by the code similar to the index discovery code</p>

<p>hard to find every place where we have something loaded in the cache (collections, communities, items, metadatavalues, bundles, bitstreams ...) so the result is:</p>

<p>finished after 175 Minutes: 107695 items in the hibernate cache. To index one item needs about 0,4 seconds (instead of ~ 5 milliseconds)</p>

<p><b>Using Session#clear()</b> from the Hibernate Session object</p>

<p>Finished after 9 Minutes. As expected 0 items in the cache. About 4 milliseconds to index an item. Should be able to index every amount of items because the cache size is constant</p>

<p> </p>

<p>So I am going to add a pull request which adds the possibility to clear the whole cache which is great for batch reading of items.</p>

<p>I could add the flush method as well to make batch creation of a large number of items possible as described here:</p>

<p><a href="http://docs.jboss.org/hibernate/core/3.6/reference/en-US/html_single/#batch-inserts" class="external-link" target="_blank" rel="nofollow noopener">http://docs.jboss.org/hibernate/core/3.6/reference/en-US/html_single/#batch-inserts</a></p>

<p> </p>

**Comment by tdonohue** [comment]
Closing, as this was noted as fixed in #1694 (which is already merged)
