### ISSUE TITLE
[DS-3566] A fault on a single bitstream should not kill the execution of Filter-Media

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6915]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3566">[DS-3566]</a> created by bram</i>
<p>In certain cases filter-media can choke on a particular bitstream, leaving all of the remaining bitstreams unprocessed.</p>

<p>Where possible, these type of exceptions or crashes should be handled appropriately, so a message can be written to the log about the erroneous bitstream/fault, and then proceed with the next one.</p>

**Comment by tdonohue** [comment]
Closing based on comments above as it was unreproducible.  Also noted that it's possible this issue was specific to old WordFilter, which is no longer the default in 7.x. The newer `PoiWordFilter` is the default.
