### ISSUE TITLE
[DS-3643] Ingest adds empty license file for collections using the default license

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#6992]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3643">[DS-3643]</a> created by sulfrian</i>
<p>On ingest the packager will add a license, if the package does not contain a license bundle. The packager will use the license of the collection, even if the collection is using the repository default license. It will simply add an empty license file and does not fall back for the global default license.</p>

**Comment by tdonohue** [comment]
First fixed in 6.4
