### ISSUE TITLE
[DS-3725] Homepage DiscoveryConfiguration never used due to missing IDs

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7072]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3725">[DS-3725]</a> created by lotte.hofstede</i>
<p>The method SearchUtils#getAllDiscoveryConfigurations(Item) checks if a certain DiscoveryConfiguration has already been added by comparing it's ID to the existing map keys. If the key already exists, the DiscoveryConfiguration is not added to the list of used configurations by this item. </p>

<p>However, both the 'site' and 'default' DiscoveryConfiguration do not have a property 'id' defined in DSpace's vanilla discovery.xml. Because both their ID is 'null', and null can be a key in a hashmap, both configurations will never be added to the same item.</p>

<p>The result is that the 'default' DiscoveryConfiguration is also used on the home page, instead of the 'site' DiscoveryConfiguration.<br/>
Looking at the code, I suspect the issue also exists in DSpace 5 (and maybe earlier versions), but I haven't tested this yet.</p>

<p>I propose we add the id property to each configuration.</p>

**Comment by tdonohue** [comment]
Closing, fixed in 6.x by #2662.  Was NOT ported to 7.x as it doesn't work there and isn't necessary.
