### ISSUE TITLE
[DS-3776] Document the use of the authentication in the new REST API

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7123]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3776">[DS-3776]</a> created by bollini</i>
<p>This is issue to remember to move the documentation available in the PR <a href="https://github.com/DSpace/DSpace/pull/1873" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/pull/1873</a> to the REST Contract</p>

**Comment by tdonohue** [comment]
Closing, fixed in https://github.com/DSpace/RestContract/pull/89
