### ISSUE TITLE
[DS-3920] Solr MoreLikeThis: slow query response and innacurate results

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7267]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3920">[DS-3920]</a> created by brizzo</i>
<p>The query used for MoreLikeThis using the item's handle has a space character (": ")</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
solrQuery.setQuery(HANDLE_FIELD + <span class="code-quote">": "</span> + item.getHandle());
</pre>
</div></div>
<p><a href="https://github.com/DSpace/DSpace/blob/829ee0687a2c84b9d28bff591def8e0ec06048b2/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L2002" class="external-link" target="_blank" rel="nofollow noopener">link </a></p>

<p>That space character causes a strange behaviour when simulating a query using Solr Interface (localhost:8080/dspace/solr), for example. That space is interpreted by Solr as a "+" sign in the beginning of the query. In our instance, it makes MoreLikeThis not to work properly, causing items to show very slowly and not giving correct results, especially when adding more fields to MLT (MoreLikeThis) in discovery.xml.</p>

<p>In some cases, some items were taking more than 1 minute to load when verifying the query response time in Solr interface.</p>

<p>After we removed that space, the problem disappeared. The items started to load quickly (milisseconds) and MLT results became accurate:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
solrQuery.setQuery(HANDLE_FIELD + <span class="code-quote">":"</span> + item.getHandle());</pre>
</div></div>

**Comment by tdonohue** [comment]
Closing, this was fixed in #2080, and is a duplicate of DS-3930 (#7277)
