### ISSUE TITLE
[DS-3921] Error when delete item from workflow overview

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7268]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3921">[DS-3921]</a> created by santit96</i>
<p>I have an error when trying to delete an item from workflow overview, the following message is shown:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Batch update returned unexpected row count from update [1]; actual row count: 0; expected: 1</pre>
</div></div>
<p>and the item is not deleted.</p>

<p>Steps:</p>
<ol>
	<li>Log In as an Administrator</li>
	<li>Go to workflow overview</li>
	<li>Try to delete an item from the list</li>
</ol>

<p>Doing some debugging apparently the error is in the following line:</p>

<p><a href="https://github.com/DSpace/DSpace/blob/a9d83925cd1a1904e626200cf2f8453dac51cea2/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/xmlworkflow/admin/DeleteWorkflowItemsAction.java#L65" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/a9d83925cd1a1904e626200cf2f8453dac51cea2/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/xmlworkflow/admin/DeleteWorkflowItemsAction.java#L65</a></p>

<p> </p>

<p> </p>
<h1><a name="%C2%A0"></a> </h1>

**Comment by tdonohue** [comment]
This issue is already fixed in 7.0.  Administrators can delete workflow items.

So, this ticket only refers to 6.x and below
