### ISSUE TITLE
[DS-3969] OAI Indexing failing if XMLWorkflow was enabled in Versions prior to 6.3

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7316]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3969">[DS-3969]</a> created by christian.scheible</i>
<p>If XMLWorkflow was enabled in DSpace Version < 6.3 there are Resource Policies for archived Items where an EPersonGroup is missing.</p>

<p>Additionally with DSpace 6.3 There was a <a href="https://github.com/DSpace/DSpace/pull/1867/" class="external-link" target="_blank" rel="nofollow noopener">Bug Fix</a> for Embargoed Items which checks Resource Policies and doesn't handle NULL for Groups:</p>

<p><a href="https://github.com/DSpace/DSpace/blob/dspace-6.3/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L438" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6.3/dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java#L438</a> </p>

<p>This leads to a NullPointerException when updating the OAI index. So the index will never get updated with DSpace 6.3 in this cases.</p>

**Comment by tdonohue** [comment]
Closing, this was fixed in #2213 and this ticket was a duplicate of DS-4019 (#7366)
