### ISSUE TITLE
[DS-3974] Orphaned files in assetstore after REST update

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7321]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3974">[DS-3974]</a> created by dimitrove</i>
<p>I installed version 6.3.<br/>
Ingested one item with packager:</p>

<p>dspace packager -e ed@nomail.xx -p nls/2 -t METS D:\DSPACE.6.3\DSPACE_data\testitem_01.zip</p>

<p>The zip file is attached.</p>

<p>Replaced one file using REST:</p>

<p>curl -v -X PUT --cookie cookie.txt --upload-file mets_new.xml <a href="http://localhost:8080/rest/bitstreams/a3fbe373-7fd5-4665-a363-cd9732da3b53/data" class="external-link" target="_blank" rel="nofollow noopener">http://localhost:8080/rest/bitstreams/a3fbe373-7fd5-4665-a363-cd9732da3b53/data</a></p>

<p>The result is one orphaned file in assetstore.</p>

<p>-----------<br/>
"bitstream" table and assetstore before REST update</p>

<p>bitstream_id bitstream_format_id checksum checksum_algorithm internal_id deleted store_number sequence_id size_bytes uuid<br/>
<null> 16 d8dab40b5178ae3bb22399e58d1228e3 MD5 99552147714687398195088648322615069704 false 0 10001 7981 28e7bffe-1b08-4852-8e82-8c9c1c22d9e5<br/>
<null> 16 dbe4028cbcc994daf7da35bbe8c95973 MD5 128034867104577610303118274209040277312 false 0 20001 133827 890cbef3-0931-4fc0-87d7-aa2d8af24f63<br/>
<null> 5 670611a4b7629760745092ce210be164 MD5 150688568019294964190566672384371588135 false 0 30001 2218 a3fbe373-7fd5-4665-a363-cd9732da3b53<br/>
<null> 2 d41d8cd98f00b204e9800998ecf8427e MD5 99750278015380062141218552285495509190 false 0 30002 0 ed653405-5e80-4251-b78d-add0d2ffe26f</p>

<p>dir /s D:\DSPACE.6.3\DSPACE\assetstore</p>

<p>07/08/2018 15:31 133,827 128034867104577610303118274209040277312<br/>
07/08/2018 15:31 2,218 150688568019294964190566672384371588135<br/>
07/08/2018 15:31 7,981 99552147714687398195088648322615069704<br/>
07/08/2018 15:31 0 99750278015380062141218552285495509190</p>

<p>-----------<br/>
"bitstream" table and assetstore after REST update</p>

<p>bitstream_id bitstream_format_id checksum checksum_algorithm internal_id deleted store_number sequence_id size_bytes uuid<br/>
<null> 16 d8dab40b5178ae3bb22399e58d1228e3 MD5 99552147714687398195088648322615069704 false 0 10001 7981 28e7bffe-1b08-4852-8e82-8c9c1c22d9e5<br/>
<null> 16 dbe4028cbcc994daf7da35bbe8c95973 MD5 128034867104577610303118274209040277312 false 0 20001 133827 890cbef3-0931-4fc0-87d7-aa2d8af24f63<br/>
<null> 2 d41d8cd98f00b204e9800998ecf8427e MD5 99750278015380062141218552285495509190 false 0 30002 0 ed653405-5e80-4251-b78d-add0d2ffe26f<br/>
<null> 5 621f034180da362544e9ff3094a51c0a MD5 121010454751012672449325080203395050588 false 0 30001 2218 a3fbe373-7fd5-4665-a363-cd9732da3b53</p>

<p>dir /s D:\DSPACE.6.3\DSPACE\assetstore<br/>
07/08/2018 16:08 2,218 121010454751012672449325080203395050588<br/>
07/08/2018 15:31 133,827 128034867104577610303118274209040277312<br/>
07/08/2018 15:31 2,218 150688568019294964190566672384371588135<br/>
07/08/2018 15:31 7,981 99552147714687398195088648322615069704<br/>
07/08/2018 15:31 0 99750278015380062141218552285495509190</p>

<p> </p>

**Comment by tdonohue** [comment]
Closing as associated PR #2165 was closed as won't fix
