### ISSUE TITLE
[DS-3976] Reduce initialization of ItemCounter

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7323]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3976">[DS-3976]</a> created by kingkrimmson</i>
<p>When <tt>ItemCounter</tt> is initialized (in 5.x versions of DSpace), a solr query is performed to count the number of items in each community/collection.<br/>
<tt>CommunityViewer</tt> and <tt>CommunityBrowser</tt> each initialize this object once for every node, greatly reducing performance.<br/>
Simply initializing one global <tt>ItemCounter</tt> and using it throughout the transformar fixes the issue</p>

**Comment by tdonohue** [comment]
Closing, fixed by #2161
