### ISSUE TITLE
[DS-3984] Improve performance/strategy to lookup a DSO by UUID in Hibernate

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7331]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3984">[DS-3984]</a> created by bollini</i>
<p>Hibernate uses only the UUID to retrieve a DSpaceObject crossjoin the Community, Collection, Item, Bitstream, etc. table. </p>

<p>Finding a way to store the resource type in the dso table aside the uuid could be a way to improve the hibernate query knowing in advance which other table contains the additional information</p>

**Comment by tdonohue** [comment]
Closing, as this looks to have been implemented in #2179
