### ISSUE TITLE
[DS-3996] The "first few letters" search input in the browse (authors, subject, etc) works poorly

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7343]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3996">[DS-3996]</a> created by santit96</i>
<p>In a browse, If the user jumps to any of the letters, or do a search by "first few letters" and then do another "first few letters" search this last search is not properly done.</p>

<p>The error was brought in this <a href="https://github.com/DSpace/DSpace/commit/7b2050e1de24a79ae6fa4412e5bb3bd9e3cea8a9#diff-ded764e50a74460f44be811a77ff6d32" class="external-link" target="_blank" rel="nofollow noopener">commit</a></p>

<p>Steps to recreate the error:<br/>
 1- Go to any of the browses (authors, subject, etc)<br/>
 2- Jump to any of the letters or perform a "first few letters" search<br/>
 3- Perform a "first few letters"search</p>

<p>I solved this at CIC-DIGITAL repository: <a href="https://www.google.com/url?q=https://github.com/CICBA/DSpace/blob/555f15144c4be168d372c75cecfda5009ade25ac/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/ConfigurableBrowse.java%23L435-L436&sa=D&source=hangouts&ust=1535639615329000&usg=AFQjCNFPCuk5BMSsdnCFshd8f5SWoIrLxwmmit" title="https://www.google.com/url?q=https://github.com/CICBA/DSpace/blob/555f15144c4be168d372c75cecfda5009ade25ac/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/ConfigurableBrowse.java%23L435-L436&sa=D&source=hangouts&ust=1535639615329000&usg=AFQjCNFPCuk5BMSsdnCFshd8f5SWoIrLxw" class="external-link" target="_blank" rel="nofollow noopener">link to commit line</a></p>

**Comment by tdonohue** [comment]
Closing as this was fixed by https://github.com/DSpace/DSpace/pull/2113 and duplicated DS-3945 (#7292) which is already closed
