### ISSUE TITLE
[DS-3998] ORCID - NullPointException by querying orcid web services

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7345]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-3998">[DS-3998]</a> created by qzhao</i>
<p>I used author lookup to search for an author with given name "Thomas", in the log file I saw an NullPointException in class <em>org.dspace.authority.orcid.Orcidv2AuthorityValue#setValues(Person)</em>. And I got nothing in the lookup list. </p>

<p>While searching at orcid.org with the same key "Thomas" I got a list of authors, some have no family name. The NullPointException looks like that caused by calling <em>name.getFamilyName().getValue()</em> in the <em>setValues(Person)</em> method. </p>

<p>I don't know why orcid.org allows "bad" data, but I think that althrough we can throw the "bad" record directly. </p>

<p>I added a try/catch in this method and let it return null by exception (see below). It works well. The author list is not empty any more.</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
<span class="code-keyword">protected</span> void setValues(Person person) {
    <span class="code-keyword">try</span> {
      	 NameType name = person.getName();
<span class="code-keyword">if</span> (!StringUtils.equals(name.getPath(), authority.getOrcid_id())) {
	authority.setOrcid_id(name.getPath());
}
<span class="code-keyword">if</span> (!StringUtils.equals(name.getFamilyName().getValue(), authority.getLastName())) {
	authority.setLastName(name.getFamilyName().getValue());
}
...
authority.setValue(authority.getName());
    } <span class="code-keyword">catch</span> (Exception e) {
    	<span class="code-comment">// <span class="code-keyword">throws</span> bad record
</span><span class="code-keyword">return</span> <span class="code-keyword">null</span>;
   }
   <span class="code-keyword">return</span> authority;
}
</pre>
</div></div>
<p> </p>

**Comment by tdonohue** [comment]
Closing as "won't fix".  Unable to reproduce the issue...see comments on #2194

**Comment by tdonohue** [comment]
Disregard previous comment. This turned out to be reproducible after all. Keeping closed though, as it was just fixed by #7940
