### ISSUE TITLE
[DS-4002] Automatic Metadata Extraction updates in-progress submissions without notifying Angular UI

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7349]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4002">[DS-4002]</a> created by tdonohue</i>
<p>This is a usability issue rather than a specific "bug". It was discovered in the testing of <a href="https://github.com/DSpace/dspace-angular/pull/279" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/dspace-angular/pull/279</a></p>

<p>When automatic metadata extraction is enabled for DOIs (or similar identifier fields), extracted metadata may sometimes get duplicated in the workspace item <b>without</b> notifying the user.  This only occurs in the new DSpace 7 REST API (as it's a new feature there).</p>

<p>For example, if you update a PDF into DSpace 7 Angular UI, that PDF's metadata will be extracted to start a new workspace item.  If the user then adds a DOI (and the DOI metadata lookup is enabled), then additional metadata may be added to the workspace item from the DOI.</p>

<p>While in some scenarios, this is a great feature, it can result in duplicate titles/abstracts/etc if the DOI metadata differs from the PDF metadata by just a single character (e.g. a period or comma).</p>

<p>Ideally, the REST API should notify the Angular UI when a metadata update is about to occur. We may even want to prompt the user to "approve" or "reject" an automated metadata update. Currently, this update is entirely on the server-side, and new metadata suddenly appears in the submission UI (without any notification or approval).</p>

<p> </p>

<p> </p>

<p> </p>

**Comment by tdonohue** [comment]
Closing, per previous comment... this is "fixed" in 7.0 for now in that the behavior won't occur.

Further work in this space will be done in #2833 and #2834... so, this ticket has no purpose anymore.
