### ISSUE TITLE
[DS-4034] The "first few letters" search doesn't work with diacritics

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7381]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4034">[DS-4034]</a> created by adan.roman</i>
<p>It can be tested at <a href="http://demo.dspace.org/xmlui/browse?type=author" class="external-link" target="_blank" rel="nofollow noopener">http://demo.dspace.org/xmlui/browse?type=author</a> searching an author with diacritic "Azcárate" for example. It return no results.</p>

**Comment by tdonohue** [comment]
Closing, fixed by #2276
