### ISSUE TITLE
[DS-4044] DataCiteConnector assumes schema version 2.2

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7391]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4044">[DS-4044]</a> created by mwood</i>
<p>After transforming DIM for an item to DataCite XML metadata, the code adds an <identifier identifierType='DOI'/> element with the generated DOI as content before sending the document to DataCite.  This is hardcoded to use "http://datacite.org/schema/kernel-2.2" as the element's namespace.  That matches the current distributed transform's default namespace and thus will be suppressed, but if a site alters the default namespace of the transform (perhaps to use elements not defined in 2.2) then the element gets an explicit namespace different from the rest of the document.  DataCite rejects this.  They could accept it – it is in theory understandable – but they don't.</p>

<p>It is a simple matter to ask the document object for its default namespace and use that, so that the <identifier/> element tracks the document's namespace.</p>

**Comment by tdonohue** [comment]
Closing, fixed in 6.0
