### ISSUE TITLE
[DS-4065] DSpace 6 REST API includes restricted items in its internal count

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7412]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4065">[DS-4065]</a> created by hrafn.malmquist</i>
<p>It is a known issue that the REST API in 6 does not supply total results when doing pagination (see <a href="https://jira.duraspace.org/browse/DS-3887" class="external-link" target="_blank" rel="nofollow noopener">DS-3887</a>) which makes iterating the results an exploratory process.</p>

<p>This problem is compounded by the fact that the REST API does an internal count, then responds with those items that are not restricted. This means that if you send an anonymous query like so:</p>

<p> curl -s -H "Accept: application/json" <a href="https://demo.dspace.org/rest/items?offset=0&limit=5" class="external-link" target="_blank" rel="nofollow noopener">https://demo.dspace.org/rest/items?offset=0\&limit=5</a>"</p>

<p>you will get 5 results provided they're all open to anonymous users</p>

<p>if you then login to the server and pick one item and make it private and do the same query</p>

<p>you will get 4 results</p>

<p>even though the next query:</p>

<p> curl -s -H "Accept: application/json" <a href="https://demo.dspace.org/rest/items?offset=5&limit=5" class="external-link" target="_blank" rel="nofollow noopener">https://demo.dspace.org/rest/items?offset=5\&limit=5</a></p>

<p>would give you up to five results</p>

<p>there are at the time of this writing 63 items in the demo server and I've made two of them private.</p>

<p>the bug can be confirmed by doing a curl query like above with a low limit, selecting one of the items and making it private and then redoing the same query to see that the next record does not cascade down.</p>

<p> </p>

<p> </p>

<p>  </p>

**Comment by tdonohue** [comment]
Closing, the old (v6) REST API is no longer being actively developed and will be removed in 8.0 (see #7643).  The new REST API v7 is the current REST API: https://github.com/DSpace/RestContract/#readme
