### ISSUE TITLE
[DS-4072] Generate password reset link from command line

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7419]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4072">[DS-4072]</a> created by saiful</i>
<p>Currently resetting password requires email system to be working. There are situations where setting up email is not trivial. Resetting password becomes a problem in those scenarios.</p>

<p>It would be nice to have a command line interface (say "bin/dspace user -M <email>" with an additional option) to generate password reset link for a user and display it on the screen instead of sending an email.</p>

<p>In Drupal, the command-line tool (drush) has such feature and I find it quite useful.</p>

**Comment by tdonohue** [comment]
Closing, replaced by #3363 and #3364 which allow for password reset from CLI
