### ISSUE TITLE
[DS-4106] Add option to "dspace database" command to create SITE object and default groups

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7453]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4106">[DS-4106]</a> created by terrywbrady</i>
<p>I am testing an upgrade from DSpace 5.9 to DSpace 6x. The site object is not created in the database during the migration. What action should trigger the creation of this object? There are some /rest components that expect this object to exist.</p>

<p>Kevin Van de Velde (Atmire) <span class="error">&#91;1:51 AM&#93;</span><br/>
@terrywbrady It should be created by a flywayCallBack: <a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/storage/rdbms/SiteServiceInitializer.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/storage/rdbms/SiteServiceInitializer.java</a></p>

<p>The flywaycallbacks are set here: <a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseUtils.java#L513" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseUtils.java#L513</a></p>

<p>They are configured in spring on the following location: <a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/resources/spring/spring-dspace-core-services.xml#L43" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/resources/spring/spring-dspace-core-services.xml#L43</a></p>

<p>So in theory the site object should be created after flyway was migrated :thinking_face:</p>

<p>Tim Donohue <span class="error">&#91;6:23 AM&#93;</span><br/>
@terrywbrady: You might want to check for errors in the upgrade (in dspace logs). I have seen scenarios where errors in one Flyway Callback cause other Flyway Callbacks to <em>not be run</em>. As @kevinvdv notes, the callback should have run to create the Site. But, if it didn't that implies something else in the upgrade threw errors.</p>

<p>Terry Brady <span class="error">&#91;8:44 AM&#93;</span><br/>
Thanks @kevinvdv and @tdonohue. I will likely re-run the migration and look for any errors that might have halted the process.<br/>
I encountered a registry loader error, so I am now not surprised that this step did not get run.</p>

<p>Mark Wood <span class="error">&#91;8:59 AM&#93;</span><br/>
'bin/dspace database status' will also show if there was a problem with the migrations. (Well, it shows whether there are any left to be done, which is always a problem.)</p>

<p>Terry Brady <span class="error">&#91;9:02 AM&#93;</span><br/>
I had tried that and all looked good. I think all the sql ran. I was not as familiar with the code steps triggered by Flyway.</p>

<p>I have things isolated to an issue with my bitstream-format.xml file.</p>

<p>Tim Donohue <span class="error">&#91;9:02 AM&#93;</span><br/>
Unfortunately though, `database status` doesn't show status of <b>Flyway callbacks</b>, it only shows whether official migrations succeeded or fails.</p>

<p>Mark Wood <span class="error">&#91;9:03 AM&#93;</span><br/>
Aha! Sorry for the noise.</p>

<p>Tim Donohue <span class="error">&#91;9:03 AM&#93;</span><br/>
Keep in mind that <b>after</b> all migrations succeed, there's a series of Flyway callbacks that are triggered to add in default data (registry info, Site object, default groups).<br/>
Sometimes you don't realize those callbacks failed, as they only log errors to dspace logs. At some point maybe we can investigate ways to make them "complain more" (or better detect issues & report to user). But, this is just how they work in Flyway by default.</p>

<p>Terry Brady <span class="error">&#91;9:06 AM&#93;</span><br/>
It could also be helpful to make that step invokable from the cli tools.</p>

<p>Tim Donohue <span class="error">&#91;9:08 AM&#93;</span><br/>
@terrywbrady: agreed. These could be turned into `dspace database <span class="error">&#91;action&#93;</span>` commands. The registry imports already are CLI enabled. It'd just be the site creation & default groups (Anonymous / Admin) that'd need to be added there</p>

**Comment by tdonohue** [comment]
Closing, as this was fixed by #7945
