### ISSUE TITLE
[DS-4145] Curation basic link checker doesn't follow redirects

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7488]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4145">[DS-4145]</a> created by kevin van de velde</i>
<p>The curation task that verifies if links attached to items are still operational doesn't follow redirects.</p>

<p>The most simple of links (a call to hdl.handle.net) will be marked as failed because of the 302 code that is returned.</p>

**Comment by tdonohue** [comment]
Closing, fixed by #9658 (for 9.0) and ported to 8.1 and 7.6.3
