### ISSUE TITLE
[DS-4148] Add ability for admin to set user password

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7491]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4148">[DS-4148]</a> created by pongtawat</i>
<p>Currently, there is no way for an admin to forcefully set a password for a user either in XMLUI, JSPUI or even CLI. Probably this is by design. But there are use cases that this feature is useful. All other systems I use have some way for an admin to set user's password. So, please. At least on CLI.</p>

**Comment by tdonohue** [comment]
Closing. Setting password by CLI is coming in #3363.  In DSpace 7.0 you can also change a users password by using the "Login As" or Impersonate feature.  So, this ticket is covered by others.
