### ISSUE TITLE
[DS-4157] Save and Exit on workflow edit metadata

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7499]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4157">[DS-4157]</a> created by philipatmire</i>
<p>When you edit the item metadata during the workflow and choose "Save & Exit" to save the changes, the changes are not actually saved. This issue was introduced in DSpace 6 with Hibernate. </p>

<p> </p>

<p>My suggestion to resolve this is to do a context commit in the describe step to make sure all changes are pushed to the database.</p>

<p> </p>

<p>I will create a pull request with this suggested fix. The fix for this issue was funded by Griffith University.</p>

**Comment by tdonohue** [comment]
Closing, fixed by #2339
