### ISSUE TITLE
[DS-4160] DSpace 6.3 REST-API fail to start on ubuntu 18.04 LTS's tomcat8

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7502]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4160">[DS-4160]</a> created by pbecker</i>
<p>If you install DSpace 6.3 on Ubuntu 18.04 Bionic Beaver and use tomcat8 as provided by the distribution dspace-rest cannot be deployed successfully. The problem is described in the following thread on dspace-tech: <a href="https://groups.google.com/forum/m/#!topic/dspace-tech/VOZFwRamd3M" class="external-link" target="_blank" rel="nofollow noopener">https://groups.google.com/forum/m/#!topic/dspace-tech/VOZFwRamd3M</a>. Basically rest is not able to open a database connection. The problem can be reproduced by installing a Ubuntu 18.04, using apt-get install to install OpenJDK 8 and tomcat 8, installing DSpace, deploying jspui, solr and rest to the tomcat, and using tomcat8 as DSpace user (who should then own dspace.dir and included files).</p>

<p>The log output is quite long, so I put it into a gist: <a href="https://gist.github.com/the-library-code/ca42a171f19f18b3575c085fbb4dc3e7" class="external-link" target="_blank" rel="nofollow noopener">https://gist.github.com/the-library-code/ca42a171f19f18b3575c085fbb4dc3e7</a></p>

<p>Workaround: I was able to deploy rest to tomcat 8.5.30 on ubuntu 18.04 by using a tarball I downloaded from tomcat.apache.org instead of using the installation provided by ubuntu.</p>

**Comment by tdonohue** [comment]
Closing as this (now deprecated) REST API works in v7 on Java 11.  However, DSpace 6 doesn't support Java 11.
