### ISSUE TITLE
[DS-4168] Performing metadataschema or metadatafield PUT requests as an unprivileged user results in a 404 instead of a 403

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7510]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4168">[DS-4168]</a> created by paulo_graca</i>
<p>Reported in the code review process of this PR: <a href="https://github.com/DSpace/DSpace/pull/2291#pullrequestreview-202680789" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/pull/2291#pullrequestreview-202680789</a> </p>

<p>As noted in those comments, if you perform a PUT request to "metadatafield" or "metadataschema" as an unprivileged user (an EPerson without correct permissions), a 404 response is returned. </p>

<p>The expectation is a 403 Forbidden response should be returned.</p>

<p>You can test with the Atmire's database - <a href="https://www.dropbox.com/s/ovqp394y3vofnwa/entities7-test-db.sql.gz?dl=1" class="external-link" target="_blank" rel="nofollow noopener">https://www.dropbox.com/s/ovqp394y3vofnwa/entities7-test-db.sql.gz?dl=1</a><br/>
And with a user that doesn't have any record on epersongroup2eperson, like atmirenv+write5a@g****.com.</p>

<p>Trying this PUT <a href="http://localhost/spring-rest/api/core/metadataschemas/1" class="external-link" target="_blank" rel="nofollow noopener">http://localhost/spring-rest/api/core/metadataschemas/1</a><br/>
`{"id":1,"prefix":"dc","namespace":"http://dublincore.org/documents/dcmi-terms/"}`</p>

<p>I've got an 404 error, please check out my apache log:</p>

<p>`SERVER - - <span class="error">&#91;11/Feb/2019:15:14:37 +0000&#93;</span> "PUT /spring-rest/api/core/metadataschemas/1 HTTP/1.1" 404 949 "http://localhost/admin/registries/metadata/eperson?pageId=registry-metadatafields-pagination&page=1&pageSize=25&sortDirection=ASC&sortField=id" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"`</p>

<p> </p>

**Comment by tdonohue** [comment]
This appears to be fixed. Closing
