### ISSUE TITLE
[DS-4170] Modifying metadata registries usability issues

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7512]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4170">[DS-4170]</a> created by paulo_graca</i>
<p>The admin metadata registries interface is presented with some usability issues like:<br/>
. if the user wants to change an existing schema it will be very hard to accomplish this task at first time (we've tried this with 3 different people)<br/>
. The content and actions will be accessible even if the user isn't an administrator<br/>
. The fields list is visible (without the actions) even when your logged session expires<br/>
. if you have an extensive list of fields/schemas, if the user clicks on the a bottom row to change that field/schema, it seems like nothing happened. The user need to figure out that he must scroll up to the form<br/>
. the "Delete Selected" button, will not be visible if you have an extensive list of fields/schemas</p>

<p>For more information, please visit: <a href="https://github.com/DSpace/dspace-angular/pull/355" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/dspace-angular/pull/355</a></p>

**Comment by tdonohue** [comment]
This seems outdated.  Closing, as I think most of these issues have been fixed with pagination, session timeouts, and better authorization handling.
