### ISSUE TITLE
[DS-4172] Withdrawn & private items accessible through open-search/

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7513]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4172">[DS-4172]</a> created by david.atmire</i>
<p>If you use the open-search endpoint and query a withdrawn handle, it is retrieved in the results while it should not : </p>

<p><a href="https://demo.dspace.org/xmlui/open-search/?query=10673/49" class="external-link" target="_blank" rel="nofollow noopener">https://demo.dspace.org/xmlui/open-search/?query=10673/49</a></p>

<p>(please note that as demo.dspace is periodically refreshed, this handle might not exist anymore when this issue is investigated).</p>

**Comment by alanorth** [comment]
For what it's worth, I cannot reproduce this for _withdrawn_ items on my DSpace 7.6.1 instance.

The claim about "private" items needs more information: non-discoverable items are not private _per se_, so those can be accessed by their Handle if they are known. Unless by "private" the original issue was about items where metadata is limited via authorization policies (ie not available to Anonymous).
