### ISSUE TITLE
[DS-4183] XML Schema for metadata schema documents (dspace-dc-types)

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7523]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4183">[DS-4183]</a> created by mwood</i>
<p>Because I'm the sort of person who thinks no XML document is complete if it can't be validated, I wrote an XML Schema definition for DSpace's metadata schema documents.  Pull Request to follow.</p>

**Comment by mwoodiupui** [comment]
Well, it's a DTD, not a Schema, but better than nothing.

**Comment by tdonohue** [comment]
@mwoodiupui : Good point. If you want to replace with a Schema at some point, I'm OK with that. I just am trying to "cull down" the huge list of open tickets...so, in this case, a DTD serves the validation need defined in this ticket.
