### ISSUE TITLE
[DS-4207] Modify design of submissions page for logged in users

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7547]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4207">[DS-4207]</a> created by gss1</i>
<p>Some (we think) rational suggestions from one of our power users to improve the usability of the submissions page:</p>
<ul>
	<li>Place workflow tasks at the top of the page, then submissions.</li>
	<li>Either list only the ten most recent submissions, or make that an expandable/collapsible list.</li>
	<li>Probably have to rename the link under my account - perhaps "tasks and submissions".</li>
</ul>

<p>Thanks for considering.</p>

**Comment by tdonohue** [comment]
Closing, as this is outdated.  The Submission & MyDSpace pages are much easier to use in 7.0
