### ISSUE TITLE
[DS-4208] XMLUI Jump to Date: Form parameters are not retained on second year selection

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7548]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4208">[DS-4208]</a> created by terrywbrady</i>
<p>In my repository, I have set the first sort field to be "Creators".</p>

<p>On demo.dspace.org, the default sort is "Issue Date".  This partially masks the issue that I am seeing.</p>
<ul>
	<li>Search the repository or a collection by issue date</li>
	<li>Jump to a specific year</li>
	<li>Note the form parameters: "rpp=20&sort_by=2&type=dateissued&etal=-1&order=ASC&year=2015&starts_with=&submit="</li>
	<li>Select a different year</li>
	<li>Note the form parameters: "year=2014&starts_with=&starts_with=&submit="</li>
</ul>

<p>Because of the default sort on demo.dspace.org, the results sort of make sense.</p>

<p>If you have a different sort order as your primary sort (such as creator), it will try to search creators by "year".</p>

**Comment by tdonohue** [comment]
Closing, fixed by #2490
