### ISSUE TITLE
[DS-4233] Utility class to convert dotted metadata field to schema, element, qualifier

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7573]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4233">[DS-4233]</a> created by benbosman</i>
<p>An object to store metadata field names and convert dotted syntax to schema, element, qualifier and vice versa would be useful in many areas in DSpace</p>

**Comment by tdonohue** [comment]
Closing, this appears to exist in `Utils.tokenize()` and `Utils.standardize()`.
