### ISSUE TITLE
[DS-4254] Authority control - "Suggest" type is not working

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7594]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4254">[DS-4254]</a> created by marcio.gurgel</i>
<p>The rendering type "suggest" for the authority plugin is not working on DSpace 6.3.</p>

<p>There's is an string concatenation error when the call to </p>

<p>"DSpaceSetupAutocomplete" is built (edit-metadata.jsp) . </p>

<p>This concatenation problem results the following invalid HTML:</p>

<p><img src="https://jira.lyrasis.org/images/icons/attach/noimage.png" imagetext="image-2019-05-20-11-20-03-319.png" align="absmiddle" border="0" /></p>

<p>(notice that "collection" attribute became invalid)</p>

<p> </p>

**Comment by tdonohue** [comment]
Closing, fixed by #2918.  See also comments in #2434
