### ISSUE TITLE
[DS-4255] Support use of AWS roles and profiles for S3 bitstore access

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7595]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4255">[DS-4255]</a> created by cwilper</i>
<p>The current S3Bitstore implementation expects you to directly enter AWS credentials into DSpace configuration. The AWS SDK supports a more flexible and secure means of providing credentials, through the use of profiles.</p>

<p>This improvement would do the following:</p>

<ul>
	<li>Do away with specifying the AWS access key and secret access key directly in DSpace configuration</li>
	<li>Instead, have DSpace configuration optionally specify:</li>
	<li><b>profileName:</b> identifies the named profile in the AWS credentials file. If unspecified and DSpace is running in EC2, the instance role (if assigned) would be used. If not running in EC2 and profileName is unspecified, the "default" profile in the credentials file would be used.</li>
	<li><b>credentialsFile:</b> provides the path to the AWS credentials file. If unspecified, the default location of ~/.aws/credentials will be used.</li>
</ul>

<p>This would provide better security for DSpace installs running in EC2, because deployers would not need to store credentials on the host. In addition, by using the standard AWS credentials file, it would support a more familiar and flexible way for people to specify credentials: Direct access keys could be used, or profiles could be set up that automatically assume roles with appropriate permissions when needed.</p>

<p><b><em>Implementation note:</em></b> This would amount to replacing this code: <a href="https://github.com/DSpace/DSpace/blob/dspace-7.0-preview-1/dspace-api/src/main/java/org/dspace/storage/bitstore/S3BitStoreService.java#L90-L91" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-7.0-preview-1/dspace-api/src/main/java/org/dspace/storage/bitstore/S3BitStoreService.java#L90-L91</a> ...with something like this: <a href="https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/GetObject.java#L49-L52" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/java/example_code/s3/src/main/java/GetObject.java#L49-L52</a></p>

**Comment by tdonohue** [comment]
Closing, as this appears to be a duplicate of #8363, which was fixed by #8356
