### ISSUE TITLE
[DS-4260] CLI harvest promotes non-exisiting command

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7600]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4260">[DS-4260]</a> created by pbecker</i>
<p><span class="error">&#91;dspace&#93;</span>/bin/dspace harvest &#45;h describes a command &#45;o that should start a harvest run with specified parameters once, without saving those parameters. This command is shown in the online help, but is not implemented anywhere. Furthermore I doubt how much sense this would make, as we might end up in a situation where we shouldn't or cannot store the harvest status of the collection / of the harvested items. Fix is simple: remove that from the online help.</p>

**Comment by tdonohue** [comment]
Closing, fixed in #2438 and #2439
