### ISSUE TITLE
[DS-4271] Discovery "contains" filter does not perform a phrase query

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7611]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4271">[DS-4271]</a> created by cwilper</i>
<p>When doing a "contains" filter query, if the value entered for the field contains spaces, the behavior is to return documents where the individual words are present in any order the field.</p>

<p>A typical user would expect "contains" to do a phrase query, where the entire phrase occurs somewhere in the field's value.</p>

<p>This is a long-standing issue that stems from the following line in SolrServiceImpl, which has remained untouched since the original Discovery implementation, and is present in versions 4.x through 7.0 Preview 1:</p>

<p><a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L2110" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L2110</a></p>

<p>Notice how it surrounds the text sent to solr with "(" and ")". <em>This has specific meaning in solr, which differs from surrounding the text with double quotes.</em> Surrounding with double quotes would have the expected effect of doing a phrase query. Surrounding with parentheses is equivalent to entering multiple fielded search tearms, one for each word. For example, a the solr query:</p>

<p><tt>title:(introduction to dspace)</tt></p>

<p>...is the same as the solr query:</p>

<p><tt>title:introduction title:to title:dspace</tt></p>

<p>...which is not the expected effect.</p>

<p>The solution, which we have tested, is to replace the surrounding parentheses in the code referenced above, with double quotes.</p>

**Comment by tdonohue** [comment]
Closing, first fixed in 6.4 via https://github.com/DSpace/DSpace/pull/2543.  
Also fixed in 7.3 via https://github.com/DSpace/DSpace/pull/8284
