### ISSUE TITLE
[DS-4284] (Google Scholar) Extend Submission Metadata Extraction to lookups on common fields (Title, Date, etc)?

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7624]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4284">[DS-4284]</a> created by tdonohue</i>
<p>This is a request of the Google Scholar team.  I had a brief meeting with them today to discuss the upcoming DSpace 7 release.</p>

<p>As noted in other tickets, the biggest issues that Google Scholar encounters in metadata entired (manually) in DSpace is either incorrect Dates, or incorrect (or incomplete) Author lists.</p>

<p>While they are happy to hear that DSpace 7 Submission UI provides automatic metadata extraction features (via Identifier lookups, like DOIs, and PDF metadata extraction), they noted that an additional improvement may be to compare entered metadata (e.g. Title, a few Authors, etc) with an external system in order to validate the metadata. </p>

<p>This might be almost like a "Did you mean?" feature where a lookup using Title & perhaps the first Author could allow a user to select an external Item to prepopulate the rest of the metadata. </p>

**Comment by tdonohue** [comment]
Closing as this is outdated/obsolete
