### ISSUE TITLE
[DS-4286] Fix http: code repository URLs in our POMs

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7626]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4286">[DS-4286]</a> created by mwood</i>
<p>See <a href="https://medium.com/bugbountywriteup/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb" class="external-link" target="_blank" rel="nofollow noopener">this report</a>.  We declare at least one non-HTTPS repository URL (for id:maven-snapshots).  I used the attached XQuery to find candidates.  All fetching of remote artifacts should use HTTPS.</p>

**Comment by tdonohue** [comment]
Closing, just checked and this is fixed in both 7.x (`main`) and 6.x (`dspace-6_x`)
