### ISSUE TITLE
[DS-4288] Deleted items not being removed from OAI-PMH index

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7628]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4288">[DS-4288]</a> created by bbranan</i>
<p>When an item is deleted from DSpace it is not being completely removed from the OAI-PMH index. This is resulting in external systems that make use of harvesting via OAI-PHM retaining links to and information about content that has been removed from the repository.</p>

<p>I saw this initially in DSpace 5.8, then verified that the same behavior exists in 6.3 by performing a test on demo.dspace.org.</p>

<p><b>Steps to reproduce</b></p>
<ol>
	<li>Choose or create an Item in the repository and verify that it is listed in the OAI-PMH index. Capture the OAI ID and the link where the item can be found in the DSpace OAI-PHM index.</li>
	<li>Delete the Item, then wait overnight for the cron job that updates the OAI index to run.</li>
	<li>Check again to see if the Item is still referenced in the OAI-PMH set listing.</li>
</ol>

<p>It is worth noting that I only see the deleted item when using the ListRecords verb in the OAI request. Using the GetRecord verb (correctly) does not return a result.</p>

<p><b>Example (on demo.dspace.org)</b> </p>

<p>I deleted this item yesterday:<br/>
URL: <a href="http://demo.dspace.org/xmlui/handle/10673/214" class="external-link" target="_blank" rel="nofollow noopener">http://demo.dspace.org/xmlui/handle/10673/214</a><br/>
Handle URI: <a href="http://hdl.handle.net/10673/214" class="external-link" target="_blank" rel="nofollow noopener">http://hdl.handle.net/10673/214</a><br/>
OAI ID: oai:demo.dspace.org:10673/214</p>

<p>The item was in two collections: <a href="http://demo.dspace.org/xmlui/handle/10673/142" class="external-link" target="_blank" rel="nofollow noopener">http://demo.dspace.org/xmlui/handle/10673/142</a> and <a href="http://demo.dspace.org/xmlui/handle/10673/213" class="external-link" target="_blank" rel="nofollow noopener">http://demo.dspace.org/xmlui/handle/10673/213</a></p>

<p>Today, the item is available in the OAI via a ListRecords request</p>
<ul>
	<li>Seen here: <a href="http://demo.dspace.org/oai/request?verb=ListRecords&metadataPrefix=oai_dc&set=com_10673_126" class="external-link" target="_blank" rel="nofollow noopener">http://demo.dspace.org/oai/request?verb=ListRecords&metadataPrefix=oai_dc&set=com_10673_126</a></li>
	<li>And here (as part of a collection): <a href="http://demo.dspace.org/oai/request?verb=ListRecords&metadataPrefix=oai_dc&set=col_10673_142" class="external-link" target="_blank" rel="nofollow noopener">http://demo.dspace.org/oai/request?verb=ListRecords&metadataPrefix=oai_dc&set=col_10673_142</a></li>
</ul>

<p>The item is not found via the GetRecord request: <a href="https://demo.dspace.org/oai/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:demo.dspace.org:10673/214" class="external-link" target="_blank" rel="nofollow noopener">https://demo.dspace.org/oai/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:demo.dspace.org:10673/214</a></p>

<p><b>Workaround</b></p>

<p>In experiments with DSpace 5.8, performing a full OAI-PHM reindex using {{}}</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
./dspace oai <span class="code-keyword">import</span> -c</pre>
</div></div>
<p> </p>

<p>fixed the issue. After this command was run the item no longer showing up in the OAI-PMH index.</p>

<p>It is worth noting that attempts to clear the OAI-PMH cache using </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
./dspace oai clean-cache</pre>
</div></div>
<p>made no difference.</p>

**Comment by tdonohue** [comment]
Closing as this is a duplicate of #7870 (DS-4537)
