### ISSUE TITLE
[DS-4291] Browse Starts-With 0-9 only returns results for 0

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7631]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4291">[DS-4291]</a> created by kingkrimmson</i>
<p>Currently when browsing by Author, if you click the "0-9" link at the top, it is only showing results for 0 instead of 0-9.</p>

<p>Under the hood, this is being done by a solr facet query prefix, which doesn't support ranges and so is currently only returning results for 0. However, it is fairly quick (even on a large repo) to perform separate queries with prefixes 0-9.</p>

**Comment by tdonohue** [comment]
Fixed in 6.x in #2463  
Has a PR for 7.x in #2696
Ticket can be closed once applied to main for 7.x
