### ISSUE TITLE
[DS-4292] Browse pagination with starts-with is broken

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7632]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4292">[DS-4292]</a> created by kingkrimmson</i>
<p>Currently, if you're browsing by Author, select a starts-with link and then click the next page, it brings you to the 2nd page of <em>all</em> results rather than the 2nd page of those _starts_with results.</p>

**Comment by tdonohue** [comment]
PR #2464 was closed as `won't fix` as the error was found to already be fixed.  Closing this as well
