### ISSUE TITLE
[DS-4295] DSpace REST API - create new item - 500 internal server error

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7635]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4295">[DS-4295]</a> created by samuelcambien</i>
<p>When trying to create a new item through the REST API, a "500 internal server error" status is returned. This only happens the first time after logging in.</p>

<p> </p>

<p>Steps to reproduce:</p>

<p> </p>

<p>curl -X POST \<br/>
<span class="error">&#91;DSpace REST endpoint&#93;</span>/login \<br/>
 -H 'Content-Type: application/json' \<br/>
 -d '{"email":"<span class="error">&#91;email&#93;</span>", "password": "<span class="error">&#91;password&#93;</span>"}'</p>

<p> </p>

<p>curl -X POST \<br/>
<span class="error">&#91;DSpace REST endpoint&#93;</span>/collections/<span class="error">&#91;collection ID&#93;</span>/items \<br/>
 -H 'Content-Type: application/json' \<br/>
 -H 'rest-dspace-token: <span class="error">&#91;token from previous call&#93;</span>' \<br/>
 -d '{}'</p>

**Comment by tdonohue** [comment]
Closing, the old (v6) REST API is no longer being actively developed and will be removed in 8.0 (see #7643).  The new REST API v7 is the current REST API: https://github.com/DSpace/RestContract/#readme
