### ISSUE TITLE
[DS-4296] Indonesian language code change

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7636]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4296">[DS-4296]</a> created by samuelcambien</i>
<p>The language code for Indonesian has been changed from 'in' to 'id'.</p>

<p> </p>

<p><a href="https://www.loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=207" class="external-link" target="_blank" rel="nofollow noopener">https://www.loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=207</a></p>

<p> </p>

<p>The Locale.convertOldISOCodes method will reflect this change.</p>

<p> </p>

<p>As a result, DSpace will look for the file "messages_id.xml" when this language is selected, but the corresponding messages file is still named "messages_in.xml".</p>

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/dspace-xmlui-lang/pull/40
