### ISSUE TITLE
[DS-4314] Remote Handle Resolver currently unsupported in DSpace 7 codebase

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7654]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4314">[DS-4314]</a> created by tdonohue</i>
<p>As discovered by <a href="https://jira.lyrasis.org/secure/ViewProfile.jspa?name=ilittle.cnri" class="user-hover" rel="ilittle.cnri">Ian Little</a> (in Slack), the `/handleresolver` path which is required by the Remote Handle Resolver was tied to the old XMLUI & JSPUI.  It was removed alongside those UIs and will need replacement in DSpace 7 – either as a part of the REST API v7, or as a parallel endpoint in the new "dspace-server-webapp".</p>

<p><a href="https://github.com/DSpace/Remote-Handle-Resolver/" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/Remote-Handle-Resolver/</a></p>

<p>The `/handleresolver` endpoint previously returned JSON, so it may make the most sense to reimplement this as a REST API v7 endpoint.</p>

<p>Here's the old code from the XMLUI and JSPUI:</p>
<ul>
	<li>XMLUI: <a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/handle/HandleResolverReader.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/handle/HandleResolverReader.java</a></li>
	<li>JSPUI: <a href="https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-jspui/src/main/java/org/dspace/app/webui/handle/HandleJSONResolver.java" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-6_x/dspace-jspui/src/main/java/org/dspace/app/webui/handle/HandleJSONResolver.java</a></li>
</ul>

<p> </p>

<p>Once this is fixed (or if this is delayed), the official Handle setup documentation may also require an update. See: <a href="https://wiki.duraspace.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-ToinstallaHandleresolveronaseparatemachine:" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.duraspace.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-ToinstallaHandleresolveronaseparatemachine:</a></p>

<p> </p>

**Comment by tdonohue** [comment]
Closing, this was fixed in 7.4 by #8357
