### ISSUE TITLE
[DS-4320] Metadata bulk editing of related Entities

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7660]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4320">[DS-4320]</a> created by paulo_graca</i>
<p>Currently, on JSPUI, the admin user is able to export metadata from "simple search" and certain "browse by" pages, the results will include the filtering the user is performing on that specific search.</p>

<p><span class="image-wrap" style=""><img src="https://jira.lyrasis.org/secure/attachment/19522/19522_2019-08-06+17_28_35-Reposit%C3%B3rio+Cient%C3%ADfico+do+Instituto+Polit%C3%A9cnico+de+Santar%C3%A9m_+Browsing+Repository.png" style="border: 0px solid black" /></span></p>

<p>And with that metadata results in the CSV format, the user can do metadata batch editing.</p>

<p>That Export feature it's also available in CLI (but only for communities, collections, items or all) -  <a href="https://wiki.duraspace.org/display/DSDOC6x/Batch+Metadata+Editing#BatchMetadataEditing-ExportFunction" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.duraspace.org/display/DSDOC6x/Batch+Metadata+Editing#BatchMetadataEditing-ExportFunction</a>.</p>

<p><tt><span class="error">&#91;dspace&#93;</span>/bin/dspace metadata-export</tt></p>

<p> </p>

<p>My suggestion it's to extend that feature to be able to also export related items.</p>

<p><tt><span class="error">&#91;dspace&#93;</span>/bin/dspace metadata-export -f name_of_file.csv -i 1023/24 --relation isAuthorOfPublication</tt></p>

**Comment by tdonohue** [comment]
Closing, as this appears to be fixed by #2522 (and related work)
