### ISSUE TITLE
[DS-4327] Configurable workflow: Provenance metadata lacking submitter details

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7667]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4327">[DS-4327]</a> created by bram</i>
<p>To reproduce this:</p>
<ol>
	<li>Ensure you have configurable workflow active, and not the legacy workflow</li>
	<li>Submit an item to a collection that doesn't have any workflow steps enabled. Submission should appear in recent submissions immediately after the original submission.</li>
	<li>As admin, look at the dc.description.provenance metadata field</li>
</ol>

<p>You will see something like:</p>

<p><span class="image-wrap" style=""><img src="https://jira.lyrasis.org/secure/attachment/19529/19529_Screenshot+2019-08-21+at+11.19.39.png" style="border: 0px solid black" /></span></p>

<p>While you are also expecting details about the submitter in there.</p>

<p>In contrast, when a workflow step IS active, there IS an entry that references the original submitter:</p>

<p><span class="image-wrap" style=""><img src="https://jira.lyrasis.org/secure/attachment/19528/19528_Screenshot+2019-08-21+at+14.05.27.png" height="53" width="910" style="border: 0px solid black" /></span></p>

<p>This is an important issue for repositories with many different submitters, and where workflow steps are turned off. Without a fix for this, it is not possible for admins to see which items were submitted by which EPeople.</p>

<p> </p>

**Comment by aroman-arvo** [comment]
I think this can be closed because Dspace 5 and 6 will only receive security updates and Dspace 7 version is at:
#8585

**Comment by tdonohue** [comment]
Closing as this is replaced by #8585
