### ISSUE TITLE
[DS-4328] Error after checking published during initial questions submission step

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7668]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4328">[DS-4328]</a> created by philipatmire</i>
<p>When you don't check the published checkbox on the initial questions step, and after starting the describe step you return to the initial questions step and do check the Published checkbox, an error occurs when continuing to the describe step:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Java stacktrace: java.lang.NullPointerException
at org.dspace.content.DCDate.getYear(DCDate.java:298)
at org.dspace.app.xmlui.aspect.submission.submit.DescribeStep.renderDateField(DescribeStep.java:624)
at org.dspace.app.xmlui.aspect.submission.submit.DescribeStep.addBody(DescribeStep.java:233)
</pre>
</div></div>

<p>This happens because value "today' is added as date issued when the item is not published before. Once you select that the item is published before, the issue date can be filled in during the describe step. But "today" can't be parsed into a date by the DCDate class, causing the nullpointer when rendering the issue date field on the describe step. </p>

<p>Suggested solution:<br/>
Clear the dc.date.issued metadata field when published is selected in the initial questions submission step. </p>

<p> </p>

**Comment by tdonohue** [comment]
Closing, fixed in 6.4 by #2493
