### ISSUE TITLE
[DS-4352] Inconsistent way to guess Mimetype by the REST API

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7691]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4352">[DS-4352]</a> created by bollini</i>
<p>The REST API uses the following method <br/>
<a href="https://github.com/DSpace/DSpace/blob/master/dspace-rest/src/main/java/org/dspace/rest/BitstreamResource.java#L716" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/master/dspace-rest/src/main/java/org/dspace/rest/BitstreamResource.java#L716</a></p>

<p>to guess the mimetype instead than<br/>
dspace 5: org.dspace.content.FormatIdentifier.guessFormat(Context, Bitstream)<br/>
dspace 6 & 7: org.dspace.content.service.BitstreamFormatService.guessFormat(Context, Bitstream)</p>

<p>far from be perfect but at least we should use a consistent strategy in all the layer.</p>

<p>In our specific case, this lead to an issue trying to ingest office file via REST as it rely on the JDK URLConnection and also if the doc, docx extension is added to the dspace file format registry it is not found</p>

**Comment by tdonohue** [comment]
Closing as won't fix. This older REST API is deprecated in 7.x. The new REST API v7 is recommended instead
