### ISSUE TITLE
[DS-4362] Feedback link breaks on sites without sub-domain

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7701]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4362">[DS-4362]</a> created by saiful</i>
<p>On the DSpace 6.4-snapshot the feedback page breaks if the <em>dspace.hostname</em> in config has a single dot (say 'example.com'). The error in the stacktrace is:</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Java stacktrace: java.lang.StringIndexOutOfBoundsException: <span class="code-object">String</span> index out of range: -1
 at java.lang.<span class="code-object">String</span>.substring(<span class="code-object">String</span>.java:1927)
 at org.dspace.app.xmlui.aspect.artifactbrowser.SendFeedbackAction.act(SendFeedbackAction.java:67)</pre>
</div></div>
<p>The line 67 of <em>SendFeedbackAction.java</em> tries to extract the sub-domain even when it doesn't exist and it breaks the page.</p>

**Comment by tdonohue** [comment]
Fixed in #2250 in 6.4
