### ISSUE TITLE
[DS-4374] 400 error when exporting search results

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7713]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4374">[DS-4374]</a> created by alaw</i>
<p>As reported locally in <a href="https://github.com/VTUL/vtechworks/issues/649," class="external-link" target="_blank" rel="nofollow noopener">https://github.com/VTUL/vtechworks/issues/649,</a></p>

<p>On <a href="https://vtechworks.lib.vt.edu/" class="external-link" target="_blank" rel="nofollow noopener">vtechworks.lib.vt.edu</a>, I searched for "Alwang, J." in the Advanced Search box, got 93 search results, and was able to export them. Then I searched for the same term in the author field, author / contains / "Alwang, J." , got 11 search results, and exporting failed with a 400 error,</p>

<p>```<br/>
HTTP Status 400 – Bad Request</p>

<p>Type Exception Report</p>

<p>Message Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986</p>

<p>Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p>

<p>Exception</p>

<p>java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986<br/>
 org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:479)<br/>
 org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684)<br/>
 org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)<br/>
 org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)<br/>
 org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)<br/>
 org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)<br/>
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>
 org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/>
 java.lang.Thread.run(Thread.java:748)</p>

<p>Note The full stack trace of the root cause is available in the server logs.<br/>
```</p>

<p>I repeated with variations:</p>

<p>advanced search = alwang (can export)<br/>
advanced search = "alwang" (can export)<br/>
advanced search = "alwang, j." (can export)<br/>
author contains alwang (can export)<br/>
author / contains / "alwang" (export fails with 400 error)<br/>
author / contains / alwang, j. (export fails with 400 error)<br/>
author / contains / alwang, j (export fails with 400 error)<br/>
author / contains / alwang j (export fails with 400 error)<br/>
author / contains / alwang, jeffrey (export fails with 400 error)<br/>
author / contains / alwang, jeffrey (export fails with 400 error)</p>

**Comment by tdonohue** [comment]
This appears to be the same as #7899, so I'm closing in favor of that other issue (as it has more details on possibly why this occurs)
