### ISSUE TITLE
[DS-4382] BTE ignores fields on import if they are configured in input-types.xml using value pairs

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7721]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4382">[DS-4382]</a> created by pbecker</i>
<p>The Submission Lookup Step in JSPUI uses BTE (biblio transformation engine) to import data into submission items. When importing data into a certain metadata field, the BTE checks if that field is configured for submission in input-types.xml. If a field is configured to be used with the input-type qualdrop an a value pair, the BTE does not recognize the qualifier of that fields. It silently ignores the field.</p>

<p>To reproduce the bug:</p>
<ul>
	<li>configure a field in input forms to be used with value pairs, e.g. dc.identifier. The stored values of the value pairs will be used as field qualifiers.</li>
	<li>configure the BTE to use such a field including its qualifier (e.g. dc.identifier.uri) to import data into it</li>
	<li>create an item using the SubmissionLookupStep, importing data that should create the field you prepared</li>
</ul>

**Comment by tdonohue** [comment]
Closing as "Won't fix" as BTE was removed in 7.0 & the associated PR was rejected.
