### ISSUE TITLE
[DS-4406] Creative Commons step: Public Domain and CC0 choice have same result

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7744]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4406">[DS-4406]</a> created by alaw</i>
<p>In the Creative Commons license submission form step, the user can choose from </p>
<ol>
	<li>Public Domain</li>
	<li>CC0</li>
	<li>Creative Commons</li>
	<li>No Creative Commons license.</li>
</ol>

<p>The result of Public Domain and CC0 are identical:</p>
<ul>
	<li>dc.rights CC0 1.0 Universal *</li>
	<li>dc.rights.uri <a href="http://creativecommons.org/publicdomain/zero/1.0/" class="external-link" target="_blank" rel="nofollow noopener">http://creativecommons.org/publicdomain/zero/1.0/</a> *</li>
	<li>the <a href="http://creativecommons.org/publicdomain/zero/1.0/" class="external-link" target="_blank" rel="nofollow noopener">public domain mark image</a></li>
	<li>license_rdf</li>
</ul>

<p><rdf:RDF><cc:Work rdf:about=""><cc:license rdf:resource="http://creativecommons.org/publicdomain/zero/1.0/"/></cc:Work><cc:License rdf:about="http://creativecommons.org/publicdomain/zero/1.0/"><permits rdf:resource="http://creativecommons.org/ns#DerivativeWorks"/><permits rdf:resource="http://creativecommons.org/ns#Distribution"/><permits rdf:resource="http://creativecommons.org/ns#Reproduction"/></cc:License></rdf:RDF></p>

<p>Licenses are intimidating. The choices should be reduced to 3 or made unique. I also suggest listing the CC license first in the description and dropdown list, since that is commonly the one that submitters want. (It is possible to change an incorrect choice of CC instead of CC0, but not the other way around.)</p>

**Comment by alexandrevryghem** [comment]
@tdonohue this issue can now also be closed since it's a duplicate of #8543

**Comment by tdonohue** [comment]
Closing, fixed by #8903
