### ISSUE TITLE
[DS-4416] Mirage 2 "easy" build broken because gem proxy site was shut down

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7754]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4416">[DS-4416]</a> created by mwood</i>
<p>The Mirage 2 component optionally depends on a proxy which was provided by the torquebox project.  The proxy made rubygems.org appear to be a Maven repository, so that Maven could fetch Ruby 'gems' (packages).  That proxy has been permanently shut down, breaking the "easy" build.</p>

<p>A work around is to install all of Mirage 2's prerequisites manually as explained in the <a href="#installation]." target="_blank" rel="noopener">Mirage 2 'readme'</a></p>

<p>To fix this, we might:</p>
<ul>
	<li>find a different way to automagically acquire the SASS gem</li>
	<li>since we also require node.js, use one of the Javascript SCSS processors and remove all the Ruby-based machinery</li>
	<li>write a Java wrapper around jsass</li>
</ul>

**Comment by tdonohue** [comment]
Closing, as this was noted as a temporary issue above.  We can reopen if it ever appears again
