### ISSUE TITLE
[DS-4439] Orcidv2AuthorityValue loses ORCID info stored in solr record

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7776]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4439">[DS-4439]</a> created by yanadepauw</i>
<p>The Orcidv2AuthorityValue does not retrieve the ORCID information from Solr when the record is reused.</p>

<p>This is caused by the Orcidv2AuthorityValue reusing the PersonAuthority method to</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
setValues(SolrDocument document) </pre>
</div></div>
<p> which does not set any of the ORCID related data.</p>

<p><a href="https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/authority/PersonAuthorityValue.java#L142" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-5_x/dspace-api/src/main/java/org/dspace/authority/PersonAuthorityValue.java#L142</a></p>

<p> </p>

<p>As a consequence, when the record is stored again in Solr after use, the info will be lost.</p>

<p>Because of this issue, no ORCID related info is shown in the lookup window during submission when the value has been previously used in the repository.</p>

**Comment by tdonohue** [comment]
Closing, this was fixed in 6.x via #2710.  It doesn't apply to 7.x as we're now on ORCID v3
