### ISSUE TITLE
[DS-4442] Underlying S3Object is not closed by BitStore

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7779]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4442">[DS-4442]</a> created by kingkrimmson</i>
<p>This bug is partly related to <a href="https://jira.lyrasis.org/browse/DS-3870" class="external-link" rel="nofollow">DS-3870</a> which partially solved this issue. However, because the underlying <tt>S3Object</tt> is never closed after an S3 bitstream is retrieved, an AWS connection pool overflow eventually occurs. This makes bitstream retrieval either extremely slow or completely unfunctional.</p>

**Comment by tdonohue** [comment]
This appears to be a duplicate of #8078 (which was just closed/fixed).  So, I believe this issue is now resolved on `main` (as of 7.2)
