### ISSUE TITLE
[DS-4472] Backporting - Submission Resource Policy not correctly removed during XMLWorkflow

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7807]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4472">[DS-4472]</a> created by l_a_p</i>
<p>see linked issue <a href="https://jira.lyrasis.org/browse/DS-3522" class="external-link" rel="nofollow">https://jira.lyrasis.org/browse/DS-3522</a></p>

**Comment by tdonohue** [comment]
Closing as this ticket duplicates #6873, which was already fixed in 6.x and main.
