### ISSUE TITLE
[DS-4475] Add support for Controlled Vocabulary in the REST API v7

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7810]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4475">[DS-4475]</a> created by bollini</i>
<p>DSpace provides support for hierarchical vocabulary defined in external xml files <a href="https://wiki.lyrasis.org/display/DSDOC7x/Authority+Control+of+Metadata+Values#AuthorityControlofMetadataValues-HierarchicalTaxonomiesandControlledVocabularies" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.lyrasis.org/display/DSDOC7x/Authority+Control+of+Metadata+Values#AuthorityControlofMetadataValues-HierarchicalTaxonomiesandControlledVocabularies</a></p>

<p>and it supported by the authority control (isHierarchical() method) already exposed over the new REST API, see<br/>
<a href="https://github.com/DSpace/Rest7Contract/blob/master/authorities.md" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/Rest7Contract/blob/master/authorities.md</a></p>

<p>Nevertheless, to build an efficient UX we need to add some extra feature as</p>
<ul class="alternate" type="square">
	<li>the capability to configure which level are shown open by default</li>
	<li>the capability to get the top element in a vocabulary to start to build the tree</li>
	<li>a search capability by parent to allow an easy drilldown</li>
</ul>

<p>These features have been already implemented in DSpace-CRIS 7 but need to be cleaned, formalized (rest contract) and enriched with proper test to be included in DSpace 7</p>

<p>See commits<br/>
REST:<br/>
<a href="https://github.com/4Science/DSpace/commit/129909f4435d3f9b936e8920f115b4163961a325" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/129909f4435d3f9b936e8920f115b4163961a325</a><br/>
<a href="https://github.com/4Science/DSpace/commit/ccda1ef80ee390e0f59520ba4528ed4c2c646641" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/ccda1ef80ee390e0f59520ba4528ed4c2c646641</a><br/>
<a href="https://github.com/4Science/DSpace/commit/672f486380708dd2e3ac4bd21390b290d352ad2f" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/672f486380708dd2e3ac4bd21390b290d352ad2f</a><br/>
<a href="https://github.com/4Science/DSpace/commit/60aae2d59111512f90e7fd35861a6955cdb1d436" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/60aae2d59111512f90e7fd35861a6955cdb1d436</a><br/>
<a href="https://github.com/4Science/DSpace/commit/23df3c708e975f1ca5ec761df3e8535d7911da56" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/23df3c708e975f1ca5ec761df3e8535d7911da56</a><br/>
<a href="https://github.com/4Science/DSpace/commit/0859dc0ceb186132364ba75ad1bb93bc2d8971fe" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/0859dc0ceb186132364ba75ad1bb93bc2d8971fe</a><br/>
<a href="https://github.com/4Science/DSpace/commit/dfb5fdf50aeb389053df71b8cfda880d59da3906" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/dfb5fdf50aeb389053df71b8cfda880d59da3906</a><br/>
<a href="https://github.com/4Science/DSpace/commit/cc8139a78e00cedaecfb47c05ea41efa939120ba" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/cc8139a78e00cedaecfb47c05ea41efa939120ba</a><br/>
<a href="https://github.com/4Science/DSpace/commit/96ea1644c55c1429e8c8b4f1972d546a625ddc59" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/96ea1644c55c1429e8c8b4f1972d546a625ddc59</a><br/>
<a href="https://github.com/4Science/DSpace/commit/1fdf95c3d6b17952ba8761b673021c4e21381eb9" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/1fdf95c3d6b17952ba8761b673021c4e21381eb9</a><br/>
<a href="https://github.com/4Science/DSpace/commit/15f5c64b54bd06d03bef4effb4f354f906c6e366" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/15f5c64b54bd06d03bef4effb4f354f906c6e366</a><br/>
<a href="https://github.com/4Science/DSpace/commit/d6ade530b412a8c75fdb483ee5b753780c4bb2ae" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/DSpace/commit/d6ade530b412a8c75fdb483ee5b753780c4bb2ae</a></p>

<p>Angular<br/>
<a href="https://github.com/4Science/dspace-angular/commit/62e31e8755dfd12d8ab04233ec7ac500d4091f9f" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/dspace-angular/commit/62e31e8755dfd12d8ab04233ec7ac500d4091f9f</a><br/>
<a href="https://github.com/4Science/dspace-angular/commit/719b043c59b992a51ce85918ec1ba653cd688689" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/4Science/dspace-angular/commit/719b043c59b992a51ce85918ec1ba653cd688689</a></p>

**Comment by tdonohue** [comment]
Closing, this was fixed/implemented in https://github.com/DSpace/RestContract/pull/128 and https://github.com/DSpace/DSpace/pull/2792   Already exists in 7.0
