### ISSUE TITLE
[DS-4477] Implement Resource Policy patch operations for policyType and action properties

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7812]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4477">[DS-4477]</a> created by giuseppe.digilio</i>
<p>Replace operation for properties policyType and action are not supported by resourcepolicies endpoint. Implement them</p>

**Comment by abollini** [comment]
@tdonohue a PR is coming, we spent 6 hours on that
