### ISSUE TITLE
[DS-4488] Usage stats not logged if GeoLiteCity db is not in place

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7822]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4488">[DS-4488]</a> created by cwilper</i>
<p>The comment regarding the GeoLite2-City.mmdb file in usage-statistics.cfg, "This MUST BE CONFIGURED if you want statistics with location data", suggests that statistics <b>will</b> be logged in solr if the file is absent – they will just not contain location data.</p>

<p>However, if the file is absent, view statistics will not be logged at all.</p>

<p>This is due to postView immediately returning in case locationService is null, here:</p>

<p><a href="https://github.com/DSpace/DSpace/blob/dspace-7.0-beta2.1/dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java#L232" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/DSpace/DSpace/blob/dspace-7.0-beta2.1/dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java#L232</a></p>

<p>It should instead just avoid logging the location portion of the event.</p>

**Comment by nwoodward** [comment]
This issue has caused us problems in DSpace 6 if we don't notice that the dbfile is still commented out in usage-statistics.cfg and then we hear months later from repository manages asking why they don't have any views stats.
