### ISSUE TITLE
[DS-4498] DSpace 7 submission dropdown missing

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7832]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4498">[DS-4498]</a> created by benbosman</i>
<p>The DSpace 7 submission currently doesn't support a normal dropdown yet. This is a problem in both REST and Angular UI<br/>
The only way the DSpace 7 submission supports a dropdown, is via authority control. DSpace 6 supported both solutions, where the non-authority dropdown was the standard.</p>

<p>This implies e.g. dc.language.iso contains an authority ID (visible at manual submissions, e.g. <a href="https://dspace7.4science.cloud/server/#/server/api/core/items/05ff9d54-df92-43e8-899e-9a2f55438725" class="external-link" target="_blank" rel="nofollow noopener">https://dspace7.4science.cloud/server/#/server/api/core/items/05ff9d54-df92-43e8-899e-9a2f55438725</a>, not submitted by me) if it is configured as a dropdown in DSpace 7.<br/>
This has a direct impact on the data being stored and DSpace currently treats authority values different from non-authority values on many parts (think about search, browse, CSV export, ...).</p>

<p>There are also quite a few bugs in the authority implementation of the dropdown, but these can be part of another JIRA ticket</p>

**Comment by tdonohue** [comment]
Closing as this appears (to me) to be outdated. If it's still accurate we should update the description in a new `dspace-angular` ticket
