### ISSUE TITLE
[DS-4518] Google Scholar Tags: deprecate citation_date in favor of citation_publication_date

### ISSUE THREAD

**Issue by dspace-bot** [DSpace/DSpace#7851]
<i>Imported from JIRA <a href="https://jira.lyrasis.org/browse/DS-4518">[DS-4518]</a> created by bram</i>
<p>This originally came up in <a href="https://jira.lyrasis.org/browse/DS-4104" class="external-link" rel="nofollow">https://jira.lyrasis.org/browse/DS-4104</a>, which had a different scope.</p>

<p>citation_date is an old/deprecated tag, and should be replaced by citation_publication_date</p>

**Comment by tdonohue** [comment]
Closing, as this was fixed in 7.0
