### ISSUE TITLE
Remove -o ("optimize") option from 'dspace oai'

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#7936]
**Describe the bug**
The Solr maintainers now recommend against "optimizing" cores.  We should remove this option from `dspace oai`.  I missed this one when removing other instances of core optimization.

**Expected behavior**
Do not offer deprecated operations on Solr cores.

**Comment by tdonohue** [comment]
Agreed, this needs removal.  I'm pulling this into our board, but it's `low priority` for now.  That said, if anyone has time to do this sooner, I'd welcome a PR earlier.

**Comment by misilot** [comment]
I followed from #7671, is the recommendation for 6.x to not run `./bin/dspace oai -o` as well?

**Comment by mwoodiupui** [comment]
On Wed, May 04, 2022 at 05:17:17PM -0700, Tom Misilo wrote:
> I followed from #7671, is the recommendation for 6.x to not run `./bin/dspace oai -o` as well?

Again, I would say just let Solr manage its storage.  Situations in
which you can do significantly better than that by manual intervention
should be very rare, and I don't think DSpace is likely to evolve one.

About the only case where I would consider a manual "optimize" is a
core that will never receive new records.  Even then it may not be
worth the effort.

I don't know the history here, but I suspect that all of these '-o'
flags are leftovers from a much, much earlier version of Lucene.

-- 
Mark H. Wood
Lead Technology Analyst

University Library
Indiana University - Purdue University Indianapolis
755 W. Michigan Street
Indianapolis, IN 46202
317-274-0749
www.ulib.iupui.edu
