### ISSUE TITLE
oracle migration errors

### ISSUE THREAD

**Issue by jvribell** [DSpace/DSpace#7958]
### **Environment:**
	DSpace5.8
	Centos 7
	Apache Tomcat/8.0.36
	Oracle Database 11g Enterprise Edition Release 11.2.0.4.0

I tried to migrate our DSpace to version 7 from version 5 But it ended with a fatal error ,so I tried to run the scripts that fail by hand until the migration was finished

This is the list of scripts that fail me with the adopted solution:

**File:** 		
V6.0_2016.04.04__DS-3086-OAI-Performance-fix.sql
**Sentence:**
CREATE UNIQUE INDEX metadataschema_idx_short_id on metadataschemaregistry(short_id)
**Error Message :**
ORA-01408: such column list already indexed
**My temporal fix :** 
The index already exits in the database. Remove sentence

**File:**
V7.0_2018.04.16__dspace-entities.sql 
**Sentence:**

	CREATE TABLE relationship
	(
		id                      INTEGER NOT NULL PRIMARY KEY,
		left_id                 uuid NOT NULL REFERENCES item(uuid),
		type_id                 INTEGER NOT NULL REFERENCES relationship_type(id),
		right_id                uuid NOT NULL REFERENCES item(uuid),
		left_place              INTEGER,
		right_place             INTEGER,
		CONSTRAINT u_constraint UNIQUE (left_id, type_id, right_id)
	);

**Error Message:** 
ORA-00902: invalid datatype
**My temporal fix:** 
no type uuid. Change uuid for raw(16)

	CREATE TABLE relationship
	(
		id                      INTEGER NOT NULL PRIMARY KEY,
		left_id                 raw(16) NOT NULL REFERENCES item(uuid),
		type_id                 INTEGER NOT NULL REFERENCES relationship_type(id),
		right_id                raw(16) NOT NULL REFERENCES item(uuid),
		left_place              INTEGER,
		right_place             INTEGER,
		CONSTRAINT u_constraint UNIQUE (left_id, type_id, right_id)
	);

**Sentence:**
	
	CREATE INDEX relationship_type_by_left_type_idx ON relationship_type(left_type);
	CREATE INDEX relationship_type_by_right_type_idx ON relationship_type(right_type);
	CREATE INDEX relationship_type_by_left_label_idx ON relationship_type(left_label);
	CREATE INDEX relationship_type_by_right_label_idx ON relationship_type(right_label);

**Error Message:**
ORA-00972: identifier is too long
**My temporal fix:**
shorten identifiers below 30 characters

**File:**
V7.0_2019.07.31__Retrieval_of_name_variant.sql 
**Error Message:**
ORA-00906: missing left parenthesis
**Sentence:**
  
     ALTER TABLE relationship ADD leftward_value VARCHAR(50);
     ALTER TABLE relationship ADD rightward_value VARCHAR(50);

**My temporal fix**:
Specify length. Use VARCHAR2 instead of VARCHAR		

    ALTER TABLE relationship ADD leftward_value VARCHAR2(50);
    ALTER TABLE relationship ADD rightward_value VARCHAR2(50);

**File:**
V7.0_2019.11.13__relationship_type_copy_left_right.sql			

**Sentence:**  

		ALTER TABLE relationship_type ADD copy_to_left BOOLEAN DEFAULT FALSE NOT NULL

**Error Message:**
ORA-00984: column not allowed here

**My temporal fix:** 
No BOOLEAN type in ORACLE. I don't have a clear solution. I have changed BOOLEAN to NUMBER, but this change leads to changes in the DSPACE source code.

**Comment by tdonohue** [comment]
@jvribell : Thanks for the ticket here describing some possible fixes.  Would you be interested/able to possibly create a Pull Request for us with the fixes you are recommending?  If not, I'll see if I can find someone to create it on your behalf.

**Comment by jvribell** [comment]
I will try to create a pull request for the easy ones.

The first bug is already being discussed in #7873

Regarding the last one I propose to change the type of the copy_to_left column to NUMBER(1) like other existing boolean columns (in_archive column in the ITEM table for example). I think hibernate is able to do the appropriate conversions, but a DSpace source code review would be necessary.
