### ISSUE TITLE
DSpace 7: After changing file accessibility options in access-conditions.xml, "grant access from" and "grant access until" fields are displayed incorrectly

### ISSUE THREAD

**Issue by f-rapp** [DSpace/DSpace#7977]
**DSpace 7: File accessibility dropdown entries during submission and corresponding "grant access from" and "grant access until" fields do not make sense**
While the offered accessibility options (open access, lease, embargo, administrator) and corresponding "grant access from" and "grant access until" fields make sense when using the default setting in access-conditions.xml, they change when only "open access" and "embargo" are offered (this may not only be the case for this particular setting, but for other settings as well)

**UI with **default** configs: accessibility options and offered fields match:**
![grafik](https://user-images.githubusercontent.com/67266996/136000413-d495e73b-bb25-4074-b54d-b06a40dc25af.png)
Setting for open access:
![grafik](https://user-images.githubusercontent.com/67266996/136000482-8fd13093-6895-41df-bb37-e9ed83790426.png)
Setting for lease:
![grafik](https://user-images.githubusercontent.com/67266996/136000529-fa75ff8e-55db-4f41-8f08-8bcfbd722e90.png)
Setting gor embargo:
![grafik](https://user-images.githubusercontent.com/67266996/136000570-e15eb081-13b1-4118-81df-f732e3bbec01.png)
Setting for administrator:
![grafik](https://user-images.githubusercontent.com/67266996/136000602-5d300fdc-5419-4989-94c9-db7405448ffe.png)

**UI after configs were changed: accessibility options and offered fields don't match**
Changed accessibility settings to offer "open accesss" or "embargo" in dropdown:
![grafik](https://user-images.githubusercontent.com/67266996/135999834-2c3a8050-89a6-4361-9901-1e220da61e02.png)
See results where offered fields don't make sense:
Setting for open access:
![grafik](https://user-images.githubusercontent.com/67266996/135999722-eaed8fdb-b9ae-4a00-90b4-0be39e8ce87c.png)
Setting for embargo:
![grafik](https://user-images.githubusercontent.com/67266996/135999781-800d4b14-91c2-4234-a22d-4f37e7721acb.png)

**To Reproduce**
1. Change file dspace/config/spring/api/access-conditions.xml
` <bean id="uploadConfigurationDefault" class="org.dspace.submit.model.UploadConfiguration">
    <property name="name" value="upload"></property>
    <property name="configurationService" ref="org.dspace.services.ConfigurationService"/>
    <property name="metadata" value="bitstream-metadata" />
    <property name="options">
        
        <list>
            <ref bean="openAccess"/>
           
            <ref bean="embargoed" />
           
        </list>
    </property>
</bean>`
2. Start a submission, upload a file, edit the file, check the accessibility options and whether "grant access from" and "grant access until" are offered.

**Expected behavior**
After changing the accessibility options in access-conditions.xml, the chosen accessibility option (e.g. embargo) and the corresponding fields "grant access from" and "grant access until" should still match.

**Comment by abollini** [comment]
@tdonohue estimation 4 hours. Please assign to us

**Comment by tdonohue** [comment]
Assigned to @abollini for work in 7.2.  Please also review https://github.com/DSpace/dspace-angular/issues/1359, as it is possible that these two issues are directly related & might be fixed together.

**Comment by davidenegretti-4science** [comment]
Solved together with:
- #1337 
- #1359 
- #1399 
- #1415 
- DSpace/Dspace#7977
