### ISSUE TITLE
SAF (Simple Archive Format) scripts/tools are missing Integration Tests

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#7980]
**Describe the bug**
While other import mechanisms (e.g. AIP, CSV) have Integration Tests to prove their behavior, these tests were never created for the Simple Archive Format (used for the basic "./dspace import" and "./dspace export" scripts).  These tools were some of the earliest created, well before we started building ITs.

**Expected behavior**
ITs should exist which can import, export and/or round-trip content into DSpace using the Simple Archive Format (SAF).  These tests should validate all params in our documentation: https://wiki.lyrasis.org/display/DSDOC7x/Importing+and+Exporting+Items+via+Simple+Archive+Format

**Related work**
This work might be based on other import ITs, for example
* AIP integration tests: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/test/java/org/dspace/content/packager/ITDSpaceAIP.java
* CSV integration tests: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/csv/CsvImportIT.java and https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/test/java/org/dspace/app/rest/csv/CsvExportIT.java

**Comment by francescopioscognamiglio** [comment]
hi @tdonohue, we are working on that together with https://github.com/DSpace/DSpace/issues/2850
