### ISSUE TITLE
RelationshipType embedding from relationships

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#7984]
**Describe the bug**
This issue regards "to reproduce" steps  2 and 3 of #7960  (embedding in relationships resource response)

While working at above issue, we found out that the embedding of relationshipType in relationships resource would require more work than expected and a Rest contract review.
This because current Relationship rest response reports link to relationshipType resource itself instead of one following relation i.e. https://api7.dspace.org/server/api/core/relationships/561  response contains

```"_links": {
    "relationshipType": {
      "href": "https://api7.dspace.org/server/api/core/relationshiptypes/3"
    },
```

instead of 

```"_links": {
    "relationshipType": {
      "href": "https://api7.dspace.org/server/api/core/relationships/561/relationshipType"
    },
```
This response is documented into relationships rest contract. 
We propose a change in rest contract so that relationships REST response contains relationshipType response as per above example, and to implement a LinkRestRepository properly embedding relationshipType in relationships response where required. 

An additional angular check is needed, to be sure of having the links followed as per architecture design and not hardcoded when for any reason angular needs to retrieve a relationshipType object starting from the relationship

4Science can take in charge this activity, our estimation for rest contract update, LinkRestRepository with a proper test coverage is 6 hours of work

**Comment by tdonohue** [comment]
Thanks @corrad82-4s .  Apologies for the late response, but this all seems reasonable to me.  Will add your estimate. Let me know if you'd like to claim this to fix it.
