### ISSUE TITLE
Use a connection pool for communication with Solr

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#7986]
**Is your feature request related to a problem? Please describe.**
When we are busy, I have noticed a great many connections between DSpace and Solr, the vast majority of which are in CLOSE_WAIT or some other connection-teardown state.  Making and breaking connections has a CPU cost, and large numbers of concurrent connections have a memory cost.

**Describe the solution you'd like**
We could use Solr more efficiently by keeping a pool of open connections.  SolrJ uses an Apache HttpComponents HTTP client instance for connecting to the service, and we can allocate from the pool and pass a pooled connection to the client builder.

**Comment by tdonohue** [comment]
Pulling this onto the 7.2 board since you already started work on this. Thanks @mwoodiupui !
