### ISSUE TITLE
Metadata value place is not updated when migrating from DSpace 5.10

### ISSUE THREAD

**Issue by ybnd** [DSpace/DSpace#7997]
#### Describe the bug

After migrating a database from DSpace 5.10 to 6.x or 7.x, the `metadatavalue.place` of existing MDVs still starts from 1 instead of 0.

This can cause unexpected behaviour e.g. when editing metadata in the frontend:

* Editing the MDV `N` edits MDV `N+1` instead and "fixes" some MDV's `place` as they get overwritten
* Editing the _last_ MDV fails ~ `422: Unprocessable or invalid entity` 

#### To Reproduce

1. Deploy a clean DSpace ~ [dspace-5.10](https://github.com/DSpace/DSpace/tree/dspace-5.10)

2. Add a few Items with multiple values for some MDFs

3. Dump the resulting database

4. Deploy a clean DSpace ~ `main` with the same database and run ignored migrations

   ```
   ./dspace database migrate ignored
   ```

6. Compare the migrated database to the original 5.10 database
   * `metadatavalue.place` will still start from 1 instead of 0

#### Expected behavior

The `place` of existing MDVs should be updated when migrating to DSpace 6+

#### Proposed solution

Add a new migration:

```sql
UPDATE metadatavalue AS mdv
SET place = mdv.place - minplace
FROM (
  SELECT dspace_object_id, metadata_field_id, MIN(place) AS minplace
  FROM metadatavalue
  GROUP BY dspace_object_id, metadata_field_id
) AS mp
WHERE mdv.dspace_object_id = mp.dspace_object_id
  AND mdv.metadata_field_id = mp.metadata_field_id
  AND minplace > 0;
```

* We've tested this with

  * a "test database" with a few MDVs
  * some production databases which has the same issue.

* Also covers cases where `place` starts at values >1; we've encountered a few of these during testing

* Things to note:

  * Time will be a concern for large databases:
     * ~700k MDVs → ~20 seconds
     * ~15M MDVs → ~20 minutes

  * Because we're performing a lot of `UPDATE`s, the database can swell quite a bit during/after the migration because _Postgres keeps both values_.

    We can address this by [adding a `VACUUM`](https://www.postgresql.org/docs/9.0/routine-vacuuming.html).

**Comment by tdonohue** [comment]
@ybnd : Could you create a PR with the changes you've suggested.  They sound "reasonable", but we need to also be sure they don't impact upgrades from 6.x -> 7.x, or other upgrade scenarios.  I'd also like to better understand why this _only impacts_ upgrades from 5.x -> 7.x....and that might be easier to test out once a PR is created.
