### ISSUE TITLE
The discover factes endpoint returns 500 if an invalid query is provided

### ISSUE THREAD

**Issue by LucaGiamminonni** [DSpace/DSpace#8004]
**Describe the bug**
The server/api/discover/facets endpoint cause an internal server error if the provided query is not a valid solr query.

**To Reproduce**
1. Call the endpoint server/api/discover/facets/* with an invalid query (as https://api7.dspace.org/server/api/discover/facets/author?page=0&size=5&sort=score,DESC&page=0&size=10&query=test%3A)

**Expected behavior**
An error with status 400 or 422 should be returned.

**Related work**
Related to https://github.com/DSpace/dspace-angular/issues/1365

**Comment by tdonohue** [comment]
Moving this over with the related ticket to 7.2 board.
