### ISSUE TITLE
destroy() method in PackagerIT preventing *Builders cleanup

### ISSUE THREAD

**Issue by mspalti** [DSpace/DSpace#8016]
**Describe the bug**
The `destroy()` method in `PackagerIT` is used to remove a temp file and is overriding the parent method in _AbstractIntegrationTestWithDatabase._ As a result, *Builder objects are not cleaned up and this can affect other ITs. In my environment, this consistently causes `DiscoveryIT` to fail. Renaming the method  method in PackagerIT fixes the problem.

**To Reproduce**
It might be difficult to reproduce since others haven't seen the problem and CI tests succeed. Perhaps because of the order of test execution, I'm not sure. I see the error consistently when running `mvn clean install -DskipIntegrationTests=false -Dit.test=PackagerIT,DiscoveryIT -DfailIfNoTests=false`

**Expected behavior**
All ITs pass.

.

**Comment by tdonohue** [comment]
@mspalti : I was able to reproduce this using your instructions in the description. It seems it only occurs if `PackagerIT` happens to run before `DiscoveryIT`.... and on some systems it seems that ordering rarely occurs (like in our CI environment).

Nonetheless, I've found a fix in #8026 .  Could you give it a try to ensure it fixes it for you as well?
