### ISSUE TITLE
Rely on https handle.net urls instead of http ones

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8018]
**Describe the bug**

In all DSpace versions, we use and advertise http handle.net links. However, handle.net fully supports https urls and may even implement future auto-redirects from http to https.

HTTPS link usage is already a ranking signal for many years. 
https://developers.google.com/search/blog/2014/08/https-as-ranking-signal

**To Reproduce**
1. Visit any DSpace item page
2. Look for the hdl.handle.net link
3. Check if it's http or https

**Expected behavior**
It should be https, but http is currently observed everywhere

**Related work**
Place in the code to update, not sure if it's the only place:

https://github.com/DSpace/DSpace/blob/34c1e82275dbbc42010b79cd5872a86d861d9827/dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java#L131

**Comment by bram-atmire** [comment]
As a consequence of this dialog, handle.net updated their own documentation page to https urls where they previously only mentioned http at https://www.handle.net/hnr_documentation.html

**Comment by tdonohue** [comment]
I believe this is a one-line fix (see reference to line in `HandleServerImpl` above).  Though we also may want to remove the http version of the configuration `handle.canonical.prefix = http://hdl.handle.net/` from `local.cfg.EXAMPLE` and `dspace.cfg`.

PRs welcome, but I'll pull it over onto the 7.2 board to look for a volunteer.
