### ISSUE TITLE
DSpace 7.1 Zip Missing \dspace directory

### ISSUE THREAD

**Issue by HunterBlacker** [DSpace/DSpace#8019]
After downloading the .zip file with DSpace 7.1, I found that it is missing the entire \dspace directory. I was able to extract from the tar.gz file instead

**Comment by tdonohue** [comment]
@HunterBlacker : I'm not able to reproduce this.  The Zip File available for download at https://github.com/DSpace/DSpace/releases/tag/dspace-7.1 seems to have all the necessary contents.  Maybe it was a temporary download error?

**Comment by HunterBlacker** [comment]
Hi, @tdonohue . Thank-you for checking. I've tried downloading it twice. While it appears to finish downloading, I do receive an error in Windows Explorer that "Windows cannot open the folder". I am able to open it in 7-Zip though which is where I see all of the other files. It appears to be an incomplete download issue on our side with the .zip, but the .tar.gz file is complete and I'm able to use that instead.
