### ISSUE TITLE
"UUID string too large" error after rebuilding of the index

### ISSUE THREAD

**Issue by mgrothe-gu** [DSpace/DSpace#8039]
**Describe the bug**
I did a full reindex with "./bin/dspace index-discovery -b". The command showed no errors. Afterwards solr functionality is not working on the site anymore and the log shows the the following error message:

org.dspace.discovery.SearchServiceException: UUID string too large

**To Reproduce**
I'm not sure how to reproduce the error. I have rebuilt the index successfully before.

**Comment by tdonohue** [comment]
@mgrothe-gu : We'd need more information here on how to reproduce this issue.  What version of DSpace is this? Have you been able to reproduce this again?  I've not yet encountered this error, so we'd need to better understand how to reproduce it before we can look into a fix.  It's also possible this was a Solr configuration issue or somehow bad/corrupt data, in which case there may not be a way to fix it.

**Comment by mgrothe-gu** [comment]
I'm on DSpace 7.1. I have not been able to reproduce the error. I tried replacing the solr cores with the default empty ones, but that didn't help. Since it's only a test system yet, I have now resorted to drop the database and do a database migrate.

**Comment by tdonohue** [comment]
In that case, I'm going to close this issue as it's unreproducible.  However, if we ever find a way to reproduce it, we can reopen this in the future.
