### ISSUE TITLE
If a workflow user rejects an item that they submitted, the item becomes uneditable

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#8042]
**Describe the bug**

If a certain users (who is also a reviewer) submits an item and they then reject their own item in the workflow, the item cannot be edited any longer in the workspace.

This is because all WRITE rights have been removed from that item.

**To Reproduce**
1. Create (a non admin) user whom is both submitter in a certain collection and a reviewer
2. Submit an item in that collection
3. Reject that item yourself
4. Go back to your workspace & attempt to modify some metadata & save
5. This won't work & you will get a message stating: "There was an issue when saving the item, please try again later."

**Expected behavior**
There is prob something wrong either with the granting or removing permissions. The permissions should be granted / removed with the proper "type" ( ResourcePolicy.TYPE_SUBMISSION/ ResourcePolicy.TYPE_WORKFLOW). There is prob something wrong with a check somewhere.

**Comment by tdonohue** [comment]
Thanks @KevinVdV for creating a ticket...pulling this over onto the 7.2 board & flagging as `high priority` as this sounds like something we'd want to figure out quickly.  Let me know if your team is interested, and if so, I'll assign to you to estimate & work on.
