### ISSUE TITLE
error when installing Dspace Backend

### ISSUE THREAD

**Issue by ahmed264** [DSpace/DSpace#8056]
error when installing Dspace Backend
Dear Dpsace Users and Developer 
plz I need help to solve this problem 
attached is show it
Dec 07 07:45:43 Dspace7 tomcat9[33889]:     at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
Dec 07 07:45:43 Dspace7 tomcat9[33889]:     at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:724)
Dec 07 07:45:43 Dspace7 tomcat9[33889]:     at org.springframework.orm.hibernate5.LocalSessionFactoryBean.buildSessionFactory(L>
Dec 07 07:45:43 Dspace7 tomcat9[33889]:     at org.springframework.orm.hibernate5.LocalSessionFactoryBean.afterPropertiesSet(Lo>
Dec 07 07:45:43 Dspace7 tomcat9[33889]:     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.inv>
Dec 07 07:45:43 Dspace7 tomcat9[33889]:     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.ini>
Dec 07 07:45:43 Dspace7 tomcat9[33889]:     ... 178 more
Dec 07 07:45:43 Dspace7 tomcat9[33889]: Deployment of web application directory [/var/lib/tomcat9/webapps/server] has finished >
Dec 07 07:45:43 Dspace7 tomcat9[33889]: Starting ProtocolHandler ["http-nio-8080"]
Dec 07 07:45:43 Dspace7 tomcat9[33889]: Server startup in [27,051] milliseconds
![error](https://user-images.githubusercontent.com/44668204/144989872-eb75cf01-0a86-4cd5-a941-3842bd797d12.png)

**Comment by tdonohue** [comment]
Not enough information is given about your DSpace setup or environment, or the error messages encountered.  Closing this ticket as it's more than likely a configuration issue.

@ahmed264 : Please see our Troubleshooting guide for DSpace 7, for hints on finding the entire error message in your logs.  The error you copied above is only a partial error message, and doesn't include the entire error stacktrace (so it's not helpful as is). https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

If you need more support, please see our Support guide for where to go for support: https://wiki.lyrasis.org/display/DSPACE/Support
