### ISSUE TITLE
Make filter-media available from the REST APi

### ISSUE THREAD

**Issue by artlowel** [DSpace/DSpace#8062]
**Is your feature request related to a problem? Please describe.**
Filter-media can currently only be triggered from the CLI. It would be good to convert it to a Scripts & Process script, so it can be triggered by admins from the UI as well

This can be done in an estimated **6** hours

**Comment by tdonohue** [comment]
@artlowel : This makes sense to me to add, and the intention is definitely to move as many CLI scripts to REST API / Scripts & Processes as we can.  Is this something you are suggesting be completed for 7.2, or should we move to 7.3?

**Comment by artlowel** [comment]
We could still fit it in for 7.2 if needed

**Comment by tdonohue** [comment]
@artlowel : I'll assign to you then and move to the 7.2 board. Thanks!
