### ISSUE TITLE
S3 connection leak

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#8078]
**Describe the bug**

DSpace can use S3 as a backend to store & retrieve files, but there is a leak somewhere in the BitstreamResource that doesn't always close connections. 
Every download opens up a connection to S3 & these aren't closed so after a certain amount of downloads the download AND upload just quit working because the S3 connections are up.

**To Reproduce**
1. Enable S3 on DSpace 7
2. Download different files & after a while the downloads won't work any more (they just time out)

**Expected behavior**
Connections to S3 should be properly closed.

**Comment by KevinVdV** [comment]
We had the specific issue with loading of thumbnails. As these are sometimes cached by spring.

The problem is that on the [following line](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java#L158) we are creating a spring resource with an inputstream. We noticed that SOMETIMES (not always) that inputstream isn't closed.

After spending some time on this already I think the following issue is the problem: https://github.com/spring-projects/spring-framework/issues/22626

In that thread the developers are stating that you can't trust a Resource to properly close the inputstream (we noticed this as well, that spring at times tends to CACHE file downloads). So IF you have a cached download that connection won't be closed until the tomcat shuts down.

We need to alter the code in our BitstreamResource to only open up an inputstream when we need it.

In terms of work I think we need around 12 hours (as we need to determine the approach to fix this)

**Comment by hardyoyo** [comment]
Hi, @KevinVdV today I was sorting out some errors with our pilot instance of dspace, and noticed that when the S3 assetstore was configured to be used, Tomcat would not longer boot up. In a fit of googling the error message, I found some posts that seemed to indicate that a newer version of the aws-java-sdk-s3 library might help things out. I bumped the version number from 1.10.50 to the current 1.12.129, and Tomcat came back up, and we confirmed we could upload bitstreams to our S3 assetstore.

I'll be making an issue and PR for that change, I just wanted to offer the suggestion that using a newer version of aws-java-sdk-s3 *might* also help with this issue?

**Comment by KevinVdV** [comment]
Created a PR to potentially fix this: https://github.com/DSpace/DSpace/pull/8113

**Comment by mwoodiupui** [comment]
Might this be related to #7779?

**Comment by KevinVdV** [comment]
@mwoodiupui Yes you are correct, this is the same issue.
