### ISSUE TITLE
_links.self.href is without TLS, while other urls detect TLS correctly

### ISSUE THREAD

**Issue by agp8x** [DSpace/DSpace#8081]
**Describe the bug**
I run a docker setup with dspace/dspace:dspace-7_x (dspace/dspace@sha256:9da23d5a3ef2e2ae49a6800a3f25faf36e248e6be41a01aa8046f3b2b9fbd7a8). It is behind a TLS-terminating reverse proxy (traefik), so I use `https://dspace.me/server/api/`, which reaches the dspace container via plain text HTTP.
All links to `_links.self.href` use http, which is a) bad because clear text, b) bad because the reverse proxy only handles TLS, so any further connections from the angular frontend fail.

![Bildschirmfoto_2021-12-20_12-19-51](https://user-images.githubusercontent.com/1840171/146759925-df4783ba-b1bb-4d62-945d-1e8cb7530f5a.png)

My local.cfg is:
```
dspace.server.url=https://dspace.me/server
dspace.ui.url=https://dspace.me
dspace.name=DSpace Started with Docker Compose
```
(+ some email stuff)

**Expected behavior**
The self-href should use https if applicable

**Comment by tdonohue** [comment]
@agp8x : Apologies for the delayed response, but this sounds like you are hitting this Proxy-specific issue: https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-MyRESTAPIisrunningunderHTTPS,butsomeofits%22link%22URLsareswitchingtoHTTP?

 If that doesn't solve your problems, you also may wish to investigate whether changing Spring Boot's default "forward-headers-strategy" for your specific proxy. This may be overridden in your local.cfg as necessary: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/resources/application.properties#L80-L90

Closing, as this sounds like a configuration issue. See that guide for details on correctly configuring your Proxy.
