### ISSUE TITLE
Port OpenID Connect plugin from DSpace-CRIS 7 to DSpace

### ISSUE THREAD

**Issue by hardyoyo** [DSpace/DSpace#8087]
**Is your feature request related to a problem? Please describe.**
Integrating other systems with DSpace is a challenge that is made easier by having a shared user database. [Open ID Connect](https://openid.net/connect/) provides such infrastructure. [Keycloak](https://www.keycloak.org/) is an opensource way of providing such a service, and [AWS Cognito](https://aws.amazon.com/cognito/) is a hosted option to do the same.

**Describe the solution you'd like**
DSpace-CRIS 7 has an OpenID Connect auth plugin, it should be fairly straightforward to port this code to DSpace 7.

**Describe alternatives or workarounds you've considered**
rewriting this code from the ground up

**Additional context**
The [NGLP project](https://educopia.org/next-generation-library-publishing/) has identified OIDC authentication support as a core need for building/delivering systems that integrate with DSpace.

PR no. 1: https://github.com/DSpace/DSpace/pull/8088
PR no. 2: https://github.com/DSpace/dspace-angular/pull/1470

**Comment by 49913352** [comment]
Guys
