### ISSUE TITLE
Converge all use of EHcache to v3

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#8099]
**Describe the bug**
As I write this, DSpace v7 depends on both EHcache v2 (for Hibernate and general caching) and v3 (in the dspace-server-webapp).  We should converge on a single version.

While we are working on caching, we should also consider moving all of our own code to use the Jcache/JSR107 API, which EHcache supports, rather than the proprietary EHcache API, and to configure Hibernate to use it as well.  Hibernate recommends its own Jcache adapter over its own native-EHcache adapter:  https://hibernate.atlassian.net/browse/HHH-12441

**To Reproduce**
Search for ehcache*.jar in the install target tree (`dspace/target/dspace-installer`).  You will find v2 in `lib/` and v3 in `webapps/server/`.

**Expected behavior**
We should find only one version of the EHcache JARs.

**Comment by mwoodiupui** [comment]
@tdonohue pointed this out and provided some research.  Thanks!

**Comment by tdonohue** [comment]
@mwoodiupui  volunteered via Slack (thanks!)  Also scheduled for 7.3 (as it's too late for 7.2 at this point).
