### ISSUE TITLE
findAll collections fails in oracle

### ISSUE THREAD

**Issue by jvribell** [DSpace/DSpace#8106]
the end point "server/api/core/collections" throw an error when the user is an administrator.

`org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ ORA-00932: inconsistent datatypes: expected - got CLOB`

The error occurs in the findAll procedure in CollectionDAOImpl and occurs because Oracle does not support ORDER BY with CLOB columns.

In non-admin users SOLR performs the search and works correctly.

The same error occurs in the DAO community

I think CLOB columns are going to be a continuous source of problems.

In Oracle 12 there is a possibility to increase the VARCHAR2 up to 32767 characters by changing a initialization parameter, 
CLOB could be changed by these extended VARCHAR2 although this solution might be too restrictive for some users
Any ideas?

**Comment by jvribell** [comment]
I've written a temporary fix to continue testing. Do you think it is an acceptable solution? Do I make a pull request?
```
String orderBy=context.getDbType().toLowerCase().contains("oracle")
        		? " ORDER BY LOWER(dbms_lob.substr(title.value,length(title.value)))"
        		: " ORDER BY LOWER(title.value)";

 queryBuilder.append("SELECT c" +
                                " FROM Community c" +
                                " left join c.metadata title on title.metadataField = :sortField and" +
                                " title.dSpaceObject = c.id and" +
                                " title.place = (select min(internal.place) " +
                                                "from c.metadata internal " +
                                                "where internal.metadataField = :sortField and" +
                                                    " internal.dSpaceObject = c.id)" +
                                orderBy);
```

**Comment by tdonohue** [comment]
@jvribell : We discourage adding a ton of "if this database, do this" throughout the codebase, as it's a pain to maintain and manage.  Instead, we do our best to rely on Hibernate to translate database syntax for different databases.

That said, based on simple searches, I'm not finding a way to do this in Hibernate HQL syntax.  So, it might be OK here if you moved this logic to it's own utility method, perhaps in `AbstractHibernateDSODAO`.  That way it's not duplicated into multiple DAO classes (as you noted this same change may be needed by communities & collections).   

There's already some other utility methods there related to adding sort/order by, for example https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/core/AbstractHibernateDSODAO.java#L128   It's possible you could even just enhance one of these existing `addMetadataSortQuery()` methods to better deal with CLOBs...not sure though which approach would be easier for this scenario.

**Comment by tdonohue** [comment]
Closing as Oracle Support was removed in https://github.com/DSpace/DSpace/pull/8822
