### ISSUE TITLE
HAL Browser Static Assets / API 404 on Fresh Install

### ISSUE THREAD

**Issue by BrandonKowalski** [DSpace/DSpace#8114]
**Describe the bug**
I installed the DSpace 7 Backend per the instructions given here:
https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-BackendInstallation

I went to test this install prior to moving on to the frontend UI following step 15 from above. 

While accessing the dspace.server.url, 'The HAL Browser' loads without static assets and API calls fail.

**To Reproduce**
1. Fresh install of DSpace 7 
2. Copy webapps directory to Tomcat webapps directory (server is the only folder moved)
3. Access link via localhost address (address matches dspace.server.url setting)
4. HAL browser loads but all static assets 404. Additionally API calls fail

**Expected behavior**
The page to load like the provided demo: https://api7.dspace.org/server/

**Comment by tdonohue** [comment]
@BrandonKowalski : Please check that the dependencies you've installed (especially Java, Maven & Tomcat) are supported versions: https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-BackendRequirements  My immediate suspicion is you may be running a newer, untested version of either Java (we only support JDK11) or Tomcat (we only support Tomcat 9) which is causing issues.

**Comment by BrandonKowalski** [comment]
You are wonderful. I had the correct version of Java and Maven but didn't pay attention to Tomcat. It was on version 10.

Thank you for your help and time!
