### ISSUE TITLE
Implement Linked Data Notification (LDN) Specification for COAR Notify

### ISSUE THREAD

**Issue by ghost** [DSpace/DSpace#8120]
Please refer to the Development Implementation proposal here https://wiki.lyrasis.org/display/DSPACE/Implementation+of+the+COAR+Notify+protocol+in+DSpace+8 for updated information about the implementation of COAR Notify in DSpace 8

Original descriptionfrom @wwelling is keep below as it is still useful and accurate to understand one of the scenarios that will be addressed by the COAR Notify implementation. Please note that since the time of @wwelling writing the use case for linking between DSpace 7 and Dataverse is becomed an [official use case of COAR Notify](https://notify.coar-repositories.org/scenarios/10/)

----
I would like to begin a design and implementation discussion on bringing [LDN ](https://www.w3.org/TR/ldn/) support into DSpace 7. This is of existing interest to the [COAR Notify](https://notify.coar-repositories.org/) project and an MVP for [Dspace 5](https://github.com/4Science/DSpace/tree/coar-notify-5) and [DSpace 6](https://github.com/4Science/DSpace/tree/coar-notify-6) have been implemented by 4Science. Thanks to @abollini for sharing. The driving effort for this next collaboration/contribution is for linking between DSpace 7 and Dataverse which is not yet a defined [use case](https://notify.coar-repositories.org/usecases/) or [scenario](https://notify.coar-repositories.org/scenarios/) of COAR Notify. The use cases for this are defined below.

It is desirable to generally implement LDN without coding to a specific use case or scenario. With the configurable affordance for COAR Notify scenarios and the use cases expressed below. The feasibility is unknown and may incur a higher level of difficulty to achieve. Would also like to have a shared nomenclature and patterns between DSpace, COAR, and other stakeholders for inclusion of LDN. Starting with what has been documented by COAR Notify would allow additional scenarios to be expressed and if necessary, extending COAR Notify patterns and vocabulary.

It could be considered to port the existing MVP solutions from 4Science to DSpace as a starting point.

**Use Case 1**
Submitting an article to DSpace, including data in the Dataverse Repository

A researcher, submitting a publication to DSpace and entering the DOI of a Dataverse dataset as metadata, would like for the publication and dataset to be cross-linked, i.e. for the dataset to be updated with metadata pointing to the publication in DSpace, and conversely, for the DSpace record to be updated with a link to the Dataverse dataset.

A researcher is submitting a work for deposit to DSpace using the Quick Submit Form. She wants the DSpace work, via its metadata record, to link to a corresponding dataset already published in Dataverse. She also wants the Dataverse dataset, via its metadata record, to link to the DSpace work. She enters the URI for the dataset into the corresponding field on the Quick Submit Form, following the instructions she reads on the form. She submits the form, and the work is submitted to DSpace (but is not yet deposited).

Upon submit, the DSpace Manager evaluates the article for deposit. For articles that the Manager deposits, a to-be-developed DSpace component creates an LDN message containing the NRS (Name Resolution Service) link and title of the DSpace work and the URI and title of the Dataverse dataset, and passes the message to the DSpace LDN Producer. The DSpace LDN Producer sends the message to the Dataverse LDN Inbox. 

The Dataverse Curation Team Administrator is notified of the message in the Dataverse LDN Inbox, reviews it, and updates the indicated Dataverse dataset’s metadata record (related publication field) with the indicated DSpace NRS. The Dataverse Manager then initiates a message acknowledging the completed crosslink, which is sent to the DSpace LDN Inbox and received by the DSpace Manager. 

Later, the researcher visits the landing page for the deposited DSpace work and sees the URI of the Dataverse dataset is listed in the metadata record. She then visits the Dataverse dataset and sees the metadata record now lists the NRS link to the DSpace work. The DSpace work and Dataverse dataset are now crosslinked.

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/8352733/153880978-42230171-b52c-42b1-a215-d4a42c4910ab.png">

**Use Case 2**
Depositing data to the Dataverse Repository, including a link to an article in DSpace

**A**. Depositor-managed collection use case

A researcher, depositing a dataset to Dataverse and entering the NRS (Name Resolution Service) link of a DSpace publication as metadata, would like for the publication and dataset to be cross-linked between DSpace and Dataverse, i.e. for the dataset to be updated with metadata pointing to the publication in DSpace, and conversely, for the DSpace record to be updated with a linked to the Dataverse dataset.

A researcher is creating a new Dataset in the Dataverse repository. After creating the draft, the researcher sees a system prompt to add a link to an article in DSpace if they have one, along with a link to learn about depositing to DSpace. The prompt is based on the researcher’s login data and/or affiliation. Researchers seeing the prompt may or may not have an article in DSpace. In the case that an article does exist, the researcher adds a DSpace NRS link, via the “Related Publication” field on the optional metadata form.

When the researcher submits updated metadata with the DSpace NRS link, the system displays a feedback message informing the researcher that the dataset will need to be published in order for the linking between DSpace and the dataset to be complete. 

When the researcher publishes the dataset, the link is complete. The Dataverse system sends information to the DSpace LDN Inbox. The DSpace Manager then initiates a message acknowledging the completed crosslink, which is sent to the Dataverse LDN Inbox and received by the Dataverse Curation Team Administrator, i.e. as a Dataverse notification. It will also email the researcher and post a notification to their Dataverse account, informing them of the change of status. 

**B**. Department managed collection use case, submit for review workflow

A researcher is depositing a dataset to CFA (Center for Astrophysics, for example) collection and entering the NRS (Name Resolution Service) link of a DSpace publication as metadata.

When the researcher submits updated metadata with the DSpace NRS link, the system informs the researcher that once the dataset is submitted for review, and published by the collection manager, the link to DSpace displayed in the dataset metadata will be complete. 

When the collection manager publishes the dataset, the link is complete. The Dataverse system sends information to the DSpace LDN Inbox. The DSpace Manager then initiates a message acknowledging the completed crosslink,... (TBD) It will also email the researcher and post a notification to their Dataverse account, informing them of the change of status.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/8352733/153881020-253b1b3b-312d-4b4f-9f39-1da010179ecb.png">

**Use Case 3**
Updating existing data in each repository: the Dataverse Repository and DSpace

A researcher has previously deposited a DSpace publication and a Dataverse dataset, but the metadata records are not crosslinked. The researcher now wants these records, which are already published, to be updated and crosslinked.

A researcher asks the DSpace Manager to include the DOI of the Dataverse dataset in her existing DSpace metadata record. The DSpace Manager adds the DOI to the corresponding field, and a to-be-developed DSpace component creates an LDN message containing the NRS (Name Resolution Service) link and title of the DSpace work and the URI and title of the Dataverse dataset, and passes the message to the DSpace LDN Producer for sending to the Dataverse LDN Inbox. Subsequent steps to complete the crosslink follow use case (1). 

The researcher updates the dataset metadata in Dataverse to include the DSpace NRS of a related publication. A to-be-developed Dataverse component creates a LDN message containing the Dataverse dataset URI, title of the dataset, and DSpace NRS, then passes the message to the Dataverse LDN Producer for sending to the DSpace LDN Inbox. Subsequent steps to complete the crosslink follow use case (2).

Use cases and sequence diagrams have been provided by Harvard Data Commons Team.

**Comment by abollini** [comment]
Please refer to the Development Implementation proposal here https://wiki.lyrasis.org/display/DSPACE/Implementation+of+the+COAR+Notify+protocol+in+DSpace+8
