### ISSUE TITLE
TotalDownload returns the file name as id instead than label

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#8121]
**Describe the bug**
If you look to the total download report of an item you will note that all the data points have a null label. The file name is used as id, this lead angular to produce a table with no label over the rows (each file will be a different row)

**To Reproduce**
1. find an item with some file
2. visit the statistics page of this item and look to the File visits table

An example is https://demo7.dspace.org/statistics/items/beab7608-ab45-43f7-b630-210f1e515e0b

**Comment by tdonohue** [comment]
This appears like it may be the same issue as https://github.com/DSpace/dspace-angular/issues/1369

**Comment by abollini** [comment]
It is not the same issue, here the issue is on the REST side it is not related to authorisation permission. Our estimation is 4 hours

**Comment by tdonohue** [comment]
@abollini : This appears to have been fixed in 7.4 (at least I'm no longer able to reproduce it with the given example).  Perhaps it was fixed by #8446?

**Comment by abollini** [comment]
yes, it is
