### ISSUE TITLE
Mails not being sent when using office365 smtp mail server

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#8123]
**Describe the bug**
When using "smtp.office365.com" as a mail server at random times an email won't be sent, it will lead to exceptions like this:

`
javax.mail.AuthenticationFailedException: 421 4.7.66 TLS 1.0 and 1.1 are not supported. Please upgrade/update your client to support TLS 1.2. Visit https://aka.ms/smtp_auth_tls. [SY6PR01CA0029.ausprd01.prod.outlook.com]
`

**To Reproduce**
1. Configure the "smtp.office365.com" as a mail server
2. Trigger several mails at random times (we had the issue with workflow tasks)
3. Some won't arrive

**Expected behavior**
All mails should go out.

**Comment by mwoodiupui** [comment]
https://stackoverflow.com/q/47166425/2916377 may be relevant.

**Comment by KevinVdV** [comment]
Potential fix: https://github.com/DSpace/DSpace/pull/8124
