### ISSUE TITLE
Community/Collection admin cannot edit "Default read access"

### ISSUE THREAD

**Issue by alejandratenorio** [DSpace/DSpace#8126]
A community or collection admin cannot edit "Default read access" group or add people. When a community/collection administrator tries to do so, he/she is redirected to an "Insufficient Privileges" page.

**To Reproduce**
1. Create a community and a Collection inside this.
2. In this community, enable the 'Administrators' role and add a user. Also restrict the "Default read access".
3. Log in with the community administrator, go to the new collection and try to add another user to the "Default Read Access" role.

![image](https://user-images.githubusercontent.com/31973211/150381181-6562c65a-3ef8-4338-88c4-086b51df922a.png)

When i try to add people to "Default read access"
![image](https://user-images.githubusercontent.com/31973211/150381233-259592b3-afdc-4e92-8504-9be7be5f014c.png)

**Comment by tdonohue** [comment]
This is not reproducible in DSpace 7.x (at least not in the lastest code). Maybe this was in an older version of DSpace?

**Comment by tdonohue** [comment]
Closing, I checked this again in 7.3 and it's not reproducible there either.  So, I'm assuming this was fixed somewhere along the way.
