### ISSUE TITLE
Exception is thrown when including " in search string

### ISSUE THREAD

**Issue by firoball** [DSpace/DSpace#8131]
**Describe the bug**
DSpace 7.1.1
When searching for any string containing a `"`, the backend throws an exception.

**To Reproduce**
Include `"` in any search string when using search function in Frontend

**Expected behavior**
Search of any string should not ever throw an exception

**Related work**
From dspace.log:
`2022-01-22 23:58:40,152 INFO  d48f6652-ed56-4e76-b85f-0d8f54988784 84906a45-300b-41ba-95b5-d094b6cdf45f org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/discover/search/objects] originated from /search?spc.page=1&query=%22
2022-01-22 23:58:40,165 ERROR d48f6652-ed56-4e76-b85f-0d8f54988784 84906a45-300b-41ba-95b5-d094b6cdf45f org.dspace.app.rest.repository.DiscoveryRestRepository @ Error while searching with Discovery
org.dspace.discovery.SearchServiceException: Error from server at http://localhost:8983/solr/search: org.apache.solr.search.SyntaxError: Cannot parse '"': Lexical error at line 1, column 2.  Encountered: <EOF> after : ""
`

**Comment by tdonohue** [comment]
Closing, as this appears to already be fixed on `main` (pre-7.2) and our demo site at demo7.dspace.org. I just verified and searches with quotes work on our demo site.  I'm not sure exactly which recent commit fixed this, but it may have been the changes related to #1365

**Comment by firoball** [comment]
Not sure if relevant, might be same issue and might also be fixed then:

```
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/search: org.apache.solr.search.SyntaxError: Cannot parse 'x'; DROP TABLE members; --': Encountered " "-" "- "" at line 1, column 25.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <LPARAMS> ...
    "filter(" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
```

Seems like also `-` can trigger a series of exceptions.

**Comment by tdonohue** [comment]
@firoball : We improved the exception handling of searches recently in https://github.com/DSpace/dspace-angular/pull/1419 and https://github.com/DSpace/DSpace/pull/8044  so that search errors are less likely to occur, and when they do occur the resulting response is much more useful.

You can try it yourself on our demo site at https://demo7.dspace.org, which is always running the latest code.

**Comment by firoball** [comment]
Thanks a lot for pointing out these issues. I'll check whether I can merge these safely into our setup.
