### ISSUE TITLE
Refactor DSpace 6.x to use reload4j, slf4j-reload4j (log4j12 replacements with active security maintenance)

### ISSUE THREAD

**Issue by kshepherd** [DSpace/DSpace#8143]
@misilot reported a new drop-in replacement for log4j 1.2.*, created by the original author of log4j 1.x, which is actively maintained for security and critical fixes.

I have a branch successfully building and running. Would love some help with testing! PR at  #8144 

I'm adding this as a public security / feature issue as this is not an active vulnerability, just some proactive maintenance related to security which we could do for future 6.x releases. I've tentatively added a milestone of 6.5 to avoid stalling 6.4 but if others are happy with it, perhaps we can squeeze it in for 6.4?

The project is called reload4j: https://reload4j.qos.ch
SLF4J has also published a replacement for slf4j-log4j12 called slf4j-reload4j: https://www.slf4j.org/news.html

These are meant to work **exactly** like log4j 1.2 and use the same java package path, so no logging code or import statements need to be changed, just dependency and exclusion configuration in our Maven POMs.

As noted when the log4j 2.x security vulnerabilities were being discussed and mitigated in many Java projects, DSpace versions prior to v7 were not affected as they use log4j 1.2.* (1.2.14-1.2.17 depending on exact transitive dependencies).
Although not vulnerable to the latest critical issue, there are several other security vulnerabilities out there which affect log4j 1.2.* and it does not get actively maintained. There will likely be more vulnerabilities discovered in the future.

reload4j and slf4j-reload4j were created to address the need for an exact replacement of log4j 1.2.17 with no changes apart from security maintenance.

A full list of the CVE references to fixed issues in reload4j can be found [at its webpage](https://reload4j.qos.ch/index.html).

**Comment by tdonohue** [comment]
Closing as this was fixed in 6.4

**Comment by kshepherd** [comment]
@Braxvang Apologies for the late reply to you here. The way to avoid the 'old' log4j or slf4j dependencies from creeping in via 3rd party maven artifacts is to configure exclusions for them, similar to the exclusions already in place in pom.xml:

In the `<dependency>` node for the particular artifact that is bringing in log4j (if you don't know, there's no harm just excluding from all of your 3rd party artifacts, put in an exclusions section (or append to existing exclusions) like this:
```
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
```

If you're not using Maven POMs to pull in 3rd part dependencies it could be trickier to manage easily but you could have an extra post-build 'clean' step where you remove the log4j or slf4j jars from lib folders in various modules.

Hope this helps!

**Comment by Braxvang** [comment]
@kshepherd Thanks for the reply!  I did end up just going back and cleaning all those up by hand (after trying to exclude them) with no adverse effects, so I could definitely see a 'clean' step working here.  

Thank you for the suggestions!

**Comment by minurmin** [comment]
@Braxvang , @kshepherd : Just to let you know, I had the very same issue when trying out the new DSpace 6.4 release (=solr and rdf-related old log4j jars appear to build). We have also a customized DSpace instance but local customizations should not be related to these components.
I added a PR #8648 that adds exclusions that should prevent the issue. Please check it out.
