### ISSUE TITLE
DSpaceApiExceptionControllerAdvice logs nothing of interest

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#8148]
**Describe the bug**
Method `sendErrorResponse` is also responsible for logging the exception, but except in a few specific cases it logs only the HTTP response code, without mentioning the actual exception or location.

In the few specific cases we get a stack trace.  As stated in comments, we probably don't want that level of detail for most exceptions, but I think that we *do* want to know what happened and where -- why are we sending this non-success response?

**To Reproduce**
1. Trigger a 404 response.
2. See the log.  All you'll find is "org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:404)".

**Expected behavior**
When logging an exception, we should always log the actual exception and its location.

**Comment by tdonohue** [comment]
@mwoodiupui : IIRC, this is by design.  4xx errors don't log exceptions, but 5xx errors *do* log exceptions.  See discussion in this ticket from last year: https://github.com/DSpace/DSpace/issues/3139#issuecomment-770963612

We could change this approach or make it configurable if we are noticing that some 4xx error should generate logs.  I think we just wanted to avoid some spammer filling up logs with 404 exception stacktraces just by hitting REST API endpoints over and over again.  

That said, I can see how at least providing an error message for 4xx exceptions would be nice...maybe we should update it to only log the exception text for 4xx errors, while the full stacktrace is logged for 5xx errors.

**Comment by mwoodiupui** [comment]
I ran into a specific case today.  A user reported incorrect behavior, but the log gives no help in tracking down the problem.  I've written a patch which just adds the exception's own message and location to the single line log entry.  I agree that we don't want a stack trace for every 404.

**Comment by tdonohue** [comment]
@mwoodiupui : Aha, at a glance your PR looks exactly like what I suggested... don't log a full stacktrace, just log the exception that occurred.  That seems reasonable...pulling this ticket & that PR over to the 7.3 board

**Comment by LucaGiamminonni** [comment]
Hi @tdonohue @mwoodiupui , what about to introduce a configuration property to specify for which http statuses we want to log the entire exception stack? I agree that in the case of 404 the exception stack shouldn't be shown, but maybe in cases where we get an unexplained 404 maybe it could be useful. We could add a property that lists all the statuses for which the exceptions should be logged with more details (perhaps setting 422 and 500 as default). During development or testing it could be useful to log more exceptions than those that should instead be detailed in production. One configuration property would make the switch fast.

**Comment by tdonohue** [comment]
@LucaGiamminonni : I think that idea is a good one, if it's not too complex to implement.  If it's too complex to implement in a highly configurable manner, it might also be good enough to simply provide a "debug" configuration which logs more exceptions than the default.

In any case, @mwoodiupui has already created an early PR at #8149 which may help us better analyze our options.

**Comment by mwoodiupui** [comment]
There is already a set LOG_AS_ERROR containing the single status 422.  This could be filled from configuration instead of a static assignment.  Members of LOG_AS_ERROR get a stack trace.  All 500-class statuses are already treated this way.
