### ISSUE TITLE
Migrate Advanced ORCID Integration from DSpace-CRIS into DSpace core

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#8157]
DSpace core only has very limited ORCID integrations at this time.  Specifically, DSpace can only pull in metadata via ORCID.

DSpace-CRIS (built/maintained by 4Science) has advanced ORCID-related features/functionalities which are not yet available in DSpace core.  These include:
1. ORCID Authentication in DSpace
2. Ability to link an EPerson (user account) with their Person Entity (user profile).  This link allows an EPerson to be the "owner of" their Person Entity (similar to how a Collection can be the "owner of" an Item).
    * The link between an EPerson and a Person Entity can be created by a Administrator, or by a user themselves _once they authenticate via ORICD_.  Once authenticated via ORCID, if a matching ORCID is found on a Person Entity object, the user can "claim" it and link it to their account (EPerson). If no corresponding Person Entity object exists yet, it could instead be created & linked to their account (EPerson).
3. Updates to a Person Entity in DSpace can be pushed automatically to user's ORCID profile.
4. New/Existing Publication Entities in DSpace can be pushed to ORCID (and linked to user's ORCID profile).
5. Updates to ORCID profile can be _pulled_ to the DSpace Person Entity (either manually or via a scheduled batch update).
    * Some limitations may exist if this is ported to DSpace...e.g. pulling down the ORCID "affiliation" field might require some basic "hierarchical metadata" to be implemented in DSpace.  DSpace-CRIS has a basic "hierarchical metadata" concept to support it, using the "place" value of metadata fields to create a basic hierarchy.
6. The above changes will allow DSpace to legally display the ORCID badge (which can only be displayed for authenticated ORCIDs) in the same manner that DSpace-CRIS is able to do so

NOTE: Implementing ORCID in DSpace in the above manner will _minimally require Person Entities to be enabled in DSpace_ (for any sites which wish to use these advanced ORCID features). However, we likely should require Publication and Project Entities as well to allow ORCID to properly sync publications and funders.  This means that in DSpace sites _without_ Entities only the current basic ORCID integration (i.e. pulling in metadata from ORCID) may be possible.

**Additional context**

The above was discussed with @abollini at 4Science in December 2021.  This effort was estimated at around **240 hours** (30 days). This is a very small percentage of the overall development effort that 4Science needed to build the functionality in DSpace-CRIS (which was more like 6 months of effort).  This amount of effort is required because, although the code is stable & well tested, it will require modifications/improvements when migrating into the DSpace data model  (e.g. the linkage between an EPerson and a Person Entity will need to be updated).

This was also discussed briefly in a DSpace Steering meeting in December 2021, and decided that this is of interest to DSpace. However, it was determined not to be in Tier 1 (Highest Priority) at least at this time.  Therefore, it's tentatively added to the Tier 2 board.

**Related Work**
The OpenAIRE Graph work (also by 4Science as part of the [OpenAIRE ELD project](https://www.openaire.eu/openaire-eld-enrich-local-data-via-the-openaire-graph)) is semi-related to this ORCID implementation because, once OpenAIRE graph is supported, the ORCID implementation could be enhanced to allow an EPerson to be "notified" on their MyDSpace page if new publications are linked to their ORCID profile. If so, you could immediately import them from ORCID into DSpace (linking them to your DSpace Person Entity). 

OpenAIRE Graph PRs:
* Frontend: https://github.com/DSpace/dspace-angular/pull/1007
* Backend: https://github.com/DSpace/DSpace/pull/3143

**Comment by paulo-graca** [comment]
I would like to point a reference for an ORCID synchronization library:
https://github.com/fccn/PTCRISync/wiki

![image](https://user-images.githubusercontent.com/877488/161047125-a6331d4e-c7e2-457d-b969-b5407c530900.png)

The promotional video:
https://vimeo.com/251179542

and an implementation demo:
https://vimeo.com/251312395

**Comment by sheilarabun** [comment]
Since DSpace CRIS is a certified ORCID service provider (https://info.orcid.org/certified-service-providers/orcid-certified-service-providers-list/) are there plans to do the same for DSpace once the ORCID functionality is added? That would be awesome!

**Comment by sheilarabun** [comment]
@abollini (Hi Andrea!) One other question/suggestion for consideration in additional to my question about certified service provider status above: 

Regarding user experience: with the current DSpace CRIS functionality that is expected to be added to DSpace, researchers have to 'manually' push works from DSpace to ORCID per work. It would be great just to ask the researcher up front for permission, and after that simply automate pushing the data from DSpace to ORCID, that way users don't have to take an action every time. The user can always delete works from their ORCID record, or change the visibility of those works on their ORCID record if needed after the works are pushed. Let me know what you think, and many thanks for working on this!

**Comment by tdonohue** [comment]
Hi @sheilarabun : Currently, the plan is to migrate the Advanced ORCID features from DSpace-CRIS to DSpace as-is.  That's the work that we've been working to fund so far.  Any additional enhancements/changes would need to be planned out & funded appropriately as well -- so, while requests are welcome, this particular ticket is just about migrating the existing features from DSpace-CRIS to DSpace. 

As for having DSpace becoming a certified ORCID service provider. I'd anticipate that'd likely be something we'd investigate, but that'd require approval of the DSpace Governance / Steering Group. It's not yet been talked about since this feature doesn't yet exist in DSpace (although work has started & we hope it will be part of 7.3)

**Comment by tdonohue** [comment]
Closing as this was implemented in a series of PRs all included in 7.3. 

ORCID PRs include:
* #8232 (with corresponding frontend PR https://github.com/DSpace/dspace-angular/pull/1617)
* #8263 (with corresponding frontend PR https://github.com/DSpace/dspace-angular/pull/1618)
* #8266 (with corresponding frontend PR https://github.com/DSpace/dspace-angular/pull/1626)
* #8268 (no frontend PR required)
