### ISSUE TITLE
Submissions can be completed without granting the license

### ISSUE THREAD

**Issue by ybnd** [DSpace/DSpace#8183]
**Describe the bug**
Submissions can be completed without granting the license, this has become apparent after the "Always enable Deposit button" PR in the frontend.

I'm listing this as a backend bug because
* The backend just deposits submissions with `/sections/license/granted=false` without complaining, so it seems that this is a REST issue. It shouldn't be the frontend's responsibility to enforce that the license is granted.
* The backend doesn't flag `/sections/license/granted=false` as an error when patching, so the frontend can't know it has to mark the checkbox as invalid

**To Reproduce**
1. Start a new submission on https://demo7.dspace.org/home
2. Leave all fields unfilled and click "Deposit"
    * You should see two notifications: "There are incomplete sections" & "Submission saved successfully"
    * **The license checkbox will not be marked as invalid**
3. Fill out all required fields, upload a file, _but leave the license checkbox unchecked_. The click "Deposit" again.
    * **The submission will just complete**

**Expected behavior**
When attempting to deposit a submission without granting the license, it should be rejected and the license checkbox should be marked as invalid.

**Related work**
[Angular #1427](https://github.com/DSpace/dspace-angular/pull/1427)

**Comment by tdonohue** [comment]
Thanks @ybnd : Agreed this needs resolution. Pulling this onto the 7.3 board and flagging as "high priority"

**Comment by LucaGiamminonni** [comment]
Hi @ybnd @tdonohue , we would be interested in solving the problem. We estimate 4/6 hours to find the cause, fix it and test it.
