### ISSUE TITLE
Unable to upload bitstream to a new BUNDLE for archived items

### ISSUE THREAD

**Issue by MarijkaA** [DSpace/DSpace#8187]
**Describe the bug**
It is not possible to upload a bitstream to a new BUNDLE e.g. a BUNDLE which does not already exist for an item via Edit Items. 

**To Reproduce**
1. Log in as Administrator
2. Use “Edit - Item” search to access an archived item which has a LICENSE bundle only (you will be uploading a bitstream to the ORIGINAL bundle)
3. Access “Bitstreams” Tab
4. Select “Upload” Button

![image](https://user-images.githubusercontent.com/20429062/155264620-ad8ba6dd-2ca9-4b08-935d-dd680b0d1036.png)

5. Select “Bundle” – Select a bundle list

![image](https://user-images.githubusercontent.com/20429062/155264505-1db07fad-d86a-46f8-a298-248dc62132f0.png)

**Result:** Only the BUNDLE(S) which already exist for the archived item are listed. Administrators cannot upload bitstream to a new BUNDLE e.g. ORIGINAL bundle.

**Expected behavior**
All BUNDLES should be listed in the “Bundle” – Select a bundle list, including those which do not already exist for the archived item so that administrators can upload to existing and new BUNDLES.

**Related work**
None.

**Comment by tdonohue** [comment]
Agreed, this is a (known) bug... this ticket duplicates https://github.com/DSpace/dspace-angular/issues/1380 (which is already on the 7.3 board but is awaiting a volunteer).  Closing this ticket as a duplicate. See that other ticket instead.
