### ISSUE TITLE
Items browse not filtered, jump to functionality causes issues

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/DSpace#8203]
**Describe the bug**
The items browse, eg [/browse/title?startsWith=T](https://demo7.dspace.org/browse/title?startsWith=T), does not filter the results with the "startsWith" but rather jumps to the page where items starting with this query are.

This is however in opposition, and causing the same issues, that lead to the changes done here: https://github.com/DSpace/DSpace/pull/1730

The plain-text metadata browse does have entries that get filtered by the startsWith query, eg /browse/subject?startsWith=T

**To Reproduce**
Items browse
1. Go to items browse [/browse/title](https://demo7.dspace.org/browse/title)
2. Add a startsWith query/letter, for which there are no results,  [/browse/title?startsWith=X](https://demo7.dspace.org/browse/title?startsWith=X)
3. Looking at results from REST https://api7.dspace.org/server/#/server/api/discover/browses/title/items?sort=dc.title,ASC&page=0&size=20&startsWith=X => Still shows results, not filtered

Plain-text metadata browse:
1. Go to metadata browse [/browse/subject](https://demo7.dspace.org/browse/subject)
2. Add a startsWith query/letter, for which there are no results,  eg [/browse/author?startsWith=stent](https://demo7.dspace.org/browse/author?startsWith=stent)
3. Looking at results from REST https://api7.dspace.org/server/#/server/api/discover/browses/subject/entries?sort=default,ASC&page=0&size=20&startsWith=stent => No results, since filtered

Items browse not all browse results completely pageable with jump to method either:
- [browse/title?startsWith=14](https://api7.dspace.org/server/#/server/api/discover/browses/title/items?sort=dc.title,ASC&page=0&size=20&startsWith=14) vs [/browse/title](https://api7.dspace.org/server/#/server/api/discover/browses/title/items?sort=dc.title,ASC&page=0&size=20)
- On https://demo7.dspace.org/browse/title?startsWith=14&bbm.rpp=100 => Can't navigate back to previous page, even though there are items that alphabetically precede it, ex "090952/Z/09/Z" item in complete title browse

**Expected behavior**
Both types of browses should behave similarly on whether they filter their results or jump to the page with expected results.
The jump-to method however causes unexpected results for the items browse and is likely not possible for the metadata browse (since it works with facetting), so both should act as a filter.

**Related work**
- Similarly fixed before here: https://github.com/DSpace/DSpace/pull/1730
- Both items and metadata values browse can be clearly labeled as filtering results after this is done, like suggested in: https://github.com/DSpace/dspace-angular/issues/1379

**Comment by MarieVerdonck** [comment]
This will take an estimated **8 hours** to fix and adjust/add IT.

**Comment by tdonohue** [comment]
@MarieVerdonck : We discussed this in this week's meeting, and all agreed this seems good to fix.  @artlowel said I should assign this back to you, so I did.

One note though, there was some feedback that with this "filter" approach, the alphabetic letters at the top of the browse may not provide great usability (as clicking on some letters can result in no entries being returned... and the "0-9" option would no longer work as well as a filter, as you can only filter by one number at a time)

![browse](https://user-images.githubusercontent.com/483997/157709884-552ec485-3e44-4cd4-8777-c82c24e3a665.png)

One suggestion was that we might want to consider simply **removing** that entire list of alphabetic letters, and requiring users instead to use the input field below it to "filter" results based on whatever letter/number/word they want.   We may want to update the text of that box though to make it clear that it will filter your browse results, _not search_ them.

So, as you are implementing this fix, you may want to consider that feedback as well.  It's not necessarily **required** for this PR, but I do agree that the alphabetic list of letters may not have the best "usability" once all these browse options use a "filter".

**Comment by tdonohue** [comment]
@MarieVerdonck : Also wanted to make sure you are aware of separate work going on in the "Browse by" pages, see https://github.com/DSpace/dspace-angular/pull/1552

I just want to make sure you are aware of this, so that, if needed, you can build any Angular UI updates off that existing PR.  If you have any interest in help reviewing/testing that PR (to help get it merged quickly), let me know as well.
