### ISSUE TITLE
Google Scholar Meta Tag citation_pdf_url contains link to embargoed files

### ISSUE THREAD

**Issue by TanyaHolm** [DSpace/DSpace#8205]
In DSpace7, we have Google Scholar meta tags configured.
The meta tag _citation_pdf_url_ contains links to embargoed files - presumably because embargoed files are contained in the Original Bundle. I believe Google will not like being taken to a log-in page.

Expected behavior
It should be possible to exclude embargoed files from being included in the meta tag _citation_pdf_url_.

**Comment by tdonohue** [comment]
Thanks @TanyaHolm for reporting this... I'm pulling this over onto our 7.3 project board to see if I can find a volunteer.  I agree, it's likely not proper behavior for embargoed content.  The `citation_pdf_url` likely should only link to a public bitstream.

**Comment by benbosman** [comment]
This will take an estimated 4 hours, atmire would like to claim it
You can assign @MarieVerdonck

**Comment by MarieVerdonck** [comment]
REST side this check is already done for the "citation_pdf_url" google meta tag

`google.citation_pdf_url` corresponds to the ` $simple-pdf` config (see crosswalk [here](https://github.com/DSpace/DSpace/blob/dspace-7.0/dspace/config/crosswalks/google-metadata.properties#L47)) 
=> File links are added to the Google accessible metadata in `org.dspace.app.util.GoogleMetadata` [here](https://github.com/DSpace/DSpace/blob/dspace-7.0/dspace-api/src/main/java/org/dspace/app/util/GoogleMetadata.java#L258)
=> Link created in `getPDFSimpleUrl` [here](https://github.com/DSpace/DSpace/blob/dspace-7.0/dspace-api/src/main/java/org/dspace/app/util/GoogleMetadata.java#L900) 
=> Retrieved first CONTENT bitstream of item that is publically accesible in item [here](https://github.com/DSpace/DSpace/blob/dspace-7.0/dspace-api/src/main/java/org/dspace/app/util/GoogleMetadata.java#L942-L952) 
=> `isPublic` check [here](https://github.com/DSpace/DSpace/blob/dspace-7.0/dspace-api/src/main/java/org/dspace/app/util/GoogleMetadata.java#L974-L982)

So this already prevents embargoed files from being accessible to Google meta tags REST side. Test REST added showing this here: https://github.com/atmire/DSpace/commit/2408aa9fc4fb3d61fdc1a24d9b53b8ce106f68a7 => Unsure whether worth adding as continuous verification? If so I'll open a PR to add that too.

For the Angular side fix to prevent the addition of the "citation_pdf_url" meta tag for embargoed / non publicly accessible files, PR created: https://github.com/DSpace/dspace-angular/pull/1597

**Comment by tdonohue** [comment]
@MarieVerdonck : I think it'd be good to submit your Test in https://github.com/atmire/DSpace/commit/2408aa9fc4fb3d61fdc1a24d9b53b8ce106f68a7 as a separate backend PR, as that ensures the code/logic doesn't change in the future

If you can find time to do so, please assign it to me and I'll get it quickly merged (as I've already reviewed the code of that test, and it looks good to me).  Thanks!
