### ISSUE TITLE
Special groups are not dispayed in the profile page

### ISSUE THREAD

**Issue by atarix83** [DSpace/DSpace#8206]
**Is your feature request related to a problem? Please describe.**
Special groups which the current user belong to are not showed in the list present in the profile page

**Describe the solution you'd like**
The profile page should also display the list of group which the current user belong to.

This could be done by adding a new `specialGroups` link to the response from [api/authn/status endpoint](https://github.com/DSpace/RestContract/blob/main/authentication.md#status). On angular side we could use this link to show also the special groups if any 

**Additional context**
https://github.com/DSpace/DSpace/issues/8161

**Comment by atarix83** [comment]
@tdonohue 

The estimation for the solution described in the issue is about 16hours for REST and Angular implemenation

**Comment by tdonohue** [comment]
@atarix83 : I agree this would be very useful. I didn't realize that Special Groups were not already displayed.

I'll move this over to the 7.3 board & assign to you. If your team can fit this into 7.3, I think it'd be useful to fix soon.
