### ISSUE TITLE
Oracle support deprecated in 7.3. Will be removed in 7.6 release

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#8214]
## Deprecation of Oracle Support

Per a unanimous vote in today's DSpace Steering Meeting, DSpace will **deprecate support for Oracle Databases in the upcoming 7.3 release.** 

**All Oracle-specific classes/code will be removed one year after the 7.3 release**.  Assuming that we remain on the three-releases per year schedule for 2022-2023, this likely means complete removal of Oracle support in version 7.6.

See announcement on mailing lists: https://groups.google.com/g/dspace-community/c/nXNMVBY_CJo/m/4pu7WKdUAgAJ

This decision was not made lightly. 
* Over several releases we have found that our ability to support Oracle has been very inconsistent. None of the core DSpace developers use Oracle at their institutions, which means most major releases are not well tested on Oracle, resulting in a lot of [Oracle specific bugs](https://github.com/DSpace/DSpace/issues?q=label%3A%22backend%3A+Oracle%22+).  While some of those bugs get fixes slowly over time, a number are still open issues with no volunteers.
* We surveyed the community via [emails to dspace-community, dspace-tech and dspace-devel](https://groups.google.com/g/dspace-community/c/nXNMVBY_CJo/m/WbvtpXm2CQAJ) asking for help in better supporting Oracle.  Unfortunately, no offers of help have been formally made. We only had a few responses out of a community of thousands, implying that Oracle is not frequently used with DSpace.
* We also feel that DSpace should strive to provide an entirely open source platform.  Oracle is obviously not an open source product, and the cost of running it can be significant. This speaks to the challenge of finding anyone to help support it.

## What this means

**For 7.3:** ( :white_check_mark: Completed in #8300 )
* Add deprecation warning to Release Notes & README
* Add deprecation warning to mentions of Oracle in DSpace Documentation.
* Log deprecation as a `WARN` in `dspace.log` on every restart of DSpace backend for sites which currently use Oracle.

**For Summer 2023 release (version 7.6):**
* Remove all Oracle-specific migrations under `dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/`.
* Remove all Oracle-specific code from `org.dspace.storage.rdbms.*` classes.
* Remove all Oracle-specific profiles/dependencies from POMs
* Remove all mentions of Oracle in READMEs and configurations (*.cfg)

## Oracle to PostgreSQL Migration options

_Choose ONE:_
* Use `Ora2Pg` (Recommended) : Consider using Ora2Pg to migrate from Oracle to PostgreSQL.  An early guide for how one institution did this migration is available at https://wiki.lyrasis.org/display/DSPACE/DSpace+Oracle+to+PostgreSQL+migration
* Use AIPs: If that's not possible, you could also use [AIP Backup & Restore](https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore) as a migration tool. 
    * Simply export AIPs from DSpace + Oracle, install DSpace + Postgres and import AIPs there. 
    * WARNING: AIPs currently do have some [known limitations](https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore#AIPBackupandRestore-HowdoesthisdifferfromtraditionalDSpaceBackups?WhichBackuprouteisbetter?), especially that they do not store "in progress Items" (ones that are not yet submitted or in workflow) or Item versions.  Therefore, using AIPs for migration will result in some data loss.

**Comment by mwoodiupui** [comment]
We should provide some guidance on *how* to migrate one's DSpace instances from Oracle DB to PostgreSQL.  Offhand I don't know whether Packager export/import will get everything *in the database*.  One alternative I recall is [Ora2Pg](https://ora2pg.darold.net/index.html) but I've never yet used it.  Anyway we need to do some planning and testing.

**Comment by tdonohue** [comment]
@mwoodiupui : If it's of interest to you to look into this, I'd welcome anyone documenting their experiences to share with others. Unfortunately though, because the number of Oracle users is so very low (at least based on responses to surveys), providing a migration guide from Oracle to PostgreSQL is not very high priority.  I'm not aware of anyone who has done this migration & it's not funded work at this time, so it'd need to be volunteer driven.  

That said, the two options you mention (using [AIP Backup & Restore](https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore) as a migration tool and using `Ora2Pg`) are likely the best paths.

AIP Backup & Restore is likely the _easiest path_ as it requires no knowledge of Oracle vs Postgres.  Simple export AIPs from Oracle, install Postgres and import AIPs there.  But, AIPs currently do have some [known limitations](https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore#AIPBackupandRestore-HowdoesthisdifferfromtraditionalDSpaceBackups?WhichBackuprouteisbetter?), especially that they do not store "in progress Items" (ones that are not yet submitted or in workflow) or Item versions.
