### ISSUE TITLE
IIIF manifest and canvas cache eviction is asynchronous and could led to unexpected responses

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#8243]
**Describe the bug**
While testing parallel builds on same machine (Bitbucket instance) we experienced systematic failures of following tests:
- IIIFControllerIT.findOneWithCacheEvictionAfterBitstreamUpdate
- IIIFControllerIT.findOneWithCacheEvictionAfterItemUpdate 

We suppose this can be done to an asynchronous cache eviction and invalitation. 

**To Reproduce**
1. configure a parallel execution of unit-tests and integration-tests builds on same machine (i.e. a bitbucket Pipeline)
2. run parallel builds

**Expected behavior**
Test passing

**Related work**
We (4Science) can look into this in order to have synchronous cache eviction, in 1 or 2 hours.
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Closing, fixed by #8245
