### ISSUE TITLE
Ask current password to user when he / she sets a new password

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#8255]
**Is your feature request related to a problem? Please describe.**
When a logged in user changes his / her password from profile section, he / she does not have to insert the current one. 

**Describe the solution you'd like**
User changing his / her password should be asked for current one. If not inserted, or if the inserted one is wrong, password change operation should not be allowed. Could it be worth allowing a user, impersonating another, to change password without having to enter the impersonated user current password?

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by corrad82-4s** [comment]
As possible solution, we think following steps could be done.

Step 1 - user can change password only if current authentication method is "password" and if he / she is not impersonating other user.  To reach this goal a further check on already existing CanChangePassword feature could be done.

Step 2 - AuthenticationMethod interface exposes a new method accepting context and a "challenge" and returning a boolean. At first phase all implementations but PasswordAuthentication will return 'false', while PasswordAuthentication will check challenge value, if matches against current password, method implementation returns true. 
Above logic is used by EPersonRestRepository patch. Resource endpoint accepts an optional "challenge" parameter. 
If patch contains a password update, challenge value is verified using above described new method. If challenge is resolved, password change can be performed, otherwise a 403 error is returned.

Step 3 - Profile page's "Security" box, displayed if and only if current user can change password, is updated with a new field where user must enter his / her current password.
This mandatory value, is sent in payload as "challenge" for password update (Eperson resource patch) request

As 4Science we are interested in this development, our rough estimation is 2 days

**Comment by abollini** [comment]
hi @tdonohue we are working on that, can you assign it to @corrad82-4s  estimation was already provided (previous comment)

**Comment by tdonohue** [comment]
@abollini : Sounds good, I'll update the estimate and assignment.
