### ISSUE TITLE
New users might be registered in a massive way by a robot

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#8256]
**Is your feature request related to a problem? Please describe.**
This might be a problem. When an user starts his / her registration process, he / she just have to insert the email address with which registration should be made in this page https://demo7.dspace.org/register . 
A robot navigating automatically the site, might perform registration in a massive way. This might lead to a DoS and to spam, having many users receiving a registration email related to a not requested operation. The same would happen by calling `/server/api/eperson/registrations` endpoint in a massive way. 

**Describe the solution you'd like**
A captcha-like anti robots solution could be implemented. Registering user solves a captcha on front-end side, then a captcha token is released and should be sent together with email address by form data. Token is validated by the backend, if it is all valid, registration request is tracked and registration email is sent. 
It could make sense leaving the activation or deactivation to DSpace7 administrator by mean of configuration, so that if, for any reason, an administrator does not want this kind of validation, can disable it. 

We (4Science) are open to discuss which solution could be the best one.

**Comment by amgciadev** [comment]
Hi, just to mention that this is also an issue for any of the other forms such as feedback, or request a copy. Agustina

**Comment by tdonohue** [comment]
@corrad82-4s : I'm open to ideas here, though it seems like it may be too late for 7.3 at this point (unless your team sees a quick fix approach).

I should point out that any such attack would need to use the UI/frontend.  The Backend already has CORs checks to ensure that it only "trusts" specific origins.  By default the Backend will only trust the Frontend, which means such a DoS/spam attack cannot occur via direct commands to the REST API... instead it would *have* to utilize the UI to send the requests.  Therefore, it might also be possible to find a front-end only solution that would suffice here (e.g. https://www.npmjs.com/package/ngx-captcha or similar).  We may not even need the backend to verify a token, as it's already validating against CORs and CSRF, provided that something at the UI-level can validate the person driving the UI is not a robot.

**Comment by abollini** [comment]
@tdonohue please assign to us it should take 2 hours
