### ISSUE TITLE
Allow to do group/eperson patching of a resourcepolicy

### ISSUE THREAD

**Issue by Micheleboychuk** [DSpace/DSpace#8277]
**Describe the problem**
Considering that group/eperson resourcepolicy attributes are associative,
we can't do the normal patching as has been done for other resourcepolicy attributes.
**Solution**
To modify an eperson or the group it would be necessary to implement the POST of the uri-list to the /eperson or /group association link.
If a resourcepolicy is linked to an eperson it should be possible to only replace such eperson with another but not with a group. The same is true for resourcepolicy linked to a group. Add/remove of the linked eperson/group should also fail with a 422.

**As required:** https://github.com/DSpace/dspace-angular/issues/1585

**Comment by tdonohue** [comment]
This seems to relate to #7812 as well.  I'll move all these over into the 7.4 board as it seems too late for 7.3 for these new features.

**Comment by abollini** [comment]
@tdonohue this should took 10-12 hours and we have already started to look to this in parallel with the other task
