### ISSUE TITLE
An email template was not converted to Velocity

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#8278]
**Describe the bug**
`config/emails/request_item.to_admin` still uses the old `java.text.MessageFormat` placeholders, not the Velocity placeholders that are now required.  This probably leads to un-usable emails.

Also, this template and `request_item.author` could use a comment block to explain the purpose of the template and its parameters.

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**
Email requesting a copy of a restricted document, sent to an administrator, should be correctly filled out with the supplied parameters.

**Comment by tdonohue** [comment]
@mwoodiupui : Moving this over to the 7.3 for tracking purposes. Since this is a small bug, if you have time to fix it for 7.3 we can try and get it in that release.

**Comment by mwoodiupui** [comment]
Further investigation shows that `request_item.to_admin` was introduced in #2229 but was not referenced in any code.  It is not referenced now.  This file should be deleted.  We still need to document `request_item.author`.

**Comment by mwoodiupui** [comment]
The 'suggest' template is also unused.  It is part of the "Item Request" feature of JSPUI, which is not scheduled to be re-implemented.  Removing it.  See commit 95f1175321996699219d44a7302b9666bc4214e4 and surroundings for the origin of this template.
