### ISSUE TITLE
Custom resource policies are duplicated if multiple upload configuration share the same access conditions

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#8282]
**Describe the bug**
If you configure multiple upload step to use different metadata and/or access conditions when the user select an access condition that is shared among multiple configuration the corresponding resource policies is applied n times (1 for each configuration).
Due to the same bug it is possible to set an access condition in the submission also if not allowed by the specific submission configuration associated with the collection if this access condition is defined in another configuration

**To Reproduce**
1. in the `access-conditions.xml` duplicate the `uploadConfigurationDefault` bean configuration giving it a second name. Map also this bean in your `uploadConfigurationService`
2. make a submission and assign any access condition to a bitstream in your item
3. check the resource policy of the bitstream once the item has been archived, you will see two copies of the TYPE_CUSTOM resource policy selected during the submission

**Expected behavior**
Only one resourcepolicy should be created. Only access condition allowed by the specific submission configuration should be processed

**Comment by abollini** [comment]
It should take 12 hours to fix it and provide ITs

**Comment by tdonohue** [comment]
@abollini : I'm not against implementing this fix, but I'm worried about available reviewers to get this done in time for 7.3.  I'll assign this to you, but understand I cannot guarantee it would be reviewed in time for 7.3
