### ISSUE TITLE
Turn on discovery in DSpace 7.2

### ISSUE THREAD

**Issue by ammanabrolua** [DSpace/DSpace#8291]
I want to turn on discovery in DSpace 7.2. I need the faceted sidebar search to be available in all pages. How can I achieve this? Please help.

**Comment by tdonohue** [comment]
@ammanabrolua : Discovery is "on" by default.  In DSpace 7.x, at this time faceted sidebars are only available on the search pages.  There are no options to make the faceted sidebar available elsewhere at this time.  

That said, if you or anyone else wants to enhance the UI to provide facets on other pages, we'd welcome contributions.  See our code contribution guidelines for details: https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines

Closing this as answered as the question was answered and it's not actionable at this time.
