### ISSUE TITLE
Our contributions guideline are unknown to github

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#8294]
Our guidelines available here
https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines

are unknown to github that expect to have them as a CONTRIBUTING file in the repository (or in the .github folder).
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

Should we create a such file? should we link from this file to our wiki or viceversa?
I'm inclined to move the content from the wiki here and put a link to github from the wiki

**Comment by tdonohue** [comment]
I agree we probably should clean this up at some point.  At a minimum, we could link to our Wiki from GitHub, but I do agree it might be more appropriate to move the docs into GitHub entirely (that way they are closer to the code).

I'll claim this ticket, but I feel it's `low priority` right now.  Will try and get to it when I can find time.
