### ISSUE TITLE
Shibboleth users can't see restricted communities & collections without reloading the page.

### ISSUE THREAD

**Issue by samj55** [DSpace/DSpace#8307]
**Describe the bug**
Shibboleth users after successfully logged in need to reload the landing page to see the restricted communities and collections.

**To Reproduce**
1. Restrict the anonymous access to any community you choose and give any Shibboleth Special group you pick a read access to it.
2. Login with a Shibboleth user belongs to the special group given access above.
3. The community won't be visible unless you do a reload/refresh to the page.

**Expected behavior**
No page reload needed by end users to see restricted communities or collections.

**Related work**
None.

**Comment by tdonohue** [comment]
This needs to be retested with 7.4, as it's possible this behavior has been fixed by #1805.

**Comment by mspalti** [comment]
@tdonohue , this issue still exists in 7.4.

**Comment by tdonohue** [comment]
This should be re-tested in 7.6.  It's possible this was fixed (or improved) by https://github.com/DSpace/dspace-angular/pull/2187

**Comment by mspalti** [comment]
@tdonohue, yes, this was fixed by https://github.com/DSpace/dspace-angular/pull/2187. It looks like a duplicate issue.

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/dspace-angular/pull/2187 in 7.6
