### ISSUE TITLE
Users have to log in to DSpace 7.2 to approve or deny request a copy requests.

### ISSUE THREAD

**Issue by peter975** [DSpace/DSpace#8311]
**Describe the bug**
When a user follows a link to approve ('Send copy') or deny ('Don't send copy') a request a copy, they need to login to DSpace.

This unexpected behavior occurs both when request links are sent directly to the user AND when the Help Desk workflow is enabled.

**To Reproduce**
1. Enable Help Desk strategy: https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-(Optional)RequestingacopywithHelpDeskworkflow
2. As anonymous user, look at an item with an embargoed bitstream; click on the embargoed bitstream.
3. Complete the request a copy form.
4. As helpdesk staff, receive an email containing a link to the approve/deny screen.
5. While not logged in to DSpace, select the link that leads to the approve/deny screen.

**Expected behavior**
A user (submitter or repository staff) should be able to access the approve/deny screen without needing to log into DSpace.

I believe this is the intended behaviour as described in the documentation (https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy) "If the original submitter can not evaluate the request, he or she can forward this email to the right person, who can use the link containing the token without having to log into DSpace.

**Related work**
https://github.com/DSpace/DSpace/issues/8304

**Comment by tdonohue** [comment]
Closing this ticket in favor of #8304, as it appears to be the same issue as described in #8304 (and that other ticket has more discussion already).
