### ISSUE TITLE
Address many long-standing LGTM complaints

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#8320]
**Describe the bug**
LGTM calls out many things that it sees as problems, which we have never addressed.

**To Reproduce**
Submit a pull request, and watch LGTM report more than 150 issues that have nothing to do with your changes.

**Expected behavior**
LGTM should have little or (preferably) nothing to point out.

**Comment by tdonohue** [comment]
Thanks for starting this @mwoodiupui !  I'm definitely supportive of getting things cleaned up more.  Pulling this over onto the 7.4 board, so that we can try to fit this into that next release.

**Comment by tdonohue** [comment]
Initial PR #8321 was merged into 7.4

**Comment by tdonohue** [comment]
Closing this as LGTM is no more & the original work was already merged.  Now, these "complaints" have moved over into GitHub Code Scanning, where they appear as their own "ticket".  So, they can be addressed one by one or in bulk as folks see fit.  See https://github.com/DSpace/DSpace/security/code-scanning
