### ISSUE TITLE
XMLUI : Reset button on advanced filters doesn't work

### ISSUE THREAD

**Issue by leonardoguerrero** [DSpace/DSpace#8329]
**Describe the bug**
DSpace version: 6.x
Theme: Mirage2
When advanced filters are set and user wants to restore filters form, reset button doesn't execute an action.

**To Reproduce**
1. Go to /discover.
2. Set an advance filter like title (at least one filter).
3. Click on "Apply" button.
4. After results has been shown, click "Reset" button. You will notice that this button has no effect.

**Expected behavior**
After results are shown, clicking "Reset" button should restore advanced filters form to its original empty state.

**Related work**

**Comment by leonardoguerrero** [comment]
It is possible also affects DSpace 5.x. I've tried on 5.10 and has same issue.

**Comment by alanorth** [comment]
Just confirmed this issue on our DSpace 6.3 instance as well as demo.dspace.org.
