### ISSUE TITLE
Allow setting bundle when creating a bitstream in item with REST (DSpace 6.x)

### ISSUE THREAD

**Issue by minurmin** [DSpace/DSpace#8342]
**Is your feature request related to a problem? Please describe.**

Currently, adding bitstream to item with REST API sets it to ORIGINAL bundle. However, in customized installations different bundles may be used with different access settings or shown in different way.

**Describe the solution you'd like**

Proposed solution for DSpace 6: extend the endpoint

`POST /items/{item id}/bitstreams (Add a bitstream to the specified item)`

with a new optional bundleName parameter that allows setting a custom bundle. ORIGINAL is used as default so the change is backwards-compatible.

**Describe alternatives or workarounds you've considered**

A workaround is to create the bitstream in original bundle first and then change it - either using the UI or with another REST extension #8339 (DS-2983) that allows setting bundle of an existing bitstream. However, if a custom bundle is expected it is more straightforward to place the item there in the first place.

**Additional context**

Custom bundles have been used as part of JYU repository https://jyx.jyu.fi/ in at least two use cases:
 - CONTRACT bundle to store thesis-related contracts (submitted by a non-DSpace form application with REST). These are not shown publicly.
 - DATASET bundle to show individual files related to a dataset in a compressed list separate from files in ORIGINAL bundle (=that in the case of datasets contains zip package containing all the files), visually somewhat similar to solution used in Edinburgh Datashare https://datashare.ed.ac.uk/ . As with theses, dataset files and metadata are submitted from a non-DSpace application using REST.

One should also note that this proposal deliberately negates an older issue 
DS-2348 REST Bitstreams should be only in original bundle. #777

**Comment by tdonohue** [comment]
Closing, the old (v6) REST API is no longer being actively developed.  The new REST API v7 already supports this feature because Bitstreams must be added via a POST to the bundle endpoint.  See https://github.com/DSpace/RestContract/blob/main/bundles.md#bitstreams
