### ISSUE TITLE
Wiki site server redistricting access to the docs 

### ISSUE THREAD

**Issue by erastus909** [DSpace/DSpace#8345]
![image](https://user-images.githubusercontent.com/35610114/173189781-38e2aed1-3d71-4266-958a-17fa2ef277b0.png)

**Comment by pollob666** [comment]
The wiki is not accessible at all currently. 
![Screenshot_২০২২০৬১৩_০৯১০১১](https://user-images.githubusercontent.com/3469402/173272759-c8154603-ee96-4901-bd70-85fe7493f9b7.png)

**Comment by tdonohue** [comment]
Closing, the Wiki was unavailable for emergency maintenance.  It's back up again.  See announcements on mailing lists: https://groups.google.com/g/dspace-community/c/BbMDHOHx6NM
