### ISSUE TITLE
Use `@autowire` in favor of `new` operator

### ISSUE THREAD

**Issue by BrunoRoemers** [DSpace/DSpace#8360]
**Describe the bug**
It's important to respect inversion of control to keep DSpace maintainable and extendable.
The `new` operator should be avoided at all costs and instead Spring should be used to create instances of classes (whether it be singleton or prototype beans or by using a factory).

Since class [DiscoverFacetValueConverter](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverFacetValueConverter.java) is a bean (it has the `@component` annotation), the following line should be replaced by an `@autowire`: [DiscoverFacetsConverter#L37](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverFacetsConverter.java#L37).

This can be done safely, because `DiscoverFacetValueConverter` does not have state. Case in point: [DiscoverFacetResultsConverter](https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverFacetResultsConverter.java#L33) already uses `DiscoverFacetValueConverter` as a singleton bean.

**Comment by mwoodiupui** [comment]
Injection also improves testability, since a unit test can easily inject a test double as needed.
