### ISSUE TITLE
DSpace 7 Edit Item doesn't support Curation Tasks (like DSpace 6)

### ISSUE THREAD

**Issue by amgciadev** [DSpace/DSpace#8384]
**Is your feature request related to a problem? Please describe.**
DSpace 7 documentation states in https://wiki.lyrasis.org/display/DSDOC7x/Curation+System#CurationSystem-IntheadminUI that 

> From the "Curate" tab/button that appears on each "Edit Community/Collection/Item" page: this tab allows an Administrator, Community Administrator or Collection Administrator to run a Curation Task on that particular Community, Collection or Item. When running a task on a Community or Collection, that task will also execute on all its child objects, unless the Task itself states otherwise (e.g. running a task on a Collection will also run it across all Items within that Collection).

as one was able to do in DSpace 5/6. 
That option does not seem to be available anymore in the Edit item/collection/community pages anymore in DSpace 7. At present you only seem able to run curation tasks from the Admin curation process screen.

**Describe the solution you'd like**
As stated in documentation:

> "Curate" tab/button that appears on each "Edit Community/Collection/Item" page: this tab allows an Administrator, Community Administrator or Collection Administrator to run a Curation Task on that particular Community, Collection or Item. When running a task on a Community or Collection, that task will also execute on all its child objects, unless the Task itself states otherwise (e.g. running a task on a Collection will also run it across all Items within that Collection).

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
Thanks @amgciadev for reporting this.  It appears this was overlooked, so I'm flagging this as a "bug" (as we should have done this when implementing curation tasks) and moving to the 7.4 board (in the hopes we can get this done in that release).

**Comment by abollini** [comment]
we (at 4Science) are interested in working on that. To add the tab and the feature reusing what already exists for communities and collections 4 hours will be enough

**Comment by tdonohue** [comment]
Thanks @abollini .  That sounds good & I'll assign you for your team to work on.
