### ISSUE TITLE
Optional element in submission forms

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/DSpace#8386]
In `submission-forms.xml` there is an optional element `<dc-qualifier>`. According to its DTD this element is mandatory, and it should be marked as optional.

It is sufficient to replace this line in `submission-forms.dtd`
```xml
<!ELEMENT dc-qualifier (#PCDATA) >
```
with:
```xml
<!ELEMENT dc-qualifier (#PCDATA)? >
```

The question mark sets the element as optional.

**Comment by tdonohue** [comment]
@davide-negretti : If you want to submit a PR for this, I think it makes sense to just quickly fix this.  Qualifiers should obviously be optional.

**Comment by davide-negretti** [comment]
@tdonohue I submitted the PR

https://github.com/DSpace/DSpace/pull/8388
