### ISSUE TITLE
In Advanced Search, list collections alphabetically

### ISSUE THREAD

**Issue by alawvt** [DSpace/DSpace#8408]
**Describe the bug**

In DSpace 6.3 XMLUI, in Advanced Search, e.g. https://demo.dspace.org/xmlui/discover, the top level communities are listed alphabetically.
<img width="1068" alt="DSpace6 3_advanced_search_collection_dropdown" src="https://user-images.githubusercontent.com/13037168/179315141-09852c66-6706-4d69-9f9d-0d916899df6f.png">

In DSpace 7.3, in Advanced Search, e.g.https://demo7.dspace.org/search, the collections are listed randomly. The community containing the collection is listed above it. Some of them have "Home" which isn't useful.
<img width="1165" alt="DSpace6 3_advanced_search_collection_dropdown" src="https://user-images.githubusercontent.com/13037168/179314934-a80b1cc1-c561-4c92-b213-e3456db5b229.png">. 

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**

Please either list the top-level communities alphabetically, like DSpace 6, or list the containing communities alphabetically or list the collections alphabetically.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
@arvoConsultores : Just seeing your above comment.  I think it makes sense for each of these Community/Collection search boxes to have the same behavior.  So, yes, it might make sense to ensure they all are alphabetically ordered.

That also might imply that the underlying query itself might need to be updated to return results ordered by title (as if you update the underlying query, it should change the behavior in all tools that use that query).  I'm not sure exactly how easy that is, but I wanted to point out that all these tools are likely using the same sort of query (against Solr, IIRC) to find their results.

**Comment by aroman-arvo** [comment]
As the requests are made using "discover" it is not easy to introduce the changes in the "Dspace" project. However, the changes are minimal if they are made in the angular part. I create this pull request that fix the issue:
https://github.com/DSpace/dspace-angular/pull/2007
