### ISSUE TITLE
Update Google Analytics to version 4

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#8413]
**Describe the bug**
Google Universal (GA 3) is deprecated and will be dropped by Google by July 2023. Moreover GA3 has been reported as to be NOT GDPR compliant, complains and discussions around GA4 are also ongoing in several country but it looks clear that at least usage of the latest version is required. DSpace still use GA3 both on the angular side, via the analytics.js than on the backend to push event related to bitstream download.

**How to reproduce**
Try to configure an api key for the GA4 version (G-xxxxx) no data will be collected

**Expected behavior**
The user should be able to configure an apikey (G-xxxxx) related to the new version of google analytics and see the data coming to the analytics dashboard.
We propose to extend the current implementation so that version 3 is still supported if the google-apikey starts with UA- but by default the new version of the google service is used.

An option should be also introduced to allow anonymization of IP address both on the angular than on the rest side.

We (4Science) are interested on working on that, it should take around **3-4 days on the REST part** (test are missing) and **2 days on the Angular side**

**Comment by tdonohue** [comment]
@abollini : This looks good & seems reasonable for 7.4.  This was already mentioned in https://github.com/DSpace/dspace-angular/issues/1672... but, I'll just link these two tickets together (as one is a frontend ticket & one is a backend one).
