### ISSUE TITLE
Multiple objects and authorization features endpoint does not support pagination

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#8416]
**Describe the bug**
Endpoint `/authorizations/objects` is not correctly handling pagination

**To Reproduce**
1. Call `/authorizations/objects` with page=1 and size = 1 parameters
2. Response will contain pagination information with page=0 and size = 20

**Expected behavior**
Response paginated as required, when pagination information is sent in rest request

We (4Science) can take in charge this fix, adding further tests to prove correct pagination. For this task, we estimate 4 hours of effort

**Comment by tdonohue** [comment]
I agree this is worth addressing... however it's unclear to me if this has impact on the UI, or if it's REST API only.  If it's REST API only, then I'd rank this as `medium priority`.  If it impacts UI behavior in some manner, then it likely would be bumped to `high priority`.  In any case, I'll add the estimate & pull it over to the 7.4 board.  But, I'm flagged as `medium priority` for now, as I feel it's higher priority to address bugs/usability issues that impact the UI.
