### ISSUE TITLE
Workflow's steps doesn't preserve order

### ISSUE THREAD

**Issue by vins01-4science** [DSpace/DSpace#8419]
**Description**
Inside the file `workflow.xml` we can configure a workflow and its steps.
When the steps are configured properly we expect them to be ordered in the same way as they are defined.
However, if you list all the collections `https://{dspace-server}:{dspace-server-port}/server/api/core/collections/`, you'll notice that some, or possibly all of them, doesn't respect the configuration file ordering.

**To Reproduce**
Search inside `workflow.xml` configuration file for the steps, by default are configured like this:
```xml
...
<bean class="org.dspace.xmlworkflow.XmlWorkflowFactoryImpl">
        <property name="workflowMapping">
            <util:map>
                <entry key="defaultWorkflow"
                     value-ref="defaultWorkflow"/>
          </util:map>
      </property>
</bean>
...
<bean name="defaultWorkflow" class="org.dspace.xmlworkflow.state.Workflow">
    <property name="firstStep" ref="reviewstep"/>
    <property name="steps">
        <util:list>
            <ref bean="reviewstep"/>
            <ref bean="editstep"/>
            <ref bean="finaleditstep"/>
        </util:list>
    </property>
</bean>
...
```
Here, the property `steps` has three entries, with a precise order.
Now, if you search in the collection `https://{dspace-server}:{dspace-server-port}/server/api/core/collections/`, you'll find that this order is not preserved.
The direct link to check for some workflows' steps is: `http://{dspace-server}:{dspace-server-port}/server/api/config/workflowdefinitions/{workflowName}/steps`, you should have access at least to one workflow (`defaultWorkflow`).

**Expected behavior**
The order of the steps inside each workflow should be preserved.

**Comment by vins01-4science** [comment]
We at @4science are interested to work on this issue.
The extimated resolution time is in 4-8h.

**Comment by tdonohue** [comment]
@vins01-4science : Sounds good, I'll assign this back to you for 7.4 and add the estimate.

**Comment by vins01-4science** [comment]
Here is the [linked PR](https://github.com/DSpace/DSpace/pull/8422)
