### ISSUE TITLE
Display Search Facets on all Home, Community, and Collection pages

### ISSUE THREAD

**Issue by alawvt** [DSpace/DSpace#8426]
**Is your feature request related to a problem? Please describe.**
In DSpace 6 XMLUI, search facets are displayed on all Home, Community, and Collection pages. Please enable this in DSpace 7. This will allow users to immediately browse and search the repository and collections. This will maintain the experience and functionality our users have come to expect. 

**Describe the solution you'd like**
I think the collection pages in the Iowa State University Repository, https://dr.lib.iastate.edu/home, hosted by Atmire are a good solution. For example, the Theses and Dissertations collection page, https://dr.lib.iastate.edu/collections/0830d32e-14e1-4a4f-bb8f-271a75ed35af?scope=0830d32e-14e1-4a4f-bb8f-271a75ed35af, begins with the same collection information that other DSpace 7 collection pages contain, including the horizontal Browse bar. However, below the Browse bar, instead of the simple list of items, there are the search results for that collection including the search facets.  

Default DSpace 7 collection page, https://demo7.dspace.org/collections/38113d78-54aa-4417-8741-a903cd5f4b5e,
<img width="928" alt="DSpace 7_collection" src="https://user-images.githubusercontent.com/13037168/181085628-c34fa768-2ab9-4481-afaf-69d7951ac72a.png">

Iowa State collection page, https://dr.lib.iastate.edu/collections/0830d32e-14e1-4a4f-bb8f-271a75ed35af?scope=0830d32e-14e1-4a4f-bb8f-271a75ed35af, with search results and search filters,
<img width="1154" alt="DSpace7_Iowa_State_collection" src="https://user-images.githubusercontent.com/13037168/181085807-f17d3498-af48-4d26-b1cc-f3e70fe98c04.png">

Notes:

- In the Browse bar, they have replaced the "Recent Submissions" tab with a "Search Collection" tab.

- Extend this to Community pages. They would be set up the same way with Community information above and search results below. 

- To support the "Recently Added" view, add "Date Accessed Descending" to the "Sort By" options and make it the default.

**Describe alternatives or workarounds you've considered**

**Additional context**
I plan to submit related requests such as continuing support of DSpace 5 and 6 XMLUI customized facets per collection.

**Comment by tdonohue** [comment]
Pulling this over to the 7.4 board, but I'm flagging as `medium priority` for now until we have more feedback.  I do agree though that is is something we should add to 7.x, but I'm worried this is more complex and don't wish to detract from higher priority bugs at this time.

**Comment by DSquareTechnologies** [comment]
@tdonohue Here is the filters addition scope document. Kindly help with the validation.

**Filters on the Home page**
•	Filters appearance on the home page illustrated 
![image001](https://user-images.githubusercontent.com/6321834/203241053-2c28c438-b628-486f-ac3d-1831fd994ff6.png)


 
•	Filter’s behavior will be the same as it is on the advanced search page at present.
•	Upon selecting a value from any filter, the user will be redirected to the advanced search page with items listed as per the value selected in the filter. Based on the users’ access rights, results will be filtered from the entire repository. Users can narrow down the list by adding filters available on the advanced search page.
![image003](https://user-images.githubusercontent.com/6321834/203241558-a1cb1127-3601-4c52-87ff-648b47dd9ff3.png)


 

**Filters on the Community page**
Filters' appearance on the community page is illustrated below
 
![image005](https://user-images.githubusercontent.com/6321834/203241582-37d36c58-1f99-40d5-af82-b4334b3bc646.png)

•	Filter’s behavior will be the same as it is on the advanced search page.
•	Upon selecting a value from any filter, items will be listed as per the value selected in the filter from the target community/sub-community. Users can narrow down the list by adding filters available on the advanced search page.
•	Breadcrumb will show Home / Community Name / Search (as per behavior in the DSpace 6.x’ XMLUI)
 
![image007](https://user-images.githubusercontent.com/6321834/203241654-3449a946-1fa6-484c-bcd8-649379473262.png)


**Filters on the Collection page**
Filters' appearance on the collection page is illustrated below
 
![image009](https://user-images.githubusercontent.com/6321834/203241677-08ca8353-bb44-4e47-a42a-177071403083.png)

•	Filter’s behavior will be the same as it is on the advanced search page.
•	Items will be listed in the collection as per the current mechanism i.e. Recent Submissions.
•	Upon selecting a value from any filter, items will be listed as per the value selected in the filter from the target collections. Users can narrow down the list by adding more filters available on the advanced search page.
•	Breadcrumb will show Home / Community Name / Collection Name / Search (as per behavior in the DSpace 6.x’ XMLUI)
 
![image011](https://user-images.githubusercontent.com/6321834/203241697-a2a4d456-142e-43eb-858c-0f4a0dff91ba.png)

**Comment by tdonohue** [comment]
@DSquareTechnologies : I feel the layout of these pages **needs work**, as I find it to be extremely confusing & I feel it hurts the usability of these pages. For instance, the "Filters" displayed on each page no longer filter the content you are seeing on the page... instead they redirect you to the search page.  That means these are no longer filters...they are links to searches.

* On the Homepage screenshot.
    * The Heading "Filters" doesn't make sense where you display it, as it is *not* filtering the Community list to its immediate right.  This impacts the usability of the homepage.  In DSpace 6.x, I see these filters were all under a heading called "Discover" & were displayed to the *right* of the Community list in a separate menu (to keep them separate from the page content).  
        * We may want to consider if these would look better on the right, or maybe even in a "tabbed" view similar to the current Community / Collection homepages (where there could be potentially 3 tabs...one for "Communities", one for "Recent Submissions" and one for "Search"... the last of which would show these filters)
        * We also could consider dropping these filters from the homepage entirely, as I'm not sure these filters are more useful than just typing in a search to start searching content.
        * I also want to note that there are potential performance concerns with putting too much content on the homepage.  At the very least, this feature needs to be possible to disable if it exists on the homepage.
    * The "Settings" section makes no sense here, as you cannot use it to change the sort/results count on the homepage. It should be removed.
* On the Community / Collection screenshots
    * Again, the Heading "Filters" makes no sense & the layout on the page doesn't make sense (as these filters don't filter the page contents)
        * I prefer the design that Iowa State has implemented for its Communities/Collections, as it provides a separate tab for "Search".  See the screenshot in the description of this ticket, or https://dr.lib.iastate.edu/collections/0830d32e-14e1-4a4f-bb8f-271a75ed35af?scope=0830d32e-14e1-4a4f-bb8f-271a75ed35af
        * I think this same design could be used for both Communities & Collections.  Instead of redirecting you to the main search, you can provide an embedded search which is already filtered by that Community/Collection
   

Overall, I'd highly recommend rethinking the user interface design here.  The current layout is confusing because you are attempting to embed "Filters" on pages which _cannot be filtered_.  If you need more feedback, let me know. I'd also recommend considering bringing this to either DCAT or a Developer Meeting for additional feedback, as those groups may be able to provide brainstorms on how to make these pages more user friendly.

**Comment by DSquareTechnologies** [comment]
@tdonohue @artlowel 
Here are updated user interfaces of the Homepage, Community page, and collection page with the Discover option per input received during the working group meeting dated December 8th, 2023.

**Discover facets on Homepage**

- Discover the appearance on the home page illustrated below

![image](https://user-images.githubusercontent.com/6321834/210246669-8b05fa07-5d6f-4100-b70c-6bdf28e3b865.png)

- Discover facet’s appearance on the homepage will be configurable.
- Based on the value selected in a facet on the homepage, results from the entire repository will be listed on the advanced search page. Users can narrow down results by adding more filters on the advanced search page.

![image](https://user-images.githubusercontent.com/6321834/210246720-70bf5f1d-b286-42a7-b6d1-61229af2e68a.png)

**Discover on Collection page**
Discover facets' appearance on the collection page illustrated below
![image](https://user-images.githubusercontent.com/6321834/210246834-74a1a86f-1214-4872-ab21-6f53b5ce4805.png)

- The default listing of items on the collection homepage will be like the search result page and items will be sorted based on submission date and time.
- Based on the value selected in a facet on the collection homepage, results from the respective collection will be listed on the page. Users can narrow down results by selecting more filters from discover facets.
- Full text search field will search content within the collection.
- 

**Discover facets on the Community page**
Discover facets appearance on the community page illustrated below
![image](https://user-images.githubusercontent.com/6321834/210246908-03484c35-57e0-481c-8e18-2f1efa6c50a1.png)

- The default listing of items on the Community/Sub-community homepage will be like the search result page and items will be sorted based on submission date and time.
- Based on the value selected in a facet on the community/sub-community homepage, results from the respective community/sub-community will be listed on the page. Users can narrow down results by selecting more filters from discover facets.
- The full-text search field will search for content within the community/sub-community.
- Next to the “Recent Submissions” link, the “Sub-communities & collections” link will be available. Upon clicking this link users shall see a list of sub-communities and collections. The appearance of this list should remain unchanged from the current state.

**Comment by tdonohue** [comment]
@DSquareTechnologies : The new overall design looks reasonable to me, and looks to have taken the prior feedback into account.  

That said, I think we may want to make (very) minor tweaks to the Community/Collection pages where these facets are displayed. 
*  On those pages, since the entire search results are embedded into the page, I think all search options can be displayed (including changing the "Discover" heading back to "Filters").  The only reason we cannot use the term "Filters" on the homepage is because you are sent to a separate page after clicking on one.  Since you remain on the Community/Collection page while searching, you can keep the term "Filters" on those pages.
* The Browse tab might need to be renamed from "Recent Submissions". as this embedded search is not _only_ recent submission any longer.  Instead it might be named something like "Search Within" or "Search Collection" / "Search Community"

Neither of these are major changes to your design.  They are very minor comments/improvements.  I suspect there may be other minor improvements that may be necessary once the code is completed, but I think the overall design looks good & reasonable.

So, as far as I'm concerned, this looks fine & seems to be in line with what was discussed in the Dev meeting.  If others have comments hopefully they'll let you know on this page.

**Comment by tdonohue** [comment]
Fixed by:
* Added facets to homepage: https://github.com/DSpace/dspace-angular/pull/2275
* Added facets to community/collection pages: https://github.com/DSpace/dspace-angular/pull/2732
