### ISSUE TITLE
Provide an Advanced Search page with Boolean options

### ISSUE THREAD

**Issue by alawvt** [DSpace/DSpace#8431]
**Is your feature request related to a problem? Please describe.**
Getting the Search Facets working well, etc. is higher priority but after that, an Advanced Search interface is necessary to provide thorough search functionality. I would compare it to the functionality of Advanced Search in DSpace 6 XMLUI and WorldCat.org.

DSpace 6 XMLUI Advanced Search, https://vtechworks.lib.vt.edu/discover
<img width="1107" alt="DSpace6_XMLUI_advanced_search" src="https://user-images.githubusercontent.com/13037168/181118757-ecbe63ec-8bdd-485c-ae40-c7289e8eaf04.png">

WorldCat.org Advanced Search, https://www.worldcat.org/advancedsearch?&lang=en
<img width="1178" alt="WorldCat_advanced_search" src="https://user-images.githubusercontent.com/13037168/181118857-477b797d-5d19-4306-97b0-9c8e64e11ab9.png">

**Describe the solution you'd like**
The essential feature is multiple field search boxes that can be combined to allow complex or specific searches. It should provide a configuration to choose which fields are included. For example, for administering collections we would want specific fields such as LOC call number, ISSN, ISBN, etc.

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
@alawvt : Just a quick note regarding this feature.  

Advanced boolean options are already supported in the DSpace 7 search function.  Boolean keywords can be used, and you can also specify to search within specific fields by name.  Some examples:

* Searching: `test AND power` will return results with both these words in them. E.g. https://demo7.dspace.org/search?query=test%20AND%20power
* Searching `test OR power` will return results with either of these words in them. E.g. https://demo7.dspace.org/search?query=test%20OR%20power
* Searching `test NOT power` will return results with "test" but not including "power". E.g. https://demo7.dspace.org/search?query=test%20NOT%20power
* Searching `dc.title:title` will only return results where the `dc.title` includes "test".  E.g. https://demo7.dspace.org/search?query=dc.title:test
* Searching `dc.title:test AND dc.description.abstract:green` will only return results where the `dc.title` field includes "test" and the `dc.description.abstract` field returns "green".  E.g. https://demo7.dspace.org/search?query=dc.title:test%20and%20dc.description.abstract:green

However, you are correct that there is not yet a separate page for advanced search...which would make it easier to craft more complex queries.  So, I'll leave this ticket open for the creation of such a page.  But, in the meantime, it might be useful to simply document how to perform advanced searches in DSpace 7, maybe in https://wiki.lyrasis.org/display/DSDOC7x/Learning+DSpace

**Comment by alawvt** [comment]
@tdonohue, thank you for the information about the current Boolean search capabilities in DSpace 7 which I have added to the stub page, "Search" in the Learning DSpace section, https://wiki.lyrasis.org/display/DSDOC7x/Search. A dedicated advance search interface would avoid the user having to know and (mis)type field names. It would also allow us to configure fields so "author" includes dc.creator and dc.contributor.author, etc.

**Comment by mwoodiupui** [comment]
Actually, building UI for the general case could be challenging.  It really wants a cut-down *visual programming language* implementing only expressions.  Unless we want users to transform their Boolean queries into Łukasiewicz notation, which could be represented by a simple list of operators and operands.  The DSpace 6 "advanced" search form shown above is actually *less* expressive than what DSpace 7 already has, no?

See https://en.wikipedia.org/wiki/Scratch_(programming_language)

**Comment by alawvt** [comment]
Thanks, @mwoodiupui, for the comment. The Boolean search functionality is already there. A search interface would make that capability apparent and much more convenient. We have used the customizations in XMLUI to add advanced search filters and have been satisfied with that approach.

**Comment by alawvt** [comment]
Thanks, @tdonohue. Are you linking to https://wiki.lyrasis.org/display/DSDOC7x/Search+-+Advanced?

**Comment by DSquareTechnologies** [comment]
@tdonohue  Kindly help with scope validation for the ticket:

- Advanced filters appear below the global search field on the advanced search page.

<img width="1957" alt="001" src="https://user-images.githubusercontent.com/6321834/203243595-509b049c-67a7-4ad4-9818-44caad9428f6.png">

-  User clicks the “Show Advanced filters” to access the functionality and advanced filters appear as demonstrated in the below screen. Clicking **add** icon will add another filter to the list and **remove** will reduce the filter list. Below are other important details:

- The user will be able to select one metadata element per row from the drop-down list.
- Below operators will be available in the operators' drop-down list
      - Contains
      - Equals
      - ID
      - Not Contains
      - Not Equals
      - Not ID

- Clicking the “Reset” button will reset the search query.
- Clicking the “Apply” button will trigger the search query.
- “AND” operator will be used between multiple advanced search filters used in developing the query. 
<img width="1882" alt="002" src="https://user-images.githubusercontent.com/6321834/203244581-d1467828-931b-4c7f-abca-b10e307a47a5.png">
 

- Search filters and values used to make a search will appear in the same way as filters are appearing at present. “Show advanced filter” will appear below the searched terms. 
![003](https://user-images.githubusercontent.com/6321834/203244683-490b4b1e-d005-48b5-aae6-95511ae9ed19.png)

**Comment by tdonohue** [comment]
@DSquareTechnologies : To be honest, one might argue that this ticket could be resolved with an "inline help menu" which simply describes the syntax options listed at https://wiki.lyrasis.org/display/DSDOC7x/Search+-+Advanced   

That seems to be the approach that Google takes these days (there's no direct link anywhere to an Advanced Search, instead you are always sent to [docs on "Refine web searches"](https://support.google.com/websearch/answer/2466433))

My main concern here is that DSpace 7's search options are so advanced that I'm not sure how well an "advanced search" menu like your screenshots would work.  For example, you can search within *any metadata field* in DSpace 7 (e.g. "dc.title:Testing" finds "Testing" in the Title field).  Does that mean we'd need to list every metadata field in the list of filters?  Or are you proposing somehow making the list of fields configurable / dynamic / smarter, so that searching by "Author" knows whether to search "dc.contributor.author" or "dc.creator" (as either of those fields could be an Author)?

Overall, I'm not against your design here. But, I'm concerned that it could be highly complex to implement if it offers every search option.  So, it makes me wonder what approach is best here (and I don't know that I have a good answer to that question yet).

Again, this might be something better asked to DCAT (and maybe the Developers Meeting).  Do users need this help building basic boolean queries, or would some sort of "pop up" syntax guide provide them with more power over the searches they need to run?  I'd recommend we better understand the full use case here, as I'm not sure we do.

**Comment by DSquareTechnologies** [comment]
@tdonohue and @artlowel 
Here is the updated user interface for Advanced Search and Filters as per input received during the working group meeting dated December 8th, 2023.

- Advanced search to appear above filters as an expandable box.
![image](https://user-images.githubusercontent.com/6321834/208367894-d3282dff-4f10-4780-8ae4-b6410198dbbf.png)

- Click the **Advanced Search** box to expand.
![image](https://user-images.githubusercontent.com/6321834/208367964-28dba9ee-9798-456f-bdcd-985fec4b8e20.png)

- Select the advanced search filter from the drop-down list,
- Enter the search string in the text box
- Select one of the operators from the drop-down list. The below operators will be available in the operators' drop-down list
  o	Contains
  o	Equals
  o	ID
  o	Not Contains
  o	Not Equals
  o	Not ID

- Operators are required under each filter in the Filters section also. Please refer below illustration:
![image](https://user-images.githubusercontent.com/6321834/208368431-24704a4e-3964-40a2-a7cf-8e8439a05fa3.png)

- Click **Add** button in advanced search or filters to execute the query.
![image](https://user-images.githubusercontent.com/6321834/208368490-54ad8e34-cdd2-4883-87fb-03a458a497dd.png)

- **Reset filters** to be used for resetting the query.

**Comment by tdonohue** [comment]
@DSquareTechnologies : This looks reasonable and looks to be aligned with what was discussed in the Dec 8 meeting.  I think the design also looks like what @artlowel suggested in that meeting.

My only (small) recommendation here would be to move the "Advanced Search" options to **below** the "Filters" section (but it could be above "Settings" perhaps).  I feel that most users are still going to use the "Filters" initially, so those should appear first. That's a very minor suggestion though.

Similar to the other design, I suspect there may be other minor suggestions/improvements that are recommended once the code is complete & we move into testing it.  But, the overall idea/design here seems good to me.

**Comment by DSquareTechnologies** [comment]
Noted and development begun accordingly.

**Comment by mwoodiupui** [comment]
In today's meeting I mentioned that I perceived proposed changes to the search sidebar as being ordered strangely.  This comes from thinking of the assembly of controls as a sentence, which I tend to do when feasible.  So, counter-argument 1:  maybe most people don't think that way.  Counter-argument 2:  there are many SVO languages and many SOV languages (and some number of VSO languages, plus some in which word order is arbitrary) so switching the controls around simply disadvantages a different set of language users.

All that to say:  I continue to think this is a (minor) usability issue, but I don't see a good way to address it, so we may as well keep the current order.  A proper fix would reorder the controls according to the user's language, but I couldn't find an existing type which has language/word-order mapping, and it's probably not worth the effort to create (and maintain!) our own.

**Comment by DSquareTechnologies** [comment]
@tdonohue Here is the list of inputs received during the meeting dt. 03/30:

- The operator drop-down list should have four values: Contains, Not Contains, Equals, and Not Equals.
- The operator drop-down list should move above the text field in the Advanced Search section.

Please confirm if there is anything else to be incorporated/eliminated. Thanks!

**Comment by tdonohue** [comment]
@DSquareTechnologies :  One last thing mentioned in the meeting on Mar 30:

* The advanced search options should be either *removed* from individual facets (Author, Subject, etc), or have a User Interface configuration allowing them to be turned on/off easily.  By default, they should only appear in the separate "Advanced Search" section.

There were other small usability issues mentioned (like how the Author would appear as "Name, Contains" if you used the Advance search "Contains" option in the Author field).  But, those can always be cleaned up once the PR is in the review stage.
