### ISSUE TITLE
Solr search core initialization is fragile

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#8437]
**Describe the bug**
If `discovery.search.server` is incorrect, `org.dspace.discovery.SolrSearchCore#initSolr` just logs an error but leaves the class uninitialized, causing obscure errors later.  At time of writing, it causes the server Context to fail to start.  This is because the SolrClient reference held by the class is still null.

**To Reproduce**
1. Set `discovery.search.server` to a valid URL that won't connect to Solr.
2. Try to start `webapps/server`.

**Expected behavior**
There's no good way to recover, but perhaps `initSolr` could throw a more informative exception instead of silently failing.

**Comment by tdonohue** [comment]
@mwoodiupui : I agree that maybe we just need a better exception here... perhaps simply logging that `discovery.search.server` seems to be invalid? (or something similar).

I'll pull this over to the 7.4 board, as it seems like a small, quick fix is all we may need.
