### ISSUE TITLE
Upgrade Checkstyle and review the rule set?

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#8441]
Checkstyle is at v10.3.2 at time of writing.  DSpace still uses v8.30.  Perhaps it is time to upgrade?

The configuration DTD has changed, so some configuration repairs will be needed.  We may wish to review the rule set while doing so.  There are rules which are disabled due to the volume of style violations in older code, but the problem may be less now, or perhaps it is time to bite the bullet and fix them all.

**Comment by alanorth** [comment]
I was just looking into this myself using checkstyle v10.11.0 and it's actually not too bad. There seems to be [a regression in the Indentation check](https://github.com/checkstyle/checkstyle/issues/10582) which prefers this:

```java
@LinksRest(links = {
    @LinkRest(
        name = ClaimedTaskRest.STEP,
        method = "getStep"
    ) // <--- here
})
```

... to be reformatted like this:

```java
@LinksRest(links = {
    @LinkRest(
        name = ClaimedTaskRest.STEP,
        method = "getStep"
        ) // <--- here
})
```

**Comment by MW3000** [comment]
It would be useful to upgrade CheckStyle to a version newer than 8 as the popular IntelliJ CheckStyle Plugin dropped support for 8 earlier this year. So people using IntelliJ loose the functionality to run CheckStyle continuously in their IDE, which was a very helpful feature.

https://github.com/jshiell/checkstyle-idea/releases/tag/5.88.0    
https://plugins.jetbrains.com/plugin/1065-checkstyle-idea

**Comment by alanorth** [comment]
@MW3000 yes I agree. I have [a draft PR with the latest version of Checkstyle](https://github.com/DSpace/DSpace/pull/8868) (8.17.0 at the time of this writing), unfortunately there is a regression in the indentation checks that upstream is not keen on fixing (I won't link it here to avoid spamming the upstream issue, see details in my PR).

**Comment by alanorth** [comment]
Thanks @tdonohue. Yes we can use the latest Checkstyle now (10.19.0) with no problems thanks to your indentation fixes. I am surprised upstream didn't want to do anything about that, but oh well. I've rebased #8868 and marked it ready for review.
