### ISSUE TITLE
NPE in classes extending from AbstractCondition when calling itemService

### ISSUE THREAD

**Issue by amgciadev** [DSpace/DSpace#8449]
I am developing some custom item-filters (via item-filters.xml) and have noticed that that itemService is not being injected correctly in AbstractCondition class (package org.dspace.content.logic.condition) as it always return null

**Comment by mwoodiupui** [comment]
Is this addressed by #8421?

**Comment by tdonohue** [comment]
@amgciadev : I think @mwoodiupui is correct that this has already been fixed by #8421 ... that fix came in after 7.3 however, so it's only available on the `main` branch until 7.4 is released.

**Comment by amgciadev** [comment]
Apologies both for not having spotted the 7.4 fix - it does fix it indeed! thank you

**Comment by tdonohue** [comment]
Closing as this seems to be fixed by #8421
