### ISSUE TITLE
Compiling Mirage2 with mirage2_dev generate a bad theme

### ISSUE THREAD

**Issue by arvoConsultores** [DSpace/DSpace#8463]
**Describe the bug**
Dspace version: 6.4
The Mirage2 theme cannot reach some javascripts. All of them are defined at scripts.xml with the starting src: "node_modules"
    <script src="node_modules/jquery/dist/jquery.min.js">&#160;</script>
    <script src="node_modules/jquery-ui-dist/jquery-ui.min.js">&#160;</script>
    <script src="node_modules/handlebars/dist/handlebars.js">&#160;</script>
    <script src="node_modules/holderjs/holder.js">&#160;</script>
    
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/alert.js">&#160;</script>
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/button.js">&#160;</script>
    
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/collapse.js">&#160;</script>
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js">&#160;</script>
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/modal.js">&#160;</script>
    
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/tab.js">&#160;</script>
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js">&#160;</script>
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/popover.js">&#160;</script>
    <script src="node_modules/bootstrap-sass/assets/javascripts/bootstrap/transition.js">&#160;</script>
    <script src="node_modules/datatables/media/js/jquery.dataTables.js">&#160;</script>

**To Reproduce**
Compile Mirage2 using mirage2_dev profile and deploy.
Enter to any DSpace page with "development tools" active, or view source code and check javascript urls to see the 404 errors

**Expected behavior**
The previous js should be accesibles.

**Related work**

**Comment by alanorth** [comment]
Interesting. I've never used the `mirage2_dev` profile before. I will need to check the dev tasks in `dspace-xmlui-mirage2/src/main/webapp/Gruntfile.js` to see what's going on.
