### ISSUE TITLE
Openaire requests soon (OCT 2022) to be limited to not authenticated user

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#8487]
**Describe the bug**
Starting from October 2022, Openaire APIs will limit the usage rate to 60 requests per hour to not registered clients as stated [here](https://graph.openaire.eu/develop/authentication.html) 

This could possibly impact Live Import. This service uses `org.dspace.external.OpenAIRERestConnector` which already does support usage of client and client secret, configurable in .cfg. 

This limit would also impact Publication Claim feature target of PR #8280 . Connector used by this feature should be checked and, in case, updated to use authentication in order to have a good request rate allowance guaranteed.

**Comment by paulo-graca** [comment]
The current feature already supports authentication. 
You need to provide:
```
openaire.token.clientId = CLIENT_ID_HERE
openaire.token.clientSecret = CLIENT_SECRET_HERE

```

Please check:
https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/openaire-client.cfg

**Comment by tdonohue** [comment]
As @paulo-graca notes above, this appears to already be supported via a "Service registration" approach, which is noted as supported at https://graph.openaire.eu/develop/authentication.html
> To access the OpenAIRE APIs with better rate limits, send your access token using the Authorization header.

>
>	GET https://api.openaire.eu/{resourceServicePath}
>	Authorization: Bearer {ACCESS_TOKEN}
> To get an access token, we support [personal access token](https://graph.openaire.eu/develop/personalToken.html) creation and [service registration](https://graph.openaire.eu/develop/registeredService.html).

To register your service, use the instructions provided by OpenAIRE and configure your `openaire.token.clientId` and `openaire.token.clientSecret` in your `local.cfg` as shown in `openaire-client.cfg`: https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/openaire-client.cfg#L29-L32
