### ISSUE TITLE
Solr query exception on workspace submission save due to ORCID "will be generated::orcid::..." authority key syntax

### ISSUE THREAD

**Issue by uofmsean** [DSpace/DSpace#8490]
**Describe the bug**
DSpace 7.3:
When adding a new ORCID authority author (dc.contributor.author) to a submission workspace item, a temporary authority key is created with the syntax "will be generated::orcid::ID" (where ID is the ORCID ID). If you select Save, or Save for later, a Solr authority query is performed with this temporary key and results in a server-side Solr org.apache.solr.search.SyntaxError exception. The exception also occurs when first loading a previously saved submission that has any such temporary authority keys.

See [solr-exception.txt](https://github.com/DSpace/DSpace/files/9627022/solr-exception.txt) for full stack trace.

**To Reproduce**
1. Enable ORCID authority for dc.contributor.author
2. Start a new submission that accepts dc.contributor.author in the input form
3. Search for and add an ORCID author
4. Select Save or Save for later
5. Check dspace.log file for exception

**Expected behavior**
Solr queries for "will be generated::orcid::..." keys should be skipped since they will not be in the Solr authority core. Or, the Solr query should be transformed into an acceptable syntax to avoid the exception.

**Related work**
First discovered while investigating issue #8436

**Comment by amtuannguyen** [comment]
I see the the code attempt to escape the ":" in the string "will be generated::orcid::...". But, the since String.replaceAll(regex,regex) expects regex as the replacement, the \ needs to be escaped twice, once for the java string and one for the regex. So, "\\\\:" => \: as final replacement value. 

See https://github.com/DSpace/DSpace/compare/main...amtuannguyen:DSpace:main

Can I create a PR for this?

**Comment by uofmsean** [comment]
When testing an alternate fix for this issue, I found cases where a successful Solr query actually causes other issues related to authority lookup. I'm working on a fix for those cases that I can submit as a PR before we close this issue. Basically, the extended fix makes sure that queries for "will be generated::" authority keys never occur so that acceptable default logic can properly handle these cases. I will also need to create a separate issue and PR for dspace-angular.

**Comment by uofmsean** [comment]
While creating pull request #8799, I suddenly realized that there might be a deeper issue here. Indexing an item's content via the discovery consumer should have the properly generated authority key from the authority consumer as configured below:

 `event.dispatcher.default.consumers = authority, versioning, discovery, eperson`

They are executed in order as far as I can tell because Dispatcher uses [LinkedHashMap](https://github.com/DSpace/DSpace/blob/fea4067464b499f1104478f7edf018bb0aab5d9a/dspace-api/src/main/java/org/dspace/event/Dispatcher.java#L35) for the list of consumers.

Why would the IndexEventConsumer (discovery) be trying to look up a preferred label for an authority key that has not yet been generated if AuthorityConsumer (authority) runs first?
