### ISSUE TITLE
bin/start-handle-script sometimes fails with class-not-found

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#8507]
**Describe the bug**
On some instances, `bin/start-handle-server` fails, reporting:
Error: Could not find or load main class org.dspace.app.launcher.ScriptLauncher
Caused by: java.lang.ClassNotFoundException: org.dspace.app.launcher.ScriptLauncher

On other instances it works.

**To Reproduce**
Behavior is not consistent across instances, but when you have it, running the script will report a ClassNotFoundException in `log/handle-server.log`.

**Expected behavior**
If correctly configured, the handle server should start.

**Comment by tdonohue** [comment]
closing, fixed by #8508
