### ISSUE TITLE
No items returned 

### ISSUE THREAD

**Issue by santilococo** [DSpace/DSpace#8510]
**Describe the bug**
After an installation of DSpace on a production server, I am unable to get anything from the rest of the API. It's weird because the items exist but they just won't show up. For example, knowing the id of a community I can retrieve it manually: https://ri.itba.edu.ar/communities/f6dd0126-9451-4c8a-a3a5-eccd34eee2c5 or an item: https://ri.itba.edu.ar/items/4429d349-00a3-4953-9f52-6a918c00e891

Already reinstalled dspace, solr and all services with no luck.

Nor do the tomcat or dspace logs help me. Do you know what I can do? The same installation but on another PC works perfectly.

It seems that to get the items I need to log in to Hal Browser, but that doesn't happen on my other PC (in test). Also, in angular UI I can never see the elements (even though I am logged in).

If you need a specific record or file, please tell me.

I have the DSpace server running at https://ri.itba.edu.ar/server, Solr running at https://ri.itba.edu.ar/solr and the UI running at https://ri.itba.edu.ar.

**To Reproduce**
1. Install DSpace 7.3
2. Get communities https://ri.itba.edu.ar/server/#https://ri.itba.edu.ar/server/api/core/communities for example

**Expected behavior**
You should see that totalElements = 0 and it should say 14. If you are logged in, you will see that totalElements = 14: https://i.imgur.com/rSLwmGd.png

**Comment by tdonohue** [comment]
Closing, as this sounds like a local configuration issue.  Please use one of our dedicated support channels if you have questions about a possible misconfiguration: https://wiki.lyrasis.org/display/DSPACE/Support

In terms of what you can do, please see our Troubleshooting guide for help on locating errors that may be occuring in the UI or backend: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

Additionally, if you are certain you have content, you may want to reindex everything in Solr (which is a required step of any upgrade). See step 12 of the backend upgrade process: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

If you need more help/support, please use one of the recommended support channels

**Comment by santilococo** [comment]
Sorry Tim, I didn't know that.

> Additionally, if you are certain you have content, you may want to reindex everything in Solr (which is a required step of any upgrade). See step 12 of the backend upgrade process: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

You helped me a lot, anyway! Thank you very much. Rebuilding the index solved the problem.
