### ISSUE TITLE
Facets search endpoint doesn't give results with queries containing capital letters

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/DSpace#8516]
**Describe the bug**
The facets endpoint, `/server/api/discover/facets/{facetName}` search doesn't take into account capital letters.

**To Reproduce**
Example capital letters:

- [author?prefix=a](https://api7.dspace.org/server/#/server/api/discover/facets/author?prefix=a) => results, all starting with A or a
- [author?prefix=A](https://api7.dspace.org/server/#/server/api/discover/facets/author?prefix=A) => no results, despite there being authors starting with A

**Expected behavior**
Since the facet can return values with capital letters, it should accept prefix queries with them. It should just do a case insensitive search in REST and return results, regardless of which letters are capitals.

**Related work**
Found whilst investigating issue: https://github.com/DSpace/dspace-angular/issues/1900

**Comment by MarieVerdonck** [comment]
Addressing this issue would take **2 hours** to address and test.

**Comment by tdonohue** [comment]
Same as the other ticket, I'll pull this over to the 7.5 board, add the estimate & assign back to you for your team to work on.  Thanks @MarieVerdonck !
