### ISSUE TITLE
Bug report assetstore.cfg and bitstore.xml

### ISSUE THREAD

**Issue by unibravo** [DSpace/DSpace#8520]
**Describe the bug**
**OS:**
Ubuntu 20.04
OpenJDK version 11.0.16
**Default Upgrading Steps for 7.3 to 7.4**

Failure during kernel init: Invalid bean definition with name 'org.dspace.storage.bitstore.BitstreamStorageService' defined in file [/dspace/config/spring/api/bitstore.xml]: Could not resolve placeholder 'assetstore.index.primary' in value "${assetstore.index.primary}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'assetstore.index.primary' in value "${assetstore.index.primary}"

**To Reproduce**
**Default Upgrade Steps for 7.3 to 7.4**
1. mvn -U clean package
2. ant update

**Comment by tdonohue** [comment]
@unibravo : It sounds like you are missing the setting `assetstore.index.primary`?  It should be defined in this new configuration (added in 7.4): https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/assetstore.cfg#L19

**Comment by tdonohue** [comment]
Closing, this was answered above
