### ISSUE TITLE
Refreshing spider files fails with null pointer exception 

### ISSUE THREAD

**Issue by christian-scheible** [DSpace/DSpace#8528]
**Describe the bug**
 Running the cron job /dspace/bin/dspace stats-util -u fails with a null pointer exception because the Project of the Get request is null.
 Adding a Project before the Get gets excecuted fixes that.

[This](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/statistics/util/StatisticsClient.java#L138) is the Get request.

Changing it to this:

```java
Get get = new Get();
get.setProject(new org.apache.tools.ant.Project()); // THIS IS THE FIX
get.setDest(new File(spiders, url.getHost() + url.getPath().replace("/", "-")));
get.setSrc(url);
get.setUseTimestamp(true);
get.execute();
```

**To Reproduce**
1. Run this on command line: `/dspace/bin/dspace stats-util -u`

**Expected behavior**
It should download the spider files.

**Comment by tdonohue** [comment]
@christian-scheible : Could you create us a small PR with this fix?  This seems like something I can try to review quickly just to get it patched in the codebase.

**Comment by christian-scheible** [comment]
> @christian-scheible : Could you create us a small PR with this fix? This seems like something I can try to review quickly just to get it patched in the codebase.

Hi @tdonohue I made a pull request for this issue.

**Comment by tdonohue** [comment]
Thanks @christian-scheible !  I've pulled your PR over to our 7.5 board, so I'll find some reviewers and see if we can get this added to 7.5.
