### ISSUE TITLE
Common Extendend Regex format for submission-forms

### ISSUE THREAD

**Issue by vins01-4science** [DSpace/DSpace#8563]
As of now it will be impossible to define a common regex tag value that has flags usable for both `REST` and `angular` projects.
Moreover, using regex with the form `/{regex}/` will be invalid for `REST`.
It will be nice to use a common format / parser to analyze, parse and correctly create the `regex`.
Because we are currently showing the mismatched pattern inside the wrongly filled field in the `angular` project, it will be useful to use the standard regex format with flags: `/{regex}/{flags}` inside the `input-forms.xml` definition files. In this way the user will have a quickly understandable pattern (standard with flags) for check and adjust the configuration also using some famous online tools.

**To Reproduce**
Insert some regex with flags `/{regex}/{flags}` inside `input-forms` definition file, or insert a regex with `/` as delimiter: `/{regex}/`. This could led to wrong / unexpected behaviors.

**Expected behavior**
We should use the extended definition for regex, that will support all of these cases:
* `/{regex}/{flags}`
* `/{regex}/`
* `{regex}`

In this way we could easily parse and compute the right pattern with or without flags, and also check that the regex field contains a valid pattern.

**Comment by vins01-4science** [comment]
@tdonohue: We @4science can work on this issue.

**Comment by tdonohue** [comment]
@vins01-4science : I'm not sure I understand this issue ticket.  There is no `input-forms.xml` anymore in DSpace 7... it was replaced with `submission-forms.xml`.  So, I'm assuming you are talking about the RegEx format accepted by the `<regex>` tag in `submission-forms.xml`?

Could you better describe examples of how the current `<regex>` tag's behavior is limiting & how you propose changing it?  I'm not sure I understand your recommendations here...and looking at the backend code, I don't see any limitations placed on the value of the `<regex>` tag, but I'm sure I must be missing something.

I'm not against this idea of improving our regex syntax.  But, I think I need more examples of the problem you are seeing & how you plan to solve it before I can decide the priority of this ticket.

**Comment by vins01-4science** [comment]
> @vins01-4science : I'm not sure I understand this issue ticket. There is no `input-forms.xml` anymore in DSpace 7... it was replaced with `submission-forms.xml`. So, I'm assuming you are talking about the RegEx format accepted by the `<regex>` tag in `submission-forms.xml`?

Yes, my mistake. I meant that `<regex>` tag inside `submission-forms.xml` file.

> Could you better describe examples of how the current `<regex>` tag's behavior is limiting & how you propose changing it? I'm not sure I understand your recommendations here...and looking at the backend code, I don't see any limitations placed on the value of the `<regex>` tag, but I'm sure I must be missing something.

Sure, if you want to use a flag inside the regex itself you should choose a format for that declaration.
As of now, because the same field (`regex`) is shared between `Java` and `JS/TS` languages you can't use a common flag format to make it work for both.
As an example, if you choose the _Java inline flag format_ your regular expression will be: `(?i)[a-z]+`
> This expression will search for a word made of characters between `a` and `z` in upper or lower case (i flag means `case insensitive`).
With this regex the `REST` part will work as expected, but the `anglular` one will not recognize this syntax.
- The String `hello`:
  - will be recognized valid by the `angular` part;
  - will be recognized valid by the `REST` part.
- The String `123`:
  - will be recognized valid by the `angular` part;
  - won't be recognized valid by the `REST` part.

> The `angular` part can have unexpected behavior, because the string `(?i)[a-z]+` is not a valid `RegExp`, and will throw an exception during the creation phase.

Similarly, if you choose the ECMAscript format: `/[a-z]+/i`.
- The String `hello`:
  - won't be recognized valid by the `angular` part;
  - won't be recognized valid by the `REST` part.
- The String `/hello/i`:
  - will be **wrongly** recognized valid by the `angular` part;
  - will be **wrongly** recognized valid by the `REST` part.

The baddest news is that `/hello/i` could have been successfully saved in DSpace, and for the String `hello` the red input-box will have a red border and a validation message will be shown saying that: _**the value is not valid for the regex**_ `/[a-z]+/i`.
The user could misunderstand this message, because the string 'hello' will be valid for the format `/[a-z]+/i` inside a regex-tester, and because we are in ECMAScript-domain this should be valid.

The solution could be use of the standard ECMAScript `/{regex}/{flag}` recognize it and split it into two parts, using them correctly to create `RegExp`. And also use this format `/{regex}/flag` as part of validation message for the user (because we show it inside the `angular` part, and I think is easily understandable, the other format could led to misunderstanding because of `?` that is also the lookaround hook).

@tdonohue: Let me know if it's more clear, thank you!

**Comment by tdonohue** [comment]
@vins01-4science :  Thanks for the clearer explanation. I didn't realize that the regex syntax used by Java was invalid on the Angular side...so, this ticket makes much more sense to me now as it's about ensuring we are using a **common RegEx format that works for both Java/backend and Angular/frontend.**

I'll pull this over to the 7.5 board & flag as high priority, as I agree this is an issue we need to resolve.  I'll assign to you to work on.
