### ISSUE TITLE
Toggle to mark bitstream as primary does not work

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#8567]
**Describe the bug**
The toggle present in Administrative panel to edit bitstream metadata, used to define if a bitstream is the primary is not working as expected. In case it is switched on, no information is sent to backend to define it as primary. 
![image](https://user-images.githubusercontent.com/70699836/200026931-0977f2d7-5e0d-4a84-9415-38b1a0bc3582.png)

**To Reproduce**
1. login as administrator
2. go to an Item detail page, of an item having an attachment
3. Edit the item
4. From "Bitstreams" tab, select to edit one of bitstreams
5. Click on "primary bitstream" toggle and save the information of the bitstream
6. Bitstream won't actually be marked as primary

**Expected behavior**
We would expect the bitstream marked as primary in its bundle. From a deeper look in code and rest contract, it seems no operations to set a bitstream as primary are defined. So this issue would require not just frontend troubleshooting, but an update on REST side to mark a bitstream as primary (e.g. a POST or a PUT against `/server/api/core/bundles/<bundle uuid>/primaryBitstream` with uri of bitstream in payload).
Furthermore, as UX update, it could be worth to move the toggle from its current place, to `/edit/bitstreams` page, maybe here 

![image](https://user-images.githubusercontent.com/70699836/200030821-12cfac3b-a6e5-42c0-89f8-3a0d050aba8e.png)

so that the user could have a clear idea, bundle by bundle, about which is the primary bitstream and select one.

A rough estimation of work needed to solve this issue is 5 days, including both angular and REST updates.

**Comment by tdonohue** [comment]
@corrad82-4s : This is a duplicate as this bug already has tickets created at https://github.com/DSpace/dspace-angular/issues/1578 and https://github.com/DSpace/DSpace/issues/3349.  Both those tickets are already on the 7.5 board and flagged as `high priority`.

If your team is interested in working on these for 7.5, I can assign them both to you & add your estimate.  Currently they are unclaimed.
