### ISSUE TITLE
Type-bind submission config removes metadata field values present in submission

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/DSpace#8587]
**Describe the bug**
There is a bug in type-bind submission code that when there are multiple input fields in config for the same metadata field, but with different type-bind. That when a type is selected, that is not present in the first of such configured fields, that the value submitted into that metadata field is removed again.

**To Reproduce**

- two `dc.title` fields in submission configured, one for "Book" type and one for "Journal article" type
- `dc.type` = Journal article selected => Fill in title field => save => ok => fill in author field => save & reload page => title field now no longer filled in & metadata value for `dc.title` indeed no longer present if you check corresponding item (at endpoint `/api/core/items/{uuid}`)

**Expected behavior / Suggested fix**
This occurs because of the submission validation detection, because it checks whether the *first* configured field for that metadata field has a type-bind match with the selected one, and if not it removes the value(s) in that field. But does *not* check whether there are *other* input fields with the same metadata field, but a type-bind that *does* match the currently selected one

**Related work**
- Original issues type-bind: 
  - https://github.com/DSpace/dspace-angular/issues/806
  - https://github.com/DSpace/DSpace/issues/2873
- REST work PR: https://github.com/DSpace/DSpace/pull/8175

**Comment by MarieVerdonck** [comment]
Estimate of 8 hours to address, test and write IT for.

**Comment by tdonohue** [comment]
Thanks @MarieVerdonck !  Definitely a bug we should fix immediately. I'll assign back to you for you/your team to work on, and pull it over to the 7.5 board

**Comment by MarieVerdonck** [comment]
Apologies, after further investigation discovered there already was a fix created for this issue: https://github.com/DSpace/DSpace/pull/8296 
Issue was discovered in 7.2 and retested in main, but apparently something went wrong with the testing communication there, can now no longer be reproduced.
