### ISSUE TITLE
Import item via SAF with handle provided in collections file produces error 

### ISSUE THREAD

**Issue by Ma-Tador** [DSpace/DSpace#8592]
**Describe the bug**
When I import via SAF with the handle provided in the collections file, I get the error: "Invalid UUID string: Skipping".
When I use the same handle, but provide it in the CLI via -c option, the import works.

**To Reproduce**
1. Create a SAF item to import, and provide a collections file where a valid DSpace collection handle is specified.
2. Import as specified in the documentation (without providing a handle via -c).
3. After the script starts, the following error message appears: "Invalid UUID string: Skipping"

**Expected behavior**
The import should work as described in the DSpace documentation when a collections file with handle is provided.

**Comment by tdonohue** [comment]
@Ma-Tador : What version of DSpace is this related to?

**Comment by Ma-Tador** [comment]
Sorry, I forgot to mention that I use DSpace 7.4. However now is working, after I deleted a new line after the handle, everything works fine. So maybe we can add a note in the documentation to not have any new line after the handle is provided.

**Comment by Ma-Tador** [comment]
Remove new line after the handle and works as expected. Please add this hint in the documentation in case someone has this problem.
