### ISSUE TITLE
Browse results contain withdrawn/private Items for admin users

### ISSUE THREAD

**Issue by ybnd** [DSpace/DSpace#8610]
**Describe the bug**
Withdrawn/private Items are shown in browse when logged in as a (comm/coll) admin.

**To Reproduce**
1. Log in as an admin user
2. Find or set up a Collection with at least one withdrawn/private Item
3. Browse the Collection
   * The withdrawn/private Item will be visible

**Expected behavior**
Withdrawn/private Items should only be shown in administrative search, even for admin users.

**Proposed approach**
The same issue was recently reported for search, and it was fixed by adjusting the discovery configurations.
We should adjust `BrowseEngine` & related classes to include the filter queries from the Community/Collection's configuration so that browse results match up with search results again.

**Related work**
#8479
#8488

**Comment by ybnd** [comment]
@tdonohue Atmire would like to claim this issue; it should take about **8h** to fix

**Comment by tdonohue** [comment]
@ybnd : Sounds good, thanks!  I'll pull this over to the 7.5 board and add the estimate.  Feel free to work on it for 7.5
