### ISSUE TITLE
Request a Copy's "helpdesk" strategy requires authentication to respond

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#8636]
**Describe the bug**
Discovered while testing #8319 

In DSpace 6, selecting the "helpdesk" strategy for Request a Copy allowed anyone receiving the helpdesk email to respond to the request _without authenticating into DSpace._  This is currently not possible in DSpace 7.

**To Reproduce**
1. Activate request a copy with Helpdesk Strategy: https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-(Optional)RequestingacopywithHelpDeskworkflow
2. As anonymous user, look at an embargoed item, click on the file to display the request a copy form.
3. Complete and send the request a copy form
4. As helpdesk staff, look at the email inbox
5. Open the Request a copy email and click on the link to respond to it.
6. **You are now required to login to DSpace** in order to respond.  Previously this was available anonymously.
7. After logging in, you can approve or decline the request.

**Expected behavior**
You should be able to approve or deny the request without authenticating.  The link sent to the helpdesk staff includes a unique token which is all that is necessary to respond to the request.

**Related work**
Related to #8319 and originally reported in #8304

**Comment by tdonohue** [comment]
@arvoConsultores has asked to claim this ticket. Assigned to their team.

**Comment by aroman-arvo** [comment]
The last tests I've done seem to have no problems with that simple fix. Can someone check with a large number of bitstreams?
