### ISSUE TITLE
Options for submission through Community, Collection not found

### ISSUE THREAD

**Issue by zeekreey** [DSpace/DSpace#8637]
![image](https://user-images.githubusercontent.com/122846321/212795691-07f9275a-c925-4d6c-b6f0-5874c6acf1b3.png)
![image](https://user-images.githubusercontent.com/122846321/212795764-0eec397c-d21c-490a-8e3e-b16d5cd87ba9.png)

Hi! I'm a first time user for dspace software. I have a problem. How can I configure a user so that they can submit their item in collection or community like in administrator account? It appears that a non-admin user has no list of options for "Community" and "Collection".

**Comment by tdonohue** [comment]
@zeekreey : Those Community/Collection options only exist if you have the permissions to *Create* (New menu) or Edit (Edit menu) the Community/Collection itself. Those require that you have Admin or Community Admin or Collection Admin permissions.

Users with basic submit permissions will just see "New -> Item" as that can be used to submit (create) a new Item into a Collection which they have permissions to submit to.

For more details on using DSpace, see the "Learning DSpace" docs: https://wiki.lyrasis.org/display/DSDOC7x/Learning+DSpace (work in progress) and the "Using DSpace 7.4" webinar: https://wiki.lyrasis.org/display/DSPACE/2022-11+-+DSpace+7.4+Webinar+Series

Closing this as answered. Behavior seems correct.  If you have further questions please use one of our Support options: https://wiki.lyrasis.org/display/DSPACE/Support
