### ISSUE TITLE
Requesting a copy causes item to be undeletable

### ISSUE THREAD

**Issue by Raf-atmire** [DSpace/DSpace#8654]
**Describe the bug**
If we have an item with one or more Bitstreams that are under embargo for which an EPerson has done a "Request a Copy" call, that item will not be deletable as an entry is created in the RequestItem table which won't be deleted on item deletion, causing a Foreign Key Constraint exception to be thrown as can be seen hereunder
`org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ ERROR: update or delete on table "item" violates foreign key constraint "requestitem_item_id_fkey" on table "reques
titem"
  Detail: Key (uuid)=(a1d0b513-749f-43cc-acbf-83eebf218b10) is still referenced from table "requestitem".`

**To Reproduce**
1. Create an Item in the Repository
2. Add a bitstream to this Item, making sure it's under embargo
3. As an anonymous user, request a copy of this bitstream
4. Try to delete this item as the admin user
5. Verify that the error is thrown & that the item is not deleted

**Expected behavior**
The item should be deleted

Atmire would like to claim the work to fix this & it should require 4 hours of dev work including a test

**Comment by mwoodiupui** [comment]
Suggestions:
1. The copy request should be updated to set the Item reference to NULL.  IIRC we seem to keep historical requests which have been resolved.
2. The requester and the request recipients should receive an email saying that the request was resolved by deleting the requested object.

**Comment by tdonohue** [comment]
@Raf-atmire : If you have time to quickly create a PR for 7.5, we can do our best to see if we can find a reviewer in time.  If the fix is large or complex though, it may need to wait for 7.6.  Either way, I'll assign to you and add the estimate.
