### ISSUE TITLE
SAF Import - Batch Import (ZIP) failure due to file size is not clear to end user

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8668]
**Describe the bug**

Not 100% sure if this report makes most sense for the REST back-end rather than Angular. Happy to create it in the other repo if needed.

The file size limit on SAF imports is currently capped by the configuration in application.properties for spring boot spring.servlet.multipart.max-file-size.

When you upload a file that is too large through the UI, the back-end logs almost immediately recognize that the file is too big, WAY before completion of upload of the entire file:

`2023-02-15 17:29:40,145 WARN  ebb7e429-c0c5-4cae-82e1-598d89b0d02b ee126068-ad06-4513-9b22-9c0fb11037d8 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Request is invalid or incorrect (status:400 exception: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (814735869) exceeds the configured maximum (536870912) at: org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:122))
2023-02-15 17:29:40,147 WARN  unknown unknown org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Request is invalid or incorrect (status:400 exception: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (814735869) exceeds the configured maximum (536870912) at: org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.handleParseFailure(StandardMultipartHttpServletRequest.java:122))`

However, as a user in the UI you are waiting very long and only get a generic HTTP error 400. Even in Inspect/developer tools I wasn't able to find a message that the cause was that the file was too big.

It might be cleaner if the backend returns an HTTP 413 instead.

**To Reproduce**
1. Go to /admin/batch-import
2. Upload a SAF file larger than 512MB

**Observed behavior**
The request takes a long time to time out, and results in a generic HTTP 400.

**Expected behavior**
You should get an error warning that the file you're trying to submit, is failing because it is too large.

**Related work**
Link to any related tickets or PRs here.

**Comment by mwoodiupui** [comment]
I second the motion to return 413, which actually tells the user what was done wrong.  We have too many cases of 400/500 "Something is not right.  Try to guess what it is."  We have too many cases of the front end patiently awaiting a success response that is never coming.

**Comment by tdonohue** [comment]
This makes sense to me. It might require a fix to both the backend (to return better error code) and frontend (to deal with the error).  Pulling this over to 7.6 board, as this could go into that release if we can locate an interested volunteer.
