### ISSUE TITLE
Reset Password from Admin UI does not work in latest 7.5-snapshot

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#8670]
**Describe the bug**
Reset Password from Admin UI does not work and throws an error in UI and a warning in the log in latest 7.5-snapshot

**To Reproduce**
1. Log in as admin
2. Select any Eperson from Access Control > People
3. Press "Reset Password" button
4. No password reset email is sent
5. You see this banner: 
<img width="1178" alt="Screenshot 2023-02-16 at 15 28 22" src="https://user-images.githubusercontent.com/8408850/219394984-b4b487ec-f2ae-48c6-a7ed-e3f25bd2bbec.png">

6. On the backend, you see the following log message:
```2023-02-16 15:27:24,573 WARN  d4005e72-77df-4db1-9201-d9f6efe803e0 c18ca03b-74e5-442c-a981-0f3eb76c2750 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ Request is invalid or incorrect (status:400 exception: Needs query param 'accountRequestType' with value forgot or register indicating what kind of registration request it is at: org.dspace.app.rest.repository.RegistrationRestRepository.createAndReturn(RegistrationRestRepository.java:120))```

**Comment by MW3000** [comment]
You can observe the frontend error on the demo site too

**Comment by mwoodiupui** [comment]
This may actually be a dspace-angular issue.  Probably the frontend should be sending `accountRequestType=forgot`.
