### ISSUE TITLE
Unexpected error with IPAuthentication and enabled debug

### ISSUE THREAD

**Issue by kosarko** [DSpace/DSpace#8671]
**Describe the bug**
There was an unexpected error (type=Internal Server Error, status=500).
Cannot invoke "java.lang.Boolean.toString()" because "org.dspace.authenticate.IPAuthentication.useProxies" is null

useProxies (https://github.com/DSpace/DSpace/blob/b2d64c52e4e7bf93f2951437ef2adbac5a9fbadd/dspace-api/src/main/java/org/dspace/authenticate/IPAuthentication.java#L58) is never initialized but is called from https://github.com/DSpace/DSpace/blob/b2d64c52e4e7bf93f2951437ef2adbac5a9fbadd/dspace-api/src/main/java/org/dspace/authenticate/IPAuthentication.java#L253 

I'm running 7.2 at the moment but there seem to be no changes in the later versions

**To Reproduce**
1. Have `plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.IPAuthentication` among auth methods
2. set log level to debug on that class (or the whole package) like this:
```
+
+        <!-- AUTH is the name of the appender for the Authentication classes -->
+        <Appender name='AUTH'
+                  filePattern="${log.dir}/authentication.log-%d{yyyy-MM-dd}"
+                  type='RollingFile'
+                  fileName='${log.dir}/authentication.log'>
+            <Layout type='PatternLayout'
+                    pattern='%d %-5p %equals{%X{correlationID}}{}{unknown} %equals{%X{requestID}}{}{unknown} %c @ %m%n'/>
+            <policies>
+                <policy type='TimeBasedTriggeringPolicy'>yyyy-MM-dd</policy>
+           </policies>
+           <!-- TODO MaxLogs=0 -->
+        </Appender>
+
+
     </Appenders>

     <Loggers>

+        <Logger name='org.dspace.authenticate'
+                level='DEBUG'
+                additivity='false'>
+                <AppenderRef ref='AUTH'/>
+        </Logger>
+
+
```
3. access /api

**Expected behavior**
Should not get 500

**Comment by tdonohue** [comment]
It looks like this was accidentally caused by #2207, which removed the usages of `useProxies` from IPAuthentication, but didn't remove the variable or the info from that log.debug().

I think the fix here is to simply remove `useProxies` variable and all usages.  It shouldn't be in this class anymore.

Needs a volunteer & it's likely a simple fix.
