### ISSUE TITLE
Combine multiple import sources (Crossref + DataCite -> DOI)

### ISSUE THREAD

**Issue by philipprumpf** [DSpace/DSpace#8674]
**Is your feature request related to a problem? Please describe.**
Users generally don't know which source (DataCite or Crossref) to use for DOIs. Similar concerns apply to ISBNs (#8673).

(Sorry if we've missed a more obvious way of doing this...)

**Describe the solution you'd like**
It would be nice if we could enter a DOI and retrieve results from all potentially relevant sources.

**Describe alternatives or workarounds you've considered**
* asking the user to try both providers: not workable for more than two or three sources/identifier
* querying all sources (rather than the relevant ones): false positives, DoS

**Additional context**
* we have some code for the DOI case, but (as usual) it needs work

**Comment by philipprumpf** [comment]
We've opened this in DSpace/DSpace rather than DSpace/dspace-angular since this is where our code lives.

**Comment by tdonohue** [comment]
This also seems generally useful but may not be highest priority for the main team. So, it needs a volunteer to help move forward.

**Comment by pnbecker** [comment]
It is useful for a lot of sources. Imagine loading data about persons from central identity management and from ORCID. For the DOI case I think an API exists that you can query to get to know which registration agency was used for the DOI (DataCite, CrossRef or something else). This could be used for a DOI specific solution. Saying this, I would prefer a general solution over a DOI specific one.

**Comment by abollini** [comment]
in previous version of DSpace-CRIS (5/6) we have followed the approach to query all the providers that potentially are able to respond to a query and combine they results together. In DSpace/DSpace-CRIS 7 this approach was loss due to the transition from BTE to the live import framework. That said, from our experience in version 5 try to query all the providers and combine the result would not work well. The performance will suffer a lot, real pagination will become impossible and "combine" results would be not trivial.
My suggestion is to keep each provider independent and solve the issue of Datacite DOIs lookup writing a dedicated provider using their API. Only for automatic metadata extraction, feature not enabled by default in DSpace but only in DSpace-CRIS, based on the addition of a DOI to an existing inprogress submission it is possible to write a DOIGenericProvider that would make use of the Content-Negotiation header over the DOI URI instead than an agency specific API https://citation.crosscite.org/docs.html
as far as I know all the major DOI registration agency support it (CrossRef, Datacite, Medra)

**Comment by philipprumpf** [comment]
I believe there are two similar but distinct issues here: what we want to do is to query multiple sources (DataCite, Crossref) and represent their individual entries in a single list; what @abollini and @pnbecker describe sounds more like combining several entries by enrichment, which used to be the case in DSpace-CRIS 5.x.

About the first issue (multiple sources, entries derive strictly from a single source)
I think it's unrealistic to expect users to know their DOI registrar or which source for an ISBN is best.

Note that for our installation, we specifically ask for a DOI to query; we don't support keywords or free text searches for the DOI registries (pinging @johannastaudinger here as she's the one implementing that). Thus we don't have many results; pagination isn't really a concern for us at present, and performance problems aren't (as) noticeable.

So for us the user's workflow is to decide which "identifier namespace" to search in, then paste the identifier into the correct field and search for it using all applicable external sources:

![image](https://user-images.githubusercontent.com/42467687/223109146-6e35ef3a-c8dd-486c-b245-3614319581ba.png)

This is quite different from the demo installation, where users are asked to specify the external source in question:

![image](https://user-images.githubusercontent.com/42467687/223109693-a6f10413-c373-4cd7-9394-e97b4e64d5d0.png)

Of course, any changes would be subject to configuration and optional. Each installation would be free to choose which workflow to offer to users.

As far as the second issue (enriching entries from several sources), we think that's going to be very difficult. Maybe we could generate a temporary-but-somewhat-persistent list of enriched entries, somewhat similar to #8469 ?

**Comment by tdonohue** [comment]
@philipprumpf : I like that [improved design](https://github.com/DSpace/DSpace/issues/8674#issuecomment-1456063365) (searching by field: DOI, ISBN, ORCID), for the initial import process. 

It's somewhat similar to the import that is possible from the Submission Form when you are creating a new Entity. e.g. the Publication Form lets you search for Authors via their name or ORCID across several resources (in this case just ORCID and local data, but others could be easily added) via a tabbed interface.  See this screenshot:
![search-multiple-tabs](https://user-images.githubusercontent.com/483997/223207312-d5ab9131-51e3-4363-994a-a443afa6fd58.png)

Overall, I agree that your idea would make this import interface more "user friendly".  However, I do suspect this redesign may require some refactoring of the REST API (or adding some new endpoints) to support this interface.  Therefore, I think this would not be possible to add into DSpace until v8 (at the earliest).  That said, we do hope to start v8 work hopefully by mid-2023, so this discussion may be well timed.

I also agree that we need to keep this *separate* from any work to *merge* information from multiple sources.  It sounds like this initial work is just about making it easier to **perform the same search across multiple sources** (and it could even be via a tabbed interface like shown above)  **and then import from a single source**.

**Comment by philipprumpf** [comment]
I've reopened a part of this PR as #9132 .
