### ISSUE TITLE
grunt 1.6.x requires Node.js v16

### ISSUE THREAD

**Issue by alanorth** [DSpace/DSpace#8676]
**Describe the bug**
The Mirage 2 theme in DSpace 6.x relies on grunt to run tasks during the frontend build. A few weeks ago [grunt was updated 1.6.0](https://github.com/gruntjs/grunt/blob/HEAD/CHANGELOG#L6), which requires Node.js v16. This breaks the build because Mirage 2 is limited to Node.js v14:

```console
error grunt@1.6.1: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.21.2"
```

DSpace 6 is nearing end of life, but the solution is to pin grunt to version 1.5.x using the `~1.5.3` semver specifier in `dspace-xmlui-mirage2/src/main/webapp/package.json`.

**Comment by tdonohue** [comment]
@alanorth : If you wanted to provide a quick fix, we could patch this in `dspace-6_x` for now & perhaps cut one last (**small, important fixes only**) 6.x release prior to EOL.

That said, if it's not a priority for you, that's perfectly OK as well.  This ticket provides enough clues for anyone to patch this themselves if they are impacted.

**Comment by alanorth** [comment]
Easy fix, done! https://github.com/DSpace/DSpace/pull/8677

**Comment by alanorth** [comment]
Closing as DSpace 6.x is no longer supported. Anyone facing this issue can see how to resolve it here anyway.
