### ISSUE TITLE
Submission form fields of item-type:list do not respect type-bind elements - they will always display when depositing a new item to DSpace 7.5

### ISSUE THREAD

**Issue by peter975** [DSpace/DSpace#8678]
**Describe the bug**
When submission-forms.xml includes a element with an input-type of list and a type-bind element, the list field will always display when depositing a new item even if the user chooses a Type not defined in the type-bind element.

**To Reproduce**
1. Define a submission-forms.xml that includes a field that passes values to dc.type (ie allows the submitter to choose a Type of item)
2. Define a matching value pairs for the field in step 1.
3. Add a further two elements: onebox and list input-types. Bind the onebox to a type defined in step 2, bind the list to a different type defined in step 2.
4. Submit a new item. In the Type field defined in step one, change the type of item being submitted.
5. Any field with a type-bind of list will always display even if they do not match the type selected by the user.

**Expected behavior**
The only fields visible in the submission interface should either have a type-bind that match the type selected by the user or have no type-bind selected. When a user switches between types, all non-matching fields should no longer display.

**Comment by mirkoscherf** [comment]
@peter975 Did the problem occur for checkbox lists (repeatable=true) **and** radio-button lists (repeatable=false) or only for one of them?
