### ISSUE TITLE
HAL Browser links ingoring subpath

### ISSUE THREAD

**Issue by deusilva** [DSpace/DSpace#8689]
**Describe the bug**
I am deploying both DSpace 7.4 backend at dspace.domain.br/server and the frontend at dspace.domain.br/app. 
I use NGinx as reverse proxy. Here is the NGinx configuration:

![image](https://user-images.githubusercontent.com/55598888/222135869-c8a8fca0-c5b1-4b14-9d19-8f6b9da644bc.png)

The HAL Browser show endpoins and it seems OK.
![image](https://user-images.githubusercontent.com/55598888/222133161-f3aec192-db7e-41c5-8d9c-13423b574410.png)

But if you go any endpoint with _links like **statistics** or **collections**, the generated links ignores "/server". It returns like https://dspace.domain.br/api/core/collections.
![image](https://user-images.githubusercontent.com/55598888/222133367-ef71cdb7-3f47-4c63-8f60-b5c37b737c06.png)

This is the environment on backend and frontend respectively:
![image](https://user-images.githubusercontent.com/55598888/222134840-401763f1-e479-4324-a361-d21f5962cdb6.png)
![image](https://user-images.githubusercontent.com/55598888/222134652-06a9bc1b-c013-4faa-b0ab-7702d81cc2b8.png)

Why DSpace its not using the complete dspace.server.url on the other endpoints?
What am i could doing wrong?

**To Reproduce**
1. Deploy the backend and frontend in same domain but in different subpaths

**Expected behavior**
Should keep using the complete dspace.server.url configured like https://dspace.domain.br/server

**Comment by tdonohue** [comment]
@deusilva : This works fine on our demo site backend which is running at https://api7.dspace.org/server (We've had this same setup for a long time, so it has worked from 7.0-7.5)

This makes me wonder if either your configuration or Nginx proxy is to blame for the changes in URL?

Simply put, I cannot reproduce this locally or on our demo site, so I don't think it's a bug in DSpace itself.  DSpace The configurations you shared look correct at a glance... so maybe Nginx is doing something unexpected here & causing the `/server` to be dropped?  As you showed in the HAL Browser (first image) the "_links" section seems to have correct URLs (look at the URLs on the right hand side of that image).  Those URLs are what will be called when you click a button in the HAL Browser.

**Comment by deusilva** [comment]
@tdonohue Thanks in advance for the rapid response.

Exactly. In the main page of HAL Browser, everything is working fine. The others pages don't.

But, i figured out the problem. Its now working. I will document below my solution. Hope this could help someone in similar situation.

1. Debbuging the NGinx, `$1` was returning `api/core/collection` for example. `/server` was missing but the $request_uri was correct like `/server/api/core/collections` So, i changed the proxy_pass of `/server` location in NGinx from `proxy_pass http://dspace:8080/$1$is_args$query_string;` to `proxy_pass http://dspace:8080$request_uri$is_args$query_string`; Now the backend receives the complete uri `/server/api/core/collections`.
2. I was deploying the backend on context's directory `/ROOT` of tomcat. I changed now to deploy into `/server` directory to match the `/server` of my NGinx location. After all this, i think is not recommend to deploy backend into `/ROOT` if you are using subpath of a domain.

Additional notes:

- The Nginx have SSL certificate configured
- Both backend and frontend are deployed using docker containers with Dockerfiles created by me based the one you provided [here](https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+7#TryoutDSpace7-InstallviaDocker) and [here](https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+7#TryoutDSpace7-InstallviaDocker) making the required changes for production. `dspace`is the backend container and `dspace-ui` is the frontend container.

If anyone needs more information about my context, i am here to help.

Thanks again for the support.
