### ISSUE TITLE
The VersionedHandleIdentifierProviderWithCanonicalHandles doesn't work as advertised

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#8691]
**Describe the bug**

When it comes to versioning and handles there are two views on how handles should behave, these are detailed below.

_Handles always linked to a specific version_

The first one (that is the default) states that a handle once created should always link to a specific version. If our original item has handle: "123456789/10" then a subsequent version would have "123456789/10.1" as handle, the one after that "123456789/10.2" and so forth.

_Handles always link to the latest version of an item_

This was the default up until DSpace 6 but is still available as an optional configuration (documented [here](https://wiki.lyrasis.org/display/DSDOC6x/Item+Level+Versioning#ItemLevelVersioning-Importantwarnings-readbeforeenabling)). If we take the example from above then if we create a first version out of our item the following handles would be allocated:

* Item 1: 123456789/10.1
* Item 2: 123456789/10 AND 123456789/10.2

When a third version would be created the handle "123456789/10" would move to that version, ...

This is current broken & the VersionedHandleIdentifierProviderWithCanonicalHandles works in exactly the same manner as the original one.

**To Reproduce**
1. Enable the VersionedHandleIdentifierProviderWithCanonicalHandles
2. Create a new version of an item
3. Check the handles that are allocated, it will be exactly the same as without the VersionedHandleIdentifierProviderWithCanonicalHandles bean enabled

**Expected behavior**
The behavior is described above.

**Related work**
Link to any related tickets or PRs here.

**Comment by KevinVdV** [comment]
We are interested in fixing this bug & creating IT's to prove it has been fixed.

We think we need 15 hours to properly fix it.

**Comment by tdonohue** [comment]
@KevinVdV : Sounds good, I'll assign this back to you then and add to the 7.6 board.  Thanks!
