### ISSUE TITLE
Metadata field IDs selected wrongly

### ISSUE THREAD

**Issue by furkanakkurt1335** [DSpace/DSpace#8704]
**Describe the bug**
We have deployed DSpace 7.5 at https://tulap.cmpe.boun.edu.tr/dspace/home . Creation of metadata fields has been problematic. Going through the logs, I realized the system tries to create a metadata field record with record IDs already existent. In our version, we have 260 metadata fields from the start. When I realized the problem, it was trying to give record IDs of 200~. I realized the IDs the system tried to give increased for every attempt. I attempted to create new metadata fields just so the IDs would increase to the point of passing all the metadata field IDs (260). After dozens of attempts, the system came to the ID 261 and it was successful. I hope this is helpful. You can ask me to elaborate on any part.

**To Reproduce**
1. Deploy DSpace 7.5
2. Create a metadata field, either by UI or API

**Expected behavior**
I expected the metadata field to be created.

**Comment by mwoodiupui** [comment]
That sounds as though the database SEQUENCE value `metadatafieldregistry_seq`
was not consistent with the actual content of the `metadatafieldregistry`
table.  I don't know how that might have happened.

`select max(metadata_field_id) from metadatafieldregistry;` will tell
you what the highest used sequence value is.  `select last_value from
metadatafieldregistry_seq` will tell you the most recent value of the
sequence.

I'm feeling cautious about advising how to set the sequence's next
value but I'm sure there's a more convenient way than advancing it one
value at a time.

**Comment by tdonohue** [comment]
@furkanakkurt1335 : As @mwoodiupui notes, It does sound like the database sequences were just outdated.  You could run `./dspace database update-sequences` to correct that.

I don't believe this is a bug, as it sounds like a data error that could have been corrected by running `./dspace database update-sequences`

**Comment by furkanakkurt1335** [comment]
Thank you two for your responses. I will try to solve this by updating the database. I still wonder how that happened though.

**Comment by tdonohue** [comment]
@furkanakkurt1335 : Database sequences can sometimes get out of sync after any restore from backup or AIP restoration (using https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore).  That is why the `./dspace database update-sequences` tool exists .. and it's documented that you should run it after any major restore from backup.

So, my best guess is that at some point data was restored or moved around from one DSpace to another via AIP or just a traditional backup.  That may have caused the sequences to get out of sync.

**Comment by furkanakkurt1335** [comment]
Thank you again for the swift response!  🙏

I'm closing the issue.
