### ISSUE TITLE
The search of deleted bitstreams during cleanup should be paginated

### ISSUE THREAD

**Issue by LucaGiamminonni** [DSpace/DSpace#8708]
The script to cleanup deleted bitstream use a find method that is not paginated and this can create memory leaks if there are many deleted bitstreams that need to be cleaned up (for example after a massive delete).

The method that perform this cleanup is
https://github.com/DSpace/DSpace/blob/b956bcd3891e372cc0fe5b1595e422e5d059bced/dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java#L225

The query currently used to extract bitstreams should be modified to add pagination.

**Comment by corrad82-4s** [comment]
Hello @tdonohue , you can assign this to 4Science. Thank you
