### ISSUE TITLE
update-sequences incomplete

### ISSUE THREAD

**Issue by aroman-arvo** [DSpace/DSpace#8719]
**Describe the bug**
update-sequences.sql don't updates all sequences. 
At least doi_seq is missing
It affects dspace 6.4 & 7.x

**To Reproduce**
Check update-sequences.sql against database structure.

**Expected behavior**
All sequences should be updated to last used value.

**Comment by tdonohue** [comment]
@arvoConsultores has asked to claim this ticket. Assigned to their team.

**Comment by aroman-arvo** [comment]
We have updated (and ordered) update-sequences with missing sequences.
history_seq is no longer used, also we created a sql to delete it.
Its only made to postgres at Dspace7, because Oracle support will end with next version.
Missing sequence updates at Dspace7:

alert_id_seq
checksum_history_check_id_seq
cwf_claimtask_seq
cwf_collectionrole_seq
cwf_in_progress_user_seq
cwf_pooltask_seq
cwf_workflowitem_seq
cwf_workflowitemrole_seq
doi_seq
entity_type_id_seq
openurltracker_seq
orcid_history_id_seq
orcid_queue_id_seq
orcid_token_id_seq
process_id_seq
relationship_id_seq
relationship_type_id_seq
subscription_parameter_seq
supervision_orders_seq
versionhistory_seq
versionitem_seq
