### ISSUE TITLE
net.handle:handle:jar:9.3.0 is missing

### ISSUE THREAD

**Issue by zhaojp0411** [DSpace/DSpace#8720]
**Describe the bug**
I pull master to local and use mvn compile but  report "[WARNING] The POM for net.handle:handle:jar:9.3.0 is missing, no dependency information available " ,
I can't find the net.handle:handle:jar:9.3.0 in center repo  but net.handle:handle-client:jar:9.3.0 
where is bug , how to fix it

**Comment by tdonohue** [comment]
Closing, not reproducible. This should be moved to one of our Support options if the issue still exists: https://wiki.lyrasis.org/display/DSPACE/Support

The Handle.jar version 9.3.0 should be automatically downloaded via our Maven configuration (when you run `mvn package` or similar).  It's available here https://handle.net/maven/net/handle/handle/ , but the settings in our main pom.xml should autodownload it as we have that location listed as a Maven repository: https://github.com/DSpace/DSpace/blob/main/pom.xml#L1971-L1974

If you are still having issues, use one of the support options above to ask for help.
