### ISSUE TITLE
Orcid queue cannot handle long title

### ISSUE THREAD

**Issue by floriangantner** [DSpace/DSpace#8730]
**Describe the bug**
Orcid queue entries cannot be created if their description is longer than 255 characters.

We have seen this issue on DSpace-Cris (2022.03.00 / 7.4), but it should also be reproducable on DSpace because the ported code has not changed at the relevant lines of code. 

**To Reproduce**
1. ensure that orcidqueue consumer and orcid sync are active in the configuration.
2. select some item A which is related with some person B that got some authenticated orcid and the orcid sync enabled
4. edit this item A dc.title and use some text longer than 255 characters.
3. The orcid queue consumer is triggered and some orcidqueue entry for person B with item A should be generated. This new entry will use the item A metadata dc.title as the description [(see OrcidQueueServiceImpl)](https://github.com/DSpace/DSpace/blob/b956bcd3891e372cc0fe5b1595e422e5d059bced/dspace-api/src/main/java/org/dspace/orcid/service/impl/OrcidQueueServiceImpl.java#L99) and at this point... 
4. ... the consumer is interrupted by some SQLError that can be found in the logs
 ```
2023-03-20 15:35:05,250 ERROR unknown unknown org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ Batch entry 0 insert into public.orcid_queue (attempts, description, entity_id, metadata, operation, owner_id, put_code, record_type, id) values (0, 'Desbois, Patrick, In broad daylight: the secret procedures behind the Holocaust by bullets / Father Patrick Desbois, with a historical introduction by Andrej Umansky, translated from the French by Hilary Reyl and Calvert Barksdale. First paperback edition: New York, 2021', '<anonymized>'::uuid, NULL, 'UPDATE', '<anonymized>'::uuid, '<anonymized>', 'Publication', 1) was aborted: ERROR: value too long for type character varying(255)  Call getNextException to see other errors in the batch.
2023-03-20 15:35:05,250 ERROR unknown unknown org.hibernate.engine.jdbc.spi.SqlExceptionHelper @ ERROR: value too long for type character varying(255)
```

**Expected behavior**
We expect the orcid queue entry to be generated sucessfully.

**Related work**
The description is only shown on the orcid registry queue to the orcid owner. Some description with 255 characters should in most cases be enough information for the orcid owner to distinguish the entries in the registry queue. We suggest that the [OrcidQueueServiceImpl](https://github.com/DSpace/DSpace/blob/b956bcd3891e372cc0fe5b1595e422e5d059bced/dspace-api/src/main/java/org/dspace/orcid/service/impl/OrcidQueueServiceImpl.java#L99), in case the metadatavalue for dc.title is longer than 255 characters, shorten the metadatavalue at position 252 and add three dots to the end.

Another approach could be to change the database schema for [Orcid queue table](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.3_2022.04.29__orcid_queue_and_history.sql ) to text.

**Comment by tdonohue** [comment]
Definitely sounds like a bug.  I have a slight preference for the approach to change the database schema `orcid_queue.description` field to be `TEXT` instead of `CHARACTER VARYING(255)`.  That seems like a relatively simple change, though it will require a new Flyway migration.

In any case, this requires a volunteer to move forward.  I'll move it tentatively to 7.6 board in the hopes that someone volunteers.

**Comment by hutattedonmyarm** [comment]
We, Universität Konstanz, can confirm that we also have this issue in vanilla DSpace 7.4. As a workaround we changed the column type to `TEXT` in both `orcid_queue` and `orcid_history` which did indeed fix the issue.

We'd also be willing to create the necessary migration

**Comment by tdonohue** [comment]
@hutattedonmyarm : If you are willing to contribute your change back via a PR, it'd be very welcome.  I would do my best to ensure it gets into the upcoming 7.6 release.
