### ISSUE TITLE
Default filter always applies in Register DOI via Item status page in UI

### ISSUE THREAD

**Issue by amgciadev** [DSpace/DSpace#8732]
**Describe the bug**
It was my understanding that the functionality of registering doi via the item status page should always bypass any default filter defiened in the DOIIdentifierProvider bean (identifier-service.xml config) by applying the TrueFilter.

I am seeing something very odd when trying this functionality and looking at the logs (I have added some additional logging). It looks like Truefilter is being checked twice, and an additional check is run that uses the default filter:

```
Before request [POST /server/api/pid/identifiers] originated from /items/69a962a1-0af5-4323-94f2-646fd500d8c5/edit/register-doi
org.dspace.identifier.DOIIdentifierProvider @ Check filter: class org.dspace.content.logic.TrueFilter

org.dspace.identifier.DOIIdentifierProvider @ Result of filter for 1810/347135 is true
...
org.dspace.identifier.DOIIdentifierProvider @ Check filter: class org.dspace.content.logic.TrueFilter

org.dspace.identifier.DOIIdentifierProvider @ Result of filter for 1810/347135 is true

org.dspace.identifier.DOIIdentifierProvider @ Check filter: class org.dspace.content.logic.DefaultFilter

org.dspace.content.logic.condition.IsArchivedCondition @ Result of isArchived is true

org.dspace.content.logic.condition.IsWithdrawnCondition @ Result of isWithdrawn is false

org.dspace.content.logic.condition.InCollectionCondition @ item 1810/347135 is in collection 1810/294790, returning true

org.dspace.identifier.DOIIdentifierProvider @ Result of filter for 1810/347135 is false

org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:500)

java.lang.IllegalStateException: Failed to register identifier: null
	at org.dspace.app.rest.repository.IdentifierRestRepository.registerDOI(IdentifierRestRepository.java:248)
```

In the UI, I get the error message banner twice, and I can see two API calls in the developer tools. Is the method somehow being called multiple times?

**To Reproduce**
1. Log in as admin and choose an archived item without a DOI
2. Go to Edit item > Item status
3. Click on Register DOI
4. Confirm DOI registration

**Expected behavior**
The registration always takes place, bypassing any default identifier filters

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Pinging @kshepherd as this sounds like it might be related to #8423 added in 7.5?

In any case, I'll pull this over to the 7.6 board to see if we can find a volunteer.

**Comment by amgciadev** [comment]
I've tried hard to pin it down in the backend code with no success yet :( I'll keep trying whenever I get time - difficult with our upcoming upgrade though.

**Comment by kshepherd** [comment]
@amgciadev i'll try to reproduce this - one note i have already is that DefaultFilter in your example is returning 'true' the second time... but the provider is interpreting it as false somehow? You're right though, there should not by a DefaultFilter check - there may be multiple filter checks as the provider calls mint, then register, etc. but the intention was to force the DOI registration through all those checks

**Comment by amgciadev** [comment]
Thanks @kshepherd! Re the filter returning true, e.g. item 1810/347135 is in collection 1810/294790, returning true, the filter has a not filter on top of that condition, which explains that the first filter is true (item in that collection) but the actual filter is not in collection, which explains the final false returned by the provider

**Comment by amgciadev** [comment]
@kshepherd, @tdonohue  I don't know yet if this is related to the new identifiers functionality introduced in 7.5. but I am now getting an NPE when trying to register/reserve a DOI via the doi-organiser command line:

```
/home/dspace/dspace/bin/dspace doi-organiser --reserve-doi 1810/347187
Exception: null
java.lang.NullPointerException
	at org.dspace.identifier.doi.DOIOrganiser.reserve(DOIOrganiser.java:502)
	at org.dspace.identifier.doi.DOIOrganiser.reserve(DOIOrganiser.java:492)
	at org.dspace.identifier.doi.DOIOrganiser.runCLI(DOIOrganiser.java:310)
	at org.dspace.identifier.doi.DOIOrganiser.main(DOIOrganiser.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:277)
	at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:133)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
```
My setup is that I have disabled registration of DOIs in the workflow stage:  identifiers.submission.register=false

Can you help replicating?

**Comment by amgciadev** [comment]
I think I've tracked down the root of the problem for both issues reported here. I'll report later today.

**Comment by amgciadev** [comment]
https://github.com/DSpace/DSpace/blob/bdb88724ac8434956ec52dcdcb182f2d13e5edd5/dspace-api/src/main/java/org/dspace/identifier/VersionedDOIIdentifierProvider.java#L165 this is one of the places I've located that ignore the passed filter to the calling method.
