### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by santilococo** [DSpace/DSpace#8741]
**Describe the bug**
For some reason, after a few months of perfect operation and use, the backend responds very slowly. This is giving a 504 error on the frontend. Sometimes it will work fine, but most of the time it will respond very slowly. For example, `time curl -L localhost:8080/server/api/core/communities` is 1m or more, rendering the page unusable.

The database (`postgres`) and `solr` work fine. There are no health warnings of any kind. Also, there don't seem to be any errors in the `dspace` logs.

Do you know how I can debug this?

I am running DSpace 7.3.

**Comment by tdonohue** [comment]
@santilococo : I'd recommend following our Troubleshooting Guide to look for other errors being reported in DSpace, Tomcat, Postgres, Solr, etc. https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

As this sounds like an issue with your setup and not a specific bug in DSpace, I'd also recommend using one of our Support options listed at https://wiki.lyrasis.org/display/DSPACE/Support  It's possible others on our dspace-tech (Tech Support) list may have more specific advice, if you provide more details about your setup, etc.

Flagging as "cannot reproduce"

**Comment by santilococo** [comment]
Thanks Tim. 

I resolved the issue by running the database locally, as the connection to the cloud-based database (for some reason) was unreliable.
