### ISSUE TITLE
Live Import: Pubmed: Too aggressive querying from DSpace resulting in 429 Too many requests API responses

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8743]
**Describe the bug**
When you are doing live import lookup queries in Pubmed, for example through https://demo7.dspace.org/import-external?entity=Publication, you can get confronted with HTTP 500 errors in the UI.

This problem was raised earlier in https://github.com/DSpace/DSpace/issues/8327. At that point, an additional retry was implemented (more queries), which seemed to show that sometimes the requests did get through.

We found evidence in the REST logs that the underlying problem are too frequent requests to the Pubmed API, as we see the 429s in the REST log, for example:

`2023-03-24 10:00:20,740 ERROR b3dad3d1-c735-44a4-bc4b-d8e0dea6b0f9 575d4ff2-8830-4012-9777-7315dcc01058 org.dspace.importer.external.liveimportclient.service.LiveImportClientImpl @ The request failed with: 429 code, reason= Too Many Requests
java.lang.RuntimeException: The request failed with: 429 code, reason= Too Many Requests
        at org.dspace.importer.external.liveimportclient.service.LiveImportClientImpl.executeHttpGetRequest(LiveImportClientImpl.java:78)
`
We found that 2 API calls are made per page, when retrieving the external elements, a total elements call and a call to retrieve values.

There was already a variable in the code that will sleep the calls if the last request was too recent. But neither the last request nor the variable for minimum time between the resets seemed to be set.

**To Reproduce**
1. Perform lookups against the pubmed API using https://demo7.dspace.org/import-external?entity=Publication
2. After a while, you won't see any more search results, but an error instead.

**Expected behavior**
Pubmed lookups should consistently show results.

**Related work**
https://github.com/DSpace/DSpace/issues/8327

**Comment by bram-atmire** [comment]
Note to people who are trying to reproduce this: On a slow server or workstation, you might not be able to reproduce this.
But as soon as your server is fast enough, you will hit it guaranteed.

**Comment by tdonohue** [comment]
@YanaDePauw : Sounds good. Assigning to you then to work on for 7.6. Thanks!
