### ISSUE TITLE
DOI Provider: The VersionedDOIIdentifierProvider will check if the item level versioning is enabled

### ISSUE THREAD

**Issue by francescopioscognamiglio** [DSpace/DSpace#8748]
**Is your feature request related to a problem? Please describe.**
The [VersionedDOIIdentifierProvider](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/identifier/VersionedDOIIdentifierProvider.java) defined in [identifier-service.xml](https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/identifier-service.xml#L62-L69) does not check whether item level versioning is enabled.

**Describe the solution you'd like**
If the [VersionedDOIIdentifierProvider](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/identifier/VersionedDOIIdentifierProvider.java) is enabled, but the item level versioning is disabled, an exception will be thrown at startup.

**Comment by tdonohue** [comment]
Sounds like a bug. It sounds like it can be solved by correct configuration, but I agree this should result in exceptions at startup if possible.  Needs a volunteer
