### ISSUE TITLE
Metadata schema: using a period in metadata element name should be rejected

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8753]
**Describe the bug**

Right now, users can use periods as part of the metadata field element name when adding new metadata fields to the schema. 
This creates all sorts of problems and confusion all over, so the preferred route is likely to prevent periods from being used in the metadata field name.

![Screenshot 2023-03-30 at 08 20 03](https://user-images.githubusercontent.com/958314/228747877-608932f9-8f3f-4f0f-8205-8038418d31a4.png)

![Screenshot 2023-03-30 at 08 20 52](https://user-images.githubusercontent.com/958314/228747895-e459cfa9-ef4c-4f12-9b55-5142fc2f6a20.png)

**To Reproduce**
1. Add a new metadata field to the schema, where you use a period in the element name

**Expected behavior**
A validation error should be visible to the user, explaining that period is an illegal character that can't be used in a metadata field element name.

**Comment by tdonohue** [comment]
Seems reasonable to me as well that there should be some sort of verification here.  However, I believe we have **at least** one field with a dash (`-`) (`dspace.agreements.end-user`), so I think we need to allow for that character as well.  We should verify no other special characters are used.

Needs  a volunteer

**Comment by tdonohue** [comment]
Thanks @alexandrevryghem ! Assigning to you for 7.6 then.
