### ISSUE TITLE
Metadata Schema: Editing of existing metadata fields should be limited to Scope Note only

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8754]
**Describe the bug**

The following behaviour is currently in place in 7.5
- element can be edited
- qualifier can be edited
- if no qualifier is present, a new qualifier can be added on an existing field and successfully saved
- it is impossible to remove a qualifier. If you blank it out, angular will just send back the original value.

There are at least two reasons to think of why editing of existing fields in the metadata schema is problematic:
- Such a change will not be considered an item update, to the affected items that have a metadata value. However these items WILL look different in OAI (basically everywhere).
- There is no track record or provenance of what a metadata field used to be called.

Personally I think this is a gigantic can of worms that can be resolved and avoided by restricting metadata field editing capabilities on the schema's only to scope notes.

There is already deletion protection in place for metadata fields in the schema: they can only be deleted if they are not in use in any items. That, overall is very good !!!

Improved use case flows:

Replacing the use of one metadata field for another
- Create the new field
- Move all the metadata values from the old field to the new one
- Delete the old field

**To Reproduce**
1. Try to edit or remove a qualifier, or metadata field name from a field in the schema

**Expected behavior**
You shouldn't be able to do this, you should only be able to modify the scope note for a field.

**Related work**
Link to any related tickets or PRs here.

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this issue
