### ISSUE TITLE
DSpace 7.x and Postgresql 15.x

### ISSUE THREAD

**Issue by Leano1998** [DSpace/DSpace#8757]
I hope this is the right channel for this. 
We are currently developing multiple dspace-7 instances in docker-containers and successfully connected our DSpace-7.5 backend with a Postgresql-15.2 server (also running in docker). We didn't have to make additional changes to the backend to get it working. So, perhaps it might be possible to add Postgres 15.2 support in future DSpace-7.x releases. Has someone else found any issues or problems regarding DSpace 7.5 and Postgres-15.2?

**Is your feature request related to a problem? Please describe.**
DSpace 7.x currently doesn't officially support Postgres-15 as a database-server.

**Describe the solution you'd like**
We would like to include postgres-15.x support for future DSpace-7.x releases.

**Additional context**
The Server successfully started. We created a new docker-image including pgcrypto for our containers based on the official postgres-Docker image. Our database-migrations succeeded as well.

Kind regards,
Eike.

**Comment by tdonohue** [comment]
Thanks @Leano1998 for letting us know this works for you.  It sounds like we likely can add PostgreSQL 15 under support.  However, I'm going to leave this open for more feedback / testers to help verify.

**Comment by mwoodiupui** [comment]
I've been developing 7_x against PostgreSQL 15 since late March with no issues.

**Comment by tdonohue** [comment]
Thanks for the verification! I've updated our docs to list PostgreSQL v11 - 15 (which are all the currently supported versions of Postgres). https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-PostgreSQL11.x,12.x,13.x,14.xor15.x(withpgcryptoinstalled)

**Comment by tdonohue** [comment]
Closing as fixed. Docs were updates per above.
