### ISSUE TITLE
Error while uploading file

### ISSUE THREAD

**Issue by rosenisantos** [DSpace/DSpace#8760]
**Error while uploading file**

Good morning!
We are using Dspace 6.3, xmlui. After including 60 productions, it is showing an error, it does not accept bitstream upload. Do not participate in making any further submissions due to the error.
thanks!

**Related work**
Link to any related tickets or PRs here.
![2023-04-03_10h26_02](https://user-images.githubusercontent.com/129760337/229533051-9bc76ef2-bb41-4736-857f-c622b77bbdfd.png)

**Comment by tdonohue** [comment]
Please use one of our recommend Support options to get support for errors you are seeing in DSpace.  https://wiki.lyrasis.org/display/DSPACE/Support

You also should use our Troubleshooting guide to find the underlying error.  DSpace never shows the full error message in the user interface (as that can provide hints on possible vulnerabilities to hackers).  You must locate the error message in the DSpace logs to determine the cause of the error. https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error

Closing, as this is a support question & should be asked on support mailing lists or similar.
