### ISSUE TITLE
M1 Support issues

### ISSUE THREAD

**Issue by DonRichards** [DSpace/DSpace#8761]
**Describe the bug**
Following the instructions to build via docker, and I'm getting an error associated with incompatible images. I have an M1 (Mac), and this used to be a common issue when the hardware first came out, but it's pretty common for repositories to build for M1 chips now. Can M1s be added to the list of build images?

**To Reproduce**
1. Following instructions on https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+7#TryoutDSpace7-InstallboththeUserInterfaceandRESTAPIlocally
2. At this step it fails and/or gives a warning.
```shell
docker-compose -p d7 -f docker/docker-compose.yml -f docker/docker-compose-rest.yml up -d
 Network d7_dspacenet  Creating
 Network d7_dspacenet  Created
 Volume "d7_pgdata"  Creating
 Volume "d7_pgdata"  Created
 Volume "d7_solr_data"  Creating
 Volume "d7_solr_data"  Created
 Volume "d7_assetstore"  Creating
 Volume "d7_assetstore"  Created
 Volume "d7_solr_configs"  Creating
 Volume "d7_solr_configs"  Created
 Container dspace-angular  Creating
 Container dspacedb  Creating
 dspacedb The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 Container dspace-angular  Created
 Container dspacedb  Created
 Container dspace  Creating
 Container dspace  Created
 Container dspacesolr  Creating
 Container dspacesolr  Created
 Container dspacedb  Starting
 Container dspace-angular  Starting
 Container dspace-angular  Started
 Container dspacedb  Started
 Container dspace  Starting
 Container dspace  Started
 Container dspacesolr  Starting
 Container dspacesolr  Started
```

**Expected behavior**
For it to find a compatible image to build.
This should work but doesn't  http://localhost:4000/
This does actually work http://localhost:8080/server/

**Related work**
N/A

**Comment by DonRichards** [comment]
It "appears" that it finishes building if I run a restart afterward
`docker-compose -p d7 -f docker/docker-compose.yml -f docker/docker-compose-rest.yml up -d`

Is this normal?

**Comment by DonRichards** [comment]
I don't know if this helps but this is the end of the the logs output 
```log
dspace-angular  |
dspace-angular  |
dspace-angular  | ** Angular Live Development Server is listening on 0.0.0.0:4000, open your browser on http://localhost:4000/ **
dspace-angular  |
dspace-angular  |
dspace-angular  | ✔ Compiled successfully.
⠼ Generating browser application bundles (phase: building)...
dspace-angular  | <--- Last few GCs --->
dspace-angular  |
dspace-angular  | [53:0xffffb41af2f0]   142229 ms: Mark-sweep 2009.2 (2090.1) -> 1992.0 (2088.4) MB, 585.8 / 0.0 ms  (average mu = 0.220, current mu = 0.128) allocation failure; scavenge might not succeed
dspace-angular  | [53:0xffffb41af2f0]   142892 ms: Mark-sweep 2008.1 (2088.6) -> 1993.9 (2090.6) MB, 604.5 / 0.0 ms  (average mu = 0.159, current mu = 0.089) allocation failure; scavenge might not succeed
dspace-angular  |
dspace-angular  |
dspace-angular  | <--- JS stacktrace --->
dspace-angular  |
dspace-angular  | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Done in 149.22s.
dspace-angular exited with code 0
```

**Comment by tdonohue** [comment]
@DonRichards : I don't have a Mac to test with, but I do know that we added `linux/arm64` images last year in #8305 (Backend) and https://github.com/DSpace/dspace-angular/pull/1663 (Frontend) to support M1 Macs.

The final error you shared above almost sounds like your local machine has run out of memory when running the UI docker image.  This sounds like the same issues someone reported on our support mailing list: https://groups.google.com/g/dspace-tech/c/EUsIqrWA49M/m/OWY34XqKAAAJ  The fix they reported was to increase the memory from 2GB -> 4GB

So, I *believe* M1 support already exists... but it sounds like you need to allocate more memory to Docker in your local environment.

**Comment by DonRichards** [comment]
I switched docker's memory cap to 16GB with 8 cores but still get the same error

**Comment by hutattedonmyarm** [comment]
Looks to be related to: https://github.com/DSpace/dspace-angular/issues/2259 and might even be fixed here: https://github.com/DSpace/dspace-angular/commit/113703ff6b0e38186a34e88e2120737e137417b9

**Comment by tdonohue** [comment]
Closing from lack of activity.  This may already be solved, or might be the same as https://github.com/DSpace/dspace-angular/issues/2259
