### ISSUE TITLE
Use dspace.name config variable instead of hard coded string "DSpace" in email templates

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#8768]
**Describe the bug**
The welcome email already uses variable interpolation for the config var dspace.name instead of just stating "DSpace" over at:
https://github.com/DSpace/DSpace/blob/main/dspace/config/emails/welcome

The other email templates should follow this same approach, to ensure that upon initial installation, the occurences of the word "DSpace" shouldn't be replaced manually by the institution's preferred repository name.

**To Reproduce**
1. Look at the email templates in https://github.com/DSpace/DSpace/blob/main/dspace/config/emails/
2. Look for the word "DSpace" and the variable interpolation ```${config.get('dspace.name')}``` 

**Expected behavior**
You should only see the variable interpolation ```${config.get('dspace.name')}```  and no occurrences of the hard coded string "DSpace".

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this issue

**Comment by tdonohue** [comment]
Thanks @alexandrevryghem .  Assigning to you for 7.6 then.
