### ISSUE TITLE
Workspace items are loading too much information

### ISSUE THREAD

**Issue by YanaDePauw** [DSpace/DSpace#8791]
**Describe the bug**
In the submission process, a workspace item is requested with full projection. As a consequence a lot of unnecessary information is retrieved such as all of the submitter data, the collection with all its embedded objects, the item with all of its embedded objects. This drastically slows down the creation and loading of submission items when a lot of information is available. 

**To Reproduce**
* Set up a submitter with metadata
* Set up a collection with embedded objects such as a template item, related groups, a logo, ...
* Open the network tab, and run the angular app in dev mode so all requests are visible
* Start a new submission as the submitter in the aforementioned collection
* Verify that the created workspace items is retrieved using a full projection, and contains all the embedded objects such as the collection with its embeds, the full submitter data, ...

**Expected behavior**
Only the necessary information should be retrieved, not a full projection with all of the possible embeds.

**Comment by hutattedonmyarm** [comment]
Additionally, the submission definition is included as well, which isn't needed in the workspace

**Comment by tdonohue** [comment]
@YanaDePauw : thanks!  Assigning to you and pulling it over to the 7.6 board.
