### ISSUE TITLE
Discovery Default Sorting feature support

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#8837]
This is an usability issue that was reported to me by some people that use DSpace in a daily basis...

**Is your feature request related to a problem? Please describe.**
When the user signs in and goes to his mydspace area:
```
/mydspace?configuration=workspace
```
by default he sees every submission sorted from the first to the last entry. But he was expecting to see the most recent submission (last entry) at the top. So, he has two choices:
- perform a sorting action everytime he goes to his mydspace area
- or navigate through the pagination to the last page everytime he goes to his mydspace area

both requires him to do stuff. 
I don't use DSpace, but when I'm testing it, I feel the same. In MyDSpace I couldn't see the most recent item I've just created. So I had to navigate through every page in the pagination (because I didn't remember the title of the item to perform quicker text filter).

**Describe the solution you'd like**
Currently Discovery supports default settings like Results Per Page (rows number), Default querys. But doesn't support default sorting and it's a feature that makes totally sense. And this mydspace with a default sorting by date is the use case.

We could re-use an existing bean for default sorting
```
    <bean id="workspaceConfiguration"
        class="org.dspace.discovery.configuration.DiscoveryConfiguration"
        scope="prototype">
...
        <property name="searchSortConfiguration">
            <bean class="org.dspace.discovery.configuration.DiscoverySortConfiguration">
                <property name="sortFields">
                    <list>
                        <ref bean="sortScore" />
                        <ref bean="sortTitle" />
                        <ref bean="sortDateIssued" />
                    </list>
                </property>
            </bean>
        </property>

        <property name="defaultSortConfiguration">
            <bean class="org.dspace.discovery.configuration.DiscoveryDefaultSortConfiguration">
                <property name="sortFields">
                    <list>
                        <ref bean="sortDateAccessioned" />
                    </list>
                </property>
            </bean>
        </property>
...

    <bean id="sortDateAccessioned" class="org.dspace.discovery.configuration.DiscoverySortFieldConfiguration">
        <property name="metadataField" value="dc.date.accessioned"/>
        <property name="type" value="date"/>
        <property name="defaultSortOrder" value="desc"/>
    </bean>
```

**Comment by tdonohue** [comment]
@paulo-graca : Agreed this would be nice.  I'll pull this over to the 7.6 board and flag as needs volunteer.  I'd consider this a bug, but we'd need to find a volunteer to work on it.  (If you are interested, let me know, as there still is time to include in 7.6 if we find a volunteer soon)

**Comment by buithaihai** [comment]
I am interested in taking a crack at this proposal. I have some ideas on how to approach it which will be detailed in a future PR. I will work on behalf of DLCorp; estimated time would be 8 hours.

For now, I will make a change to the part `<bean class="org.dspace.discovery.configuration.DiscoveryDefaultSortConfiguration">`, I expect to reuse `DiscoverySortConfiguration` since I see no reasons to create a new class for this.

**Comment by paulo-graca** [comment]
Thank you @buithaihai for volunteering with this!

Using **searchSortConfiguration** vs **defaultSortConfiguration**

If you use `searchSortConfiguration`, you will need a way to specify which sort fields will be the default ones. I'm assuming it could be used a new property for that. That property should support multiple sort fields. As an example:
```
        <property name="searchSortConfiguration">
            <bean class="org.dspace.discovery.configuration.DiscoverySortConfiguration">
                <property name="defaultSortFields">
                    <list>
                        <ref bean="sortDateAccessioned" />
                    </list>
                </property>
                <property name="sortFields">
                    <list>
                        <ref bean="sortScore" />
                        <ref bean="sortTitle" />
                        <ref bean="sortDateIssued" />
                    </list>
                </property>
            </bean>
        </property>
```

I think is also a good way to go.

**Comment by buithaihai** [comment]
@paulo-graca I can make `defaultSortFields` a list but because `DiscoverQueryBuilder#configureSorting` use `DiscoverQuery` which only support singular sorting and from my limited observation of the code changing that to support multiple sort options will take significant extra time. This also begs the question that is it necessary to support multiple sort options in the first place, since the angular UI only support singular sort only as well.

For your interest, currently, my implementation only accounts for singular sort option.

**Comment by paulo-graca** [comment]
That's right! That's because `DiscoverQuery` only supports a single sort field:
``` java
    /**
     * Attributes used for sorting of results
     **/
    public enum SORT_ORDER {
        desc,
        asc
    }

    private String sortField;
    private SORT_ORDER sortOrder;
```
Multiple sort fields requirement should be another issue and should be not considered here.

**Comment by paulo-graca** [comment]
Not sure if REST should be `defaultSortOption` aware, or should change it. For now, I think the main difference it would be that currently the `score` sorting is only considered as the default sorting and with this kind of change we would be able to use a different field.

at `DiscoverQueryBuilder`

``` java
    private String getDefaultSortField(DiscoverySortConfiguration searchSortConfiguration) {
        String sortBy;// Attempt to find the default one, if none found we use SCORE
        sortBy = "score";
        if (Objects.nonNull(searchSortConfiguration.getSortFields()) &&
                !searchSortConfiguration.getSortFields().isEmpty()) {
            DiscoverySortFieldConfiguration defaultSort = searchSortConfiguration.getSortFields().get(0);
            if (StringUtils.isBlank(defaultSort.getMetadataField())) {
                return sortBy;
            }
            sortBy = defaultSort.getMetadataField();
        }
        return sortBy;
    }
```

**Comment by paulo-graca** [comment]
@buithaihai You are totally right! I wasn't aware of this. I was assuming that leaving it by default, no sort parameter would be considered and the default sort would be used (that is what it makes more sense to me). Forcing a sort parameter (that isn't part of the discovery defined sort fields) doesn't sound correct to me. Perhaps a major reason is behind this option (if unknown, perhaps it makes sense to address it in a proper issue - out of the scope of this one).

**Comment by buithaihai** [comment]
I have pushed PR #8857, which hopefully will meet your expectation. Please feel free to provide feedbacks since it still leaves some rooms for improvements, mostly how to integrate with dspace-angular
