### ISSUE TITLE
error emailing user(s) for claimed task

### ISSUE THREAD

**Issue by CrisGuzmanS** [DSpace/DSpace#8867]
Hello everyone 👋

**Describe the bug**
I should receive this e-mail:
![image](https://github.com/DSpace/DSpace/assets/51240376/dbc27562-2d82-41e8-996d-f319b7cbe66b)

However, I am not receiving it.

✅ I have already configured the e-mail correctly
✅ I have already executed the command ./dspace test-email
✅ I have already verified that the other emails are sent.

In the logs, I get this error, but it doesn't tell me more.
`2023-05-25 18:06:13,468 INFO  unknown afabe638-6210-4a6e-8056-c8b259d22fdb org.dspace.xmlworkflow.state.actions.userassignment.UserSelectionAction @ cristianguzmansuarez@outlook.com::error emailing user(s) for claimed task:step\colon; editstep workflowitem\colon; 8453`

**To Reproduce**
1. Create a workspaceitem using the api (not using the UI)
2. Submit the workspaceitem through the api

**Expected behavior**
You should receive an email with the following structure:
![image](https://github.com/DSpace/DSpace/assets/51240376/87907c7e-b395-4248-b264-335c52b54507)

**Comment by tdonohue** [comment]
Closing as this appears to be a request for support.  It doesn't sound like a bug with the system itself, but might be a configuration issue with your email configs (in dspace.cfg).

I'd recommend moving this to a support channel: https://wiki.lyrasis.org/display/DSPACE/Support   I suspect it's a configuration issue, or maybe there's an error occurring in your logs which could explain the behavior.

If we find it is a bug, we can always reopen this ticket.
