### ISSUE TITLE
Localized License Files are not supported

### ISSUE THREAD

**Issue by olli-gold** [DSpace/DSpace#8882]
**Describe the bug**
On DSpace 5 and 6 under JSPUI it was possible to use language dependent repository licenses (for instance default_de.license or default_en.license), which was described here: https://wiki.lyrasis.org/display/DSDOC6x/Localization+L10n#LocalizationL10n-Localizationoflicense.default. There is a default.license https://github.com/DSpace/DSpace/blob/main/dspace/config/default.license in the configuration, which can be replaced with a custom one and it can be overridden collection specificly in the collection metadata. But DSpace 7 does not provide the option to use default_<language>.license files at the moment. 

**To Reproduce**
1. Create a file default_de.license
2. Switch to german language on the frontend
3. Start a new submission in a collection using the default license
4. The default license file will be displayed, and not the existing language specific variant

**Expected behavior**
The license displayed in the LicenseStep of the submission should use the appropriate Licensefile

**Comment by mwoodiupui** [comment]
Maybe we should treat the default deposit license bundle just like the collection license bundles:  as a metadata field, in this case belonging to the Site object.  That might simplify the code which fetches the license for display, since it would follow exactly the same process first on the Collection and then (if not found) on the Site, rather than having one bit of code for metadata fields and another, *nearly* identical, for files.

This would also make it easy to let members of the admin. group update a default deposit license remotely, if a bit of UI were built in front of it.

**Comment by mwoodiupui** [comment]
One other thing to consider:  should there be a "fallback" license in case the desired language is not available?  How to select the fallback value?  Perhaps the value with no language specified?  Then sites can determine for themselves which language will be the "default default".

**Comment by mwoodiupui** [comment]
Another idea that I toyed with was using something like `PropertyResourceBundle`, which already has language+variant selection behavior, but it seems cumbersome for long documents like deposit licenses, especially if you need to serve many languages.  It might be possible to create a `FileResourceBundle`, but I decided that keeping the design choice of putting each license in a file in `config/` was not worth the effort, even though coding it might be fun.

**Comment by olli-gold** [comment]
Thank you for sharing your ideas about this, @mwoodiupui!

I like the idea to have the localized licenses in the database rather than in the file system, as the current approach has a nasty limit: you can only translate the default language. For collections with a different license it is not possible to localize them, unless the option to translate the license is in the database.

So I second the approach to move the default license into the database and would like to propose to build localization options on that metadata level (for instance by using the language attribute for the license field?).

**Comment by tdonohue** [comment]
If there is a quick way to simply support the old JSPUI approach, then this might be considered a bug fix which could be added to a future 7.6.x bug-fix only release.

However, any larger redesigns or rethinking of this older approach would likely require waiting on 8.0 (or later).

For now, I'll pull this over to the 7.6 maintenance board in the hopes that someone will find a quick/easy way to bug fix this.  But, if that analysis finds it's not easily possible, we may have to move this to 8.0.

**Comment by tdonohue** [comment]
@damian-joz : You are welcome to link your solution into this ticket or create a draft PR.  The final decision is not mine alone, but I can bring it to the developer team meetings as necessary for more feedback.

**Comment by damian-joz** [comment]
@tdonohue You can assign me to this issue.

**Comment by damian-joz** [comment]
@tdonohue Here is my PR https://github.com/DSpace/DSpace/pull/8966

I'd like to discuss one thing. There was a simple cache of license text I had to remove. But now we read file from disk every time we start new submission (or editing). I am thinking to create a simple cache, can be hash map with locales as keys. Any thoughts?

**Comment by mwoodiupui** [comment]
IIRC our general direction now is "don't hold configuration data locally; get them when you need them."

If the license files are being accessed rarely, then the cost of reading them again is negligible and I doubt that a user would notice the delay for I/O.

If the files are being accessed frequently then there is a good chance that entire files are still cached by the OS and there will be no I/O cost at all.

I would say that we should consider the proposed cache un-necessary until we discover otherwise.

**Comment by tdonohue** [comment]
@damian-joz : I agree with @mwoodiupui .  I'm OK with the existing cache being removed here & I don't see a need to create a new cache.  We try not to cache configurations or files anymore _unless absolutely necessary_.  I don't believe caching this license file should be necessary, as I believe the license file is only loaded on the Submission form.  If we find reading this file on demand every time results in a slower submission form, then we could consider other options.  But, I doubt we will see any significant impact in this area of the code (I could always be wrong though).

**Comment by damian-joz** [comment]
Hi @tdonohue. Task is ready to assign reviewers.

**Comment by tdonohue** [comment]
Hi @damian-joz : Your PR has already been assigned to reviewers.  Code review is on a volunteer basis though at this time, so sometimes it can take some time to get to your code.  But, your PR *is on our board* to review for 7.6.1, so I can guarantee it will get a review.  (The summer months of July-Aug also are usually very slow for DSpace as many of our volunteers are taking holidays during that time)

If you would like to get immediate attention to your PR, we also do offer all developers the ability to do "PR Trading" (where you offer to review or test someone else's PR in exchange for them reviewing yours).  If that's of interest, see the details at https://wiki.lyrasis.org/display/DSPACE/Trading+reviews+on+Pull+Requests

Either way, I promise your work will be reviewed.  It's on my todo list as well, but I just haven't gotten to it yet.
