### ISSUE TITLE
Migrate from Joda-Time to java.time

### ISSUE THREAD

**Issue by alanorth** [DSpace/DSpace#8886]
**Is your feature request related to a problem? Please describe.**
According to the [Joda-Time website](https://www.joda.org/joda-time/), we should now be using `java.time`:

> Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.

As we now move on to supporting Java 11 and 17 with DSpace 7 we should really be thinking about using functionality from the standard library. This will become painful technical debt one day.

**Describe the solution you'd like**
Migrate to built-in `java.time`.

**Additional context**
From what I have read, the migration is not straightforward. Here are some resources:

- [Migrating Joda-Time to java.time](https://www.securecodewarrior.com/article/migrating-joda-time-to-java-time) (2021)
- [Converting from Joda-Time to java.time](https://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html) (2014)
- [migrate from Joda time library to Java time (Java 8)](https://stackoverflow.com/questions/35043788/migrate-from-joda-time-library-to-java-time-java-8) (2016)
- [Elasticsearch Core: Migrating from joda time to java.time](https://github.com/elastic/elasticsearch/issues/27330) (2017)

There are surely many more discussions about this.

**Comment by mwoodiupui** [comment]
Yes, please.  I have been wanting to do that for some time.  Thanks for capturing this as an Issue.

**Comment by mwoodiupui** [comment]
There are only three classes using Joda Time, all in dspace-api.  (org.dspace.submit.model.AccessConditionOption claims that `startDateLimit` and `endDateLimit` accept Joda Time date math expressions, but this can only be true by accident, as they are processed using a copy of Solr's date math code.)

**Comment by mwoodiupui** [comment]
We may want to consider a more general clean-up of the old Date object as well.
