### ISSUE TITLE
Shibboleth login leads to an error page when logging in with spaces in a GET request

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/DSpace#8888]
**Describe the bug**
If you do a search with a space in it, for example "testing turbine" & then logging in with shibboleth will result in a "Unauthorized, status=401" error.
 

**To Reproduce**
1. Go to the following page: https://demo7.dspace.org/search?query=testing%20turbine
2. Then login with shibboleth

**Expected behavior**
Login should work.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Closing, fixed by #8889
