### ISSUE TITLE
DSpace config references webui.browse.thumbnail still

### ISSUE THREAD

**Issue by misilot** [DSpace/DSpace#8906]
**Describe the bug**
Per the documentation https://wiki.lyrasis.org/display/DSDOC7x/Release+Notes#ReleaseNotes-7.0ConfigurationsRemoved `webui.browse.thumbnail.*` was removed, however there are still references to it in the dspace.cfg file.

https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L1449 and https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L1449

**Comment by alanorth** [comment]
Yes you are right @misilot. These don't appear to be used anywhere in the DSpace source code. In a DSpace 7.6 source tree:

```console
$ grep -rsI webui.browse.thumbnail *
dspace/config/dspace.cfg:# If you have enabled thumbnails (webui.browse.thumbnail.show), you must also
dspace/config/dspace.cfg:# for browse thumbnails (webui.browse.thumbnail.maxwidth, thumbnail.maxwidth)
```

References to this should be removed from `dspace.cfg`.

**Comment by alanorth** [comment]
I removed `webui.browse.thumbnail` and a few others in #8983. Appreciate a review @misilot.
