### ISSUE TITLE
Missing subject in template-based e-mails in DSpace 7.6

### ISSUE THREAD

**Issue by abelgomez** [DSpace/DSpace#8921]
**Describe the bug**
In DSpace 7.6, e-mails that are created from an e-mail template in `dspace/config/emails/` have an empty subject.

**To Reproduce**
1. Go to your DSpace 7.6 instance
2. Ask for an e-mail created from a template (e.g., ask for a reset password link using the "Forgotten password" feature)

**Expected behavior**
The received e-mail must have a subject, instead, an e-mail with a blank subject is received.

**Related work**
This seems to be caused by the commit at https://github.com/DSpace/DSpace/commit/66c452bcf93e5366e2ef4da5bd892a079e31864e. See at https://github.com/DSpace/DSpace/compare/dspace-7.5...dspace-7.6#diff-e799738ac5a322784bd336eeb841c8ca3a6f6c13c69508bccc7f027685c27752 a diff between 7.5 and 7.6 versions.

As it can be seen, `templateHeaders` are cleared in the (new) line 339 of file `dspace-api/src/main/java/org/dspace/core/Email.java`. Find below a diff between dspace-7.5 and dspace7.6 versions for brevity purposes (only for the affected file):

```
diff --git a/dspace-api/src/main/java/org/dspace/core/Email.java b/dspace-api/src/main/java/org/dspace/core/Email.java
index 6db27c9..6b86756 100644
--- a/dspace-api/src/main/java/org/dspace/core/Email.java
+++ b/dspace-api/src/main/java/org/dspace/core/Email.java
@@ -314,6 +314,8 @@
             message.addRecipient(Message.RecipientType.TO, new InternetAddress(
                 i.next()));
         }
+        // Get headers defined by the template.
+        String[] templateHeaders = config.getArrayProperty("mail.message.headers");
 
         // Format the mail message body
         VelocityEngine templateEngine = new VelocityEngine();
@@ -334,6 +336,7 @@
             repo.putStringResource(contentName, content);
             // Turn content into a template.
             template = templateEngine.getTemplate(contentName);
+            templateHeaders = new String[] {};
         }
 
         StringWriter writer = new StringWriter();
@@ -351,8 +354,7 @@
         message.setSentDate(date);
         message.setFrom(new InternetAddress(from));
 
-        // Get headers defined by the template.
-        for (String headerName : config.getArrayProperty("mail.message.headers")) {
+        for (String headerName : templateHeaders) {
             String headerValue = (String) vctx.get(headerName);
             if ("subject".equalsIgnoreCase(headerName)) {
                 if (null != subject) {
```

**Comment by abelgomez** [comment]
Restoring to the DSpace 7.5 version of `dspace-api/src/main/java/org/dspace/core/Email.java` seems to fix the issue. but I'm not sending a PR since I do not understand why the developer changed the order of the lines to clear the template headers explicitly 🤔

**Comment by mwoodiupui** [comment]
Confirmed on the `dspace-7.6` tag by examination and testing.  The reason for that line is a mystery to me as well.  I know of no reason why a template should ever not be examined for header settings.
