### ISSUE TITLE
OAI endpoint no longer supports exposing embargo dates

### ISSUE THREAD

**Issue by amgciadev** [DSpace/DSpace#8923]
**Is your feature request related to a problem? Please describe.**
In DSpace 5.x and 6.x, embargo dates where present in the item metadata, and therefore could be crosswalked and exposed in the OAI metadata. This is something particularly important when exposing the open access status of fulltext bitstreams in DSpace.
**Describe the solution you'd like**
For this information to be exposed back in the OAI metadata.

**Describe alternatives or workarounds you've considered**
We've considered using the open access status (open access, embargoed, etc.) instead but this not provide any information about when the file will become available and it is needed for a number of external open access services.

**Additional context**

**Comment by amgciadev** [comment]
@tdonohue Cambridge is willing to submit a pull request for this functionality so that it is made available for all DSpace users. To give a bit more context, this functionality not being available since the upgrade will cause issues to many institutions in the UK that currently submit theses information to the EThOS service, based at the British Library, amongst potentially other external services.

**Comment by Knelfy** [comment]
We would support this at Uni of Nottingham. We've not moved to 7 yet but when we do, we plan to start hosting our eTheses collection on it so having the embargo dates in OAI would be useful for us re. BL/EThOS too. Not sure if they show on the repository UI but if they don't, that would be useful too.

**Comment by moragm23** [comment]
We would support this at Queen Mary University of London, as we use the same service.  We are in the process of planning our migration for DSpace 7, and already host our thesis collection in our current version (5.x)

**Comment by tdonohue** [comment]
@amgciadev : I think this makes sense as a new, minor improvement to OAI-PMH.  Depending on the size of the code changes, it might also be considered a "bug fix" and could be considered for a bug-fix release of 7.6 (as we will still have bug fix releases to the 7.x platform in the future). But, I think that determination couldn't be made until we understand the scope of the changes required.

In any case, I'll assign this to you since you've volunteered to create a PR.
