### ISSUE TITLE
ORCID integration bugs: ORCID Authorizations page

### ISSUE THREAD

**Issue by JordanPedersen** [DSpace/DSpace#8925]
**Describe the bug**
In our Dpsace sandbox (version 7.5), we've set up the ORCID integration (https://wiki.lyrasis.org/display/DSDOC7x/ORCID+Integration), however we are experiencing a few bugs on the ORCID Authorizations
page. Let me know if it would be preferable to split these into separate issues.

1. When users update their ORCID credentials, they always see an error message ("The update of the synchronization settings failed" or "An error occurred while disconnecting between the profile and the ORCID registry. Try again"), regardless of whether the action was successful.
2. May be related to 1, but users must leave the page and return to see their queue being refreshed
3. When synchronizing ORCID content, Under preferences, choosing "All Publications" or "All Funding" does not seem to impact the queue. Under Profile preferences, you need to select biographical data and identifiers for publications to be put in the synchronization queue. Publications will be added to the queue even if Publication preferences and Funding preferences are set to "Disabled".

**To Reproduce**
1.  Log In to DSpace
2. Click on the profile icon at the top right of the page and select Profile from the drop-down menu.
3. In the Researcher Profile box, you should see that the Status is Public. Click on ‘View’.
4. Click on the ORCID logo on the top right corner to open the ORCID authorizations page.
5. Authenticate your ORCID (we have tried with both the sandbox- and production member API credentials)
This is the page from which we are experiencing the problems. 

To reproduce problem 1: try updating any of the settings on the page
To reproduce problem 2: try updating any of the settings on the page
To reproduce problem 3: Under Publication preferences, choose All Publications and/or All funding, save, leave the page and come back, and you will see no publications in the queue (note: your user will have to have at least one publication in DSpace to test). Publication preferences, choose disabled instead of All Publications and All funding, Under Profile preferences, select biographical data and identifiers, save, leave the page and come back, and you will see publications in the queue.

Note: a recording of this behaviour is available if helpful.

**Expected behavior**
Expected behaviour for problem 1: User would get a confirmation message if they are successful, and an error message only if their action is unsuccessful.
Expected behaviour for problem 2: ORCID queue would refresh while user is on the page
Expected behaviour for problem 3: Publications would show in the queue only if "All Publications" is selected.

**Comment by hutattedonmyarm** [comment]
> When users update their ORCID credentials, they always see an error message ("The update of the synchronization settings failed" 

We noticed the same issue. When checking the response in `orcid-sync-settings.component.ts`, it is done using `remoteData.isSuccess`, but the response is usually a stale success, so it falls through:

https://github.com/DSpace/dspace-angular/blob/c4342d3238b73d03cb92e8ce160884e66d14b49a/src/app/item-page/orcid-page/orcid-sync-settings/orcid-sync-settings.component.ts#L159-L164

As a workaround we changed `isSuccess` to `hasSucceeded`

**Comment by sheilarabun** [comment]
Expanding on the "Disconnect ORCID" issue briefly mentioned above:

If a user has already connected their ORCID iD to their profile, but then they click the "Disconnect ORCID" button, an error message appears saying:

 "an error occurred while disconnecting between the profile and the ORCID registry. Try again."

If the user clicks the Disconnect ORCID button again, they get the same error message. However, if you leave the page and come back, it turns out the ORCID was in fact disconnected, because the ORCID page returns to a state where no ORCID is connected and the user is asked to connect their ORCID.

**Comment by vins01-4science** [comment]
Hello @JordanPedersen  @tdonohue.
 
We @4Science can work on this issue 🚀!
