### ISSUE TITLE
Solr statistics core for the current year is queried twice if sharding is enabled, resulting in wrong statistics being displayed

### ISSUE THREAD

**Issue by hutattedonmyarm** [DSpace/DSpace#8933]
**Describe the bug**
Queries against the statistics core (e.g. for download statistics) are showing the wrong number.
The cause of this seems to be sharding by year: The Solr query contains a list of which cores to include (in this case: all of the sharded ones), but the list includes the current year twice.

The initialization responsible for this is here:

https://github.com/DSpace/DSpace/blob/2b42811e971853c85caf8487411de79515e2bcf3/dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java#L1686-L1698

The problem is, that `statCoreNames` already includes the core for the current year, because it of course also starts with the base name:

https://github.com/DSpace/DSpace/blob/2b42811e971853c85caf8487411de79515e2bcf3/dspace-api/src/main/java/org/dspace/statistics/SolrLoggerServiceImpl.java#L1681-L1683

**To Reproduce**
1. Enable statistics sharding, set `usage-statistics.shardedByYear = true` in the configuration
2. View usage statistics of a bitstream
3. Download numbers for the current year are counted twice

**Expected behavior**
Download numbers should be accurate

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Sounds like a bug.  PR is welcome if you've found a fix.

In the meantime, will pull over to the 7.6 maintenance board and look for a volunteer.  If you are interested, let us know!

**Comment by hutattedonmyarm** [comment]
We found a fix by removing the code which adds the base core a second time. It's be slightly more defensive for the PR and check if it needs adding instead of blindly doing or not doing so. I'm assuming there was a reason the base core was added explicitly, so removing that line (even if it works for us)  might not be the best idea
