### ISSUE TITLE
Hierarchical browse indexes to create should be configurable

### ISSUE THREAD

**Issue by toniprieto** [DSpace/DSpace#8947]
The hierarchical browse indexes are automatically generated based on the controlled vocabularies used in the submission forms and there is currently no option to disable them without removing from submission forms.

It may happen that you have defined a vocabulary in the submission form for which you do not want to create a browse index. There should be an option to configure which hierarchical browse index should be created.

**Comment by tdonohue** [comment]
Fixed by #8948
