### ISSUE TITLE
Cannot delete an EPerson via the commandline "Groomer" tool when EPerson is referenced elsewhere.

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#8963]
**Describe the bug**
Are the constraints for deletion of EPersons still up to date to the possibility of EPerson deletion in DSpace 7, as I thought we could delete EPersons regardless of their involvement in Items/Workspace-Items/Workflow-Items now?

Those restrictions seem to be applied, when trying to delete EPersons e.g. from the Groomer Tool, but seem not to be applied when deleting the same EPerson from the Angular User Interface.

`getDeleteConstraints` in `EPersonServiceImpl` lists the following restrictions:

```
public List<String> getDeleteConstraints(Context context, EPerson ePerson) throws SQLException {
List<String> tableList = new ArrayList<>();

// check for eperson in item table
Iterator<Item> itemsBySubmitter = itemService.findBySubmitter(context, ePerson, true);
if (itemsBySubmitter.hasNext()) {
	tableList.add("item");
}

WorkspaceItemService workspaceItemService = ContentServiceFactory.getInstance().getWorkspaceItemService();
List<WorkspaceItem> workspaceBySubmitter = workspaceItemService.findByEPerson(context, ePerson);
if (workspaceBySubmitter.size() > 0) {
	tableList.add("workspaceitem");
}

ResourcePolicyService resourcePolicyService = AuthorizeServiceFactory.getInstance().getResourcePolicyService();
if (resourcePolicyService.find(context, ePerson).size() > 0) {
	tableList.add("resourcepolicy");
}

WorkflowService workflowService = WorkflowServiceFactory.getInstance().getWorkflowService();
List<String> workflowConstraints = workflowService.getEPersonDeleteConstraints(context, ePerson);
tableList.addAll(workflowConstraints);

// the list of tables can be used to construct an error message
// explaining to the user why the eperson cannot be deleted.
return tableList;

```

**To Reproduce**
1. Try to delete an EPerson that has one of the listed restrictions via e.g. the Groomer tool -> it fails
2. Try to delete the same EPerson via the Angular UI -> it succeeds

**Expected behavior**
Either the restrictions are valid, then the EPerson should not be deletable in both ways, or they are invalid, then they should be deletable both ways.

**Comment by tdonohue** [comment]
@MW3000 : This sounds to me like a bug in the [Groomer tool](https://wiki.lyrasis.org/display/DSDOC7x/Managing+User+Accounts#ManagingUserAccounts-TheGroomer) you mention

As of 7.0, DSpace allows deletion of EPerson objects **even if they are referenced in Workspace/Workflow items**.  This is required to align with GDPR.  See this PR which added the improvement: https://github.com/DSpace/DSpace/pull/2229

So, it sounds to me like the Groomer tool was never updated to support the same types of deletion.  This would be a bug.  Pulling this over to the 7.6.x maintenance board to look for a volunteer (let me know if you are interested yourself).

**Comment by MW3000** [comment]
@tdonohue Yes, I can fix this in the first week of September. I looked a bit more into it. Perhaps it would be helpful for the Groomer tool to have a command line option for both variants.

**Comment by tdonohue** [comment]
@MW3000 : I'm not against there being some sort of flag that allows both behaviors, but I'd recommend not over thinking it.  It's more important for the Groomer tool to act the same as the User Interface.  It seems odd to _want_ the Groomer to throw an error when an EPerson has relationships, when that same behavior is not possible in the User Interface.  I'm not against it, but, I don't understand the use case for that scenario.

In any case, I'll assign this to you.  No worries if it will take a few weeks to get to.  Thanks for volunteering!

**Comment by MW3000** [comment]
I opened a pull-request. And you were right, @tdonohue, I fixed it the most straightforward way, without adding any additional flags and complications.

**Comment by MW3000** [comment]
Should I open a second pull-request for the main branch? I remember there was also some kind of automation for this?

**Comment by tdonohue** [comment]
@MW3000 : We do have new automation via GitHub Actions which attempts to port any merged PR with a `port to [branch]` label to the corresponding branch.  It's not perfect, but it works well with simple PRs.  Since your PR is simple, it likely will work there.
