### ISSUE TITLE
request-a-copy email: non ASCII characters are encoded as HTML character entity references

### ISSUE THREAD

**Issue by saschaszott** [DSpace/DSpace#8968]
## Bug Description

Currently, non ASCII characters, e.g. German umlauts, are encoded as HTML character entity references (instead of UTF-8) in  the body of a request-a-copy email. Since the mail header `Content-Type` is set to `text/plain; charset=UTF-8` mail clients may display non ASCII characters inappropriately.

### Example input in request-a-copy form:

![image](https://github.com/DSpace/DSpace/assets/952735/08e6eda8-b565-44da-99a1-167f29144f74)

### Payload of request-a-copy email:

![image](https://github.com/DSpace/DSpace/assets/952735/3f47b2b3-f19f-4bb8-bda0-c691a72cbcfb)

### Rendered output in mail client (in this case Thunderbird)

![image](https://github.com/DSpace/DSpace/assets/952735/758b65fc-3288-4953-b718-8422d25e242d)

## Expected behavior

Do not use HTML character entity references. As the email body is UTF-8 encoded, switch to UTF-8 encoding instead.

**Comment by saschaszott** [comment]
additional note: the request-a-copy form input is even encoded in HTML character entity references at the database level

```sql
dspace=# select request_message from requestitem where requestitem_id = 10;
 request_message
-----------------
 🙋             +
 &uuml;         +
 &szlig;
(1 row)
```

**Comment by tdonohue** [comment]
This does sound like a bug.  I'm not sure how this form differs from other forms we use (in Submission UI, or similar). But, ideally it should either not encode UTF-8 to HTML characters... or, if that proves complex, the backend should decode the HTML entities back to UTF-8. 

 In any case, this is unexpected behavior. I'll pull this over to the 7.6.x maintenance board in search of a volunteer.
