### ISSUE TITLE
Move item inheritPolicies adds the new collection's policies but doesn't erase previously present less-restrictive policies

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/DSpace#8987]
**Describe the bug**
When moving an item from a regular collection, thus having anon read policy, to a restricted collection (eg with its item_read policy on Administrator group) only, with the `inheritPolicies=true` query param, it does inherit the Admin RP from the restricted collection, but also still has the Anon read policy it originally had 

Example item: https://demo7.dspace.org/items/1934a2ab-8fbb-4464-a483-760301e9dd73 (anon accessible) => https://demo7.dspace.org/items/1934a2ab-8fbb-4464-a483-760301e9dd73/edit/authorizations (moved from open to restricted collection with inherit policies checked)

**To Reproduce**
1. Create a regular and restricted collection (restrict collection in {collection-url}/edit/authorizations => alter all RP to have Administrator group instead of Anonymous)
2. Create an item in the regular collection, check its RP in {item-url}/edit/authorizations, verify it has anonymous read RP
3. Move the item to the restricted collection with inherit policies checked
4. Check the item's RP again, verify it has both the anonymous and administrator read RP & thus is still openly accessible

**Expected behavior**
When inheriting policies at item move I would expect previous (ITEM_READ) policies to be replaced.

**EDIT**: Idem for files (bitstream & bundles): if collection has `DEFAULT_BITSTREAM_READ` and inheritPolicies=true => Should replace the READ policies of the files
Use case: If a user moves something with inherit policies into a collection where for example, the anonymous group doesn’t have default read permissions on bitstreams, the user expects the PDFs NOT to be downloadable by anon.

**Related work**
https://github.com/DSpace/DSpace/pull/8717
https://github.com/DSpace/dspace-angular/pull/2146

**Comment by MarieVerdonck** [comment]
Atmire would like to claim this issue

**Comment by tdonohue** [comment]
@MarieVerdonck : Thanks! Sounds good.  Assigning to you & moving to the 7.6.x maintenance board for tracking
