### ISSUE TITLE
Can't disable Browse-By Subject Category

### ISSUE THREAD

**Issue by mirkoscherf** [DSpace/DSpace#8989]
**Describe the bug**
Subject Category is the only browse-by entry that is not configured in dspace.cfg via webui.browse.index.<n>. It is not possible to disable it here,

**To Reproduce**
1. Check the Browse-By section in the header. Five entries are visible (on demo7.dspace.org)
2. Check dspace.cfg webui.browse.index.<.>. Only four entries are enabled

**Expected behavior**
Browse by Subject Category should be configurable the same way as the other browse by categories. There needs to be a way to disable this if needed.

**Related work**
[dspace-angular #2215](https://github.com/DSpace/dspace-angular/pull/2215)

**Comment by mirkoscherf** [comment]
Already addressed in #8948

**Comment by tdonohue** [comment]
This ticket was a duplicate of #8947 (which has a possible fix in #8948)
