### ISSUE TITLE
DOI-consumer seems unnecessary

### ISSUE THREAD

**Issue by philippcle** [DSpace/DSpace#8990]
**Describe the bug**
In DSpace 7.6, as soon as a DOIIdentifierProvider is available, it is called in the activation process, which leads to a DOI being generated and saved in the DB. This behavior is independent of whether the consumer `doi` was activated or not. If the consumer was also activated, then this recognizes that the current DSpaceObject already has a DOI and does nothing further. So it seems that the DOI consumer could be removed.

**To Reproduce**
1. Activate the `DOIIdentiferProvider` and the `DOIIdentifierConnector` in `identifier-service.xml`
2. Do not add `doi` to the `event.dispatcher.default.consumers`
3. After approving a Publication, a DOI is inserted in the `doi` table at DB.

**Expected behavior**
 If a consumer is offered, then the generation of the DOI should depend on whether the consumer is enabled or not. The Documentation https://wiki.lyrasis.org/display/DSDOC7x/DOI+Digital+Object+Identifier#Identifier%20Service also describes that the doi consumer has to be added.

**Comment by tdonohue** [comment]
@kshepherd : Pinging you on this as I know you've done a lot of DOI related work recently.  Would be interested in your feedback if you find a chance.  If this consumer is no longer necessary, then we should likely remove the code & configuration references.

**Comment by ChrisBethgster** [comment]
The consumer is necessary if the metadata were changed after publishing and registration of the DOI. EZID or DataCite are not only used for resolving, the agencies have also a store for metadata and the metadata of an item should be up to date.
-> see https://commons.datacite.org/

**Comment by kshepherd** [comment]
Yes, @ChrisBethgster is correct. The main purpose of the DOI consumer now is to track metadata updates and queue relevant objects for remote metadata update with the DOI Organiser

**Comment by tdonohue** [comment]
Thanks for clarifying @kshepherd and @ChrisBethgster .  In that case, should we add any clarifications to the documentation?  Or should we just close this ticket as answered?

I do see that the docs imply this, but don't go into great detail.  It currently says:
> DSpace should send updates to DataCite whenever the metadata of an item changes. To do so you have to change the dspace.cfg again. You should remove the comments in front of the two following properties or add them to the dspace.cfg:

This is just before the notes on enabling DOIConsumer in this section: https://wiki.lyrasis.org/display/DSDOC7x/DOI+Digital+Object+Identifier#DOIDigitalObjectIdentifier-IdentifierService

**Comment by tdonohue** [comment]
Closing, as this has been answered.  I also updated the existing docs to clarify the purpose of the DOIConsumer here: https://wiki.lyrasis.org/display/DSDOC7x/DOI+Digital+Object+Identifier#DOIDigitalObjectIdentifier-SendingmetadataupdatestoDataCite
