### ISSUE TITLE
OpenAIRE v4 Crosswalk uses item-level dc.rights metadata field rather than bitstream-level metadata

### ISSUE THREAD

**Issue by doana** [DSpace/DSpace#9050]
**Describe the bug**
As it exists now, the [OpenAIRE crosswalk](https://github.com/DSpace/DSpace/blob/c1e97188f99b7e98f295feeb2a501e65fd581668/dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl#L528) uses the dc.rights metadata to populate the accessRightsURI on the oaire:file element in the response. Since this attribute is file-specific, should it not use metadata that's associated with the bitstream specifically to populate this element? Perhaps with a fallback strategy to use the item-level dc.rights metadata if the bitstream-level metadata isn't set? 

It seems to me like the access conditions that can be set on a per-bitstream basis should interact with this functionality as they do in fact have access implications that might not be properly represented in the OpenAIRE response. While they don't map 1:1 onto the [OpenAIRE Access Rights](https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/latest/field_accessrights.html) attribute, there's certainly some overlap. 

I'm new to OpenAIRE, so maybe I'm way off base, but I'd love to hear what others think?

**Comment by tdonohue** [comment]
I think the challenge with this suggestion is that DSpace itself doesn't tend to create a `dc.rights` on a Bitstream.  I believe this `dc.rights` metadata field is only possible to set from the UI on an Item-level.  So, I suspect that is the reason for the current approach in the OpenAIRE v4 crosswalk, but maybe @paulo-graca would have more suggestions here.

**Comment by paulo-graca** [comment]
Thank you @doana, this is a real issue that is thankfully identified. 
Can you please take a look on my comment here: https://github.com/DSpace/DSpace/pull/8926#issuecomment-1720922200

> OpenAIRE's schema - https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_filelocation.html - foresees that every file could have a specific access right. In our current implementation we are assuming that every file in the item "drinks" his access rights from the defined access right calculated for the Item (work done with Access Status). But that approach isn't totally accurate for every file

The current approach aims to not bring more overhead into XOAI processing. One of the versions of this WIP Pull Request https://github.com/DSpace/DSpace/pull/8926 could add the necessary tools to address this issue. I've created this issue with a possible solution:
https://github.com/DSpace/DSpace/issues/9075
