### ISSUE TITLE
OAI: Resource Policies for every bitstream at XOAI

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#9075]
**Is your feature request related to a problem? Please describe.**
There are some use cases where we need to have specific access rights at files level to be available in the OAI interface. In our current implementation for OAI, we are assuming that every file in the item "drinks" his access rights from the defined access right calculated for the Item (work done with Access Status). But that approach isn't totally accurate for every file, mainly because we could have a different resource policy for the second or third file.

**Describe the solution you'd like**

A solution for it started here by @amgciadev , but was left for a broad discussion:
https://github.com/DSpace/DSpace/pull/8926/files/e90cae57354a4a5efdec55d97e64ac0dcc76138d#diff-633af853d8da2dc5589f5bfebf4b62592d0f3e4fc548cc4041dd1569935910e3R178

The solution will have a method in the xoai ItemUtils.java file, that will be called when the item is processed. And will add extra XML elements to the XOAI bitstream, that expose the defined resource policies. Something like:
``` xml
<element name="bitstreams">
   <element name="bitstream">
     <field name="name">2019_ENSPQ_AOliveira_Poster_R.pdf</field>
     <element name="resourcePolicies"> 
        <element name="resourcePolicy">
              <field name="group">ANONYMOUS</field>
              <field name="user"></field>
              <field name="action">READ</field>
              <field name="start-date">2023/09/14</field>
              <field name="end-date">2023/09/20</field>
        </element>
     </element>
   </element>
</element>
```
and then, one could use XSLT and XPATH to help define things like what is the embargo (group=ANONYMOUS + action=READ + START_DATE) at the XOAI level.

With those elements in place, we could address specific needs like:
- Support at Access Rights at files level at OpenAIRE's schema: 
https://openaire-guidelines-for-literature-repository-managers.readthedocs.io/en/v4.0.0/field_filelocation.html
 - Or  enable with UKETD/EthOS compliance, having:
``` xml
<dc:relation type="https://schema.org/ScholarlyArticle" deposit_date="2021-07-28" resource_exposed_date="2021-07-28">
    https://www.repository.org/article_1234567.pdf
</dc:relation>

```

**Additional context**
It was pointed that this feature will add some overhead to XOAI processing.
This discussion started here in this PR: https://github.com/DSpace/DSpace/pull/8926
This is also related with issue: https://github.com/DSpace/DSpace/issues/8923

**Comment by paulo-graca** [comment]
@amgciadev, @tdonohue, @benbosman, @abollini  I've just create this issue for a broad discussion started here: #8926.

**Comment by LEavestaff** [comment]
Would like to add a +1 for this feature to be implemented. 

Our current setup comprises of 2 separate DSpace 7.5 instances, one for internal use to get submissions from applications like Symplectic Elements, to be reviewed and then sent via OAI Harvest to our public-facing DSpace 7 instance. We have items that will have 2 bitstream files, with only one being the public facing file and the other being useful for administrators/reviewers for example. 

At the moment any file that gets harvested via OAI regardless of policy status, it will be public facing. We would like to have OAI harvest acknowledge bitstream policy.

**Comment by amgciadev** [comment]
@paulo-graca @tdonohue I hope you are well. I wanted to let you know that I have started working on this, based on the initial implementation I had added to #8926 that we agreed to remove at that time as it changed functionality. I will base the new implementation on the more generic approach that @paulo-graca is suggesting above. Please do let me know if you are already working on this to now duplicate effort. Also, the use case XLST implementation that I'll be working on to make use of this feature will be the RIOXX profile, as it's latest version 3.0 is now released.

**Comment by amgciadev** [comment]
Hi @paulo-graca , @tdonohue , I have progressed quite a lot this week on this and at this point I wanted to ask a couple of questions:

- The current PR #9231 only implements the additions needed to expose the relevant resource policies in the OAI metadata and provides a simple example of use in the opeaire.xsl transform
- To provide another full real use case (and an important development to help exposing compliant metadata for oa publications) I am also working on a RIOXX v3 OAI profile implementation (https://www.rioxx.net/profiles/v3-0-final/)
I was wondering how best to approach this: do I need a separate PR for the RIOXX work (note that it uses the development of the current PR) OR could I expand / update the description of the current PR to also include the work of the RIOXX profile

**Comment by tdonohue** [comment]
@amgciadev : In all honesty, it's up to you.  We can work with the PR either way, but (as you noted) you must obviously update the description/title of the PR if you add more features to it.

Overall, our only general suggestion is to try to not create massively large PRs (i.e. many thousands of lines of code) unless it's unavoidable for very large features.  This doesn't sound like it would get to that scale though, even if you add RIOXX work to it.

**Comment by amgciadev** [comment]
Hi @tdonohue , thanks so much for the swift response. Great, I think I'll update the description of the PR. The RIOXX work pretty much adds:

- A couple of stylesheet files
- The work of the current PR on ItemUtils.java (dspace-oai)
- A couple of small util classes
- One additional field to the solr oai schema
So in summary, no big number of added classes or lots of code added either

**Comment by paulo-graca** [comment]
@amgciadev I've assign myself to review the PR. And I will review it when you understand that's in the review state.

**Comment by amgciadev** [comment]
@paulo-graca many thanks for assigning yourself as a reviewer. I have now removed the draft status for the review as I feel is ready for review now.
