### ISSUE TITLE
Emails are sent in English only.

### ISSUE THREAD

**Issue by marciofoz** [DSpace/DSpace#9085]
**Describe the bug**
We need to send emails in other languages, but only English is used. The browser is correct (pt_BR) and so is the user profile.
We have the same solution working in version 6.3, but in 7.5 it is not correct.
We create different versions of the templates for each language, see below:

$ ls -lha /dspace/dspace-backend/config/emails/
change_password
change_password_es
change_password_pt_BR

**To Reproduce**
1. Try recovery/change the password in UI (Forgot Password).
2. Email received in english.

**Expected behavior**
The email received must be in the user's profile (and/or browser's) language.

**Related work**
-

Thanks.

**Comment by toniprieto** [comment]
Hi @marciofoz 

I think that this issue could be a configuration problem. To make it work the languages supported by the backend should be configured in this dspace.log key: webui.supported.locales

https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L1259C18-L1259C18

For example:

`webui.supported.locales = en, es, pt_BR`

Have you configure this key?

**Comment by tdonohue** [comment]
Closing, as it sounds like this was a configuration issue?  See [above comment](https://github.com/DSpace/DSpace/issues/9085#issuecomment-1731027553).   

If it is still not working, we can reopen as necessary.
