### ISSUE TITLE
Upgrade Flyway to v9

### ISSUE THREAD

**Issue by hutattedonmyarm** [DSpace/DSpace#9119]
DSpace is currently using Flyway 8.4.4, but the latest version is [9.22.2](https://mvnrepository.com/artifact/org.flywaydb/flyway-core/9.22.2). Officially, Flyway 8 only supports PostgreSQL up to version 14, while Flyway 9 includes support for PostgreSQL 15.

Since DSpace lists 15 as supported PostgreSQL version it should IMHO also use the respectable Flyway version.

Flyway 8 *seems* to run without problems with PSQL 15 though. Flyway 9 is a fairly straightforward upgrade, the only relevant API change looks to be the removal of `flywayConfiguration.ignoreIgnoredMigrations(true);` in favor of `flywayConfiguration.ignoreMigrationPatterns(String ...)`

Perhaps it would be sensible to wait until Flyway releases a version which is compatible with PSQL 16 before the upgrade

**Comment by tdonohue** [comment]
I agree that, in general, we should be keeping Flyway up-to-date.  Moving this to the 8.0 board in search of a volunteer, though priority is still lower at this time.

This may be related to #9107 as that update to PostgreSQL 16 appears to be returning a warning from Flyway that it may be unsupported. See this comment: https://github.com/DSpace/DSpace/issues/9107#issuecomment-1756705855

I agree we may want to wait until Flyway has official support for PostgreSQL 16 and then update to that version.   Currently Flyway only reports support for PostgreSQL 15 here: https://documentation.red-gate.com/fd/postgresql-184127604.html

**Comment by hutattedonmyarm** [comment]
I just took another look at the Flyway API change. I *think `flywayConfiguration.ignoreIgnoredMigrations(true);` would need to be replaced with `flywayConfiguration.ignoreMigrationPatterns("*:ignored")`, but there isn't really much documentation for that. The deprecation message for `ignoreIgnoredMigrations` just says *Use ignoreMigrationPatterns instead* without detailing **how**, so the only documentation I can go off is https://documentation.red-gate.com/fd/ignore-migration-patterns-184127507.html

**Comment by tdonohue** [comment]
This will be fixed by #9321 which upgrades us to Flyway 10.  So, we'll skip over Flyway v9 and go straight to v10.

**Comment by misilot** [comment]
@tdonohue is this something that could be backported to DSpace 7? Since that lists Postgres 15 as a supported version, yet this is a warning when running on 7.6.2 (possibly earlier).

Thanks!

**Comment by tdonohue** [comment]
@misilot : The upgrade to Flyway v10 cannot be backported, as it was highly dependent on the migration to Jakarta EE which occurred in DSpace 8.0 (see #9321).  It's impossible to backport Jakarta EE support to 7.x as it's a significant refactor.

The warning you are seeing in 7.6.2 can be safely ignored (as it also occurred before 7.6.2 if you used Postgres 15), see this comment https://github.com/DSpace/DSpace/issues/9107#issuecomment-1757834891   As noted there, Flyway is *only* used when you run `./dspace database migrate`.  We've never seen any reported issues with running that using Postgres 15 + DSpace 7.6.x

I have not investigated whether it's possible to upgrade 7.6.x to Flyway v9, as I believe Flyway (finally) added full Postgres 15 support to later versions of Flyway 9 (it did not exist in early versions of Flyway 9).  I'm not against that upgrade, but it'd require someone to look into the feasibility.  In my opinion though, it's low priority as we've found Flyway 8 works fine with Postgres 15 even with the warning.
