### ISSUE TITLE
`authority` Solr core is missing `_version_` field and cannot be loaded

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/DSpace#9122]
**Describe the bug**
The schema for the `authority` core does not define the required field `_version_`.  Solr refuses to load the core.

**To Reproduce**
1. Try to query the core.  (`curl http://localhost:8983/solr/scholarworks-authority/select?q=*:*`)  See that Solr says it is not loaded.

You should also find ERROR entries in `log/dspace.log` mentioning this core.

**Expected behavior**
The core should load normally.

**Comment by mwoodiupui** [comment]
I copied the `field` definition, and the `fieldType` definition for `long`, from the `statistics` core and now `authority` loads.

**Comment by mwoodiupui** [comment]
Here we are running Solr 8.11.2

**Comment by alanorth** [comment]
Strange that the authority core was missing the `_version` field. Even so, mine is loaded:

```console
$ curl 'http://localhost:8983/solr/authority/select?q=*:*'
{
  "responseHeader":{
    "status":0,
    "QTime":11,
    "params":{
      "q":"*:*"}},
  "response":{"numFound":0,"start":0,"numFoundExact":true,"docs":[]
  }}
```
