### ISSUE TITLE
Authentication Method related special groups are put in claim set even if a different authentication method is used

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/DSpace#9127]
**Describe the bug**
Currently, the set of special groups, to be put in context, during login flow, is always added in context and put into JWT claims set. The only constraint is that the authentication method for which they are configured is enabled. This flow makes sense for those methods which are not "actual" authentication methods, but are put in the stack (e.g. the IPAuthentication). But there are cases when repository administrators want those groups add to context only when an user logs in using a particular method, e.g. users logged in via Shibboleth might have permissions not granted to those logged in via PasswordAuthentication and vice versa.

**To Reproduce**
1. Enable Shibboleth authentication
2. Configure a special group to be put in context during Shibboleth Authentication flow, using `authentication-shibboleth.default-roles` and `authentication-shibboleth.role.shibusers` properties.
3. Login via Password Authentication and go to "Profile" Page
4. "Authorization special groups you belong to" will list the special group set at point 2

**Expected behavior**
System should distinguish when special groups are to be put in context only when an authentication method is enabled from those to be put in context only when an authentication method is used. We, at 4Science, can look into it and propose a solution in a PR.

**Comment by tdonohue** [comment]
Thanks @corrad82-4s !  Assigning to you and pulling over to the 7.6.x maintenance board.

NOTE: this also seems to be related to or the same issue as #9074

**Comment by tdonohue** [comment]
Thanks @corrad82-4s !  Assigning to you and pulling over to the 7.6.x maintenance board.

NOTE: this also seems to be related to or the same issue as #9074
