### ISSUE TITLE
Conflict locales: mail notify and Angular GUI

### ISSUE THREAD

**Issue by leandroecomp** [DSpace/DSpace#9144]
**Describe the bug**
Hi

I'm having trouble translating email messages into another language.
I created files with messages in Brazilian Portuguese, adding the sulfix `_pt_BR` to each of the translations. However, not all of them are working. 

**To Reproduce**
For example, a user's registration correctly uses the `register_pr_BR` file. In the case of sending the document, DSpace continues to use the file template in english, `submit_archive` instead of `submit_archive_pt_BR`.

DSpace `local.cf`
```
...
default.language = pt_BR
webui.supported.locales = pt_BR, es, en
...
```
Angular `config.yml`
```
...
defaultLanguage: pt-BR

languages:
  - code: 'pt-BR'
    label: 'Português do Brasil'
    active: true
  - code: 'es'
    label: 'Español'
    active: true
  - code: 'en'
    label: 'English'
    active: true
...
```

The database was migrated from DSPace 6.3, and this problem does not occur with old users, only with new ones.

**Comment by tdonohue** [comment]
This appears to be a duplicate of #9085?

It is also worth noting that emails language is chosen based on the user's preferred language/locale, with a default value of the `default.language`.  So, if the user's account has their "Language" set to English in their Profile, they will receive emails in English.

**Comment by leandroecomp** [comment]
I will extend the question in more detail. Let us initially consider that:
- All the following tests were run by recompiling the DSpace backend and frontend (Angular).
- Also consider that notification email templates in Brazilian Portuguese follow the `country_language_variant` format (Ex.: `register_pt_BR`).
- All the custom internationalization JSON file follow the `country_language-variant`, with the standard files that are already included in the Algular frontend (Ex.: pt-BR.json).  


The first aspect that caught my attention is the creation of an administrator user via the CLI.
Let's look at the example below considering that they are in the configuration file of DSpace backend `local.cfg`: 
```
...
default.language = pt_BR
webui.supported.locales = pt_BR,es,en
...
```

Following the installation manual we execute the following command to create a admin user:
```
root ~ # dspace create-administrator
Creating an initial administrator account
E-mail address: dspace.admin@domain.com
First name: DSpace
Last name: Admin
Select one of the following languages: pt_BR
Language: pt_BR
Is the above data correct? (y or n): y
Password will not display on screen.
Password:
Again to confirm:
Administrator account created
```
See who where it only shows the default language, and not all those available in the `webui.supported.locales` parameter. 
OK, next.


Let us consider that the user dspace.admin was created correctly and is in the Postgresql database as follows:

```
dspace=# select email,uuid from eperson;
            email             |                 uuid
------------------------------+--------------------------------------
 dspace.admin@domain.com      | 7c94a813-d401-4ca2-9b66-45b61f468176
```

```
dspace=# select metadata_value_id,metadata_field_id,text_value,dspace_object_id  from metadatavalue;
 metadata_value_id | metadata_field_id | text_value |           dspace_object_id
-------------------+-------------------+------------+--------------------------------------
                24 |                 2 | Admin      | 7c94a813-d401-4ca2-9b66-45b61f468176
                25 |                 1 | DSpace     | 7c94a813-d401-4ca2-9b66-45b61f468176
                27 |                 4 | pt_BR      | 7c94a813-d401-4ca2-9b66-45b61f468176
```

The metadatavalue table shows the other attributes related to the user. Note that the metadata_field_id field that stores the language has just pt and not its chosen `pt_BR`.To solve this problem I used the following command: 
```
variationdspace user --modify  -m dspace.admin@domain.com -l pt_BR
```
Now let's go to the graphical interface. As mentioned in the previous post, standard Angular notions were used to specify the languages ​​available for selection int the `config.yml` file:
```
...
defaultLanguage: pt-BR

languages:
  - code: 'pt-BR'
    label: 'Português do Brasil'
    active: true
  - code: 'es'
    label: 'Español'
    active: true
  - code: 'en'
    label: 'English'
    active: true
...
```
This configuration is supported, allowing the correct translation of terms into Brazilian Portuguese. But, when the language variable in the user profile does not match the Angular GUI config, mapping is not done as in the figure below.

![image](https://github.com/DSpace/DSpace/assets/46628962/f656da8d-1b5c-449c-8747-5e2e3b613a7f)

Basically, the variable use by DSpace backend and frontend, associated with user profil, with mail send and translation of the Angular GUI.

The following table aims to summarize how the tests performed using the combination of these variables.
|`local.cfg` 	 			|`config.yml`  		| maping lang in profile|      mail messages   |  translation angular |
|---------------------------|-------------------|----------------------|------------------|----------|
|   `pt_BR`      			| `pt_BR`	  	 	|	Yes					|	`pt_BR`	     | `ERROR`	|			
|	`pt_br`	  		 		| `pt_br`       	|	Yes					|	`en`		 | `ERROR` 	|
|	`pt-BR or pt-br`		| `pt-BR or pt-br` |	No					|	`en`		 |	`pt_BR`	|


In my opinion, it is clearly a bug because of the non-standardization of the pt_BR and pt-BR sulfixes, which causes a conflict between the backend and the frontend. The backend does not support message templates that use _pt-BR as a sulfix. The frontend does not support internationalization files that use pt_BR.

I know that such a problem may be small, and I also understand that this may have gone unnoticed, since the number of Portuguese-speaking countries is small. However, in our institution we include Brazilian Portuguese and Spanish, in addition to English.


PS.: Apologies for my poor English

**Comment by leandroecomp** [comment]
Hello

I temporarily solved this problem by overwriting any language with no variation (for example, Vietnamese 'vi') with the content 'pt_BR/pt-BR'. Both the notification emails and the Angular interface recognized the corresponding language selection.

I hope this bug will be considered and fixed in the next version.

**Comment by leandroecomp** [comment]
Hello

I temporarily solved this problem by overwriting any language with no variation (for example, Vietnamese 'vi') with the content 'pt_BR/pt-BR'. Both the notification emails and the Angular interface recognized the corresponding language selection.

I hope this bug will be considered and fixed in the next version.

**Comment by tdonohue** [comment]
@leandroecomp : If this is still a bug in the system, then we should reopen this ticket.  Otherwise it will be assumed "fixed".

If you have a fix, please consider sending us a Pull Request with the proposed changes.  DSpace has no central development team, so all bugs are fixed by volunteers who collaborate with us on the next release.  So, if you find a bug fix, we encourage you to send along a PR so that we can include that fix in the next release.

It's unclear to me whether this ticket should be reopened.  But, I'd encourage reopening it if the bug still exists in DSpace itself.
