### ISSUE TITLE
Status 500 for items without READ permission for Anonymous

### ISSUE THREAD

**Issue by olli-gold** [DSpace/DSpace#9154]
**Describe the bug**
If an item does not have READ permissions for Anonymous, the `dso` Endpoint of the REST API is responding to requests for that item with a status 500 (instead of the status 401 or 403, which I would be expecting).
I actually don't know, if this endpoint is being used at all or what it's actually good for, but I found error messages in my apache logfile (on DSpace-CRIS) and was able to reproduce such errors on the public DSpace Demo instance.

**To Reproduce**
1. Remove READ permission for Anonymous to an arbitrary item
2. Try to get this item via the `dso` endpoint (http://[dspace-server]/server/api/dso/find?uuid=[UUID of the item])

I have created an example on the public DSpace Demo instance: I have removed READ permission to item 5db5b893-7728-4f3f-9bdd-eb3878eac0a6 for Anonymous, so that nobody except for administrative users can read that (apologies, if this confused anybody). So, getting https://demo.dspace.org/server/api/dso/find?uuid=5db5b893-7728-4f3f-9bdd-eb3878eac0a6 results in an error page with the status 500 - if you try it with a browser (via URL or via HAL browser). However, when you use wget to test it, you'll get a correct status 403 (I cannot explain, why that happens).

**Expected behavior**
I would expect status 403 or 401 when I try to access the item via the `dso` endpoint (https://demo.dspace.org/server/api/dso/find?uuid=5db5b893-7728-4f3f-9bdd-eb3878eac0a6)

**Related work**
https://demo.dspace.org/items/5db5b893-7728-4f3f-9bdd-eb3878eac0a6 is responding with the correct status code (403), so I guess the problem only affects the `dso` endpoint.

**Comment by saschaszott** [comment]
Furthermore, the `api/dso` endpoint is not included in the REST contact list of DSpace endpoints: https://github.com/DSpace/RestContract/blob/main/endpoints.md

**Comment by saschaszott** [comment]
Just in case you use `wget` or `curl` to reproduce the behaviour described above: make sure to **include a User-Agent header** in the HTTP request. Otherwise, you'll get a 403 response independently of the actual request.

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this issue
