### ISSUE TITLE
WorkflowItems and WorkspaceItems do not obey projections and always embed all data.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#9164]
Discovered in #9053, and also related to #8791 (which might be solved by the same solution)

## Describe the bug
When WorkflowItems and WorkspaceItems are represented in REST API responses, they **always** embed a large amount of data.  This embedding is hardcoded into our code, and [CANNOT be controlled via projections](https://github.com/DSpace/RestContract/blob/main/projections.md).  The results is that these objects always return the equivalent of a `?projection=full` request, with no way to turn it off.

**This behavior can result in performance issues on the MyDSpace page (`/mydspace`).**  These performance issues are easier to see on the "Workflow Tasks" view (`/mydspace?configuration=workflow`), see #9053 as one example. It also can impact the "Your Submissions" view (`/mydspace?configuration=workspace`) when the page size is a very large value.  

## To Reproduce
1. From the UI, open of your browser's DevTools "Network" tab (to watch the REST API requests/responses)
2. Login. go to "MyDSpace" 
3. By default the "Your Submissions" view is shown.  This makes a request to REST that is structured like: `/server/api/discover/search/objects?sort=lastModified,DESC&page=0&size=10&configuration=workspace&embed=thumbnail&embed=item%2Fthumbnail&embed=accessStatus`
    * Notice this request has no `projection` param, and only a few `embed` params
    * If you look at the response to that request, you'll find that it's a _very large_ JSON response.  For each `workspaceitem` listed, you'll find it embeds the following (in the `_embedded` section)
        * All data about the `submitter`
        * All data about the `item`
        * All data about the `submissionDefinition`
        * All data about the `collection`
     * **BUG:** This is more information than is necessary, as this page doesn't need information like the `submissionDefinition` (which is the entire submission configuration), etc.  There's also no way to turn off these embeds. 
4. Now, using the "Show" selectbox, change to the "Workflow tasks" view.  This makes a request to REST that is structured like: `/server/api/discover/search/objects?sort=lastModified,DESC&page=0&size=10&configuration=workflow&embed=thumbnail&embed=item%2Fthumbnail&embed=accessStatus`  (This is the same request as above except `configuration=workflow` is used to load Workflow Items)
    * Notice this request has no `projection` param, and only a few `embed` params
    * If you look at the response to that request, you'll find that it's AGAIN a _very large_ JSON response.  For each `claimedtask` or `pooltask` listed, you'll find it embeds the following (in the `_embedded` section)
        * All data about the `group` that can claim the task (for `pooltask` objects only) or the `owner` who claimed the task (for `claimedtask` objects only)
        * All data about the `workflowitem`
            * All data about this workflowitem's `submitter`
            * All data about this workflowitem's `item`
            * All data about this workflowitem's `submissionDefinition`
            * All data about this workflowitem's `collection`
     * **BUG:** This is more information than is necessary, as this page doesn't need information like the `submissionDefinition` (which is the entire submission configuration), etc.  There's also no way to turn off these embeds. 

## Expected behavior
REST API responses should all obey the [rules for projections](https://github.com/DSpace/RestContract/blob/main/projections.md) & the ideal default behavior is to embed as little data as possible.  This gives the User Interface more control over requesting the exact embedded data it requires for different pages.

The core problem appears to be that the `AInprogressItemConverter` (used for both WorkspaceItems and WorkflowItems) embeds all data by default.  For example, this section of code always embeds the entire SubmissionDefinition in each of these objects: 
https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java#L82-L126

This Converter is used (by the REST API) anytime a `WorkspaceItem` or `WorkflowItem` is returned (i.e. displayed in the UI). even when they are returned/displayed in lists/searches, like on the MyDSpace page.  This causes every object listed on the MyDSpace page to load its `SubmissionDefinition` (and other unnecessary embedded data). 

This obviously impacts performance. If you change the pagesize to 100 on MyDSpace, that will result in all objects loading their SubmissionDefinition...so you will find 100 SubmissionDefinitions in the final REST response.  Logically, the SubmissionDefinition is only needed when **editing** a submission (or an item in workflow), so this extra data is wasteful and hurts performance.

**Related work**
Related to #9053
A fix to this bug might also fix #8791 (which is a similar ticket, but limited just to WorkspaceItems).

**Comment by tdonohue** [comment]
@benbosman : This is the new ticket for the follow-up work to #9053 . Feel free to enhance it as needed.  

Assigned you so that you/your team can work on it immediately.  I've moved this to the 7.6.x board in the hopes that we can include it in a 7.6.2 release sometime in the future.  NOTE This ticket might partially duplicate #8791 (also assigned to your team), so these two bugs might be solved by one PR.

**Comment by hutattedonmyarm** [comment]
This is also relevant (and more or less identical ) to #8791
