### ISSUE TITLE
DSpace 7: more meaningful regex message

### ISSUE THREAD

**Issue by f-rapp** [DSpace/DSpace#9178]
**Is your feature request related to a problem? Please describe.**
When users don't meet the regex condition on a field in submission forms, they receive a message that may not be very meaningful to them.

Example:
regex for file names:
https://github.com/DSpace/DSpace/assets/67266996/0aa8ab46-0cca-49ee-be83-3b7f52766b1c

**Describe the solution you'd like**
The error message should provide meaningful details. 

**Describe alternatives or workarounds you've considered**
cf. discussion on dspace-tech on 2023-11-07/08

**Additional context**
https://github.com/DSpace/DSpace/issues/9177

**Comment by hutattedonmyarm** [comment]
Universität Konstanz would like to claim this. We've been having the same issue and just developed a fix for us.
We'd also provide a backport to DSpace 7.x
