### ISSUE TITLE
Dspace 6.4 jspui interface is not showing

### ISSUE THREAD

**Issue by dipualnur** [DSpace/DSpace#9185]
We have tried to install the dspace version 6.3 in our library and we run the essential command, everything was fine butwhen it comes to the final part and that is to show, only xmlui interface is showing.

After we run the following command,
 sudo cp -R /dspace/webapps/* /var/lib/tomcat9/webapps/
we should be able to redirect the page localhost:8080/jspui/ as well as localhost:8080/xmlui/.

Our machine is 16GB RAM and OS is Linux Ubuntu 22.04 LTS.

**Comment by tdonohue** [comment]
Sorry, we no longer accept tickets related to DSpace 6.x, as it is no longer under support (it is end-of-life as of July): https://wiki.lyrasis.org/display/DSPACE/Releases

That said, you are welcome to ask questions on our mailing lists.  There may be other DSpace 6 users there who can provide advice.  https://wiki.lyrasis.org/display/DSPACE/Mailing+Lists

Most likely you are hitting an error that you need to determine the cause of.  See our Troubleshooting guide: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace6.xorbelow
