### ISSUE TITLE
Avoid excess load of bots going into search facet links on entity pages

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#9227]
**Describe the bug**
We're seeing in search console for several of our clients that bots go into facet links on entity pages. Given that this doesn't contribute to the quality of the indexing (e.g. bots shouldn't be going there) and that processing these requests is resource intensive, we better avoid this behaviour al together.

**To Reproduce**
1. Look at search console for an actively indexed DSpace 7 site, that has entities enabled
2. Look for the patterns in the reports of crawled urls for things like:
 
`entities/orgunit/25913818-6714-4be5-89a6-f70c8facdf7e?f.author=Wang`

**Expected behavior**
Robots should be blocked from doing this

**Proposed solution**
Add following disallow directive in robots.txt:

`Disallow: /entities/*?f`

**Related work**
N/A

**Comment by bram-atmire** [comment]
Robots.txt is managed in Angular, not here. Closing the issue here, re-issued it in Angular
https://github.com/DSpace/dspace-angular/issues/2709

**Comment by tdonohue** [comment]
@bram-atmire : Just a friendly note for the future... it's possible for any Committer to simply move a ticket from `DSpace/DSpace` to `DSpace/dspace-angular` (or visa versa).  Look for the "Transfer issue" link in the (right) sidebar.  That saves you from having to recreate it in the other repo (plus GitHub auto-redirects links from the old ticket to the new one)
