### ISSUE TITLE
Datacite import not in sync with pagination

### ISSUE THREAD

**Issue by floriangantner** [DSpace/DSpace#9230]
**Describe the bug**
The datacite import source is not in sync with the pagination form the external sources page.

**To Reproduce**
1. go to dspace demo and log in as some demo user.
2. Import `10.5281/zenodo` from datacite (this should import a lot of entries https://api.datacite.org/dois?query=10.5281/zenodo)
3. Paginate through the results. The request is made for 10 results (see console log), but 25 are returned. The pagination does not show valid informations.

![Screenshot 2023-12-11 at 17-39-03 DSpace Repository Import metadata from an external source](https://github.com/DSpace/DSpace/assets/33422716/7bcb7102-42a3-4c2c-8704-33fd6f31de94)

![Screenshot 2023-12-11 at 17-39-50 DSpace Repository Import metadata from an external source](https://github.com/DSpace/DSpace/assets/33422716/c1716707-2070-4dfe-a265-23c9e50c416a)

**Expected behavior**
We expect the pagination of the results to be in sync with the start and count settings
https://github.com/DSpace/DSpace/blob/344d79bfde40190e210ac2c5879c5e99676c595d/dspace-api/src/main/java/org/dspace/importer/external/datacite/DataCiteImportMetadataSourceServiceImpl.java#L88 
according to the [datacite api pagination](https://support.datacite.org/docs/pagination) . It seems like we have to forgotten to consider this parameters.

**Related work**

We can provide some fix for this issue.

**Comment by floriangantner** [comment]
There is also some issue with calculating the (total) number of records. By now the number of records is restricted to the pagination which default value is 25 (see screenshot). https://github.com/DSpace/DSpace/blob/344d79bfde40190e210ac2c5879c5e99676c595d/dspace-api/src/main/java/org/dspace/importer/external/datacite/DataCiteImportMetadataSourceServiceImpl.java#L76 In the screenshots describing the problem above the number should be around [448](https://api.datacite.org/dois?query=publisher:SupraBank)

There was some approach getting the total number of results from the request in the early stage of the datacite PR's  https://github.com/DSpace/DSpace/pull/8593/commits/a9cee40a15cdb00b4bf2e5f96bc7129beb57d36d#diff-49e1b00f5c9bbd91b2fb5ab6a67e7b88665f0331e66eb3344e557a15f8d25b95R345 , but it has unfortunately been modified meanwhile. 

Since both topics are related to each other (pagination+total number of results) my fix would also include this topic. Or should i open an own issue for this?

**Comment by tdonohue** [comment]
@floriangantner : You can keep two related changes in the same ticket/PR.  That's perfectly OK.  We just try to discourage unrelated changes in the same PR, unless they are clearly described in the PR.
