### ISSUE TITLE
Browse always retrieves all facet results from Solr, only to discard most of them

### ISSUE THREAD

**Issue by ybnd** [DSpace/DSpace#9244]
**Describe the bug**
`SolrBrowseDAO` uses Solr facets to generate browse entries.
Browse pages are paginated to limit the amount of these browse entries on the given page.

However, DSpace retrieves _the full facet_ to build up the list of browse entries. For example, in a client repository we're working on, DSpace requests a list of 87+ _thousand_ authors from Solr, and returns only a few tens of them.

We don't appear to do any custom filtering on this full list of facets, so this should not be necessary.

There are built-in Solr parameters to paginate facets: [`facet.limit`](https://solr.apache.org/guide/6_6/faceting.html#Faceting-Thefacet.limitParameter), [`facet.offset`](https://solr.apache.org/guide/6_6/faceting.html#Faceting-Thefacet.offsetParameter), and DSpace already [supports](https://github.com/DSpace/DSpace/blob/4bf7d178049a28e24b452455bf2db64cc13953b8/dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java#L922-L924) them.
Resolving this issue should be as easy as patching `limit` and `offset` through to the constructor [here](https://github.com/DSpace/DSpace/blob/4bf7d178049a28e24b452455bf2db64cc13953b8/dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java#L183-L191)

**To Reproduce**
1. Debug any DSpace instance with many Items
1. Go to a browse page, set the page size to more than the total number of results
1. Place a breakpoint [here](https://github.com/DSpace/DSpace/blob/4bf7d178049a28e24b452455bf2db64cc13953b8/dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java#L267)
   * You'll see that the `result.facets` contains _all_ results for the given facet
   * A few lines down, the list is truncated to the given `offset`/`limit`

**Expected behavior**
We should avoid such huge Solr requests and let Solr handle the pagination instead.

**Related work**
Link to any related tickets or PRs here.

**Comment by toniprieto** [comment]
I've submitted a PR for this issue. The current facet query does not include limits because retrieving the total number of entries is necessary to support pagination. I have implemented a different query using the [JSON Facet API](https://solr.apache.org/guide/8_1/json-facet-api.html) to retrieve all the information at once, while being able to include limits in the facet.
