### ISSUE TITLE
Change put/patch/delete to post request method 

### ISSUE THREAD

**Issue by Natasha112298** [DSpace/DSpace#9249]
Hi, facing an issue regarding the deployment of dspace in clients server cause they aren't allowing put/patch/delete request method cause of vulnerability issues with them and they want us to change it to post method.
Using dspace 7.4, is there anyway i can do the changes if so how.

**Comment by tdonohue** [comment]
@Natasha112298 : Unfortunately, this is no way to achieve this without major code customizations to both the frontend & backend code.  

The DSpace REST API purposely uses HTTP standard request methods to align with the global best practices for REST APIs.  See our REST Contract README: https://github.com/DSpace/RestContract/blob/main/README.md

Other REST APIs (e.g. [Amazon S3's REST API](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html)) use the same PUT/PATCH/DELETE methods to align with similar best practices.

My recommendation would be to gather more information about the "vulnerability issues" they see with these standard methods.  DSpace uses tactics like CSRF/XSRF protection and CORS to avoid any vulnerability issues of these sort.  https://github.com/DSpace/RestContract/blob/main/csrf-tokens.md

Closing as this ticket isn't actionable and isn't possible to fix.  Further questions can be asked via our DSpace Support channels at https://wiki.lyrasis.org/display/DSPACE/Support
