### ISSUE TITLE
Expose the item submitter over the REST

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#9260]
Currently, there is no way to get the submitter of an item via the REST API. We could eventually access the information stored in the dc.description.provenance metadata but this could be eventually removed/altered. 
The submitter is currently only exposed as a link from the workspace/workflow item but there is no way to get the same information for items already deposited

**Describe the solution you'd like**
A Link Repository able to expose the submitter from the ItemRest repository

**Additional context**
The information could eventually exposed via the UI in the administer / status tab

This is not top priority for us but we would like to get feedback on this idea, and if there is an agreement we could work for that for a future release (likely post DSpace 8)

**Comment by tdonohue** [comment]
@abollini : I'm not against the idea, but quite obviously submitter information should only be accessible/visible to Administrators (similar to the `dc.description.provenance` metadata field).
