### ISSUE TITLE
Repository indexing fails when item tika fulltext processing fails with error

### ISSUE THREAD

**Issue by eskander17** [DSpace/DSpace#9262]
**Describe the bug**
Repository indexing fails when item tika fulltext processing fails with error.

**To Reproduce**
Repository indexing fails when item tika fulltext processing

**Expected behavior**
Repository indexing doesn't fail when item tika fulltext processing.

**Related work**
https://github.com/DSpace/DSpace/pull/9263

**Comment by MW3000** [comment]
Thank you for fixing this, @eskander17. That's really appreciated and such a big improvement for our daily work with DSpace!
