### ISSUE TITLE
MediaFilter over large repository result in downtime

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#9272]
**Describe the bug**
If you attempt to run the filter-media script over a large repository is really likely to cause a downtime.
The issue is related to the fact that during the execution that could take also days in some scenario (milions of files to process) a single database transaction is keep open and as soon as an item is processed the pending update query put a lock on the database preventing also the normal access to the information from the REST API/UI.

**To Reproduce**
1. If you have a large repository you can run the script, better in force mode as this would force all the item to be re-processed taking the process longer
2. look to the log to see which items have been processed, you will be unable to access it via the UI

alternatively you can hack the code a bit or use your IDE to pause the execution of the filter-media process after having processed a couple of item. You can also monitor your DB to see the evidence of that is described above.

Please note that the updates are written to the transaction as soon as an item is processed as we uncache the item to avoid memory issue, this require the hibernate session to flush. Of course, we cannot (and should not) remove this uncache but also doing that there is no guarantee that Hibernate will not flush the session when it becomes to huge.

This issue is also related to https://github.com/DSpace/DSpace/issues/8731

**Expected behavior**

**Related work**
Link to any related tickets or PRs here.

**Comment by jonas-atmire** [comment]
I'll quickly piggy back on this issue with a thought of a possible improvements. (This obviously does not need to be fixed immediately, but might be good to start a quick discussion of what we could do)

Currently, when the filter-media runs, it simply:
* Loops over all items
* Loops over all bitstream attached to the items
* Loops through all the filter-media plugins and processes those bitstreams
* It does some checks to see if it has been processed or not
    * If it's NOT processed before -> it's processed
    * If it IS processed before -> It's skipped and logs as such

The big issue here is that if there are items that are NEVER altered, they will always also be looped over, but will never be relevant. For example -> If there are 10 000 items, and only 1 items is added every day, and the old items / bitstreams are not updated, those 10 000 items will always be looped through and skipped, greatly increasing the time it takes to process, as well as the load that it would add on the server

If those items and related bitstreams could be skipped in some way, 
(Just spitting ideas, to be checked for possibilities)
Similarly to discovery index, the last modified date COULD be used, but that has some (possible) downsides:
* We need to make sure that we have ALL events related to bitstreams caught, so the last modified date is updated as well 
    * In older versions, a bitstream edit did NOT update the last modified date
        * https://demo.dspace.org/ does update the last modified date of the item if a new bitstream is uploaded    
* The filter-media will need to be changed to use discovery as well, but if we use the latest record to begin with, it might have an impact if another script is altering/adding items
    * Might be possible to handle it in a different away to avoid that

**Comment by abollini** [comment]
hi @jonas-atmire I agree with your suggestions and these could be improvement that would alleviate the issue and improve the more common scenarios where we want to process the items in a "incremental way".
I suggest to create a separate github issue with your suggestions / remarks as further enhancement to improve the operational performance but keep this issue focus on the goal to reprocess a large set of items as it would be if the `-f` parameter is used (as it would be required when configuration are changed).
I would also to highlight that this issue is an easy one to demonstrate the general issue that we have each time that we need to create script that eventually process a large set or all the items. As noted in https://github.com/DSpace/DSpace/pull/9273 we are now able to spot the issue generated by attempting of incremental commit iterating over item via a simple IT that has been used to proof that the solution in the linked PR allows us to perform such kind of optimization whatever they will be needed.
