### ISSUE TITLE
Update DataCite Metadata Schema to new version 4, as version 3 will be deprecated on January 1, 2025

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#9291]
> DataCite Metadata Schema 3 (3.0 and 3.1) will be deprecated on January 1, 2025.

At the moment DSpace uses version 3.1 in `DIM2DataCite.xsl` for registering DOIs with DataCite. We probably should update to a newer schema version. There seem to be only two breaking changes:

> Schema 4 introduced two breaking changes:
>The resourceType property was changed from optional to mandatory. This property has resourceTypeGeneral as a mandatory attribute.
>The contributorType "Funder" was deprecated. This concept was replaced with the FundingReference property.

As we already set `resourceType` with `resourceTypeGeneral` and do not use `Funder`, those seem no problem for DSpace.
We can probably get away with just updating the `resource` element to:

`<resource xmlns="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">`

We might update our mapping for `resourceTypeGeneral` as the new schema allows a more granular vocabulary.

DataCite documentation on [Updating from Schema 3 to Schema 4](https://support.datacite.org/docs/updating-from-schema-3-to-schema-4)

**Comment by YPaulsen-TLC** [comment]
#9339 will fix this. @MW3000 can you please give it a test?

**Comment by amgciadev** [comment]
It's good that I have caught this one, as we were also working on similar work for one of our new DSpace instances. Happy to help reviewing/contributing to this one.

**Comment by MW3000** [comment]
> #9339 will fix this. @MW3000 can you please give it a test?

@YPaulsen-TLC  Cool that you did a pull request. I will test it by Wednesday.
