### ISSUE TITLE
Use projections to avoid multiple `accessStatus` requests per page.

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#9316]
**Describe the bug**
If you activate this setting on the angular side:
```yaml
item:
  showAccessStatuses: true

```
then, for every item shown in a list, there will be a request for each one, just to fetch it accessStatus. If your page expects you to return 100 items, you will perform a single query to get those 100 items, then 100 instant requests are made to get each access status. For some security mechanisms this might be presented as a DoS attack. Just to obtain this for each result:
```json
{
  "status" : "metadata.only",
  "type" : "accessStatus",
  "_links" : {
    "self" : {
      "href" : "https://MYHOST/server/api/core/items/3f456f9a-4dba-43ac-9b05-5cbb4ff6edd4/accessStatus"
    }
  }
}
```

**To Reproduce**
1. You just need to activate on your angular config file:
```yaml
item:
  showAccessStatuses: true
```
2. Then perform a simple search, you will see that your browser performed several request like this https://MYHOST/server/api/core/items/3f456f9a-4dba-43ac-9b05-5cbb4ff6edd4/accessStatus

**Expected behavior**
It would be expected that, if the configuration is active, then it would just require a single `/discover/search/objects` request to get the accessStatus embeded data in the same item context.

**Comment by tdonohue** [comment]
Agreed, @paulo-graca .  I've seen this as well.  It's definitely a performance issue, and it's one of the reasons why `showAccessStatuses` is set to `false` by default.   Moving this to the 7.6.x board.  Requires a volunteer.  

This may require code fixes  primarily to Angular to properly call the endpoint with this data embedded

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this issue

**Comment by tdonohue** [comment]
@alexandrevryghem : Assigning to you for Atmire to work on.  I agree that, as much as reasonably possible, we should backport bug fixes (as long as the bug fix in question doesn't require major refactoring which could impact 7.x sites).
