### ISSUE TITLE
Community/Collection admins can't edit logo for communities/collections

### ISSUE THREAD

**Issue by eskander17** [DSpace/DSpace#9319]
**Describe the bug**
Community or Collection admins can't edit logo for communities or collections

**To Reproduce**
1. delete/create community logo by community's admin
2. delete/create collection logo by collection's admin

**Expected behavior**
Community/Collection admins can edit logo for communities/collections.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
This is a duplicate of https://github.com/DSpace/dspace-angular/issues/2240.   Linking those issues together.
