### ISSUE TITLE
The package name of the IIIF search plugin in the iiif.cfg is not correct

### ISSUE THREAD

**Issue by marsaoua** [DSpace/DSpace#9345]
**Describe the bug**
The plugin is not found, hence the package name of the IIIF search plugin in the iiif.cfg is not correct
See: 
1. https://github.com/DSpace/DSpace/blob/fbd3d602239bc97d11f48dfcbf42bfb14b378efa/dspace-iiif/src/main/java/org/dspace/app/iiif/service/WordHighlightSolrSearch.java#L8
2. https://github.com/DSpace/DSpace/blob/fbd3d602239bc97d11f48dfcbf42bfb14b378efa/dspace/config/modules/iiif.cfg#L18

**Comment by tdonohue** [comment]
Closing fixed by #9346
