### ISSUE TITLE
Docker Container for Shibboleth Incorrectly Configured

### ISSUE THREAD

**Issue by BenjaminBlaxterParkes** [DSpace/DSpace#9351]
### The Bug
The DSpace 7_x docker container for shibboleth is not configured correctly. When pulling the container and trying to build a number of errors are encountered. This stops the container from being built and running.

### To Reproduce

1. Follow the README documentation on setting up shibboleth as an authentication method: https://github.com/DSpace/DSpace/blob/main/dspace/src/main/docker-compose/README.md
2. Run: docker-compose -p d7 -f docker-compose.yml -f dspace/src/main/docker-compose/docker-compose-shibboleth.yml build

### Expected Behaviour

If the configuration detailed in the README has been implemented we would expect the docker container to run and the proxy site should be running.

### Encountered Behaviour

docker-compose throws an error.
`Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "httpd-shibd-foreground.sh": executable file not found in $PATH: unknown`

### Proposed Solution

In order for the dspace-shibboleth docker container to run the httpd-shibd-foreground.sh needs to be up updated to be compatible with linux and made exactable. The configuration also needs to be updated as the ${APACHE_SERVER_NAME} variable string in shibboleth2.xml is appended with an extra 'https://'.

The httpd-shibd-foreground.sh is copied to the container but is not given executable permissions. Updating the Dockerfile to run a chmod command grants the needed permissions:
`RUN chmod +x /usr/local/bin/httpd-shibd-foreground.sh`

Once this is fixed running ./httpd-shibd-foreground.sh produces an error:
`sed: -e expression #1, char 32: unknown option to 's'`

This is because the format of the sed command is incompatible with linux which trips up when encountering each '/'. These need to be replaced with a pipe '|' for the the sed command to run successfully. If we update httpd-shibd-foreground.sh to run:
`sed -i "s|\${APACHE_SERVER_NAME}|$APACHE_SERVER_NAME|g" /etc/shibboleth/shibboleth2.xml
` we will avoid any issues with incompatibility.

Lastly, in shibboleth2.xml the ApplicationDefaults entityID has 'https://' hard coded into the string. The ${APACHE_SERVER_NAME} will already include a 'https://' so it will append a second 'https://' to the variable. Just removing the 'https://' from entityID negates the error:
`ApplicationDefaults entityID="${APACHE_SERVER_NAME}/shibboleth" REMOTE_USER="eppn persistent-id targeted-id">`

**Related work**
https://github.com/DSpace/DSpace/pull/9344

**Comment by BenjaminBlaxterParkes** [comment]
Hey Tim,
I'd be happy to pick this up as I've already done the work locally and I'm focused on this for my current project.

**Comment by tdonohue** [comment]
@BenjaminBlaxterParkes : Please feel free to send us a PR if you are able!

**Comment by tdonohue** [comment]
Closing, the error described in this ticket was fixed by #9344
