### ISSUE TITLE
Should dc.type be required by default?

### ISSUE THREAD

**Issue by pnbecker** [DSpace/DSpace#9357]
In #9339 we upgraded the DIM2DataCite crosswalk to follow DataCite's metadata schema in version 4.5. With version 4 the field resourceType was made mandatory by DataCite. In DSpace's default submission-forms.xml it is currently not mandatory. DataCite's metadata schema is getting a de facto standard in the open science community and being reused in other projects as well. This brings up the question, whether we want to make dc.type required in DSpace default configuration. If we don't we should add to our documentation, that you should make it required, if you mint DOIs. We already build in another fall-back into the crosswalk setting DataCite's required resource type to "Other" if dc.type is not set.

As #9339 was ported back to DSpace 7.6.2 (see #9356), we should mention in the release note of 7.6.2 that people should make dc.type required.

**Comment by bram-atmire** [comment]
I personally think it makes a lot of sense to make dc.type required: the amount of challenges that this solves will easily outweigh the minor inconvenience of those edge cases where people do not want to use it, and have to disable it in config.

Not sure if updating our standard vocabulary for dc.type should be part of this same change, or separate. But that one really needs an overhaul as well, and is even more important if dc.type would indeed become mandatory.
https://github.com/DSpace/DSpace/blob/main/dspace/config/submission-forms.xml#L1395

**Comment by tdonohue** [comment]
Per today's DevMtg, we agreed that making `dc.type` required by default in DSpace 8.0 makes sense.  (Just documenting this decision in the ticket.)
