### ISSUE TITLE
When answering a request for copy the email subject field will be ignored

### ISSUE THREAD

**Issue by MW3000** [DSpace/DSpace#9383]
**Describe the bug**
When you answer a request for copy, regardless whether you grant or deny the request, you are presented with a form, that has fields for a subject and a message. The subject gets ignored and the subject from the email template is used instead. I post the issue here, because the problem lies with the backend.

<img width="1392" alt="Screenshot 2024-02-29 at 10 11 05" src="https://github.com/DSpace/DSpace/assets/8408850/52a74a6d-75ff-4c8f-8057-9ca6ab32aadd">

I already have a fix. I will provide a pull request today or tomorrow.

**To Reproduce**
1. Request a copy of a bitstream under embargo
2. Click the link to grant or deny the request
3. Enter a custom subject line
4. Verify the email sent: the subject line provided by you in the form was ignored and the subject from the email template used instead.

**Expected behavior**
The subject you enter in the form should become the subject of the email you send

**Related work**
I have a fix. I will provide a pull request today or tomorrow.

**Comment by tdonohue** [comment]
Fixed by #9387
