### ISSUE TITLE
improve robustness of CrossRef metadata import via DOI: trailing whitespace causes URISyntaxException

### ISSUE THREAD

**Issue by saschaszott** [DSpace/DSpace#9384]
## Bug Description

The method `SearchByIdCallable.call()` cannot handle queries that contain trailing whitespaces, e.g. the search query `10.1111/jan.12345 ` (URL `/import-external?entity=Publication&sourceId=crossref&query=10.1111%2Fjan.12345%20`) results in a `java.net.URISyntaxException`.

The exception message is: 

`Illegal character in path at index 59: https://api.crossref.org/works/filter=doi:10.1111/jan.12345 `

This error is caused by

```java
URIBuilder uriBuilder = new URIBuilder(url + "/" + ID);
```

**Comment by floriangantner** [comment]
Some similar behaviour can also be spectated among other external sources.

e.g. import publication from orcid (sandbox) on dspace demo page:

![Screenshot 2024-02-29 at 14-33-01 DSpace Repository Import metadata from an external source](https://github.com/DSpace/DSpace/assets/33422716/8ca6686a-0639-4739-908b-5296e8778083)

with leading whitespaces before the orcid

![Screenshot 2024-02-29 at 14-32-53 DSpace Repository Import metadata from an external source](https://github.com/DSpace/DSpace/assets/33422716/caab2938-b177-4c35-bfb5-0877bf1718a7)

or trailing whitespaces after the orcid

![Screenshot 2024-02-29 at 14-32-43 DSpace Repository Import metadata from an external source](https://github.com/DSpace/DSpace/assets/33422716/01535ab5-3b1f-4eee-8c2c-4d9e308c0937)

**Comment by alanorth** [comment]
@saschaszott related to this (not sure if it needs its own issue): if you try to use a DOI as a URI (with the protocol and doi.org), the results are _interesting_:

![Screenshot 2024-04-15 at 14-39-24 CGSpace Import metadata from an external source](https://github.com/DSpace/DSpace/assets/191754/c180c207-ed52-46f1-b1a4-f154f19b361e)

Results work as expected with just the DOI component:

![Screenshot 2024-04-15 at 14-39-40 CGSpace Import metadata from an external source](https://github.com/DSpace/DSpace/assets/191754/4f50e4e0-911a-4644-8591-f8868311373c)
