### ISSUE TITLE
Delete sync settings when profile is unlinked/disconnected from orcid

### ISSUE THREAD

**Issue by floriangantner** [DSpace/DSpace#9390]
**Is your feature request related to a problem? Please describe.**
Currently when unlinking some profile from orcid only the metadatavalues `person.identifier.orcid`, `dspace.orcid.scope` `dspace.orcid.authenticated` are deleted.
https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/orcid/service/impl/OrcidSynchronizationServiceImpl.java#L115  

**Describe the solution you'd like**
We would also like the [metadatavalues](https://github.com/DSpace/DSpace/blob/5b76b173deb8b7a96f0aaab22158dcfadc0402e6/dspace/config/registries/dspace-types.xml#L64) `dspace.orcid.sync-mode` and `dspace.orcid.sync-*` (with the name of the profile/entity type) to be deleted when the profile is disconnected/unlinked.
These information are not necessary to be hold in the repository after the profile has been unlinked because they now have no impact on the profiles orcid functionality anymore.

**Describe alternatives or workarounds you've considered**
- There might be cases where some profile is linked again to the repository and the sync-settings are keep available. But i would assume this is some seldom edge case.  
- The Orcid Queue Entries could also be deleted when the profile is disconnected. This is implemented in DSpace-Cris https://github.com/4Science/DSpace/blob/029adbcd10365477be28e3ce91ca99715e36ab9a/dspace-api/src/main/java/org/dspace/orcid/service/impl/OrcidSynchronizationServiceImpl.java#L135 and could also be ported to DSpace.

**Additional context**

**Comment by floriangantner** [comment]
ping @tdonohue , i can provide some solution for this.

**Comment by tdonohue** [comment]
@floriangantner : Feel free to provide a solution.  However, because of the "edge cases" you mentioned, we may want to make sure this solution can be configurable (on or off).  I do worry that others may be expecting these settings to be kept, but I agree there should be an option to remove them as well.
