### ISSUE TITLE
Default form is displayed for a Publication when I specified a proper submission-name

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#9402]
**Describe the bug**
Not all collections are being presented the correct configured form. 
It you have such a configuration like this in you item-submission.xml file:
```xml
<name-map collection-entity-type="Publication" submission-name="Publication" />
```
And have more than 10 collections with `dspace.entity.type = Publication` the 11th will not display the correct form. It will use the default one.

**To Reproduce**
1. You will need more than 10 collections with `dspace.entity.type = Publication` (or any other type)
2. Add more collections and associate the Publication type
3. Deposit one new item on a recent collection

**Expected behavior**
I'm expecting to have the correct form. But the default is shown.

**Related work**
- https://github.com/DSpace/DSpace/pull/9004
- https://github.com/DSpace/DSpace/pull/8855

**Comment by paulo-graca** [comment]
This issue is related with this line:
https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java#L1122
```java
DiscoverResult discoverResult = searchService.search(context, discoverQuery);
```

because we didn't specify a number of expected rows. So the results with the default number of rows (I seems to be 10) are returned.

Two possible approaches could be addressed. The easy one is to define an high number for the returned rows (but this problem will again occur if that number exceeds). The other one is to loop every page result. Perhaps we can define a high number and do pagination so we don't have to do several or many solr queries.

**Comment by tdonohue** [comment]
@paulo-graca : I'd like to note a third option is to make that method *support pagination* similar to `findCollectionsWithSubmit()` here: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java#L1085-L1099

Essentially, any methods which can return a large number of results ideally should support pagination parameters. That way the calling code can paginate through the results (or grab all results if it needs it).  In this scenario, that'd be better than an arbitrary large number...plus it could allow for better scalability as you may not need/want to load 1000 `Collection` objects into memory at one time even if you have 1000 `Collection` objects that match an entity type.

In any case, I agree this is definitely a bug.  Pulled this over to the 7.6.x maintenance board & keeping assigned to you (thanks for volunteering!)
