### ISSUE TITLE
Default oai configuration isn't xml schema valid

### ISSUE THREAD

**Issue by ChrisBethgster** [DSpace/DSpace#9414]
**Describe the bug**
The file `dspace/config/crosswalks/oai/oai.xml` have no linked `xsd` inside. But in the same folder there are a file with name `XOAIConfiguration.xsd`. I think this is the schema of the oai configuration.
But the validation failed with a simple (not necessary?) error.

```
Programmname: Xerces
Fehlerlevel: error
Beschreibung: The content of element 'Transformer' is not complete. One of '{"http://www.lyncode.com/XOAIConfiguration":Description}' is expected.
```

All Transformer elements have no element `Description`.

```
<Transformers>
    <Transformer id="driverTransformer">
        <XSLT>transformers/driver.xsl</XSLT>
    </Transformer>
    <Transformer id="openaireTransformer">
        <XSLT>transformers/openaire.xsl</XSLT>
    </Transformer>
    <Transformer id="openaire4Transformer">
        <XSLT>transformers/openaire4.xsl</XSLT>
    </Transformer>
</Transformers>
```

If a `Description` isn't necessary and not used - I think so - the XSD should be modified.

**To Reproduce**
1. Validate the file `dspace/config/crosswalks/oai/oai.xml` against the schema `dspace/config/crosswalks/oai/XOAIConfiguration.xsd`.

**Expected behavior**
1. The `oai.xml` should linked against the Schema.
2. The schema validation doesn't failed.

**Comment by ChrisBethgster** [comment]
I see the Description is added last month in the main...

But what's the matter that the schema is not linked inside the XML?

**Comment by tdonohue** [comment]
It looks like the descriptions were added by #9231.  So, this can be closed. That said, if someone wants to add a small PR to link the schema, that'd be welcome.
