### ISSUE TITLE
Sorting Communities with diacritics

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/DSpace#9425]
**Describe the bug**
For a matter of sorting Communities, the ones with diacritics should be kind of ignored and appear listed with the ones that don't have. Take this example:
![image](https://github.com/DSpace/DSpace/assets/877488/d7154b0c-83cb-4e13-b4a8-a84a1c467239)
here: `ÁREAS CIENTÍFICAS / SCIENTIFIC AREAS`  
should appear in the first place.

**To Reproduce**
1. Ensure you have more than one community and that starts with other letter different than the letter A
2. Create a new community
3. Choose a name with diacritics like: `ÂBC-Test`  for that community

**Expected behavior**
When you access the Communities and Collections page you should see this new community near the first elements but it will be listed near the end.

**Related work**
The current sort by `dc.title` is ignoring diacritics:
https://github.com/DSpace/DSpace/blob/29ecc5c74ccb5488cd00c2f286086d97d093271a/dspace-api/src/main/java/org/dspace/discovery/indexobject/CommunityIndexFactoryImpl.java#L104

**Comment by tdonohue** [comment]
Fixed by #9432
