### ISSUE TITLE
Cancel button in process creation GUI kicks off the process

### ISSUE THREAD

**Issue by maxsullivan** [DSpace/DSpace#9426]
**Describe the bug**
Dspace 7.6.1
When using the GUI to create a new process clicking 'cancel' returns the user to the process overview page but also triggers the process.

**To Reproduce**
1. Go to processes overview > create a new process
![image](https://github.com/DSpace/DSpace/assets/9542807/b3f6d494-4bf4-4861-aac0-4a2c82ea1bd1)

2. Click cancel.

3. Note that the process appears in the list and is running.
![image](https://github.com/DSpace/DSpace/assets/9542807/05c4c37f-d52e-45af-b813-d5e2a0722418)

**Expected behavior**
The user returns to the process overview page without starting the process.

**Comment by alexandrevryghem** [comment]
This issue has already been fixed [here](https://github.com/dspace/dspace-angular/commit/52c0977489063689dba99caf004e4120a85e9fc9#diff-d76a1ef68bec8ba9b5743ea3c0f6c6b4e80b42a35f5352bc42fb39962313f7f5R10)  by changing the HTML tag from `<button>` to `<a>`. This has also already been backported on 7.6.2 [here](https://github.com/DSpace/dspace-angular/pull/2696)
