### ISSUE TITLE
Item Counts (webui.strengths): Cached Counts Not Updating 

### ISSUE THREAD

**Issue by AmyBW** [DSpace/DSpace#9434]
**Describe the bug**
Cached item counts are not updating (unless Tomcat is restarted). (Edited to add version **7.6.1**)

**To Reproduce**

1. Log in to the demo instance as an administrator: https://demo.dspace.org

2. Navigate to an existing community with a small collection, such as: https://demo.dspace.org/communities/bd0943b0-1c46-4980-b831-f9300e4740e2. Note the item count badges for the community and the collection (in this example, as of this moment, 0). Observe that there are actual items in the collection. 

3. Add some new items to the small collection: https://demo.dspace.org/collections/55a12ef1-cecc-4005-8f65-d0a4d17644ce

4. Run the index-discovery process, check item count badges again, they have not changed (still 0 as of this moment). 

5. Log out, navigate away, clear browser cache, reload in new window, and/or open in incognito mode. Check the item count badges again. They have not changed. 

6. On my test instance, if I restart the Tomcat service, the item counts update immediately.

**Expected behavior**
Item counts, even cached item counts, should update after discovery job and/or after full reload triggered by new window, logout, clearing browser cache, etc.

**Comment by alanorth** [comment]
@AmyBW we are running DSpace 7.6.1 and notice this as well. I don't pay very close attention to the strengths, and we reboot the system for updates a few times a month anyway, but I've been suspecting something wasn't right for some time.

Now I just confirmed it by submitting an item and waiting one hour. I tried hard refresh, logging out, and a private window, but the only time the strengths are updated is if we restart Tomcat.

**Comment by tdonohue** [comment]
Fix for this issue now available in #9583.  This PR is under review for 8.0 and 7.6.2.  If anyone wants to help test it, I'd appreciate it.

**Comment by pgsantiago001** [comment]
tdonohue Hello, could you help me? The counter in the categories in version 7.6.1 does not update every time I upload a document. I appreciate your help!

**Comment by alanorth** [comment]
Hi @pgsantiago001. The GitHub issue tracker is not for user support. You should use the [mailing list or Slack](https://wiki.lyrasis.org/display/DSPACE/Mailing+Lists) for support questions.

This issue was fixed in DSpace 7.6.2 so you will need to upgrade.
