### ISSUE TITLE
Failed to import file with \tbundle or \tpermissions with SAF Batch Import

### ISSUE THREAD

**Issue by chrisnaadhi** [DSpace/DSpace#9445]
**Describe the bug**
Hello!
I Have this "contents" file :
S1-2020-210210160084-FullTeks.pdf
S1-2020-210210160084-PernyataanKesamaan.pdf\tbundle:LICENSE
S1-2020-210210160084-PernyataanPublikasi.pdf\tbundle:LICENSE

so i want to add the "PernyataanPublikasi" file to other bundle than original so i add those suffix, but it won't work well when i'm uploading it. Dspace says :

```
2024-03-18 04:22:27.234 ERROR import - 30 @ java.lang.Exception: Error committing changes to database: /data/dspace/imports/importSAF/1ba73644-9f84-4b18-911f-e31fc578d44c/item_210210160084.zip-1ba73644-9f84-4b18-911f-e31fc578d44c/item_210210160084/S1-2020-210210160084-PernyataanKesamaan.pdf\tbundle:LICENSE (No such file or directory), 
aborting most recent changes at org.dspace.app.itemimport.ItemImport.internalRun(ItemImport.java:233) at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:150) at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at
java.base/java.lang.Thread.run(Thread.java:840) 
Caused by: java.io.FileNotFoundException: /data/dspace/imports/importSAF/1ba73644-9f84-4b18-911f-e31fc578d44c/item_210210160084.zip-1ba73644-9f84-4b18-911f-e31fc578d44c/item_210210160084/S1-2020-210210160084-PernyataanKesamaan.pdf\tbundle:LICENSE (No such file or directory) at
java.base/java.io.FileInputStream.open0(Native Method) at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157) at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111) at
org.dspace.app.itemimport.ItemImportServiceImpl.processContentFileEntry(ItemImportServiceImpl.java:1420) at
org.dspace.app.itemimport.ItemImportServiceImpl.processContentsFile(ItemImportServiceImpl.java:1216) at
org.dspace.app.itemimport.ItemImportServiceImpl.addItem(ItemImportServiceImpl.java:752) at
org.dspace.app.itemimport.ItemImportServiceImpl.addItems(ItemImportServiceImpl.java:313) at
org.dspace.app.itemimport.ItemImport.process(ItemImport.java:311) at
org.dspace.app.itemimport.ItemImport.internalRun(ItemImport.java:226)
```

**To Reproduce**
1. Install new DSpace 7.6.1 with frontend
2. Create SAF based on this article https://wiki.lyrasis.org/display/DSDOC7x/Importing+and+Exporting+Items+via+Simple+Archive+Format
3. Create contents file with same line as mine
4. The Metadata upload was success but the file upload was aborted because java seems can't read the \tbundle or \tpermission after file name in the content list

**Expected behavior**
all file successfully uploaded with \tbundle or \tpermission options

**Comment by mwoodiupui** [comment]
Are those `\t`s actual horizontal-tab characters (which they should be) or literal backslash-t pairs?

**Comment by chrisnaadhi** [comment]
> Are those `\t`s actual horizontal-tab characters (which they should be) or literal backslash-t pairs?

it was literal backslash-t
how to access actual horizontal-tab ? when i'm copy yours, it was plain backslash

**Comment by chrisnaadhi** [comment]
![image](https://github.com/DSpace/DSpace/assets/29543851/eddccb2c-701a-429f-947b-2f289443f39d)
it's still failed, i've tried to any possibilities and still failed

**Comment by tdonohue** [comment]
@chrisnaadhi : Just for the record, the `contents` file is supposed to include *tab characters* not a literal `\t`.  So the original format of your contents file is incorrect.

The new error seems to be saying you are including the text "-[r|w|" in your contents file permissions.  You are supposed to either include `-r` for read permissions or `-w` for write permissions. 

So, I think the problems here are a misunderstanding of the documentation.  Your `contents` file has the wrong format.

**Comment by chrisnaadhi** [comment]
> @chrisnaadhi : Just for the record, the `contents` file is supposed to include _tab characters_ not a literal `\t`. So the original format of your contents file is incorrect.
> 
> The new error seems to be saying you are including the text "-[r|w|" in your contents file permissions. You are supposed to either include `-r` for read permissions or `-w` for write permissions.
> 
> So, I think the problems here are a misunderstanding of the documentation. Your `contents` file has the wrong format. I've updated the docs to try to make it clearer: https://wiki.lyrasis.org/display/DSDOC7x/Importing+and+Exporting+Items+via+Simple+Archive+Format

@tdonohue thank you very much for the updated docs, it was really helpful and give more concise guides
i've solved the issues with literal tab character and using -r for file permissons!
