### ISSUE TITLE
Docs: DOI: Extended clarification on DOI DSpace item states

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/DSpace#9446]
**Describe the bug**

The different states for DOI in an item are described here:
https://wiki.lyrasis.org/display/DSDOC7x/DOI+Digital+Object+Identifier?focusedCommentId=328958128#DOIDigitalObjectIdentifier-'cron'jobforasynchronousreservation/registration

I'm not 100% convinced this is complete & it seems to also miss the corresponding states of the DOI in DataCite itself.
I wrote up a suggestion to extend the docs:
https://wiki.lyrasis.org/display/DSDOC7x/DOI+Digital+Object+Identifier?focusedCommentId=328958128#comment-328958128

Would be great if @tdonohue or @pnbecker could review this & if good/complete, include it on the page.

**Comment by pnbecker** [comment]
Thanks @bram-atmire for noticing and coming up with the table. @kshepherd and me added it with small editions to the DSpace 8 manual: https://wiki.lyrasis.org/display/DSDOC8x/DOI+Digital+Object+Identifier#DOIDigitalObjectIdentifier-'cron'jobforasynchronousreservation/registration
