### ISSUE TITLE
NotifyServiceRestRepositoryIT has two tests which do not succeed in GitHub CI

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#9457]
**Describe the bug**
The `NotifyServiceRestRepositoryIT` has two tests which are consistently failing in GitHub CI.  
* `NotifyServiceInboundPatternConstraintRemoveOperationTest`
* `NotifyServiceInboundPatternConstraintRemoveOperationBadRequestTest`

However, these tests are *always* succeeding for me when I run them locally.  My suspicion is that they are failing in GitHub CI because the tests are running in a different order and encountering _unexpected_ data.  This most often occurs when other tests are not sufficiently cleaning up their own data.  (It's also worth noting that the order of tests sometimes *does change* in GitHub CI...I suspect that has occurred recently, causing these tests to fail consistently.)

I've attempted to resolve these failures twice:
* #9444 (merged as it seemed successful at the time. But the failures have appeared again.)
* #9456  (closed without merging.  This might be worth referencing to see what fixes I attempted, but I was unable to get the tests to succeed.)

**These tests have been temporarily disabled in #9458**  They will require more investigation before they can be reenabled.

**Comment by tdonohue** [comment]
@abollini and @frabacche : I'm assigning this to you both as this test was added during the COAR Notify work (obviously).  I have not found a way to get these tests to succeed in GitHub CI (see description above)...they are consistently failing & have been disabled in #9458.  So, I'm hoping someone on your end will have time to dig into them to try to find a way to stabilize these tests again.

**Comment by frabacche** [comment]
solution found and implemented at pull request: https://github.com/DSpace/DSpace/pull/9479
