### ISSUE TITLE
ORCID depends on an external Maven Repository (which has been unstable)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#9480]
**Describe the bug**
In our upgrade to Jakarta EE (see #9321) we had to switch to an ORCID API which was compatible with Jakarta EE.  I chose the `org.orcid:orcid-model-jakarta` release from https://artifacts.oicr.on.ca/artifactory/collab-release/

While this was a good quick-fix, this has proven to be less than ideal as the https://artifacts.oicr.on.ca/ site seems to go down for long periods of time (it was down for 3 days earlier this week).  When it is down, anyone attempting to build/recompile DSpace will see build errors like this:
```
[ERROR] Failed to execute goal on project dspace-api: Could not resolve dependencies for project org.dspace:dspace-api:jar:8.0-rc1: Failed to collect dependencies at org.orcid:orcid-model-jakarta:jar:3.3.0: Failed to read artifact descriptor for org.orcid:orcid-model-jakarta:jar:3.3.0: Could not transfer artifact org.orcid:orcid-model-jakarta:pom:3.3.0 from/to oicr.on.ca (https://artifacts.oicr.on.ca/artifactory/collab-release/): Transfer failed for https://artifacts.oicr.on.ca/artifactory/collab-release/org/orcid/orcid-model-jakarta/3.3.0/orcid-model-jakarta-3.3.0.pom 503 Service Unavailable -> [Help 1]
```

Since the official ORCID dependencies (`org.orcid:orcid-model` in Maven Central) have no immediately plans to move to Jakarta EE, we need to find another option.  Two immediate solutions seem possible:
* Reopen https://github.com/DSpace/orcid-jaxb-api and generate our own ORCID API using JAXB with Jakarta EE compatibility.
* Or, fork the codebase behind https://artifacts.oicr.on.ca/artifactory/collab-release/ (https://github.com/dockstore/orcid-model/) and release a copy of it to Maven Central

**Expected behavior**
We need to ensure that all Maven Repositories used by DSpace (in our Parent POM) are trusted & stable.  

Currently, I'm working on reopening our ORCID API again and updating it to work for Jakarta EE:  https://github.com/DSpace/orcid-jaxb-api

**Comment by hardyoyo** [comment]
I'm pretty sure forking is the right call, but I think ORCID folks might want to know about this?

**Comment by hardyoyo** [comment]
Oh, I see, they already know: https://github.com/ORCID/orcid-model/issues/50

Forking is the right call, +1
