### ISSUE TITLE
Inclusion of xml-apis creates a potential conflict with the JDK java.xml module

### ISSUE THREAD

**Issue by jeffmorin** [DSpace/DSpace#9545]
**Describe the bug**
The `xml-apis` dependency contains classes and interfaces present in the `java.xml` module included in JDK 17. This raises over 1200 errors declared in Eclipse, possibly in other IDEs.

This bug does not prevent DSpace from running properly so I don't consider it as being critical. However, it is very annoying for developers working on the codebase, whether it is for maintenance or new features.

**To Reproduce**
1. Open Eclipse (either the original distribution from `eclipse.org` or Spring Tools for Eclipse)
2. Import the code tree through the **File | Import** command, then select **Existing Maven Projects**.
3. Let Eclipse import each project, including the root one, as a project in the **Package Explorer** view. As of writing these lines, there should be 14 of them.

In the **Problems** view, over 1200 errors should appear. They state either that a given type cannot be resolved or that a given package is available from both the `java.xml` module and the unnamed module. All these errors actually refer to classes and interfaces that are part of the `java.xml` module (included in JDK 17) as well as the `xml-apis` dependency.

As a result, it becomes extremely hard for developers to distinguish real errors from this bunch of false positives.

**Expected behaviour**
No errors should be present in the Problems view in Eclipse.

**Related work**
The key is to exclude the `xml-apis` dependency from the `tika-parsers-standard-package` (used in **dspace-api** and **dspace-server-webapp**) and `xom` (used in **dspace-sword**). Then all errors will disappear from the **Problems** view.

Please see pull request https://github.com/DSpace/DSpace/pull/9546 for a fix.

**Comment by jeffmorin** [comment]
@tdonohue : You are right, except that (1) I added the exclusion into the parent POM instead, and (2) I also cover the `xom` dependency used by **dspace-sword**. As a result, only one file, the parent POM, is impacted by my PR.

**Comment by tdonohue** [comment]
@jeffmorin : I'll give your approach a closer look today/tomorrow.  If it seems like the better one, I'll merge it.
