### ISSUE TITLE
SyndicationFeed still contains references to JSPUI and XMLUI

### ISSUE THREAD

**Issue by saschaszott** [DSpace/DSpace#9572]
## Bug Description

In `org.dspace.app.util.SyndicationFeed` some references to `JSPUI` and `XMLUI` are still present.

Furthermore, `OpenSearchController` has a reference to `SyndicationFeed.UITYPE_JSPUI` in 

```java
labelMap.put(SyndicationFeed.MSG_UITYPE, SyndicationFeed.UITYPE_JSPUI);
```

@tdonohue , I can try to fix this problem but I'm not sure if `MSG_UITYPE` is completely obsolete in DS 7 and can be safely removed from `SyndicationFeed`? I can confirm that old (DS5) RSS feed URLs do not contain any reference to the UI mode.

**Comment by tdonohue** [comment]
@saschaszott : Yes, it appears to me that `MSG_UITYPE` may be no longer necessary and likely should be entirely removed.

**Comment by tdonohue** [comment]
Claiming this as I had time to look into it.  It's a quick fix & necessary to patch soon.  The RSS/Atom feeds are returning invalid URLs for bitstreams (e.g. community/collection logos).  I'll create the PR today.
