### ISSUE TITLE
Web of Science import missing entry key-ref wosPublisherContrib

### ISSUE THREAD

**Issue by selensoftr** [DSpace/DSpace#9579]
**Describe the bug**
Version: DSpace 7.6.1
Missing entry key-ref wosPublisherContrib in DSpace 7.6.1 in /dspace/config/spring/api/**wos-integration.xml**

**<entry key-ref="wos.publisher" value-ref="wosPublisherContrib"/>**

**Comment by tdonohue** [comment]
This seems like a simple thing for someone to fix who has time, so I flagged as `good first issue`.  Needs a volunteer.

**Comment by schastlivcev** [comment]
Hi, I've fixed it in https://github.com/DSpace/DSpace/pull/9581
