### ISSUE TITLE
I18Util.getEPersonLocale: consider reducing log level from error to info

### ISSUE THREAD

**Issue by saschaszott** [DSpace/DSpace#9585]
## Description

`I18Util.getEPersonLocale` generates log messages of level error if the given `eperson` does not have a default language:

https://github.com/DSpace/DSpace/blob/1517e8cd0fe59645827164099060b1d3e80b9f9f/dspace-api/src/main/java/org/dspace/core/I18nUtil.java#L97

Since the method has valid defaults (falls back to default locale) the log level should be changed to `info`.

**Comment by tdonohue** [comment]
Agreed, this doesn't seem like an error.  Needs volunteer.

**Comment by saschaszott** [comment]
> Agreed, this doesn't seem like an error. Needs volunteer.

PR is available: https://github.com/DSpace/DSpace/pull/9588
