### ISSUE TITLE
Tracking in process submissions

### ISSUE THREAD

**Issue by jacobcameron** [DSpace/DSpace#9598]
We are constantly asked by our graduate studies department who manage thesis submission to see if a thesis is with a library cataloguer, back with a student or in the hands of someone else.  Running Dspace 7.4 here, in the process of upgrading to 7.6.1.

Is there a way to create an admin interface where any item in the submission process, whether it be with another user, rejected to a student, etc. could be displayed so that these kinds of questions could be easily answered.

This would save time trying to dig through the database to find where a submission is and what's happening with it.  We already have sections for Your Submissions and Workflow tasks.  Could another element be added there called In-Process Submissions that show who's got a submission where in the workflow?  It would solve some problems at our institution, not sure if other places have these issues.

**Comment by tdonohue** [comment]
@jacobcameron : This feature already exists in DSpace 7.5+.  As of 7.5, there's a new "Supervision Order" feature which gives the ability to search all in-progress or in-workflow submissions via the "Administer Workflow" admin menu.   If the item is still in-progress, you can even assign a group to "supervise" it, which gives members of that group the ability to complete the submission on behalf of the user.

See the docs at https://wiki.lyrasis.org/display/DSDOC7x/Supervision+Orders

I'm closing this ticket, as this appears to be exactly what you are asking for.  But, you are welcome to reopen this if I'm misunderstood.

**Comment by jacobcameron** [comment]
Thanks Tim!  I'll have a look and see.
