### ISSUE TITLE
Method "isHierarchical" of "org.dspace.content.authority.DSpaceControlledVocabulary.java" should not always return true

### ISSUE THREAD

**Issue by mahnkong** [DSpace/DSpace#9606]
**Describe the bug**
The method "isHierarchical" of " org.dspace.content.authority.DSpaceControlledVocabulary.java" always returns the value true. It should instead return the "storeHierarchy" value configured for the actual controlled vocabulary.

**To Reproduce**
view source code

**Expected behavior**
return "storeHierarchy" field instead of true.

**Related work**
Link to any related tickets or PRs here.

**Comment by abollini** [comment]
Hi @mahnkong 
thanks for reaching out. The storeHierarchy attribute has a different purpose than the isHierarchical method.
The first is used to determine if only the leaf of the vocabulary need to stored as value when selected or the whole path, the second is used to determine if an authority is hierarchical or not (i.e. as a tree structure) and indeed the DSpaceControlledVocabulary is always hierarchical as it suits specifically this purpose.
I hope this clarify, if you hit an unexpected functional behaviour please tell us more about your goals, the configuration that you have applied and what goes wrong
