### ISSUE TITLE
Merge of DSpace 8 codebase on DSpace 7.6.1+ tag results in conflict

### ISSUE THREAD

**Issue by abollini** [DSpace/DSpace#9616]
**Describe the bug**
This was firstly reported by @artlowel and discussed at the https://wiki.lyrasis.org/display/DSPACE/2024-05-30+DSpace+Developers+Meeting

**To Reproduce**
See https://github.com/DSpace/DSpace/compare/dspace-7_x...main

**Expected behavior**
We should be able from a codebase updated to dspace-7_x branch or to a tag like 7.6.1, 7.6.2, etc. to pull the updated code from the dspace-8.0 tag and dspace-8_x branch once created.

Possible solution is:  `git merge -s ours dspace-7.6.1` into `main`.  This will reset their [common ancestor](https://stackoverflow.com/a/58156381) is also the recommended way to ["supersede old development history of side branches" according to Git documentation.](https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-ours-1)

**Comment by tdonohue** [comment]
Closing, as this was fixed on `DSpace/DSpace` and `DSpace/dspace-angular` by running:
```
git merge -s ours dspace-7.6.1
git push upstream main
```
See https://github.com/DSpace/DSpace/commit/a4f3b4a57c94374afe8ae060ac33d46f5580ba17 and https://github.com/DSpace/dspace-angular/commit/db08e489d9887d21c04aeaf97efa1fb963bcb461

**Comment by tdonohue** [comment]
Documentation for this merger have been added to the Release Procedure to remind us to do this after every minor release: https://wiki.lyrasis.org/display/DSPACE/Release+Procedure#ReleaseProcedure-MergeMinorReleasesbacktomainbranch
