### ISSUE TITLE
Request-a-copy link has subpath stripped from dspace.ui.url

### ISSUE THREAD

**Issue by bkeese** [DSpace/DSpace#9667]
In a dspace instance configured to run at a subpath, that subpath is stripped when request-a-copy link is generated here:

https://github.com/DSpace/DSpace/blob/87f66fbc55cf2b8f8e265d74ce2c902ac2ee7e26/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java#L300

URIBuilder.setPathSegments removes any exiting path segments from the base url before adding the new segments.

**Comment by kshepherd** [comment]
@bkeese I ran into some odd problems when reproducing this in my local env, and just wanted to check what your `dspace.ui.nameSpace` was set to in your Angular config, and what `dspace.ui.url` is set to in your backend dspace.cfg / local.cfg

**Comment by bkeese** [comment]
Wow! Thanks for your fast response and PR!
-Brian
________________________________
