### ISSUE TITLE
CSV Import / Export can clear metadata if there are metadata values with language *

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/DSpace#9701]
## Describe the bug

If there are items with metadata with language `*` stored then exporting & importing those items, with items which have metadata in same field but with `null` language, then either of those can be cleared because the exported CSV will contains 2 column headers, one without language suffix, and one with `[*]` suffix, so empty values in second column will clear values of first column an import.

## To Reproduce

To recreate issue:

- Create such items with import in new collection; eg 

  ```
  id,collection,dc.title,dc.title[*],dc.title[en]
  +,10673/2179,test1 - null lang,
  +,10673/2179,,test2 - * lang
  +,10673/2179,,,test3 - en lang
  ```

- Export items in this collection, result:

  ```
  id,collection,dc.date.accessioned,dc.description.provenance[en],dc.identifier.uri,dc.title,dc.title[*],dc.title[en]
  "1fa5ff84-dd6b-4b98-9405-b6b856d82eae","10673/2179","2024-07-16T14:13:02Z","Submitted by Demo Site Administrator (dspacedemo+admin@gmail.com) on 2024-07-16T14:13:02Z
  No. of bitstreams: 0||Made available in DSpace on 2024-07-16T14:13:02Z (GMT). No. of bitstreams: 0","https://demo.dspace.org/handle/10673/2180","test1 - null lang",,
  "4b609486-8963-4122-87da-9adc4ae52b84","10673/2179","2024-07-16T14:13:02Z","Submitted by Demo Site Administrator (dspacedemo+admin@gmail.com) on 2024-07-16T14:13:02Z
  No. of bitstreams: 0||Made available in DSpace on 2024-07-16T14:13:02Z (GMT). No. of bitstreams: 0","https://demo.dspace.org/handle/10673/2182",,,"test3 - en lang"
  "b8d6eea5-e492-4802-ba0f-0f6e11a86482","10673/2179","2024-07-16T14:13:02Z","Submitted by Demo Site Administrator (dspacedemo+admin@gmail.com) on 2024-07-16T14:13:02Z
  No. of bitstreams: 0||Made available in DSpace on 2024-07-16T14:13:02Z (GMT). No. of bitstreams: 0","https://demo.dspace.org/handle/10673/2181",,"test2 - * lang",
  ```

- Import this csv again => item with its title in the first column will no longer have title
  -  https://demo.dspace.org/collections/c5ccf951-7670-4283-923e-f2e5e141ce67 => https://demo.dspace.org/collections/c5ccf951-7670-4283-923e-f2e5e141ce67 (untitled)

**Comment by MarieVerdonck** [comment]
Atmire would like to claim this issue

**Comment by tdonohue** [comment]
Thanks @MarieVerdonck !  I'll assign to you then.
