### ISSUE TITLE
Potentially invalid usage of == operator

### ISSUE THREAD

**Issue by saschaszott** [DSpace/DSpace#9739]
## Problem Description

I have detected the following places in the code base where the `==` operator is used in a context where it should be better `equals()`. I can create a PR to fix this, but I would like to get feedback beforehand.

A PR has already been provided for `ItemServiceImpl`: https://github.com/DSpace/DSpace/pull/9737/files

#### EntityServiceImpl

https://github.com/DSpace/DSpace/blob/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-api/src/main/java/org/dspace/content/EntityServiceImpl.java#L63

https://github.com/DSpace/DSpace/blob/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-api/src/main/java/org/dspace/content/EntityServiceImpl.java#L75

#### ResourcePolicyServiceImpl

https://github.com/DSpace/DSpace/blob/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-api/src/main/java/org/dspace/authorize/ResourcePolicyServiceImpl.java#L420

#### GroupServiceImpl

https://github.com/DSpace/DSpace/blob/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java#L150

https://github.com/DSpace/DSpace/blob/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java#L181

#### ItemMetadataValueAddPatchOperation

This was found by @jlipka and mentioned in this comment 👉 https://github.com/DSpace/dspace-angular/issues/2004#issuecomment-2264821632

**Comment by saschaszott** [comment]
PRs associated to this ticket:

- DSpace: https://github.com/DSpace/DSpace/pull/9737 (affects `ItemServiceImpl`)
- DSpace CRIS: https://github.com/4Science/DSpace/pull/465 (affects multiple classes)

**Comment by tdonohue** [comment]
FWIW, It does seem (to me) that we should be trying to use `equals()` instead of `==` when comparing objects.  So, this ticket does seem correct.  This is backed up by plenty of discussions about the differences on StackOverflow, e.g. https://stackoverflow.com/a/44623690

Simply put, if an object implements it's own `equals()` method, then it NEEDS to use `equals()`.  If it uses the default `java.lang.Object#equals` method, then technically `==` and `equals()` _behave the exact same_.   But, as a "best practice", it's probably best to switch to using `equals()` for all object comparisons.

**Comment by saschaszott** [comment]
@tdonohue , thanks for your feedback. I will include the changes mentioned in the description in PR https://github.com/DSpace/DSpace/pull/9737

**Comment by saschaszott** [comment]
@tdonohue , there are - at least - these four places in the code base where `==` is appropriate (comparison of object refences):

- https://github.com/DSpace/DSpace/blob/a25b3cb3efbc0c2108b155a4cd55fe7ff4d9ce37/dspace-api/src/main/java/org/dspace/content/Relationship.java#L243

- https://github.com/DSpace/DSpace/blob/a25b3cb3efbc0c2108b155a4cd55fe7ff4d9ce37/dspace-api/src/main/java/org/dspace/app/util/DSpaceContextListener.java#L68

- https://github.com/DSpace/DSpace/blob/a25b3cb3efbc0c2108b155a4cd55fe7ff4d9ce37/dspace-api/src/main/java/org/dspace/scripts/DSpaceRunnable.java#L181

- https://github.com/DSpace/DSpace/blob/a25b3cb3efbc0c2108b155a4cd55fe7ff4d9ce37/dspace-services/src/main/java/org/dspace/servicemanager/DSpaceKernelImpl.java#L225

Should these lines remain untouched?

**Comment by tdonohue** [comment]
@saschaszott : leaving those appropriate instances around doesn't seem harmful to me at this time.
