### ISSUE TITLE
Failed to send registration email

### ISSUE THREAD

**Issue by rpskts** [DSpace/DSpace#9763]
I successful to install dspace 7.6.2 on Debian 12.

There is a problem that I am facing. Dspace has not been able to send registration emails.

Here's the error message that appears when I run the command 

./dspace test-email

```
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

About to send test email:
 - To: hai@rpskts.com
 - Subject: DSpace test email
 - Server: mail.rpskts.com

Error sending email:
 - Error: javax.mail.SendFailedException: Invalid Addresses;
  nested exception is:
        com.sun.mail.smtp.SMTPAddressFailedException: 550 SMTP AUTH is required for message submission on port 587


Please see the DSpace documentation for assistance.
```
Help

**Comment by mpasternak** [comment]
How did you configure e-mail in dspace.cfg?

**Comment by tdonohue** [comment]
This sounds like a possible misconfiguration, as the error says that your SMTP server requires authentication:
`550 SMTP AUTH is required for message submission on port 587`

This means you haven't configured your email authentication properly (e.g. `mail.server.username` and `mail.server.password`), or something else is incorrect in your `mail.server.*` settings.

Closing as answered.  If you need more support, please use one of our Support options at https://wiki.lyrasis.org/display/DSPACE/Support

**Comment by rpskts** [comment]
> How did you configure e-mail in dspace.cfg?

I didn't change dspace.cfg.

I changed local.cfg
Here are the changes I changed regarding the email

**sudo nano /dspace/config/local.cfg**

```
# SMTP mail server (allows DSpace to send email notifications
mail.server = mail.myuniversitas.com

# SMTP mail server authentication username and password (if required) 4Q36UVz0y-xE-a
mail.server.username = repository@myuniversitas.com
mail.server.password = 4Q36UVz0y-xE-a

# SMTP mail server alternate port (defaults to 25)
mail.server.port = 587

# From address for mail
# All mail from the DSpace site will use this 'from' address
mail.from.address = repository@myuniversitas.com

# When feedback is submitted via the Feedback form, it is sent to this address
# Currently limited to one recipient!
feedback.recipient = repository@myuniversitas.com

# General site administration (Webmaster) e-mail
mail.admin = repository@myuniversitas.com

# Helpdesk E-mail
mail.helpdesk = repository@myuniversitas.com
mail.helpdesk.name = Admin Help Desk

# Recipient for server errors and alerts (defaults to mail.admin)
alert.recipient = repository@myuniversitas.com

# Recipient for new user registration emails (defaults to unspecified)
registration.notify = repository@myuniversitas.com
```

**Comment by rpskts** [comment]
As soon as i change the email configuration in local.cfg or dspace cfg?

I'm a beginner Dspace user 

Thank you sir : @tdonohue , @mpasternak 😊
