### ISSUE TITLE
Administer workflow: Delete button is not deleting workflow item, but sending it to workspace

### ISSUE THREAD

**Issue by f-rapp** [DSpace/DSpace#9776]
## Describe the bug
DSpace 7.6.1
Under administer workflow, when you delete a *workflow* item, it is not actually deleted. Instead, it is moved to the workspace. 
Please note that when you delete a *workspace* item, it is actually deleted.

## To Reproduce
1.Go to administer workflow
2. Delete a workflow item
3. Search for the item. It is still there as a workspace item.

## Expected behavior
The workflow item should be deleted, not being sent back to the workspace.

**Comment by saschaszott** [comment]
This bug was fixed in DS 7.6.2 in the Angular UI: https://github.com/DSpace/dspace-angular/pull/2227

**Comment by tdonohue** [comment]
Closing, fixed in 7.6.2 in https://github.com/DSpace/dspace-angular/pull/2227

**Comment by MMilosz** [comment]
For anyone that applied this PR and noticed both 'delete' and 'send back' buttons still behave the same, you'll need to cherry-pick this commit from DSpace 8.1 for API to properly utilize the `?expunge=true` parameter: b64ba44a51252ec96b5feab8da2eae495bdf27dd

**Comment by tdonohue** [comment]
NOTE: the commit @MMilosz is referencing above is already applied to all maintenance branches.  Here it is for 7.x (released in 7.6.3): https://github.com/DSpace/DSpace/pull/10330 and here it is in 8.x (released in 8.1): https://github.com/DSpace/DSpace/pull/10329
