### ISSUE TITLE
Index discovery not working as expected

### ISSUE THREAD

**Issue by pazfelipe** [DSpace/DSpace#9880]
## Describe the bug
I've been working on a project to setup a dspace via docker. Everything works fine but when I try to run the command /dspace/bin/dspace index-discovery -b, I can see a lot of logs (during the execution), however it suddenly stops.

I'm running solr, postgres and dspace through docker compose. The problem is I can't see any error log in the dspace container, it just stops with no error.

I know it's kind of hard to guess what's happening but this is all I can share since there's no log error.

To be more precise, when I run /dspace/bin/dspace index-dicovery -b I can see this log in the postgres container

```bash
dspace-postgres  | 2024-10-09 17:19:03.800 UTC [1141] LOG:  unexpected EOF on client connection with an open transaction
```

and when I check the solr container, there are no indexed items.

**Comment by tdonohue** [comment]
Closing, as this is a support question, and seems to not have enough information to help. It sounds like a possible custom Docker setup & it may be an issue in your Docker setup itself. If you still need help, please provide more information on the dspace-tech mailing list (as noted above).

We also do have some sample Docker Compose scripts & images (which are used to run https://demo.dspace.org) in our codebase, which may be useful.  See the README at https://github.com/DSpace/DSpace/tree/main/dspace/src/main/docker-compose
