### ISSUE TITLE
Item page sometimes fails to load

### ISSUE THREAD

**Issue by jaril1** [DSpace/DSpace#9886]
## Describe the bug
The Item page randomly gets stuck and doesn't load the content. The issue occurs for anonymous users in 8.x. I believe this is related to the implementation of the correction types (loading them).

## To Reproduce
This can be reproduced randomly e.g. by navigating several times between the Simple item page and Full item page.

<img width="1092" alt="DSpace screenshot 2024-10-11" src="https://github.com/user-attachments/assets/475c4038-1eea-4266-b517-9380d1614924">

**Comment by alexandrevryghem** [comment]
@jaril1: Could you test this again? DSpace/dspace-angular#3412 was recently merged into DSpace 8.x, and it fixes a similar issue.

**Comment by jaril1** [comment]
Still exists if you mean https://demo.dspace.org

**Comment by jaril1** [comment]
Moved to https://github.com/DSpace/dspace-angular/issues/3425
