### ISSUE TITLE
Is SSR broken in DSpace 7.6.2?

### ISSUE THREAD

**Issue by amgciadev** [DSpace/DSpace#9922]
## Describe the bug
We've discovered that when doing basic testing of caching and ssr via Chrome developer tools, when we disable javascript, we get blank pages in our 7.6.2 server. Our 7.6.1 server works as expected and we have not changed any configuration. Any ideas what could be happening?
## To Reproduce
Steps to reproduce the behaviour:
1. Run angular in production mode
2. Using Chrome dev tools, disable javascript
3. Browse item, collections, etc. pages

## Expected behaviour
Pages should display without any dynamic functionality
## Related work
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
@amgciadev : I cannot reproduce this locally using 7.6.2.  We also have an automated test that runs to verify the basics of SSR are working, and it is still passing.

I think we'd need more information here.  You may want to look for errors in your backend logs, or in the SSR logs (which normally appear on the commandline where you start Angular in Dev mode... or in PM2, if you are using that)

I'll leave this open in case others are able to reproduce this, but will flag as "cannot reproduce" for now

**Comment by amgciadev** [comment]
Thanks Tim, I think it was a misconfiguration at our end. I can confirm that we no longer experience this issue.
