### ISSUE TITLE
Duplicate declaration of plugin maven-dependency-plugin in dspace/modules/server/pom.xml

### ISSUE THREAD

**Issue by alanorth** [DSpace/DSpace#9942]
## Describe the bug
I noticed this warning from maven while building current `main` (9.0-SNAPSHOT):

```log
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.dspace.modules:server:war:9.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-dependency-plugin @ line 71, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

There are indeed two declarations of the `maven-dependency-plugin` plugin in `dspace/modules/server/pom.xml`.

## To Reproduce
1. Run `mvn package` and see the warning from Maven immediately.

**Comment by tdonohue** [comment]
I can claim this while I'm doing other dependency cleanup on `main` (using `dependabot`).  Thanks for the ticket, @alanorth !  I hadn't noticed this warning yet.
