### ISSUE TITLE
Backup and restore from DSpace 7 to 8

### ISSUE THREAD

**Issue by subratlubu** [DSpace/DSpace#9967]
Hello DSpace Team,
I was trying to migrate DSpace 7.6.2 to 8.0 but failed. However, migrating from DSpace 6.4 to 7.6.2 was successful without any error.
Any help for the migration of DSpace 7.6.2 to 8.0

**Comment by tdonohue** [comment]
Closing as this ticketing system is for bug reports / feature requests.  It's not for support questions.

Please use one of the support options listed on our support page at https://wiki.lyrasis.org/display/DSPACE/Support

You also should be aware of the [DSpace 8.0 upgrade guide](https://wiki.lyrasis.org/display/DSDOC8x/Upgrading+DSpace) and the [DSpace 8.0 migration guide](https://wiki.lyrasis.org/display/DSDOC8x/Migrating+DSpace+to+a+new+server), as these may be what you are looking for
